### ISSUE TITLE
<desktop application>

### ISSUE THREAD

**Issue by gurkankorkmaz1** [ytmdesktop/ytmdesktop#1011]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I want to download music via the desktop application.

**Comment by strugee** [comment]
Duplicate of  #843

**Comment by Alipoodle** [comment]
Duplicate of #843
Thanks @strugee
