### ISSUE TITLE
No Songs/Videos will load

### ISSUE THREAD

**Issue by OmniPhillips** [ytmdesktop/ytmdesktop#1012]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Unable to play anything. I just get a spinning loading wheel and nothing happens. I have tried uninstalling and reinstalling the app, signing out and back in of my google account and turning on/off any relevant settings to no avail.
![Screenshot 2022-07-28 191724](https://user-images.githubusercontent.com/85049778/181662831-8428fecf-c65a-40bd-b169-bae375246bda.png)

### Expected Behavior

I click play and music plays.

### Steps To Reproduce

Open the app
Click on song
Click play

### YTMDesktop

1.13.0 & 1.14.2

### OS

Windows

### OS Version

11

### Arch

x86

### Installation way

YouTube-Music-Desktop-App-Setup-1.13.0.exe

**Comment by Alipoodle** [comment]
Can you confirm that this is not the case for you on YT Music itself?
Do you use any Network based Adblockers like PiHole?

**Comment by OmniPhillips** [comment]
I am able to use YTM normally without issue in chrome on the same PC and I do not use any network AdBlock. I do use the AdBlock extension in chrome but as I said YTM does work fine there.

**Comment by OmniPhillips** [comment]
I opened the app today and it just started working again. I have no idea what fixed it all of a sudden as I did not change anything.

**Comment by OmniPhillips** [comment]
I am able to use YTM normally without issue in chrome on the same PC and I do not use any network AdBlock. I use the AdBlock extension in chrome but as I said YTM does work fine there.

________________________________
