### ISSUE TITLE
Icons for Placeholder dont show in the GUI

### ISSUE THREAD

**Issue by Herobr1ne** [ytmdesktop/ytmdesktop#1013]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Hello,
I have the problem since today (No update or anything else) that no icons are shown. Just the Icon name like "music_note" or "picture_in_picture_alt".
![YouTube_Music_Desktop_App_1Wp1V68MnY](https://user-images.githubusercontent.com/33431587/183124650-6a57d2bf-e11b-43dd-8adc-bbe808397020.png)
 

Already tryed to reinstall

### Expected Behavior

Maybe an idea to fix the bug :)

### Steps To Reproduce

1. Open YT Desktop App
2. See the failure (Picture) :)

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x86

### Installation way

YouTube-Music-Desktop-App-Setup-1.13.0.exe

**Comment by Alipoodle** [comment]
The font has simply failed to load in, Yes a backup is ideal for this but an issue which rarely happens (unless the request is blocked or fails to load)

Has a restart fixed the issue?
And we've also noticed that people using PiHole also typically have this domain as blocked as it's from a Google CDN.

**Comment by Herobr1ne** [comment]
Yeah ok, thanks. I use PiHole and Whitelist "fonts.gstatic.com" now it works again.
