### ISSUE TITLE
<TITLE HERE>

### ISSUE THREAD

**Issue by eturk1** [ytmdesktop/ytmdesktop#1014]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Couldn't Sign, Browser or app may not be secure in error in v1.14.2

Issue #866 is closed to comment thus openning a new issue to get updates please.
#866 hasn't had a comment for 5 months (Mar 2022) but still cannot sign in. 

trying uninstall/reinstall, now sign-in button does nothing.
Having Premium, app is unusable w/o sign in.

<img width="385" alt="image" src="https://user-images.githubusercontent.com/525280/183259543-4d519e01-511b-4455-a4ef-604594b063ba.png">

### Expected Behavior

Sign in should function

### Steps To Reproduce

press sign in button and try to sign in to google

### YTMDesktop

v1.14.2

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

Please give us an update or work around :)

**Comment by Alipoodle** [comment]
Please use a Title and #866 is the main issue for this, please do not open more, we only want one ticket for each issue.

We're looking into Fixes and Workarounds but nothing has been found to work yet, and there's a few "Temporary" fixes as noted within the ticket at the bottom...
