### ISSUE TITLE
[v.1.14.2 patched]JavaScript error [ERR_INVALID_CALLBACK] Callback must be a function

### ISSUE THREAD

**Issue by TarasKucher** [ytmdesktop/ytmdesktop#1018]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Hi,
I'm getting an error when starting the app on Windows

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:157:11)
    at Object.unlink (fs.js:1129:14)
    at ClientRequest.<anonymous> (C:\Users\Taras Kucher\AppData\Local\Programs\youtube-music-desktop-app\resources\app.asar\src\providers\translateProvider.js:50:16)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Everything works normally if I click OK. 
And not sure if it's related to the error - but Settings window and popup menu items for tray icon do not have translation and displaying LABEL_SETINGS_TAB_GENERAL...
![image](https://user-images.githubusercontent.com/71027802/183830955-4f31f7be-a84b-41e7-8b6a-c0600a74a706.png)

### Expected Behavior

* Error does not appear
* Correct text for labels

### Steps To Reproduce

1. Open YTM Desktop
2. Observe error
![image](https://user-images.githubusercontent.com/71027802/183831328-6e973ba0-7e30-435d-a7c3-9d9aac3ab4b1.png)

### YTMDesktop

v1.14.2_PATCHED

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

YouTube Music Desktop App Setup 1.14.2.exe

### Anything else?

Tried to re-install the app - didnt help

**Comment by 2gn** [comment]
This issue seems to be a dup of #978. fyi, I have the same issue on MacOS.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
