### ISSUE TITLE
Discord integration youtube music icon

### ISSUE THREAD

**Issue by BioTomik** [ytmdesktop/ytmdesktop#1020]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Instead of the youtube music icon being displayed in the discord integration have the album cover / song picture. Would look nice

**Comment by Alipoodle** [comment]
#888 - This has already been added and is in the Pre-release build of 1.14.2 and above.

**Comment by PsychoManiac189** [comment]
when is this going to be added to the regular version? or how do i download 1.14.2 for windows?
