### ISSUE TITLE
YTMD Log me off

### ISSUE THREAD

**Issue by Itz2ndtime** [ytmdesktop/ytmdesktop#1021]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

YTMD log me off and I can't even see the sign-in button to log in again.

### Expected Behavior

-no sign in button

### Steps To Reproduce

1. go to YTMD
2. click play some playlist
3. oops something went wrong
4. can't sign in

### YTMDesktop

lastest releases

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

YouTube Music Desktop App Setup 1.14.2.exe

### Anything else?

reinstall doesn't help

![unknown](https://user-images.githubusercontent.com/112386060/187170177-0c300597-9045-4f90-a901-851f62f3bd55.png)

**Comment by bboles** [comment]
I am seeing a similar issue on MacOS 11.6.6 except the `SIGN IN` button is visible but unclickable.  I am unable to login.

**Comment by bboles** [comment]
I'm not sure what happened but was finally able to login successfully.  Maybe some auth session weirdness that finally timed out?

**Comment by Itz2ndtime** [comment]
The way to fix it is press Get Music Premuim on the right corner as you can see in the photo. It wil let you **sign in** with your gmail. I have YTM Premium anyway so I don't need to pay anything.
