### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Leakoni** [ytmdesktop/ytmdesktop#1024]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Login button no work

### Expected Behavior

Open google login page, it did before but said not trusted.

### Steps To Reproduce

1. Download
2. Install
3. Start
4. Login
5. Windows11

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Duplicate of #866
