### ISSUE TITLE
YTM skips to next song automatically

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#1025]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Sometime YTM skips to the next song automatically, in the middle of the current playing track

### Expected Behavior

Play current track to the end

### Steps To Reproduce

Simply play and wait

### YTMDesktop

1.13

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by BewitchingPetrichor** [comment]
This has been happening to me non stop, it happened about seven or eight times over the course on two hours just now while playing NFS: Heat.

**Comment by EDIflyer** [comment]
Same here - I find it will stop partway through the current song (normally about 2/3 to 3/4 of the way through) and then stop for a few seconds and then load the next song. I wondered if it was being blocked from buffering the song for some reason?

**Comment by pdario** [comment]
I think so too, I believe it can't buffer the next song chunk and so it skips to the next song

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

**Comment by AwesomeStickz** [comment]
@Alipoodle I've been having this issue since about a month, while restarting the app usually fixed it for me for a while (till it starts doing it again), lately I've been more and more annoyed by this so decided to open an issue here and just found this issue. I'm using the latest version - 2.0.8
