### ISSUE TITLE
Can`t log in to my google Account<TITLE HERE>

### ISSUE THREAD

**Issue by Juljeim** [ytmdesktop/ytmdesktop#1027]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I have a new laptop and also wanna use YT Music for desktop, but I can`t log in to my google Account because it says the internal browser of the app is not safe.

![Screenshot 2022-09-22 140150](https://user-images.githubusercontent.com/68475849/191741384-b38b711f-34df-46a6-8949-35909cbc67f4.png)

### Expected Behavior

That I can log in with my main browser and not the app.

### Steps To Reproduce

1. Click on sign in
2. Enter your email
3. Click next
4. Then the message shows up

![Screenshot 2022-09-22 140150](https://user-images.githubusercontent.com/68475849/191741825-14f0c854-ce3e-40fb-b8f5-03c7dd077b14.png)

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Venipa** [comment]
Da gibts ein button das heißt "Wiederholen", sollte nach paar tries funktionieren

**Comment by dannlea** [comment]
There is a comment on [#866](https://github.com/ytmdesktop/ytmdesktop/issues/866#issuecomment-984782963) that helped me get logged in. This isn't a perfect fix and it may not work, but it's a known issue and the devs are working on fixing it.

**Comment by Juljeim** [comment]
I did it. I installed an older version (1.10). There I didn't have the problem with the login. Afterwards I updated to the newest version.
