### ISSUE TITLE
Download Feature for Desktop App

### ISSUE THREAD

**Issue by AhmadJaghbir** [ytmdesktop/ytmdesktop#1029]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I can't see the download button on YT Music Desktop neither can I see the Downloaded songs from the desktop app

### Solution

To add the download feature to YT Desktop and give users the same experience on YT Music Mobile App

**Comment by Alipoodle** [comment]
This is because of YTM hasn't added the feature.
And we have no intension of adding a Download feature especially as this goes against YouTube's Terms of Service.

This will only be looked into until they add this feature.

**Comment by AhmadJaghbir** [comment]
So a download feature for YouTube Music Desktop is against the terms of service, while it isn't for YouTube Music mobile app?

**Comment by dannlea** [comment]
> So a download feature for YouTube Music Desktop is against the terms of service, while it isn't for YouTube Music mobile app?

Yes, because you aren't actually downloading a file on mobile, you are downloading within their preexisting ecosystem! If YTMD allowed downloads, they would have to use some kind of downloader to get access to the files because YouTube hasn't provided that level of access.
