### ISSUE TITLE
Support for Windows 11 Snap Layouts

### ISSUE THREAD

**Issue by Hershey025** [ytmdesktop/ytmdesktop#1032]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Currently YTM Desktop doesn't support the windows 11 snap layout. So if it is possible pleas add support for the Windows 11 snap layout.
![Screenshot (220)](https://user-images.githubusercontent.com/94620635/192316887-d4a0a25d-3f3a-4c48-a11d-a3bfc70b05b2.png)
Image of file explorer.
This works in most apps like file manager, google chrome, spotify etc.
![Screenshot (221)](https://user-images.githubusercontent.com/94620635/192316902-65364bb2-6e01-4624-ba13-414728fa178c.png)
Image of ytm desktop.
But it doesn't work on yt music.

### Solution

Hover to the the maximize window button to see snap layouts.

### Alternatives

use ytm in google chrome.

**Comment by Sepulator** [comment]
> ### Alternatives
> use ytm in google chrome.
Another solution: press **WIN+Z** to open snap layouts. Seems that works with any resizable app.

**Comment by Hershey025** [comment]
For some reason it did not work for me

**Comment by Alipoodle** [comment]
We do use a Custom Navigation bar.
Swapping to the native one will fix this, but obviously you loose a bit of the flare of the application~

I doubt that we can do this snapping bits while the Fancy Navigation is used.

**Comment by Hershey025** [comment]
Check this out - 
https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

This issue should be fixed with some updates in the Titlebar on V2
