### ISSUE TITLE
Extension system

### ISSUE THREAD

**Issue by MKstudio-Tech** [ytmdesktop/ytmdesktop#1034]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I would love to have extension system that enables people to add functionality (with node.js and packages enabled) to the app (kind of #592).
For example the extension system would allow people to install adblock, use custom JS on page, integrate with other platforms, add options to settings, etc.

**Comment by Alipoodle** [comment]
This seems to close to #592 to not just have it as an extension of it.
😄 Don't feel there's a need for another ticket for it.
