### ISSUE TITLE
Chromium Embedded Framework signin depreciated.

### ISSUE THREAD

**Issue by InquisitivePuma** [ytmdesktop/ytmdesktop#1038]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

App attempts to sign in to google via the chromium embedded browser, resulting in a rejection of thhe signin request 
![image](https://user-images.githubusercontent.com/22402669/194646145-b35d7330-822f-4165-87cb-396369782de8.png)

### Expected Behavior

App should signin via the Oauth framework.

### Steps To Reproduce

Open app to homepage.
Click 'sign in'.
Enter a valid email.
Click 'next'.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x86

### Installation way

.exe

**Comment by Alipoodle** [comment]
We cannot use OAuth!!!
We are using a Google Product not our own service.
OAuth is not an option
