### ISSUE TITLE
Lyrics autoscroll

### ISSUE THREAD

**Issue by mesabuca** [ytmdesktop/ytmdesktop#104]
Lyrics window don't let me scroll and I cant see some of lyrics :(

**Comment by mesabuca** [comment]
I think there should be toggle for autoscroll

**Comment by mingjun97** [comment]
Thanks for your suggestion! This feature has been added to the development branch. It will be available at next release version!

Cheers!

**Comment by adlerluiz** [comment]
Now available on v1.9.0
