### ISSUE TITLE
sort playlist

### ISSUE THREAD

**Issue by Flaveroussome** [ytmdesktop/ytmdesktop#1046]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I would like to sort my playlists after when they were added and so on....

**Comment by Alipoodle** [comment]
This is basically gonna be a no for us doing it given how much YTM Does paging on Playlist. >.<
This is will have to be something YTM implement themselves.
