### ISSUE TITLE
Feature Request: Single instance mode (Windows)

### ISSUE THREAD

**Issue by phu54321** [ytmdesktop/ytmdesktop#105]
When I accidentally double-click the YTMDesktop icon, two instance of YTMDesktop opens.
When one exists, the latter attempt to open the app should focus on the already-on instance instead.

I hope there's at least an option for this.

**Comment by adlerluiz** [comment]
Hello @phu54321 

Thanks for the suggestion, it will soon be available.

**Comment by adlerluiz** [comment]
Now available on v1.9.0

**Comment by phu54321** [comment]
One pull request: Previous implementation didn't handle the case when the 1st window is hidden to tray. `mainWindow.restore()` won't show hidden window.

https://github.com/ytmdesktop/ytmdesktop/pull/107

**Comment by adlerluiz** [comment]
Thank you for PR
