### ISSUE TITLE
Error: A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by farsdewibs0n** [ytmdesktop/ytmdesktop#1051]
### Consent

- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**
- [X] I verified that there is no open/closed issue for the same subject.

### Current Behavior

The message provided on the screenshot will always show up and randomly pauses the music. It will always show up clearing the message (by holding enter on OK button). When the message able to disappear, the music continues.

### Expected Behavior

This message shouldn't show up.

### Steps To Reproduce

1. Error shows up on launch.

### YTMDesktop

v1.13

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

![image](https://user-images.githubusercontent.com/13050356/202866044-aa46d798-d8e4-4d14-af54-45ffc68cad33.png)

**Comment by Alipoodle** [comment]
Do you have Last.fm scrobbling enabled without being signed in?

**Comment by farsdewibs0n** [comment]
Yes, I did. Apparently the feature doesnt automatically disabled when the login prompt is closed manually.
Problem Solved
