### ISSUE TITLE
Window is invisible, even after reinstalling [Windows 10]

### ISSUE THREAD

**Issue by DXPower** [ytmdesktop/ytmdesktop#1052]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The app launches normally but no window ever appears. Hovering over the preview shows it appears to be rendered correctly, but invisible. Somewhere. I know that it is not off-screen as unplugging my side monitors doesn't fix anything, and using hotkeys or commands to move the window are ineffective.

The app worked perfectly fine for a few weeks, but crashed and suddenly did this. No idea what caused it. Reinstalling the app does nothing.

### Expected Behavior

I expect to be able to see the window.

### Steps To Reproduce

I have no idea how to reproduce this. This may be a problem solely isolated to my machine. If you can point me to some log files or something, I could share those.

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

![image](https://user-images.githubusercontent.com/4307036/203419879-3950a552-af60-43d4-bee7-1d750af9a1b5.png)

This is what I get while hovering over. No amount of attempts I have made to try to view, move, or use the window have been successful. It seems to be totally invisible.

**Comment by scotthogan** [comment]
I ran into the same exact issue, but just found a workaround fix that someone shared in [a comment in another issue (#1016)](https://github.com/ytmdesktop/ytmdesktop/issues/1016#issuecomment-1242122475): 
> Mine does this a lot too.
> It's because there is a config file that says where the window should appear. (Seems like a bad idea for exactly this reason).
> 
> You can edit the config file by going to `%appdata%/youtube-music-desktop-app/config.json`.
> Look for `window-position` and change the `x` and `y` to zero (Mine is usually -32000 for both when this happens).

**Comment by DXPower** [comment]
> I ran into the same exact issue, but just found a workaround fix that someone shared in [a comment in another issue (#1016)](https://github.com/ytmdesktop/ytmdesktop/issues/1016#issuecomment-1242122475):
> 
> > Mine does this a lot too.
> > It's because there is a config file that says where the window should appear. (Seems like a bad idea for exactly this reason).
> > You can edit the config file by going to `%appdata%/youtube-music-desktop-app/config.json`.
> > Look for `window-position` and change the `x` and `y` to zero (Mine is usually -32000 for both when this happens).

Thank you, this has fixed it. Maybe this would be a good PR to make for clamping the x/y value to be on-screen on start-up.

**Comment by Ramo-Y** [comment]
> I ran into the same exact issue, but just found a workaround fix that someone shared in [a comment in another issue (#1016)](https://github.com/ytmdesktop/ytmdesktop/issues/1016#issuecomment-1242122475):
> 
> > Mine does this a lot too.
> > It's because there is a config file that says where the window should appear. (Seems like a bad idea for exactly this reason).
> > You can edit the config file by going to `%appdata%/youtube-music-desktop-app/config.json`.
> > Look for `window-position` and change the `x` and `y` to zero (Mine is usually -32000 for both when this happens).

Thank you so much, finally, I can use the app again!

**Comment by Alipoodle** [comment]
Will close as other ticket exists.
