### ISSUE TITLE
Push remote control API

### ISSUE THREAD

**Issue by mvdwetering** [ytmdesktop/ytmdesktop#1055]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I have written an integration for [YTMDesktop with  Home Assistant](https://github.com/mvdwetering/ytmdesktop_remote), one thing I struggled with was with finding a decent poll interval so updates are visible in Home Assistant within a reasonable time, but not spamming the network with requests (settled on 6 seconds polling for now).

It would be nice if the API would just send updates of changes when they happen.

### Solution

A push API. For example using a websocket, SSE or another standard, don't really have a preference.

### Alternatives

Keep polling

**Comment by DMCroww** [comment]
This would be actually pretty cool feature even for stream overlays, chatbots, or just simple OSD while playing the music from other PC.
I've got a chatbot running localy on the same PC as I'm playing the music from, but not having to poll from other PC every 1s for stream overlay would be much appreciated.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
