### ISSUE TITLE
Corrupted custom page.css file created on installation

### ISSUE THREAD

**Issue by D0t-Matrix** [ytmdesktop/ytmdesktop#1058]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When attempting to launch YTMDesktop, I receive a pop-up informing me that "A JavaScript error occurred in the main process", and upon clicking "OK" it appears to just fully close out the YTMDesktop application. This occurs on any installation mechanism or attempt I try.

However, if I then try to re-launch, uninstall or install over top of the existing installation, I get a notification that there is a currently running process for YTMDesktop (which I was unable to easily find looking at running processes in Task Manager.

I have attempted to install both the 1.13.0 release, as well as the May 2022 nightly release with both returning the same error.

Attached is the error message I get (username in directory replaced with `CurrentUsr` for privacy)
![ytmdesktop error on launch](https://user-images.githubusercontent.com/18566042/205996285-69b196f2-00c2-4195-ba0b-10b389a1fc02.png)

### Expected Behavior

Launching the application will successfully start & run the app.

### Steps To Reproduce

1. Install application
2. Attempt to start application
3. See error instead of application

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

This is only occurring on a HP Elitebook 850 G6, was not occurring on the other laptop's I've used, nor on the desktops I've tried.

This is a consistent enough error that I am able to replicate it with 100% certainty on this machine, while also not being able to trigger this bug on other devices.

**Comment by D0t-Matrix** [comment]
As an update, I have attempted v1.12.1 & v1.14.0 as well, both of which are giving the same error

**Comment by D0t-Matrix** [comment]
I have cloned the repo & attached a debugger onto the process, and am receiving the error within the `loadApplicationPackage(packagePath)` function within the `/node_modules/electron/dist/resources/default_app.asar/main.js` file. 

This also appears to be triggered from the `fileSystem.writeFile(customThemeFile, fileSystem.readFile(oldCustomThemeFile)` call at `/main.js` at line 2099.

Following the trace down, it seems that the cause of the issue was that there was a corrupted (fragmented?) `%USERPROFILE%/Documents/youtube-music-desktop-app/custom/css/page.css` file that could not be resolved. I am confused how this file got there initially, as this machine had a fresh-installation of windows when I first attempted to get ytmdesktop running & encountered this error.

**Comment by Alipoodle** [comment]
Possibly be that installing of older versions of and then updating to the new location insideof Appdata instead.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
