### ISSUE TITLE
Feature request: Add an option to disable double-tapping Play button

### ISSUE THREAD

**Issue by rensatsu** [ytmdesktop/ytmdesktop#106]
It would be great to have an option to disable double-tapping play button to show the app.
Sometimes, I may accidentally double-tap the play button when playing games and it causes the game to minimize.
Also, waiting for the second tap delays play/pause action to 200ms and feels like app's being unresponsive or slow.

P.S.: this is similar to issue #3, though I still want to use single tap to play/pause.

**Comment by adlerluiz** [comment]
Now available on v1.9.0

(go to settings, and shortcuts => Global)
