### ISSUE TITLE
Media download

### ISSUE THREAD

**Issue by IsaqueSantosSilva** [ytmdesktop/ytmdesktop#1060]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

A way for the user to listen to songs offline.

### Solution

I don't have one.

### Anything else?

Really liked this app. I have youtube premiun and spotify premiun, since there's no official youtube music app for desktop spotify was my option, but now i can use YTMDesktop and save some money. thanks!

**Comment by Alipoodle** [comment]
Sadly this is a feature which we won't be able to support and you'll have to wait for YouTube Music to add this themselves.

We do not wish to download music via YT-DL as this goes again YouTube's terms of service. And having it integrate into YTM as a "only assailable in the app" is a feature which we cannot develop on our own given that we don't own the service NOR have access to the source in an easy fashion.
