### ISSUE TITLE
Dislike Icon on Mouse Event (On only) triggers unending skips

### ISSUE THREAD

**Issue by MetalFanatic** [ytmdesktop/ytmdesktop#1062]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Occasionally I have issues with the songs entering an endless cycle of proceeding to the next song after hitting the thumbs down icon. I do have the skip thumbs down feature enabled. When this occurs, the UI displays all proceeding songs as also being thumbed down, but I believe only the selected song is saved as a disliked song. If I were to select a new song further up in the playlist, then the application will move to that song but continue it's process of cycling past songs.

### Expected Behavior

Should be self explanatory, but I obviously expect the application to skip only the thumbed down song and then play the next.

### Steps To Reproduce

So I'm not convinced that this occurs every time, rather, I believe I have issues with this when significant computer resources are being used. For example, a moment ago when this problem occurred again, I hit ctrl-shift-esc to open the task manager. 97% of memory and 89% of CPU resources were being used. I was in the process of installing OSGeo4W (found here: https://www.qgis.org/en/site/forusers/alldownloads.html#), had a single small Excel file open, a number of Chrome tabs which obviously eat RAM, an Adobe Acrobat pdf file (397 pages, just text, not filled with images, and not a scanned file... i.e. text that was possible to highlight and copy), and VS Code with a few ".jl" files and a ".py" file open. I have my VS Code settings set to multi-threading, using all 12 threads on my device. My device has the following: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz; 16.0 GB of RAM, and 77.1 GB of SSD free out of 475 GB. I was not actively executing any of the editor files at the time that this issue began to occur, but as mentioned previously, I was actively installing a large program (OSGeo4w). 

I searched for an output log but didn't find one in the YTM Desktop directory. As such, I've tried to provide as much detail about what was occurring at the time of the issue. To be clear, this issue happens frequently enough such that the issue is a nuisance, but not every time I use the application.

Internet speeds seem to average around 85 Mbps download and 5 Mbps upload. However, I just ran a speed test (about 20 minutes after closing YTM desktop), and I'm currently experiencing 28.3 Mbps download and 5.15 Mbps upload. I mention this as a reference point close to occurrence in case loading speeds are linked to the issue.

While I suspect the skipping issue might be unresolvable and linked to computer resources, I would like to see an exception introduced to the code to prevent proceeding too far, mainly for ease of mind. When this occurs, one of the things I've tried to do to halt the skipping has been clicking the dislike icon again on whatever song it's on at the time. It'd be nice to know that it doesn't cycle through too many songs save dislikes on songs that weren't intended to be disliked.

If an exception was be thrown such that after 'n' consecutive skips after the dislike icon event listener registers a mouse click toggling it on, then the application could return a message box indicating to the user to close and reopen the application. Whether the 'n' consecutive skips is determined arbitrarily or statistically likely matters little as generally one won't have too many back to back disliked songs. I say this as a very frequent listener of music, and as someone who has very picky music tastes. I would suggest 3 skips after such a described event should be ample if using an arbitrary number. 

I hope this helps, and I love your application.

### YTMDesktop

v1.13.0.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

On a side note, I am unfamiliar with Arch, but a Google search seemed to indicate that it's a Linux thing. As such, I've left this on the default, but if I am incorrect about what it is, just let me know, and tell me where to look/what it is and I will provide this to you.

**Comment by DailytheNoob** [comment]
Can confirm this issue also happens when it is bound to a key (F20 in my case), but it actually marks them as thumbs-downed and removes them from the thumbs-up playlist.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
