### ISSUE TITLE
Sort Albums By Artist Name

### ISSUE THREAD

**Issue by MaggiePerry** [ytmdesktop/ytmdesktop#1064]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Currently the only options to sort your albums is:
- recently added
- A to Z
- Z to A

I think it would be great if you could sort albums by Artist Name, this way you can easily see all the albums you have of a given artist saved.

### Solution

- Albums can now be sorted by Artist Name

**Comment by Alipoodle** [comment]
We're not YTM Desktop and with the way they currently process the Artist we are unable to do sorting.
This is a feature you will have to get them to fix.
