### ISSUE TITLE
OBS Widget

### ISSUE THREAD

**Issue by topik** [ytmdesktop/ytmdesktop#1065]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Highly customizable OBS widget for youtube music desktop app.

### Solution

Hello guys, 

I know there already is OBS widget for Youtube Music Desktop but few years ago, I wrote my own widget for Google Music Desktop App, I had no idea there is a project like this so I discontinued the project. Today I noticed your work so I ported my little widget for your API. 

URL of the project: https://github.com/topik/youtube-music-obs-widget

Hope it will make some people happy 🤗

**Comment by mingjun97** [comment]
I found this is very easy to use. Just added a link in the integration tab for easier reach. Thanks for your contribution!
