### ISSUE TITLE
Built-in Adblocker

### ISSUE THREAD

**Issue by Tee7571** [ytmdesktop/ytmdesktop#1066]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Hello everyone, I just wanted to say that your product is fantastic. What would make it even better, though, would be an ad-blocker! I use Opera GX, a browser with a built-in AdBlocker and it is amazing. But sadly though, it doesn't support a "Rich" Windows 10 media interface (like previous/next buttons beside volume + on lock screen).

**Comment by DMCroww** [comment]
Hi, 
Apparently, you've not looked through this repo.
AdBlocker will probably not be implemented. [https://github.com/ytmdesktop/ytmdesktop/issues/114](url)

If you listen to music often, and like this app, I think that having this app for free is enough to make you pay those $10 for a premium if you dont want ads...

OR try using AdGuard DNS to (maybe) limit the amount of ads (cant test - have premium)

**Comment by Tee7571** [comment]
Alright, thanks for letting me know!
