### ISSUE TITLE
Extreme memory usage

### ISSUE THREAD

**Issue by Smity** [ytmdesktop/ytmdesktop#1067]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Sorry, I can't offer much in the way of diagnostic information. All I can tell you is that YTMD has been consistently crippling my system through RAM-hogging. The exact intervals seem to vary, but what doesn't vary is that the longer YTMD is open (or perhaps, the more music is played?), the more memory it consumes. Here's a screenshot I took a few minutes ago demonstrating the issue:
![image](https://user-images.githubusercontent.com/4725316/210188009-d309f43d-a552-4827-9ef3-75e30cd432c2.png)
Note that the time needed to reproduce a result like this is on the order of a few days. Normally I restart the program once or twice a day to free memory.

Surface Pro 7
i7-1065G7, 16GB RAM

### Expected Behavior

YTMD should not be using so much RAM

### Steps To Reproduce

1. Open program
2. Observe RAM usage

### YTMDesktop

1.14.2

### OS

Windows 10

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by mingjun97** [comment]
Close as duplicated with #699
