### ISSUE TITLE
"Up Next" playlist goes black after playing a song from the playlist

### ISSUE THREAD

**Issue by wvalkering** [ytmdesktop/ytmdesktop#1072]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I open the app and find a song I want to play
The song plays, in the navigation bar I go to the menu and press 'start radio'
I click the navication bar in an empty spot, the 'up next' playlist shows up on the right side of the screen
I click a song from the playlist

The song plays
The playlist goes black and in the bottom left 'something went wrong' shows up
It appears the list is actually gone, not just hidden. When I click 'next song' in the nav bar it won't play.

It does not happen when autoplay songs are showing up in the playlist or when loading a default or premade playlist

### Expected Behavior

When clicking a song from the playlist I expect it to play and the playlist should not disappear.

### Steps To Reproduce

Start a radio from the three dot menu when playing a song
Click a song from the playlist to play
* crash *

### YTMDesktop

1.13

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

updated via automatic updates i guess

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
