### ISSUE TITLE
[Windows 10] Pixelated icon on desktop & start menu

### ISSUE THREAD

**Issue by surajmandalcell** [ytmdesktop/ytmdesktop#108]
![image](https://user-images.githubusercontent.com/11650177/76065816-58fcc780-5fb2-11ea-90bf-e0706a29bb02.png)
![image](https://user-images.githubusercontent.com/11650177/76065845-6a45d400-5fb2-11ea-878b-1c95fdfd8adf.png)  

Its annoying, it seems like its using the tray icon as desktop icon and start menu icon which could explain why it gets stretched and pixelated in other places.
Tray: 
![image](https://user-images.githubusercontent.com/11650177/76065986-ada04280-5fb2-11ea-9b1c-999635b862fd.png)

**Comment by dansauve** [comment]
Agreed. Bugs me too. +1

**Comment by Blackrucat** [comment]
It does need an Anti Aliasing, I can design a Free Icon for this Project, as an appreciation gift.

**Comment by adlerluiz** [comment]
all help is welcome, thanks :)

**Comment by dansauve** [comment]
Are there specs for the icon format(s) and size(s) required? I can create some options for community review.

**Comment by adlerluiz** [comment]
https://www.electron.build/icons

**Comment by adlerluiz** [comment]
Great, it was very good, could you do only the Background and the foreground? I will add in the app
