### ISSUE TITLE
App is completely broken/Nothing Loads (RESOLVED)

### ISSUE THREAD

**Issue by GazTheTaz6385** [ytmdesktop/ytmdesktop#1081]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

![image](https://user-images.githubusercontent.com/101683025/214431412-062a7432-1a01-4af5-bdd2-56a26446811a.png)
![image](https://user-images.githubusercontent.com/101683025/214431486-a19eca7a-3957-496f-af83-464580658a37.png)
![image](https://user-images.githubusercontent.com/101683025/214431533-2180acfd-b058-4219-9f88-910d85e283c5.png)

### Expected Behavior

for it to load my music...

### Steps To Reproduce

YTM Outage 1/24/23

### YTMDesktop

v1.14.2

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exd

**Comment by yourbuddypal** [comment]
Same, but if you try to log in to the main website in a browser, https://music.youtube.com/ - the experience is the same.
Seems like a google issue, not an app issue.

**Comment by mingjun97** [comment]
It turns out to be YT music side issue. Mine iOS app doesn’t work as well.

**Comment by GazTheTaz6385** [comment]
Seems like an outage on googles side ig 😭

**Comment by Kubulambula** [comment]
For me it broke at the same time as I updated my graphics drivers (nVidia). I don't know if it was just a coincidence

**Comment by Zenrage** [comment]
Has happened to me as well just now.  I can search for a song and play it.  I tried signing in and out again.  It came up with an error at first of unknown browser sign in: try a different browser.   Eventually, after just clicking try again it let me sign in.

![image](https://user-images.githubusercontent.com/14347723/214437684-854901a9-9c35-41c1-8bdb-07471193f939.png)

**Comment by mingjun97** [comment]
Looks like the issue get resolved on my side. Browser, ytmdesktop, iOS App all works now.

**Comment by Zenrage** [comment]
haha its nice to know how quickly people start reporting "ITS BORK" :)
