### ISSUE TITLE
<Amazing app>

### ISSUE THREAD

**Issue by Sicrearbuild** [ytmdesktop/ytmdesktop#1082]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

u

### Expected Behavior

u are amazing

### Steps To Reproduce

ssss

### YTMDesktop

v.1.2.3

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Thanks for the feedback!
