### ISSUE TITLE
Remote control not working properly with latest version

### ISSUE THREAD

**Issue by tristany0ung** [ytmdesktop/ytmdesktop#1083]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Hi,
I updated to the latest version of the Youtube Desktop app on my computer, because i encountered the error "this app is not secure".

Since then, the remote control app on my phone is malfunctionning. Sometimes the previous/next buttons wont work, but play/pause is fine. Sometimes play/pause doesnt work but previous/next works.

I already tried pairing the phone again, no luck. I checked my windows firewall aswell. 

### Expected Behavior

All controls from remote desktop android app should work.

### Steps To Reproduce

Use latest version on computer. Pair the mobile app. Controls will randomly not work.

### YTMDesktop

1.14.2

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

exe

**Comment by Matakor** [comment]
I've noticed that the remote almost doesn't function at all (play pause seems to?) unless you have volume maxed out.

**Comment by yotamss** [comment]
The same, when connecting the phone, a js error is shown on the page

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
