### ISSUE TITLE
Can't sign in, Browser or app may not be secure #866

### ISSUE THREAD

**Issue by leopucci** [ytmdesktop/ytmdesktop#1085]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Falae!
I could not comment on #866 so i am commenting here. 
I don´t have time to solve, but i have implemented with 
https://github.com/glawson/electron-deeplink

so the flow is opening the login on the browser on some website, doing the login. 
After the login google sends back to site.. the site then redirects to a deep link url and save some id and timer on the database.  
electron-deeplink recognizes and opens the link, inside the electron you get some id on this deep link url and validate on the backend if the id matches some login done in the last 5 minutes. 
That´s it user logged in and you grab the data that you need to use google from the database

### Expected Behavior

I can´t use the app anymore because I can´t login

### Steps To Reproduce

Try to login

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

exe

**Comment by LeXoLz** [comment]
right click the system tray icon and press guest. then log in on the guest window and close the application fully and when you come back you can log in again

**Comment by leopucci** [comment]
> right click the system tray icon and press guest. then log in on the guest window and close the application fully and when you come back you can log in again

It does not work
![image](https://user-images.githubusercontent.com/38509299/217540849-f6d53cf4-764a-47ef-83f0-ef958fcd1328.png)

**Comment by Alipoodle** [comment]
This is not how OAuth works.
We are bit a third party we are requiring FULL access to your google account as this a first party service.
