### ISSUE TITLE
a button to refresh the page?

### ISSUE THREAD

**Issue by ImLunaHey** [ytmdesktop/ytmdesktop#1089]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

when refreshing you get new recommendations, i can't find any way to cause the page to reload apart from completely reopening the app.

### Solution

refresh button

**Comment by yotamss** [comment]
CTRL + R works

**Comment by Alipoodle** [comment]
Duplicate of #738
