### ISSUE TITLE
Bug: Dark grey bar at bottom of the app

### ISSUE THREAD

**Issue by surajmandalcell** [ytmdesktop/ytmdesktop#109]
![image](https://user-images.githubusercontent.com/11650177/76068099-86e40b00-5fb6-11ea-9338-798ee9020a8d.png)

- Stays after restarting app
- Stays after restarting windows

OS: windows 10

Edit: Happens only when using the "Title Bar Style : Disable titlebar"

**Comment by adlerluiz** [comment]
Fixed
