### ISSUE TITLE
Unable to download Remote Control app

### ISSUE THREAD

**Issue by bookofiyi** [ytmdesktop/ytmdesktop#1103]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I am unable to download the YTMDesktop Remote app from the Play Store because the app was made for an older version of Android. I'm currently on Android 12, and I am unable to download the application. 

![Screenshot_2023-03-24-21-12-08-069_com android vending](https://user-images.githubusercontent.com/45729650/227629661-2b8cc1dc-a056-4ecd-adb5-1c420c75c311.jpg)

### Expected Behavior

Be able to download the YTMDektop Remote app

### Steps To Reproduce

none

### YTMDesktop

v1.14.2

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Gollam** [comment]
I have the same issue.

**Comment by adhillon192** [comment]
I have the same issue

**Comment by adhillon192** [comment]
I would love to collaborate on this, can someone please email me?

**Comment by FyreWhale** [comment]
I have the same issue, but on android 13

**Comment by DeFlanko** [comment]
@adlerluiz I see your the owner in the Google play store, what would it take to update the remote app so that it can be downloaded and installed on newer Android OS Devices (11+)?

**Comment by darynliebenberg** [comment]
I have the same issue. Using Android 14.

**Comment by zejjnt** [comment]
I can download it, but I can't get the QR code to show in the app so I can't actually use it :/

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
