### ISSUE TITLE
64 bit application

### ISSUE THREAD

**Issue by vasukaviarasu** [ytmdesktop/ytmdesktop#1109]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I would like to have x64 type of application for windows and linux.

**Comment by ovitrif** [comment]
Hey @vasukaviarasu 👋🏻 

Feel free to open a PR for it. This is how OSS usually works. I'm grateful the project is open source, don't feel like we're entitled to request features… but rather to contribute.

**Comment by Alipoodle** [comment]
To my knowledge the app is built in 64 bit as we are requesting for the 64 bit version of Electron while compiling the app 😕
