### ISSUE TITLE
running on docker¿?

### ISSUE THREAD

**Issue by mmorales99** [ytmdesktop/ytmdesktop#111]
im trying to load the program in docker so i can have a multiservice machine isolated from the os, but i getting docker cannot load the app.
is there someone how had achive this or im just kinda dumb¿?

**Comment by adlerluiz** [comment]
I don't tried run on docker

**Comment by rickinbsb** [comment]
Can you please re-open the issue with more informations? Please explain how are you trying to use the app and what errors are you getting
