### ISSUE TITLE
Low volume

### ISSUE THREAD

**Issue by Marioysikax** [ytmdesktop/ytmdesktop#1110]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Setting up volume in the application, the volume is always lower than expected to actually come through. I have uploaded local MP3 file to YTM, the volume at max is identical with Foobar2000 and through Chrome, but YTMDesktop is significantly lower volume. 
I have checked I haven't changed OS volume settings and ensured it's also at max for all the applications and only master volume is lowered to half. 

### Expected Behavior

I would expect that if I set up the volume slider at max both in foobar, chrome and in the application, the volume would be exactly the same. 

### Steps To Reproduce

- Open up YTM on browser and the application 
- Set volume on both to maximum 
- Play exactly the same song in both for couple seconds 

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Marioysikax** [comment]
I have tried both % and dB settings, both cap at same maximum. 
Also double checked stuff like Windows own mixer but everything is set at 100% there. 

Here's video of playing in Chrome, then same song on the YTMD, you can just open in something like Audacity to see immense volume difference if you don't hear it. 
https://cdn.discordapp.com/attachments/666421129027518474/1113830698768404490/output.mp4

**Comment by mingjun97** [comment]
Encountered the same issue. I got it fixed by switching back to % volume settings and restarting the app.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

In YTMDv2 we do a force update on the Volume each time you swap this settings, so I suspect that this issue is fixed now~
