### ISSUE TITLE
Login to google account

### ISSUE THREAD

**Issue by msebastian100** [ytmdesktop/ytmdesktop#1111]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

400. Dies ist ein Fehler.

Die Anfrage kann vom Server nicht verarbeitet werden, da sie fehlerhaft ist. Senden Sie die Anfrage nicht noch einmal. Mehr Informationen liegen uns nicht vor.

### Expected Behavior

Login to google Acconut

### Steps To Reproduce

click on the login button
Enter email and press enter

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Duplicate of #866
