### ISSUE TITLE
Add how to setup dev environment

### ISSUE THREAD

**Issue by Adar-Dagan** [ytmdesktop/ytmdesktop#1112]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Add a file describing the dependencies of the project and what commands to run in order to get the development environment set up.

**Comment by Alipoodle** [comment]
While not a perfect guide as we have some extra libraries that are missing such as you need VS 2015 installed for some of the Windows Packages.

https://github.com/ytmdesktop/ytmdesktop#installing-ytmdesktop
this provides you the list of what you need to do. There's also a basic understanding of how to use GitHub and some of the tools if you are planning to develop with them.

**Comment by Alipoodle** [comment]
This has been updated and improved with the V2 codebase.
https://github.com/ytmdesktop/ytmdesktop?tab=readme-ov-file#developing

Closing with the new Source.
