### ISSUE TITLE
add adblock

### ISSUE THREAD

**Issue by DaniilProtogen** [ytmdesktop/ytmdesktop#1113]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

advertising

### Solution

add ublock 

### Alternatives

ad blocker

### Anything else?

![image](https://github.com/ytmdesktop/ytmdesktop/assets/113824079/da44d184-a480-40de-87ad-b2b0a65cc3da)

web : https://ublockorigin.com/

**Comment by Alipoodle** [comment]
#114
