### ISSUE TITLE
A JavaScript error occured in the main process

### ISSUE THREAD

**Issue by Super-Gil** [ytmdesktop/ytmdesktop#112]
It always shows this error message and my music would be paused. Once I close this, the music resumed... Is this a bug? It would be good if you could try to solve it! Thanks so much.
Running on Windows10.
I am a web developer and since that I have installed git and node.js...
![Screenshot_20200307213640](https://user-images.githubusercontent.com/41502813/76144487-ef68e000-60bb-11ea-8650-2b1bf173d146.png)

**Comment by amatayamada** [comment]
Another copy with similar crash. Music is streamed behind a HTTP proxy if it's relevant. Happy to provide more logs if needed.

![obraz](https://user-images.githubusercontent.com/27951815/77744379-d9df3a00-7019-11ea-8651-c8494159f319.png)

**Comment by adlerluiz** [comment]
the error happens when the system is unable to download the album image for notification

**Comment by rickinbsb** [comment]
Fixed on 1.10
