### ISSUE TITLE
Continue playing current song after restart

### ISSUE THREAD

**Issue by Noah-A-Schwartz** [ytmdesktop/ytmdesktop#1121]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

When the app is closed, whether it be from closing just the program itself or restarting the device, It would be nice to continue playing the last playing song. 

Currently, this seems to be half baked into the app, where you are taken to the last page you were on. This is fine if you're on the page for just one song, but if its a whole album, the app does not save the song you were on.

So this basically comes down to, on start up, continue playing whatever was playing last when the app was closed in addition to taking you to the last page you were on. 

### Solution

Save the currently playing song to the the app storage, continue playing it when app is started.

### Anything else?

Maybe this is a bug? It sounds like this is what the "Continue Where you left off" setting should do, but there is no selected song when I restart the app with that setting enabled. Windows 11 PC.

_No response_

**Comment by Hershey025** [comment]
you can enable continue where you left off in settings and then playback

**Comment by Noah-A-Schwartz** [comment]
> you can enable continue where you left off in settings and then playback

As I stated in my initial post, it doesnt work. I have that enabled If i quit the app then reopen it, the last song playing is not selected. The setting is enabled. @Hershey025

**Comment by Alipoodle** [comment]
The feature was improved in a 1.14.X update to grab the details of the song.
The old Continue where I left off only stored the last webpage you were on, however it wouldn't grab the details of the song/playlist if you had the player closed.

Can you try using the 1.14.2 build and see if this works better for you?

**Comment by Noah-A-Schwartz** [comment]
Thanks! Updating to the latest version worked, didnt realize I wasnt on the latest....I had downloaded the version from the website for windows, but it still links to like 1.13.x (didnt notice that was old) so I had to go the github releases to actually find the newest. But it does work on the newest version!

**Comment by Hershey025** [comment]
The version 1.14.2 is still in beta since it has many bugs. but it will soon become a stable release.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
