### ISSUE TITLE
very unoptimised 

### ISSUE THREAD

**Issue by Sponachs** [ytmdesktop/ytmdesktop#1123]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

very unoptimised app downloading stuff without consent and it takes too long just to play a plalist (2 mins) 

### Expected Behavior

it should open up with out waiting a two generations and play a playist the user has suggested 

### Steps To Reproduce

not really a an error 

### YTMDesktop

v1.13

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by Sponachs** [comment]
not really a problem like an error, sorry to staff or builders of the ytm desktop app sorry

**Comment by Alipoodle** [comment]
> Downloading stuff without consent?
What are you referring to with this?
Locales?

> Taking 2 generations to open
Not had this issue myself.
Could you share some information regarding your system you are using and actually time how long it takes.
Most things take no longer than it would do inside of chrome for me.
