### ISSUE TITLE
"Video Wake Lock" when playing any music, regardless of video or not

### ISSUE THREAD

**Issue by Xetrill** [ytmdesktop/ytmdesktop#1124]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When playing music, regardless of if the content is a video or not, a power Video Wake Lock is requested.
Meaning the display will never be turned off.

You can check power requests in Windows via `powercfg.exe /requests`.

### Expected Behavior

I'd argue the app is a music player. Video is an idiosyncrasy because of YT. And no "Video Wake Lock" should ever happen.

The display should turn off after the in Windows configured idle period.

### Steps To Reproduce

1. Start the app
2. Play any music
3. Start a CMD/PowerShell and execute `powercfg /requests`
4. Note the "Display" "Video Wake Lock" by "YouTube Music Desktop App.exe"

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Checking this again, Appears to correctly label it as `EXECUTION` category now with `Playing Audio` after it :)

Will close this issue as Solved with V2.
If this issue is still occuring for you on v2, please create a new ticket.
