### ISSUE TITLE
Japanese character support missing from flatpak release

### ISSUE THREAD

**Issue by tommydrum** [ytmdesktop/ytmdesktop#1126]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Any reference to Japanese Hiragana, Katakana, or Kanji characters all get rendered as the failover square box. This includes both within the embed window, as well as the settings page (under the Language selection). I don't dare to change the language, as likely everything will be square boxes.

This likely also affects Chinese and Korean, as I don't see any Kanji or Korean characters in the language option list.

This is under Flatpak v1.13.0 from the FlatHub repo.

### Expected Behavior

Japanese characters render correctly.

### Steps To Reproduce

Go to "Settings"
In General, select the dropdown for "Language"
On the bottom 4 items, only the last is rendered correctly, the other 3 are using failover characters.

### YTMDesktop

v1.13.0

### OS

Fedora

### OS Version

38

### Arch

x64

### Installation way

Flatpak

**Comment by mingjun97** [comment]
I guess the reason for this is lacking some font files.

**Comment by tommydrum** [comment]
> I guess the reason for this is lacking some font files.

Yep, that said, as fonts is included inside the flatpak, the fix really is just to install/include more fonts into the flatpak (essentially making it a configuration issue)

**Comment by tommydrum** [comment]
This looks like it's a more general flatpak issue with ostree. Closing as there's likely nothing that can be done here.

**Comment by tommydrum** [comment]
For the temporary workaround, within `~/.var/app/app.ytmdesktop.ytmdesktop/data` create `fonts` dir.. with something like `mkdir -p ~/.var/app/app.ytmdesktop.ytmdesktop/data/fonts`.

Then download/extract "All Static Language Specific OTCs" from https://github.com/notofonts/noto-cjk/releases into that directory. You just want the .ttc files in there, and the chromium embed will pick it up.
