### ISSUE TITLE
The scrollbar is not clearly visible

### ISSUE THREAD

**Issue by Hershey025** [ytmdesktop/ytmdesktop#1127]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

The youtube music scrollbar is not clearly visible
![Screenshot (35)](https://github.com/ytmdesktop/ytmdesktop/assets/94620635/e6211914-51de-4729-81f3-d8380b5f6937)

### Solution

It would be better if it had a scrollbar that is more clearly visible like this
![Screenshot (36)](https://github.com/ytmdesktop/ytmdesktop/assets/94620635/0dd5c01b-8d00-469b-9464-9373fa547c6f)

### Alternatives

use ytm in chrome

**Comment by Alipoodle** [comment]
Hi there.

This is the NATIVE Scrollbar which is given to YTM (nothing edited to it)
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/a5bef3db-02cd-4d32-bf45-c550333eb0a4)


if you wish to customise it yourself please read up and use the Custom CSS to apply your own one for YouTube Music:
https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp
