### ISSUE TITLE
Integrate ui window buttons

### ISSUE THREAD

**Issue by ElMaldithoDJ** [ytmdesktop/ytmdesktop#1128]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Hello, I am writing this to know why the window buttons do not integrate with the ui as chrome does, I use linux (ubuntu) to be exact and what I mean is
![image](https://github.com/ytmdesktop/ytmdesktop/assets/24962990/0cb23b68-d6a6-4726-97bd-c404fb51166b)
In this place the 3 window buttons before to the logo, That would make it look awesome.
Image edited in Krita and figma
![image](https://github.com/ytmdesktop/ytmdesktop/assets/24962990/f632960e-82e4-4332-bd51-9317117bc86f)

### Solution

integrate window titlebar before to the logo when title bar is disable in the app config

**Comment by Alipoodle** [comment]
To my knowledge, on Mac we have issues with running the Title bar as we are not using the "fancy" version and using the native one instead.

We don't integrate directly into the webpage as a security measure of the way we are hooking into YTM. We'd prefer not provide the APIs for Closing, Maximizing/Windowing and Hiding into Taskbar inside of the YTM Environment and keep them external.
Additionally with the new UI this also causes a lot more of a UI shift that I don't think is possible anymore to look clean.
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/9070bd4a-557f-4f64-adc6-e77780e2ec74)

**Comment by Alipoodle** [comment]
Future me! 👻

Looking more into this, this is actually a Electron Feature now! Traffic lights can be pushed into the bottom bar cleanly and we can add some CSS onto the Titlebar to allow for it to act as a way of moving.
Currently this is not something we have implimented however this is not impossible, it's just might look a little strange with the new design pushing some objects to no long align as nicely. 🙃

So we might have a play with it all!

**Comment by Alipoodle** [comment]
Double update 😅

We've agreed internally that we will not be doing this, due to actually having to embed into the window the buttons and  stuff like a draggable bar. We want to only include the features which are needed inside of the YTM View and not other bits like the Window management tools ETC.
