### ISSUE TITLE
Back Button is Missing After Update

### ISSUE THREAD

**Issue by njsimpson15** [ytmdesktop/ytmdesktop#1131]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The back button is no longer available.

### Expected Behavior

There used to be a back button before the latest update.

### Steps To Reproduce

1. Click on any album or artist.
2. Notice there's no longer a back button up by the search bar.

### YTMDesktop

1.13.0.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by njsimpson15** [comment]
![image](https://github.com/ytmdesktop/ytmdesktop/assets/53617516/3e23a88b-c1c8-4d04-9ef6-793a901937d8)

**Comment by yiqinfu** [comment]
Same issue for the Mac x86 build as well (ver 1.13.0.0)

**Comment by bravo4one** [comment]
Same, seems like a fundamental option to remove. Please bring it back.

**Comment by Alipoodle** [comment]
This is because YTM has updated their UI. 👀
The element which we looked at for adding in the navigation is no longer the same and a FULL update will need to be pushed to fix this.

**Comment by guywmustang** [comment]
I created a PR that fixes this: https://github.com/ytmdesktop/ytmdesktop/pull/1142

**Comment by floschwend** [comment]
Can this be prioritized? It's makes the UI very difficult to use as navigating back is very convenient.

It looks like the PR is waiting to be merged. Any chances this can be picked up?

Thanks a lot for all your help!

**Comment by guywmustang** [comment]
https://github.com/ytmdesktop/ytmdesktop/pull/1142#issuecomment-1758841073

I put a link in the other PR that has a link to the version 1.14.2 that I built (Windows only).  Previous v1 user experience but everything pretty much is working.

**Comment by Alipoodle** [comment]
As it currently stands, YTMDA v1 is unsupported now.
I plan to do some bits with getting YTMDA v2 shared properly by putting it on relvent package managers and stuff.

But I am planning on getting a 1.14.3 or even a 1.15 out with the changes done by @guywmustang sorted and released.
however that will be the LAST update ever done for the Older v1 version of the application. (Some features like Auto Update + Bug Reporting will be removed from this release)
No support will be provided for that version of the application again as we HIGHLY recommend people move  to YTMDv2 for it's increased security, up to date source code and *most* features already in it, and more to come.

Locale is one of the features which we are working on currently :)

**Comment by floschwend** [comment]
Thanks both for your answers. I downloaded this app a few weeks ago and didn't know there's a 2.0 version available. Just installed it, looks nice *and* has the back/forward buttons. 

Really cool, so certainly no need to continue 1.x from my point of view. 

Thanks again!

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
