### ISSUE TITLE
Browser to YTMDesktop redirect on link click

### ISSUE THREAD

**Issue by Scootz1** [ytmdesktop/ytmdesktop#1134]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

When I click a link for music.youtube.com, it would be nice for a redirect to the YTMDesktop application (similar to Spotify functionality). 

I know the current implementation is Clipboard based, but this doesnt have the best UX.

### Solution

Perhaps a browser extension, Tamper/GreaseMonkey script, or an OS level trigger.

**Comment by Spengreb** [comment]
This also gets me. Usually I end up just searching for the track as using the clipboard setting is a bit weird. 

It only checks the clipboard once so if you accidentally click no, you must first copy something unrelated into your clipboard then copy the ytm music link again. Also if you hit the share button on a track and hit copy there, it picks that up and prompts you to listen to the track you are already listening to

**Comment by Hershey025** [comment]
You can add a button in ytm website to open the link in ytmdesktop. Here's how you can do it-                                                                                
https://github.com/ytmdesktop/YTMD-opener-tampermonkey

**Comment by Alipoodle** [comment]
I suspect that there's nothing else to this issue as the Tamper monkey script is a good example of how to "open in YTMD" with

**Comment by Scootz1** [comment]
The tampermoneky script linked by Hershey025 does not function for me on Firefox 115.0.2
"ReferenceError: loadMusicByVideoId is not defined"
https://i.imgur.com/NurP3er.png

**Comment by Spengreb** [comment]
It seems like there is something wrong with the ytmd handler. I also get this error on chrome on linux. Maybe this will be fixed in the v2 release? 

Firefox it doesnt work at all on linux due to unsupported protocol, probably a firefox issue :(

**Comment by Alipoodle** [comment]
This issue should be solved in the 1.14.2 update as the loadMusicByVideoId was in the wrong scope of code for the Protocol!

However we do plan to fish this sort of thing in V2 although may change how the URI protocol works to allow for better handling of other things!

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
