### ISSUE TITLE
Make an effort to publish new release to brew to not risk being unpublished?

### ISSUE THREAD

**Issue by EloB** [ytmdesktop/ytmdesktop#1135]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I've created a PR to brew with latest version but because it's not considered a stable version they don't merge it and tells they might unpublish unactive repos.
https://github.com/Homebrew/homebrew-cask/pull/151094#issuecomment-1637960172

The latest version solves media keys buttons so please make this thing happen. Very thing is already there!

Is this repo unmaintained now?

### Expected Behavior

Read above

### Steps To Reproduce

Read above

### YTMDesktop

Read above

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

Read above

### Anything else?

Read above

**Comment by Alipoodle** [comment]
This issue was discussed over on the Homebrew
