### ISSUE TITLE
Bring back the "back" button

### ISSUE THREAD

**Issue by bravo4one** [ytmdesktop/ytmdesktop#1137]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

It was there, then it was removed a few years back, then it got put back, and now it's gone again. Major decrease in qol.

### Solution

Bring back a back button or hotkey...

**Comment by e2t** [comment]
Please add forward and back buttons for navigation. After changing the interface by Google, it became difficult to use the application.
