### ISSUE TITLE
The volume mixer in windows 11 shows 2 ytmdesktop icons.

### ISSUE THREAD

**Issue by Hershey025** [ytmdesktop/ytmdesktop#1138]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The volume mixer in windows 11 that allows you to change the volume of each apps shows 2 ytmdesktop icons.
![Screenshot (38)](https://github.com/ytmdesktop/ytmdesktop/assets/94620635/b436e42f-1e78-4ef4-8b90-01c7b4974b7c)
![Screenshot (39)](https://github.com/ytmdesktop/ytmdesktop/assets/94620635/1fd49256-89c1-498b-be81-87e2a398cd60)

### Expected Behavior

It show show one icon for ytmdesktop which should increase or decrease the volume in ytmdesktop.

### Steps To Reproduce

Go to the volume mixer settings, in settings > sound> volume mixer.
See 2 ytmdesktop icons.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/3586d0c2-0cdc-4b7a-a6e2-856744f46a40)

Curious to what might be causing this because I notice other things have this issue. Will investigate more later.

**Comment by Hershey025** [comment]
I just noticed this only happens after i play a song.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
