### ISSUE TITLE
Add keyboard shortcuts to go back and forward. 

### ISSUE THREAD

**Issue by Hershey025** [ytmdesktop/ytmdesktop#1144]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Add keyboard shortcuts to go back and forward. 

### Solution

go to settings > shortcuts then see no option to add / change shortcut to go back and forward. If the back and forward button disappear then at least the shortcut will be there.

### Alternatives

use ytm on the web and press alt + < to back and alt + > to go forward.

### Anything else?

N/A

**Comment by gtimbo** [comment]
Note that the main reason that this would be useful (and I think bump it's priority) is that the forward/back buttons jump around in the interface depending on which YTM page you're viewing, making navigation an exercise in frustration, especially during search.

**Comment by harsh251004** [comment]
Yes you are right 👍

**Comment by Alipoodle** [comment]
Duplicate of #365
