### ISSUE TITLE
Windows Monochrome Tray Icon

### ISSUE THREAD

**Issue by D-Maxwell** [ytmdesktop/ytmdesktop#1145]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I would appreciate an option to turn the tray icon monochrome, which would then automatically adjust depending on the theme set by the user.

### Alternatives

Having tried to replace the icon manually with 3rd party tools such as Resource Hacker, it would seem that the icon used by the app is in fact not that which Windows allows the modification of.

Perhaps fixing that could be an easier solution.

### Anything else?

![image](https://github.com/ytmdesktop/ytmdesktop/assets/98100481/9168eb2e-ec8c-4940-b7fe-67d9942dec45)
![image](https://github.com/ytmdesktop/ytmdesktop/assets/98100481/77b34a6c-1461-4860-ab36-36a3da26eb05)
![image](https://github.com/ytmdesktop/ytmdesktop/assets/98100481/d6223e3b-22d8-4583-a14b-e449bddc852e)

**Comment by A-Matt** [comment]
You appear to be using the wrong application 😵
You are using another project.

Additionally most applications use their coloured logos for their Taskbar / Tray Icons already.
There's other issues such as people using custom accent colours and the tray colours not matching up with the theme for proper readability~
