### ISSUE TITLE
Rainmeter integration not working (WebNowPlayingRedux)

### ISSUE THREAD

**Issue by hugarburdur** [ytmdesktop/ytmdesktop#1146]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Rainmeter's plugin doesn't show YTMDesktop informations and WebNowPlayingRedux outputs following errors:

WNPRedux - Error parsing data from WebNowPlaying
WNPRedux - Unknown message type: TITLE:THE; (TITLE:The Legend of Zelda: Breath of the Wild OST - Rito Village Day)
WNPRedux - Unknown message type: ARTIST:ZELDA; (ARTIST:Zelda Switch)

(I get the same on every track I play through YTMDesktop)

### Expected Behavior

YTMDesktop informations (title, artist...) should be parsed correctly for WebNowPlayingRedux

### Steps To Reproduce

1. Install Rainmeter and latest version of WebNowPlayingRedux ([https://github.com/keifufu/WebNowPlaying-Redux](https://github.com/keifufu/WebNowPlaying-Redux))
3. In YTMDesktop settings, enable Rainmeter integration
4. Open Rainmeter's log to see error

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
YTMDv2 currently does not have this feature, and will close this with the release of it.
