### ISSUE TITLE
Settings window bug - Integration Tab

### ISSUE THREAD

**Issue by realSnosh** [ytmdesktop/ytmdesktop#1149]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

If I go to Integrations and activate the companion server, the settings window is getting blank. Even if I reopen the settings (or restart the app) and click on Integrations, it's going blank again.

### Expected Behavior

not going blank. I want to use the other integrations, but I cant, since its blank.

### Steps To Reproduce

1. Fresh install of YTMD
2. Open Settings
3. Click on Integrations
4. Enable companion server

### YTMDesktop

v2.0.0-rc.1

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

![grafik](https://github.com/ytmdesktop/ytmdesktop/assets/28960389/11346a00-cfe0-4a60-b911-82e79c360811)
^ After clicking on Integrations after I enabled companion server

**Comment by realSnosh** [comment]
Even after I reinstall the app, its still blank. I cant go to Integrations anymore.

I deleted those appdata folders (on Roaming and Local) and everything is getting normal again.

**Comment by NovusTheory** [comment]
Due to how this bug occurs the only fix right now is to keep companion server turned off for rc.1. You can download the build from the CI in the commit above if you'd like to have the fix right away.

**Comment by NovusTheory** [comment]
Fixed in v2.0.0-rc.2
