### ISSUE TITLE
V 2.0RC1: shortcut do not work

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#1150]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I just removed v1.x and installed v2.0rc1; I manually defined the shortcuts (I remember they were already defined in the previous versions).
They don't work. I'm using CTRL+SHIFT+ Up, down, left, right, space

### Expected Behavior

Shortcut working

### Steps To Reproduce

Define shortcut as decribed

### YTMDesktop

2.0rc1

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

exe

**Comment by e2t** [comment]
After restarting the program, the shortcuts worked for me.

**Comment by pdario** [comment]
Yes, today, after system restart, they seem to work!

**Comment by Alipoodle** [comment]
This should still apply instantly, so I'm keeping the ticket open!
I suspect on first applying the Keybind it doesn't apply correctly 😅

**Comment by pdario** [comment]
Is it correct that I need to define them manually after installation?

**Comment by Alipoodle** [comment]
Compared to v1, we don't set any Keybinds by default.
After installing you can pick whatever keybinds you want.

Not sure how, but it should re-register the keybinds after one is updated in the settings menu. ( The same function is used when you start the application up )
Will do some poking around to see what's going wrong.

**Comment by NovusTheory** [comment]
After some investigation I believe I may have found what caused it. There's been changes pushed into development to correct some bugs and I think there may have been one which caused shortcuts to fail to register properly.

Can I get a confirmation that you have `Discord rich presence` disabled? Changing shortcuts with it disabled should result in shortcuts not registering correctly until application restart and having `Discord rich presence` enabled should make everything work as it should

**Comment by pdario** [comment]
Yes, I have all 3 integrations disabled.

**Comment by NovusTheory** [comment]
Is this still a problem in the latest rc's? If it isn't then I'm going to close this issue

**Comment by e2t** [comment]
It's working for me. Thanks!

**Comment by NovusTheory** [comment]
Closing as resolved. If this is still a problem then a new issue should be made for the latest versions
