### ISSUE TITLE
Check for updates broken - YTM 2.0.0-rc.1

### ISSUE THREAD

**Issue by grottas** [ytmdesktop/ytmdesktop#1151]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

 JavaScript's crash on app when checking for update: ERR_UNHANDLED_ERROR.

Once you exit the error message, the app stills working.

### Expected Behavior

Check if there is a new version of the app.

### Steps To Reproduce

1. Go to About in Settings.
2. Click on check for update.

### YTMDesktop

2.0.0-rc.1

### OS

Windows

### OS Version

11 22H2

### Arch

x64

### Installation way

.exe

**Comment by NovusTheory** [comment]
Crossposting from https://github.com/ytmdesktop/ytmdesktop/issues/1139#issuecomment-1699955402
> Important note: The auto updater is disabled and check for updates will throw an error. This is expected and will remain this way until v2 is fully released

The button will work when an official v2 release is published.

I'll keep this issue open until v2 releases

**Comment by Alipoodle** [comment]
Closing this with the full release of YTMDv2
