### ISSUE TITLE
last.fm scrobbling does not include album info anymore

### ISSUE THREAD

**Issue by charlesmconard** [ytmdesktop/ytmdesktop#1152]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Up until around the middle of July, the desktop app was sending album info to last.fm and I was able to see my top weekly using .fmbot. 
As time went on my scrobbles kept decreasing but I wasn't sure why. I finally logged into last.fm and saw all the tracks were being scrobbled but nothing was being shown under the "albums" tab.

I then tried using the web player and that scrobbled tracks as expected.

### Expected Behavior

The desktop app should be sending album information to last.fm and last.fm profiles should be showing scrobbles under "albums" along with "scrobbles", "artists", and "tracks" 

### Steps To Reproduce

1, Play a track
2. Check last.fm "albums" tab
3. scrobble is not there

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Album has been a problem for the method in YTMD v1 for a Long time 😅
it kept on supplying `_` or `undefined` to Last.fm. The main problem was that we were querying the Elements in the UI regarding the album's name, and it wasn't clear way of saying "this is the album" from that.

In V2 we don't have a that data as it's currently not included in the core data package we get from the YTM internal API. So we don't supply the album at all.}
Come later down the line when we have the album we will send this data.

**Comment by charlesmconard** [comment]
I appreciate the explanation. I must have fooled myself into believing it was working up until mid July.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

To my knowledge this issue is now fixed in YTMDv2 as the Last.fm integration has been entirely re-worked.
