### ISSUE TITLE
Exception upon shutting down v2.0rc1

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#1153]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When I click exti on the tray icon, this happens:

![Uploading image.png…]()

Clicking ok, repeats this forever and I can't close YTM

### Expected Behavior

Clean shtudown

### Steps To Reproduce

On Windows 11, exit via tray icon

### YTMDesktop

2.0rc1

### OS

Windows

### OS Version

11

### Arch

x86

### Installation way

exe

**Comment by pdario** [comment]
Arch is x64. sorry

**Comment by NovusTheory** [comment]
Fixed in v2.0.0-rc.2
