### ISSUE TITLE
Functionality explanations

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#1154]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I don't know where to ask, so... 

Please add explanation for these two! :-)
![image](https://github.com/ytmdesktop/ytmdesktop/assets/5813131/9e575a20-2a3d-4b0a-882d-e7b7fe1481e0)

**Comment by Alipoodle** [comment]
> Speaker Fill

On surround sound setups, Chromium tends to only play through the front left+right speakers.
Enabling that option *should* make it play through all speakers .

> Ratio volume

This makes YouTube music have lower levels of volume. By default it's quite loud so this gives it a more aggressive curve at lower volumes.

So 5% volume is actually 0.125% (or something like that) with that feature on!

**Comment by pdario** [comment]
Thank you, I find the second very useful!
