### ISSUE TITLE
Error: Could not get code signature for running application

### ISSUE THREAD

**Issue by Alipoodle** [ytmdesktop/ytmdesktop#1156]
Is this the right place to share a bug I'm getting on launch of the x64 mac executable? 

``` Uncaught Exception:
Error: Could not get code signature for running application
at 54575 (/Applications/YouTube Music Desktop App.app/Contents/Resources/app/.webpack/main/index.js:8:640600)
at i (/Applications/YouTube Music Desktop App.app/Contents/Resources/app/.webpack/main/index.js:8:1376119)
at /Applications/YouTube Music Desktop App.app/Contents/Resources/app/.webpack/main/index.js:8:1376891
at Object.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/app/.webpack/main/index.js:8:1376918)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Object..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at node:internal/modules/cjs/loader:967:12
at Function._load (node:electron/js2c/asar_bundle:2:13330)
at node:electron/js2c/browser_init:2:122264
```

<img width="514" alt="Screenshot of the above error message, as shown on a mac OSX UI" src="https://github.com/ytmdesktop/ytmdesktop/assets/9271438/4b9068cf-779f-4d24-bb92-08d80828c9f8">

--

This is on an iMac running OSX 13.5.1, can provide more specs if useful! :) 

I'll try compiling locally and see if it's the same.

_Originally posted by @yochannah in https://github.com/ytmdesktop/ytmdesktop/issues/1139#issuecomment-1706535535_

**Comment by Alipoodle** [comment]
Could I ask for more specifically which may you are running M1/2?
And what happened in terms of compiling locally.

During my quick test of running it in MacOS:
I only fixed some of the glaring issues with Window Management , Icon + Titlebar and all compiling was done by myself.
1 friend of mine successfully installed a copy from Github Actions during the middle of development 😓.

Both myself and Novus are Windows users so MacOS bugs will be a bit harder to work on by ourselves.

**Comment by yannick9906** [comment]
I get the same error. I am on a MacBook Pro with M2 Pro.
When I try to open the app from the arm64 archive I get "This app is damaged and can't be opened."
![image](https://github.com/ytmdesktop/ytmdesktop/assets/8795691/99e54284-7942-4d76-b921-102c288b21ce)

When I try the x64 version I get the code signature error from above.
Both pre-release builds are affected.
If I can look into getting further information I am here to help..

**Comment by gwonhong** [comment]
> I get the same error. I am on a MacBook Pro with M2 Pro running Ventura 13.5.2. When I try to open the app from the arm64 archive I get "This app is damaged and can't be opened." ![image](https://user-images.githubusercontent.com/8795691/266866687-99e54284-7942-4d76-b921-102c288b21ce.png)
> 
> When I try the x64 version I get the code signature error from above. Both pre-release builds are affected. If I can look into getting further information I am here to help..

Same error with the v2.0.0-rc.2 release, arm64 version, on a MacBook Pro with M1 Pro, running Ventura 13.5.2. Hope it helps for debugging :)

**Comment by yinfangchen** [comment]
I got the same error.

**Comment by mingjun97** [comment]
Tentative workaround:

Step 1: Create a self-signed certificate.

1. Open Keychain Access.
2. Choose Keychain Access(In the menu) > Certificate Assistant > Create Certificate ...
3. Enter a certificate name
4. Set 'Certificate Type' to 'Code Signing'

Step 2: Sign the application using the generated certificate

1. Open terminal
2. Execute the command: `codesign -fs CERTIFICATE_NAME --deep /path/to/YouTube\ Music\ Desktop\ App.app`

After that, you should be able to open the YTMDesktop V2.

**Comment by yinfangchen** [comment]
Thanks a lot @mingjun97 !
Glad to meet you here Mingjun!!!

**Comment by Alipoodle** [comment]
Could I check if this is an issue if you SELF build the project locally?

During Development while we tested this, it worked fine on the GitHub Builds I had provided to 1/2 users and worked fine on a self built project 🤷‍♂️

The fix above is helpful for a initial start, but obviously this is pushing the limits a bit regarding what I feel users should have to do to install the project. 😅

**Comment by fimion** [comment]
On an M2 Max: getting same popup as others, however it seems to build and run fine locally.

**Comment by Alipoodle** [comment]
Curious if it's just an issue with the publish.
I'll see if I can share one of the artifacts from GitHub and see if they work fine.

If so then it's down to the publish command!

**Comment by NovusTheory** [comment]
Auto updater has been disabled for macOS. This error should no longer occur

**Comment by gotgenes** [comment]
> I get the same error. I am on a MacBook Pro with M2 Pro running Ventura 13.5.2. When I try to open the app from the arm64 archive I get "This app is damaged and can't be opened." ![image](https://user-images.githubusercontent.com/8795691/266866687-99e54284-7942-4d76-b921-102c288b21ce.png)
> 
> When I try the x64 version I get the code signature error from above. Both pre-release builds are affected. If I can look into getting further information I am here to help..

I am still experiencing this error with rc.4 arm64 build on Ventura 13.5.2.

**Comment by mikeflynn** [comment]
I'm still seeing the same "This app is damaged and can't be opened." error on rc.5 on an M1 MacBook Pro.

**Comment by NovusTheory** [comment]
@gotgenes @mikeflynn "This app is damaged and can't be opened." should be made into a separate issue as I don't believe this issue is related as it was about a code signature error. The x64 version of mac should be working properly. If the arm version is the one appearing as damaged can you try out the [latest CI build for it here](https://github.com/ytmdesktop/ytmdesktop/actions/runs/6678783817) and if it's still reproducible then open another issue about it. The template doesn't have an arch option for arm64/m1 so just specify whatever and state in a description somewhere it's for arm64/m1

**Comment by gotgenes** [comment]
@NovusTheory Sure thing, I created #1192.
