### ISSUE TITLE
Application crash upon Discord crashing/exiting

### ISSUE THREAD

**Issue by MaxFerney** [ytmdesktop/ytmdesktop#1160]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

At 2 occasions I had discord crash on me, and the app tossed 2-4 errors up (close one, another opens), each time. the first occurrence was discord just crashing, caused the application to crash as well. Second occurrence, I needed to hard restart discord, so I opened the task tray and closed discord - which then caused the application to crash.

### Expected Behavior

Not crash based on discord state

### Steps To Reproduce

1. Open Discord
2. Open YTMD
3. have "continue where left off" enabled (but not "pause on launch")
4. open the task tray
![image](https://github.com/ytmdesktop/ytmdesktop/assets/46454102/e7bdfe2f-9e11-4e46-953b-197b90b927d1)
5. Ensure discord rich presence is working (may need to reboot ytmd a few times)
    a. ![image](https://github.com/ytmdesktop/ytmdesktop/assets/46454102/57b9124e-ab4f-4065-ae8f-07dd85150066)
    b. If you see this, then you need to restart ytmd
6. Close discord. (might need to let both run for a minute or so, cannot nail down consistent reproduction.

... - as I write these more inconsistencies pop up. I've had it purposefully crash 7ish times while trying to get a reliable list of reproduction steps..., as well as a few other bugs that are a bit too difficult to reproduce within the first few attempts.

Will also mention if ytm crashes or does not close gracefully, it will not save the latest song as for the continue playing (mentioning here since I discovered it along the way)

additional things I attempted fiddling to narrow down cause:
- Discord: Re-added YTMD as a playable game, it then successfully showed up.
- YTMD Settings: 
  - toggle rich presence
  - toggle continue where you left off
    - and pause on initialize

### YTMDesktop

v2.0.0-rc.2

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0-rc.2
    Electron 26.1.0
    Windows NT 10.0.19045

Name: Error
Message: connection closed
Cause: Unknown

Error: connection closed
    at C:\Users\Sam\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc2\resources\app\.webpack\main\index.js:8:86251
    at Map.forEach (<anonymous>)
    at e.exports.<anonymous> (C:\Users\Sam\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc2\resources\app\.webpack\main\index.js:8:86229)
    at Object.onceWrapper (node:events:628:26)
    at e.exports.emit (node:events:513:28)
    at e.exports.onClose (C:\Users\Sam\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc2\resources\app\.webpack\main\index.js:8:97631)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)

**Comment by NovusTheory** [comment]
I've been aware of this problem but thank you for opening an issue about it. This is being looked into already.

**Comment by NovusTheory** [comment]
Will close this once the next rc is published

https://github.com/ytmdesktop/ytmdesktop/commit/d7cb163bc23e2c2535ca47ea59eaeeb6b6f357e7 will be in the next rc and should correct this issue

**Comment by NovusTheory** [comment]
Closing as this is part of rc.4 release
