### ISSUE TITLE
Continue where left off fails upon a crash

### ISSUE THREAD

**Issue by MaxFerney** [ytmdesktop/ytmdesktop#1162]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

If a crash occurs, the feature "Continue where I left off" fails to load the most recent one. instead, it will load the last one from the most recent non-crash close of the app. 

### Expected Behavior

Regardless of how closing method is run, be it a graceful shutdown or via crash, save the most recent song. Therefore even if a crash occurs, it'll be able to continue smoothly.

### Steps To Reproduce

1. enable the "Continue where I left off" feature
2. Force/trigger a crash of the application while listening to a different song than what it started on.
3. re-open application - song will return to the one used in the inital session rather than the last one before the crash

### YTMDesktop

v2.0.0-rc.2

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

Assuming the function to save that most recent song occurs on a close, would suggest moving that function to update said save upon a new song loading, that way regardless of how the application is terminated the latest song will be atleast in range of the most recent.

**Comment by NovusTheory** [comment]
This was an intentional design decision to prevent writing to disk more often than necessary. We can look into improving this method as it saves upon cleanly exiting the application but not in the cases you provided.

It would also be wrong to assume the application would do what it needs to properly if it crashes. The state of the application is no longer valid upon crashing.

**Comment by Alipoodle** [comment]
We've discussed this a bit internally, the best thing I was able to think of would be to do it based upon a new Queue 🤷‍♀️
It would provide you with a good idea of what you were last doing and would mean it would only write to the disk a few times as you're unlikely to completely wipe out your queue every so often.

**Comment by MaxFerney** [comment]
Sounds good, and thank you for clearing that up, and makes sense that crash
state shouldnt be saved.

**Comment by NovusTheory** [comment]
https://github.com/ytmdesktop/ytmdesktop/commit/9adfac41df57ab5225332f41d4eb81f3ee4c8fef

This commit should help alleviate this issue by saving the state to disk every 5 minutes. This will likely just be a temporary patch up that I am satisfied with until a more robust and consistent method of saving the state to disk is made

**Comment by Alipoodle** [comment]
This appears to be added as per the commit above. So closing the issue
