### ISSUE TITLE
Immediate crash when playing songs with 1-letter titles

### ISSUE THREAD

**Issue by joshcarst** [ytmdesktop/ytmdesktop#1167]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I consistently run into a crash when playing songs with 1-letter titles, for example 21 Savage - X (ft. Future) or Kendrick Lamar - i. The crash log looks like:

```
YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0-rc.3
    Electron 26.2.1
    Windows NT 10.0.19045

Name: Error
Message: child "activity" fails because [child "details" fails because ["details" length must be at least 2 characters long]]
Cause: Unknown

Error: child "activity" fails because [child "details" fails because ["details" length must be at least 2 characters long]]
    at e.exports._onRpcMessage (C:\Users\Josh\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:86965)
    at e.exports.emit (node:events:513:28)
    at C:\Users\Josh\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:97556
    at d (C:\Users\Josh\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:96955)
    at Socket.<anonymous> (C:\Users\Josh\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc3\resources\app\.webpack\main\index.js:8:97342)
    at Socket.emit (node:events:513:28)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

It seems title attributes like '(ft. XYZ)' don't count towards title character length.

### Expected Behavior

No crash occurs upon playing these songs.

### Steps To Reproduce

1. Search for any song with a 1-letter title (examples given above)
2. Initiate playback
3. View error log

### YTMDesktop

v2.0.0-rc3

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
First of all:
![confused-really](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/450638d8-b663-46e7-8c45-626e3d437664)

Second of all, could you provide an example.

This issue is to do with the Discord Rich Presence requiring a minimum of 2 characters for the strings 😂
I added a fix for string TOO LONG but I need to fix it for 1 character songs as well.

**Comment by joshcarst** [comment]
> Second of all, could you provide an example.

Sure, I mentioned in the OP but the song I originally noticed this on was 21 Savage - X (ft. Future). Confirmed it's due to character length with Kendrick Lamar - i.

**Comment by Alipoodle** [comment]
Ah I missed that 😄 
I found Oh Sees - C (izjtDkTUIyg) while looking for this issue.

**Comment by NovusTheory** [comment]
Closing as this is part of rc.4 release
