### ISSUE TITLE
Memory Leak 

### ISSUE THREAD

**Issue by LyGhT1337** [ytmdesktop/ytmdesktop#117]
There's a memory leak issue which occures over time.

I had the programm opened for about 24 hours +- 2 hours and it was insanely laggy, so i checked taskmanger and it seemed to use around 2.5gb ram.
Restarted it ->200mb usage instead of 2.5gb.

Don't have a screenshot of it because it was 2 days ago, but if it happens again i'll happily take a screenshot and edit the issue.

**Comment by kilrah** [comment]
Same here on 1.13.0. Just closed it as it was using 5.5GB of RAM after a couple of days.
