### ISSUE TITLE
Bring back Like/Dislike Shortcuts

### ISSUE THREAD

**Issue by Sollaze** [ytmdesktop/ytmdesktop#1172]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I used those shortcuts extensively in previous versions which allowed me to use the app largely without manually interacting with it. It would be great to have that functionality back in v2.

It'd also be great to have auto-skip on disliked songs back but might be worth a separate feature req + it had many issues in previous versions with it skipping multiple songs in a row so it would make sense if it's a complicated problem.

**Comment by NovusTheory** [comment]
This is already committed in development https://github.com/ytmdesktop/ytmdesktop/commit/dfe5259d8e6d7cfba3f24bd63a61474133e74538 :)

**Comment by NovusTheory** [comment]
Closing as this is part of rc.4 release
