### ISSUE TITLE
Icons not showing in settings or the tray icon

### ISSUE THREAD

**Issue by FranciscodeMaussion** [ytmdesktop/ytmdesktop#1173]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

![image](https://github.com/ytmdesktop/ytmdesktop/assets/26274597/8c6b6172-43d2-48ce-9e69-9cb72d589f99)
![image](https://github.com/ytmdesktop/ytmdesktop/assets/26274597/f7860d2b-aec5-49e5-adef-07cd19b9de3a)
As you can see in the images, the Icons are not showing in the settings modal and in the tray icon and using the label or maybe a fallback?

### Expected Behavior

show the icons or a clearer descritpive text

### Steps To Reproduce

1. Tray:
   1. right click on the tray icon
   2. see the menu
4. settings:
   1. press the cog/settigns button
   2. see the modal

### YTMDesktop

v1.14.2

### OS

Linux

### OS Version

ArchLinux

### Arch

x64

### Installation way

pacman/aur

**Comment by Alipoodle** [comment]
There is a duplicate for this, and will probably find it later!
But the language pack has failed to download from the GitHub servers 😅

These are the default strings which it would show!

**Comment by FranciscodeMaussion** [comment]
Couldn't find the duplicate! srry for that... will try again later

**Comment by FranciscodeMaussion** [comment]
Using `en.json` from https://github.com/ytmdesktop/ytmdesktop/issues/967#issuecomment-1154658839 solved the issue
