### ISSUE TITLE
Broken view, can't use the app

### ISSUE THREAD

**Issue by uhtaceare** [ytmdesktop/ytmdesktop#1174]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I open the app to see it pixelated or black, sometimes it shows images of my other programs. I reinstalled the app a few times and it is still like this. Rebooting the computer didn't change anything. Just to check I uninstalled v2.0.0-rc.3 and installed v2.0.0-rc.2, v2.0.0-rc.2 works fine for me.

### Expected Behavior

To be able to use the app normally, see and choose my music, adjust volume and so on. 

### Steps To Reproduce

1. Download and install the pre-release latest .deb file.
2. Lauch the app.

### YTMDesktop

v2.0.0-rc.3

### OS

Linux Mint 21.2 Cinnamon

### OS Version

5.8.4

### Arch

x64

### Installation way

Installed using the .deb file from Github releaseas.

### Anything else?

![image](https://github.com/ytmdesktop/ytmdesktop/assets/126416137/84ea461d-66f0-43bd-ac04-3f19c4ffedf8)

https://github.com/ytmdesktop/ytmdesktop/assets/126416137/adb04fbf-cc0e-462d-beaf-9a95b3d68031

**Comment by NovusTheory** [comment]
This definitely looks like some foul play with your GPU if what is being recorded is what you're seeing. I don't know your specific setup but I would imagine your desktop would be having problems too if that was the case. Try disabling hardware acceleration for the app explicitly. There is a native configuration option in config.json to do this.

**Comment by uhtaceare** [comment]
Yea, I recorded what it showed me after launching the app. I'll try find the config and try with GPU acceleration off.

**Comment by uhtaceare** [comment]
Yep, that fixed it on v2.0.0-rc.3, thank you.
