### ISSUE TITLE
Crash upon changing any setting

### ISSUE THREAD

**Issue by MaxFerney** [ytmdesktop/ytmdesktop#1177]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I went to turn off discord rich presence and re-enable it - before opening discord

### Expected Behavior

A toggle of the setting without a crash

### Steps To Reproduce

1. open application
2. Navigate to settings
3. disable *or* enable discord rich presence while discord is closed
4. crash will occur (log below)

### YTMDesktop

v2.0.0-rc.4

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0-rc.4
    Electron 26.2.1
    Windows NT 10.0.19045

Name: TypeError
Message: Use `delete()` to clear values
Cause: Unknown

TypeError: Use `delete()` to clear values
    at e.exports.set (C:\Users\Sam\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc4\resources\app\.webpack\main\index.js:8:67201)
    at IpcMainImpl.<anonymous> (C:\Users\Sam\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc4\resources\app\.webpack\main\index.js:8:515419)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89074)
    at WebContents.emit (node:events:513:28)

**Comment by NovusTheory** [comment]
This is happening due to a change in the configuration file. An oversight was made and a migration wasn't made to add the default value into the config file. A commit has been pushed to add one.

To fix this you will likely have to go into your config.json file and add `zoom` under `appearance` as that is the one likely missing.
```js
"appearance": {
	// ... other config keys
	"zoom": 100
},
```

**Comment by NovusTheory** [comment]
Closing as this is corrected in v2.0.0-rc.5
