### ISSUE TITLE
V2rc4 can't start

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#1179]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

It stays like this

![image](https://github.com/ytmdesktop/ytmdesktop/assets/5813131/a2b4612c-7831-4881-ac0d-c14dccc4d5bf)

### Expected Behavior

Normal startup

### Steps To Reproduce

Start YTMD; I also tried killing all YTMD processes

### YTMDesktop

2rc4

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

EXE

### Anything else?

Yesterday it worked as usual

**Comment by pdario** [comment]
Now I noticed it briefly showed error -3 when I clicked on the home button.

**Comment by Alipoodle** [comment]
https://github.com/ytmdesktop/ytmdesktop/issues/1139#issuecomment-1758660087

**Comment by NovusTheory** [comment]
Closing as this is fixed in v2.0.0-rc.5
