### ISSUE TITLE
lyric follower

### ISSUE THREAD

**Issue by Antexous** [ytmdesktop/ytmdesktop#1185]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

the thing where it follows lyrics

### Solution

the thing where it follows lyrics

### Alternatives

the thing where it follows lyrics

### Anything else?

the thing where it follows lyrics

**Comment by roighteously** [comment]
is this the thing where it follows lyrics?

**Comment by Alipoodle** [comment]
Duplicate of #809
