### ISSUE TITLE
integrations disabled because "safeStorage isn't available"

### ISSUE THREAD

**Issue by Readf0x** [ytmdesktop/ytmdesktop#1186]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I used to use this app on Gnome back when I used Pop!_OS a ~year ago, and it was fine, but after installing on my Arch system I can no longer use the integrations. I suspect this is because I use kwallet on my arch system, but there have not been any complaints from KDE users so I have no clue.

### Expected Behavior

Integrations are allowed and safestorage works. Ideally you could just put a warning that safestorage can't be used, like vs code does.

### Steps To Reproduce

Open app
Open settings dialog
Select integrations
_Not_ be allowed to toggle companion server or last.fm :(

### YTMDesktop

v2.0.0-rc.4 commit 185d4e

### OS

Hyprland on Arch

### OS Version

Hyprland v0.31.0-7-ga0b675ec commit a0b675ec9e57af8bc631fc8cc54d062b58669a9f

### Arch

x64

### Installation way

compiled from source (aur)

### Anything else?

![image](https://github.com/ytmdesktop/ytmdesktop/assets/57838054/ab02694f-e995-4130-b44e-17db20eda8a4)

**Comment by NovusTheory** [comment]
I'm not sure if we'll explicitly allow enabling an integration if safe storage is unavailable as we encrypt data on disk that is sensitive. This isn't to hide it from you as a user or anything on your PC but it does prevent something like an authentication token sitting around on disk in plain text.

On the note of it not being available to you linux is a bit of a mess with safeStorage and electron/chromium has a hard coded selection method. The documentation for [safeStorage.getSelectedStorageBackend()](https://www.electronjs.org/docs/latest/api/safe-storage#safestoragegetselectedstoragebackend-linux) gives a hint how you can manually tell the application what backend to use.
```
basic_text - When the desktop environment is not recognised or if the following command line flag is provided --password-store="basic".
gnome_libsecret - When the desktop environment is X-Cinnamon, Deepin, GNOME, Pantheon, XFCE, UKUI, unity or if the following command line flag is provided --password-store="gnome-libsecret".
kwallet - When the desktop session is kde4 or if the following command line flag is provided --password-store="kwallet".
kwallet5 - When the desktop session is kde5 or if the following command line flag is provided --password-store="kwallet5".
kwallet6 - When the desktop session is kde6.
unknown - When the function is called before app has emitted the ready event.
```

**Comment by Readf0x** [comment]
Thank, that has solved my issue. It would be nice if you could add that to setting so I don't have to edit the desktop file, but oh well. Unless there's something you need to implement, I'll be closing this issue.

**Comment by Readf0x** [comment]
Thank, that has solved my issue. It would be nice if you could add that to setting so I don't have to edit the desktop file, but oh well. Unless there's something you need to implement, I'll be closing this issue.

**Comment by asbestosbill** [comment]
I'm newer to Linux. Can someone walk me through how to "edit the desktop file" to work around this? I'm on Mint 21.3

**Comment by Alipoodle** [comment]
@asbestosbill All things considered... you shouldn't remove this feature for Cryptographically keeping your information safe and secure and encrypting your data. We deliberately want to keep your information secure 😅

Running the application with the additional parameter of `--password-store="PUT_SOMETHING_HERE"` is the method which can be used to achieve this.
```
basic_text - When the desktop environment is not recognised or if the following command line flag is provided --password-store="basic".
gnome_libsecret - When the desktop environment is X-Cinnamon, Deepin, GNOME, Pantheon, XFCE, UKUI, unity or if the following command line flag is provided --password-store="gnome-libsecret".
kwallet - When the desktop session is kde4 or if the following command line flag is provided --password-store="kwallet".
kwallet5 - When the desktop session is kde5 or if the following command line flag is provided --password-store="kwallet5".
kwallet6 - When the desktop session is kde6.
```
Are the options you can add additionally for Linux where the application doesn't automatically detect which one to use.

I'm not aware of how Mint works, but I have no idea which one it uses. 🤷‍♀️

**Comment by filsd** [comment]
I'm NOT new to Linux and I just can't figure it out how to enable LastFM support.
Can someone help?

**Comment by Alipoodle** [comment]
> I'm NOT new to Linux and I just can't figure it out how to enable LastFM support. Can someone help?

Please review this link and see if you need to manually suggest which backend it should be using for your enviroment. 😄 
https://www.electronjs.org/docs/latest/api/safe-storage#safestoragegetselectedstoragebackend-linux

**Comment by filsd** [comment]
> > I'm NOT new to Linux and I just can't figure it out how to enable LastFM support. Can someone help?
> 
> Please review this link and see if you need to manually suggest which backend it should be using for your enviroment. 😄 https://www.electronjs.org/docs/latest/api/safe-storage#safestoragegetselectedstoragebackend-linux

It would be "gnome_libsecret", I'm on Linux Mint Cinnamon.
How do I manually sugest that? 🙏

**Comment by filsd** [comment]
> > I'm NOT new to Linux and I just can't figure it out how to enable LastFM support. Can someone help?
> 
> Please review this link and see if you need to manually suggest which backend it should be using for your enviroment. 😄 https://www.electronjs.org/docs/latest/api/safe-storage#safestoragegetselectedstoragebackend-linux

Nevermind! Just found the problem:
The unofficial Flatpak app does not support that.
Installing the deb version fixes that. :)
