### ISSUE TITLE
Cannot close program in Linux in V2

### ISSUE THREAD

**Issue by andia89** [ytmdesktop/ytmdesktop#1187]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

On Linux when opening the app and you are on a distribution without any "tray" icon support (stock GNOME) the close to tray option makes it impossible to properly close the program as it will always minimize it to tray and never closes it

### Expected Behavior

Is there a possibility to add a quit button somewhere in the app?

### Steps To Reproduce

Open app 
Enable Close to tray icon
Try to close the app

### YTMDesktop

2.0.0

### OS

Linux

### OS Version

GNOME 45

### Arch

x64

### Installation way

rpm

**Comment by NovusTheory** [comment]
This feels way too user specific to implement a fix for. Don't enable close to tray if your operating system doesn't have a tray. This instructs the application to override the native window closing from quitting the application to running it in the background instead.

Ultimately I feel like this issue would be solved by determining whether the operating system has a tray menu and hiding the setting based off that but I'm not aware of any way to query for that information and it would likely apply to only linux which while we do supply builds for we're not going to program very tiny details and edge cases to solve the vastly different experiences users have as it would just become too much.

I'm going to close this as won't fix but feel free to comment more information and I'll reconsider opening this issue.

**Comment by andia89** [comment]
I thought that in the taskbar there would be a good spot to add a "quit" button just like the settings button or the home button. But sure I do understand your reasoning. I just like to have the app in the background without it being open

**Comment by Alipoodle** [comment]
Do you restore it via opening a new process?

**Comment by andia89** [comment]
yes. For now there is no mpris interface added (so I could open it from the mpris player interface) so I open it by running a new process.

**Comment by andia89** [comment]
As a non-invasive and easy fix, would registering a shortcut (like for other programs Ctrl+Q) be an acceptable solution?

this can be added to registershortcuts and might be a useful shortcut for all architectures and OS not only linux
```
  globalShortcut.register('CommandOrControl+Q' , () => {
    applicationQuitting = true;
    app.quit();
  });
```
