### ISSUE TITLE
Additional fields to V2 Companion Server

### ISSUE THREAD

**Issue by ThatGravyBoat** [ytmdesktop/ytmdesktop#1190]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Hello,

I make work on a piece of software that integrated with YTMD for V1 and I am migrating to V2 as requested by many users and developers (https://github.com/ThatGravyBoat/Craftify/issues/82).
Currently in the V2 companion server I am missing some stuff that I need like the following:
- volume
- isAd

These 2 were very important as I used isAd to make the display generic for when an ad is playing due to the nature of how the ads are done they do not look good when displayed in a system specifically done for music.
And for volume pretty self explanatory there is currently no way to get the volume of the player so I cant display it in my custom volume control to allow users to change the volume nicely.

Thanks

**Comment by NovusTheory** [comment]
Volume had been added via https://github.com/ytmdesktop/ytmdesktop/commit/de3624345068d6e54baa494604a3cc954bf0d3d4

**Comment by ThatGravyBoat** [comment]
> Volume had been added via [aad1f77](https://github.com/ytmdesktop/ytmdesktop/commit/aad1f77209486fe6a8be09691f1a665e08766b8c)

Awesome 👍

**Comment by NovusTheory** [comment]
Ad state has been added via https://github.com/ytmdesktop/ytmdesktop/commit/a2dcaa00bb79daeb7330f4938d7cd2ec36d210ea

Seems like the two properties you asked for has been implemented now.

**Comment by ThatGravyBoat** [comment]
Those were all that I needed, thank you!

**Comment by Alipoodle** [comment]
Temporarily keeping this open until it's been released into a release candidate! 😁

**Comment by ThatGravyBoat** [comment]
Hello, just wonder if a new release candidate with this is coming soon? I keep getting reports about peoples stuff not working on 2.0.0 but I need the volume field to be able to release a version that supports 2.0.0

No rush just wondering.

**Comment by Accardi22** [comment]
It is the API that is needed for the project to continue with the new version
volume
isAd

**Comment by NovusTheory** [comment]
Closing as v2.0.0 is released which contains this
