### ISSUE TITLE
bug report 

### ISSUE THREAD

**Issue by zZTariqziadZz** [ytmdesktop/ytmdesktop#1191]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

when using pop up window there is an internet draining  

### Expected Behavior

solve this problem  

### Steps To Reproduce

when using a pop-up window 
start internet draining 

### YTMDesktop

v1.13

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
😅 You're gonna need to explain a lot.

> when using pop up window
What Pop up window?
Settings? Lyrics? Mini-player?
A YouTube Music Pop-up?

> internet draining
What is this?!
Do you mean that it's using a lot of your internet?

**Comment by Alipoodle** [comment]
No information provided in long time.
