### ISSUE TITLE
2.0.0 release candidate darwin-x64 builds do not terminate

### ISSUE THREAD

**Issue by gotgenes** [ytmdesktop/ytmdesktop#1193]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

At least on a MacBook with an Apple M1 silicon chip, when running the darwin-x64 builds of the 2.0.0 release candidates, the application will not terminate when selecting "Quit" (Command-Q).

The user will be required to Force Quit the application to terminate it.

### Expected Behavior

The application terminates normally when quit.

### Steps To Reproduce

1. Download a 2.0.0 release candidate (2.0.0-rc.5 as of today) darwin-x64 artifact.
2. Copy to Applications.
3. Ctrl-click or right-click to open.
4. Allow YouTube Music Desktop App to finish starting.
5. Command-Q or go to the menu bar and select "Quit".
6. Observe that the YouTube Music Desktop App is still running (still present in Dock, and still present in Activity Monitor).

### YTMDesktop

2.0.0-rc.4+

### OS

MacOS

### OS Version

13.6

### Arch

x64

### Installation way

.zip

**Comment by Alipoodle** [comment]
This is likely a fault of the check we do on 'Should I quit' check we do on any shutdown on the application ~

Both of these instances of closing methods were missed in my "patching" of Mac that I quickly did!

**Comment by NovusTheory** [comment]
https://github.com/ytmdesktop/ytmdesktop/commit/c60468a5974499d3e632ac1e1440e6870e3b597c *should* correct this issue. You can grab the build from the CI to test it.

**Comment by NovusTheory** [comment]
Closing as this is in the v2.0.0 release
