### ISSUE TITLE
Integrate Settings with the UI in V2.

### ISSUE THREAD

**Issue by harsh251004** [ytmdesktop/ytmdesktop#1194]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

It would be nice if you could integrate the settings UI and the button with the ytm page and you could name it like ytmd settings.
something like this - 
![image](https://github.com/ytmdesktop/ytmdesktop/assets/146340558/60a7ac02-2da9-41ce-97bf-f012ff03adc6)

### Solution

N/A

### Alternatives

N/N

### Anything else?

N/A

**Comment by NovusTheory** [comment]
This is something we're not going to do. There is a settings button on the titlebar that isn't tied to YTM keeping it away from potentially breaking changes in the YTM interface that would make accessing the settings impossible. This would also not follow the security and design principles of the app which is to keep YTM isolated as much as possible and providing a button like this within the interface starts blurring that isolation and allowing YTM to control YTMDesktop in a manner we don't want to allow.
