### ISSUE TITLE
Album cover picture is very small (scaling problem?)

### ISSUE THREAD

**Issue by KO01341** [ytmdesktop/ytmdesktop#1197]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The album cover picture is very very small on the normal playback screen (see the screenshot). It behaved normally (cover picture was big) many years, but now has become too small. I have two displays, and this problem happens only in the second one, which has different refresh rate and resolution, but same scaling (125 %). Changing the scaling on the second screen changes the cover picture size, but does not fix the problem.

### Expected Behavior

The album cover picture should be same size and not depending on the display you choose to operate YTMDesktop.

### Steps To Reproduce

1. Start YTMDesktop on the 1st display.
2. Play music with album cover picture showing in a normal way
3. Move YTMDesktop to the 2nd screen
4. Cover picture is about 1/100 of normal size.

### YTMDesktop

v.1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

![Screenshot 2023-11-04 111114](https://github.com/ytmdesktop/ytmdesktop/assets/149869230/8a76ae4e-b33c-4790-8377-0a2ec19fdacb)

**Comment by Alipoodle** [comment]
This is a YTM issue 😅
It's something I've been meaning to fix in CSS however the solution I have been s a lot more work to clean up all viewports as YTM's method of doing it is very messy.

There's likely a really easy method I am just missing.

**Comment by Alipoodle** [comment]
Noted as a YTM issue, closing
