### ISSUE TITLE
Group the background process

### ISSUE THREAD

**Issue by Mrangelito** [ytmdesktop/ytmdesktop#1201]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

When the app in background the app does not group the process. This is when the app is the background. 
![image](https://github.com/ytmdesktop/ytmdesktop/assets/70352855/61a1e5d8-1433-42f5-99b6-5e333fcc011c)
this when the app open 
<img width="701" alt="image" src="https://github.com/ytmdesktop/ytmdesktop/assets/70352855/d039cde4-1646-4ed2-a57f-f6407d5307af">

### Solution

when the application is running in the background make the processes group together

**Comment by Alipoodle** [comment]
I suspect that this is simply going to be a Won't fix.
We're actually doing any of the processes management for this application and I suspect that this is something on Electrons end.
Otherwise this is a super low priority thing and means nothing to the user
