### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by Hannesvanwyk** [ytmdesktop/ytmdesktop#1205]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Back Button Ability

### Solution

Add ability to navigate to previous page when entering playlist, album, search result and artist

![image](https://github.com/ytmdesktop/ytmdesktop/assets/51072221/6debe24a-10c9-4f6b-af23-af5ec5bed3fe)

### Alternatives

Proceed to Home, Explore or Library to "reset" navigation.

**Comment by Alipoodle** [comment]
Which version of the app are you in 🤔 
This **WAS** a feature in v1.13 -> v1.14.2 however due to some Re-design in the UI, YTM broke the code.

In v2 it does exist ❤️ 
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/ce8254a6-fca4-4f45-93fc-fc1e0bcaff22)

**Comment by Alipoodle** [comment]
This was something which was already in v1.13 but as mention it broke.
Please see the releases on hte GitHub for the v2 builds which exist <3

**Comment by Alipoodle** [comment]
This issue is fixed with the release of YTMDv2
