### ISSUE TITLE
TypeError when toggling setting 

### ISSUE THREAD

**Issue by cookbr** [ytmdesktop/ytmdesktop#1206]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

- I performed an install of YouTube Music Desktop Player v2.0.0-rc.5 on Windows using the `*Setup.exe` installer.  I have had previous installations of this version along with prior RC's on my machine.
- After installation, I launched the application, went into settings, and toggled the setting for minimizing to tray upon closure.
- I got the error below and the application crashed.  Any subsequent attempt to launch the application again fails - no process spins up, it's as if nothing is happening at all.

```
Environment Details:
    YouTube Music Desktop App 2.0.0-rc.5
    Electron 27.0.2
    Windows NT 10.0.22621

Name: TypeError
Message: Use `delete()` to clear values
Cause: Unknown

TypeError: Use `delete()` to clear values
    at e.exports.set (C:\Users\USERNAME\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:66274)
    at IpcMainImpl.<anonymous> (C:\Users\USERNAME\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:515912)
    at IpcMainImpl.emit (node:events:514:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88262)
    at WebContents.emit (node:events:514:28)
```

### Expected Behavior

No crash, setting toggles successfully.

### Steps To Reproduce

Refer to _Current Behavior_.

### YTMDesktop

v2.0.0-rc.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
This is a known bug due to a slight oops on my part of not properly migrating some of the settings.

If you set the zoom level and put it back to 100% it will remove this bug ❤️
