### ISSUE TITLE
"ContextMenu" is an invalid Keybind and crashes YTM

### ISSUE THREAD

**Issue by allthatbs** [ytmdesktop/ytmdesktop#1207]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I tried to change the play/pause shortcut and now the app will not open. I tried reinstalling but the app still won't open.

The error message is below:

YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0-rc.5
    Electron 27.0.2
    Windows NT 10.0.22621

Name: TypeError
Message: Error processing argument at index 0, conversion failure from ContextMenu
Cause: Unknown

TypeError: Error processing argument at index 0, conversion failure from ContextMenu
    at G (C:\Users\brian\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:496946)
    at App.<anonymous> (C:\Users\brian\AppData\Local\youtube_music_desktop_app\app-2.0.0-rc5\resources\app.asar\.webpack\main\index.js:8:517453)
    at App.emit (node:events:514:28)

### Expected Behavior

I expected the button to pause or play the music

### Steps To Reproduce

1. Go to the keyboard shortcut
2. change the play/pause shortcut to the menu button
3. crash

### YTMDesktop

v2.0.0-rc.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by mxc42** [comment]
Had the same behavior:

```
Evironment Details:
  YouTube Music Desktop App 2.0.0-rc.5
  Electron 27.0.2
  Linux 6.6.6-76060606-generic

Name: Type Error
Message: Error processing argument at index 0, conversion failure from CmdOrCtrl+Shift+Process
Cause: Unknown

TypeError: Error processing argument at index 0, conversion failure from CmdOrCtrl+Shift+Process
  at G (/user/lib/youtube-music-desktop-app/resources/app.asar/.webpack/main/index.js:8:498513)
  at App.<anonymous> (/usr/lib/youtube-music-desktop-app/resources/app.asar/.weebpack/main/index.js:8:517453)
  at App.emit (node:events:514:28)
```

"Copy to Clipboard and Exit" isn't copying to clipboard on the error message, but I think I transcribed it correctly.

On Pop OS! 20.04, x64. Everytime I try to open the app I get the same behavior, even after uninstalling, `sudo rm -rf /usr/lib/youtube-music-desktop-app/`, and reinstalling.

**Comment by JuanitoPatit0** [comment]
![imagen_2024-01-12_014230805](https://github.com/ytmdesktop/ytmdesktop/assets/156398584/a14d0949-48b1-4318-a42c-61bc8fdd0cbb)
I also have this same error, I have tried to reduce the version of YTM but it doesn't help me either

**Comment by NovusTheory** [comment]
Closing as this is in the v2.0.0 release
