### ISSUE TITLE
DesktopEntry property not populated in MPRIS

### ISSUE THREAD

**Issue by sakithb** [ytmdesktop/ytmdesktop#1208]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I am using GNOME on linux and it's mpris integration usually shows the icon of the app currently playing media It doesn't show the icon or the name for ytmdesktop. I inspected further and found out that the `DesktopEntry` property in the mpris spec is being populated with an empty string.

### Expected Behavior

Correctly populate the `DesktopEntry` property with the desktop file name.

### Steps To Reproduce

1. Open ytmdesktop
2. Try inspecting the `DesktopEntry` property via dbus

### YTMDesktop

v1.13

### OS

Linux

### OS Version

6.6.3

### Arch

x64

### Installation way

flatpak

### Anything else?

I have some experience with mpris and typescript. I can look into putting together a PR if the maintainers are fine with it.

**Comment by azizLIGHT** [comment]
I get a generic music player icon in KDE's Media Player plasmoid
![image](https://github.com/ytmdesktop/ytmdesktop/assets/8013867/4170dc94-f945-4d3a-869f-4245488cc144)

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
