### ISSUE TITLE
Bug: Ytmdesktop-app opening app on unspecified icon instead of attached icon on Plank-launcher

### ISSUE THREAD

**Issue by pHamala** [ytmdesktop/ytmdesktop#121]
YTM-desktop-player is opening app on unspecified icon on Plank-launcher. Expected activity should be that the app opens in previously saved icon in Plank launcher. Please see the details from screenshot. 

Not sure if the problem only occurs on Elementary OS 5.1.2 Hera. 

![Kuvakaappaus - 2020-03-22 18-05-45](https://user-images.githubusercontent.com/18518012/77254173-23b9d000-6c68-11ea-9777-dba7b9f1708d.png)

**Comment by pHamala** [comment]
It's seems that there is something wrong in the.Desktop file. StartupWMClass should be StartupWMClass=youtube-music-desktop-app instead of StartupWMClass=Youtube Music Desktop-App. Changing that line fixes the problem.

**Comment by Alipoodle** [comment]
Users has confirmed that this issue is fixed above, and should be used to refer to stuff above.

**Comment by BrianAllred** [comment]
This is still an issue with the current flatpak release.

**Comment by Alipoodle** [comment]
> This is still an issue with the current flatpak release.

We don't give a flat pack release?
So not sure how this can occur.

**Comment by BrianAllred** [comment]
Ah, in that case, someone seems to have published one to Flathub for you.

https://flathub.org/apps/app.ytmdesktop.ytmdesktop

**Comment by Alipoodle** [comment]
That's v1.13 and not V2 😖

**Comment by BrianAllred** [comment]
Just noticed that, too. Oh well, I guess I'll manually install the RPM.
