### ISSUE TITLE
Play/Pause Error

### ISSUE THREAD

**Issue by Zentisca** [ytmdesktop/ytmdesktop#1211]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When using Keyboard Play/Pause button (Such as Razer's in built multimedia buttons), App attempts to play the first playlist on profile and pause simultaneously. 

### Expected Behavior

Repetitive Pressing of Play/Pause button causes the app to flicker up and down, then resetting itself, presenting the same issue when attempting to use normally.

### Steps To Reproduce

UPDATE: I can not reproduce the error now. With Razer Synapse being updated, the function works as intended. (however, prior to the update, WhatKeyAmIUsing reported only the Play/Pause function was being run.

UPDATE #2: The error has returned after restarting the system post-update. Software still reports only the Play/Pause button being pressed.
### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x86

### Installation way

.exe

**Comment by Vimerum** [comment]
I'm also having this issue. Using the media key (play/pause) in my Redragon Mitra, the app always plays the liked playlist.

### YTMDesktop
v1.13.0

### OS
Windows

### OS Version
10

### Arch
x86

### Installation way
.exe

**Comment by Zentisca** [comment]
>"configuring a specific command to play/pause (Ctrl+Shift+Space) in the settings doesn't work, it still plays the liked songs,"

Yep, I can confirm Custom keys also do the same behavior (I didn't think to try this), spacebar works when the app is focused, but that bug presents itself when the app is not focused and short cuts try to access it to pause/play. 

I did remove all my liked songs to test and it will continue to play the first playlist on the left hand side.

**Comment by XeroxDev** [comment]
Hey. I can also confirm this. Using the latest nightly (1.14.2). Media keys, as well as my StreamDeck and Loupedeck Plugin (using your Remote Server) has the same behavior. My users are also opening issues/tickets due this error and do mention it on my discord.

See, as example, this: XeroxDev/YTMD-StreamDeck#93

Google probably changed something again ._.

**Comment by XeroxDev** [comment]
Update: #1210 seems to fix this issue.

**Comment by Alipoodle** [comment]
It appears that:
IF YOU HAVE double tap pause/play to Open/Close YTM Window:
- If No Song is currently active and you tap Pause/Play it will play the "First Playlist"
- Otherwise it will open up / close the YTM app

And YTM Decides to Pin the Liked Playlist so it will always pick that one:
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/737f3cac-5e8f-4ef5-9c7a-d9b129aa6a11)

This feature is not longer used in YTMDv2 so this issue likely will not have a fix for it 😓

**Comment by mingjun97** [comment]
The root cause for this seems to be `infoPlayerProvider.getTrackInfo().id` always return `""` now. YTM made some changes so that we cannot detect the current playing track id. I tentatively disable the `playFirst` logic as a workaround in the development branch.

**Comment by Zentisca** [comment]
> It appears that: IF YOU HAVE double tap pause/play to Open/Close YTM Window:

Oh my. I even saw this but thought it was unrelated. Pressing all the buttons would have helped. good pick up by the OP lol.
Thank you.
