### ISSUE TITLE
Play/Pause shortcuts double (?) activation

### ISSUE THREAD

**Issue by elfbread420** [ytmdesktop/ytmdesktop#1212]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Play/Pause shortcuts activate twice resulting in no effect on playback (this doesn't happen with Next Track/Previous Track shortcuts).

Tested with two keyboards with media controls and bindable keyboard shortcuts. Controls work as expected in browsers (Chrome). Tried disabling Hardware Media Key Handling in Chrome to no effect.

### Expected Behavior

Play/Pause should toggle once to swap between playing or paused.

### Steps To Reproduce

1. Press Play/Pause on keyboard media controls OR use keyboard shortcut Ctrl + Shift + Space
2. Music playback toggles twice resulting in no change.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

Chrome Version 119.0.6045.200 (Official Build) (64-bit)

**Comment by JonasCz** [comment]
Hi have the same problem. If I hold down Windows Key, Ctrl, Alt, or Shift while pressing play / pause, it does work correctly. I also tried disabling media key handling in chrome to no effect.

**Comment by StCost** [comment]
Same
Got that issue today morning. Nothing was updated

**Comment by vghougassian** [comment]
Can confirm #1211 fixed it for me.  Notably, for me, it started off with "double play/pause" behavior.  After restarting the program, it began to always play my first playlist on the menu bar, even if I was on a completely unrelated song.

**Comment by mingjun97** [comment]
Just release a hot patch 1.14.3 to avoid the issue. You may retrieve the nightly release from the following link:

https://github.com/ytmdesktop/ytmdesktop/actions/runs/7173791546

**Comment by Hank3** [comment]
> Just release a hot patch 1.14.3 to avoid the issue. You may retrieve the nightly release from the following link:
> 
> https://github.com/ytmdesktop/ytmdesktop/actions/runs/7173791546

I'm not too familiar with this platform.  What do I click on when I go to the link to download the hot patch?

**Comment by vghougassian** [comment]
> > Just release a hot patch 1.14.3 to avoid the issue. You may retrieve the nightly release from the following link:
> > https://github.com/ytmdesktop/ytmdesktop/actions/runs/7173791546
> 
> I'm not too familiar with this platform. What do I click on when I go to the link to download the hot patch?

In case you haven't figured it out, once you click on the link and scroll down you'll see a file you can download labeled as "dist-windows-2019".  That downloads a zip file, inside which you can find an installer.

**Comment by Hank3** [comment]
> > > Just release a hot patch 1.14.3 to avoid the issue. You may retrieve the nightly release from the following link:
> > > https://github.com/ytmdesktop/ytmdesktop/actions/runs/7173791546
> > 
> > 
> > I'm not too familiar with this platform. What do I click on when I go to the link to download the hot patch?
> 
> In case you haven't figured it out, once you click on the link and scroll down you'll see a file you can download labeled as "dist-windows-2019". That downloads a zip file, inside which you can find an installer.

Thank you!

**Comment by elfbread420** [comment]
No idea what happened, but this no longer is an issue for me. Maybe it was a Chrome update or something?
