### ISSUE TITLE
Play/Pause Shortcut not working

### ISSUE THREAD

**Issue by MightyX3N** [ytmdesktop/ytmdesktop#1214]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When i use the Play/Pause shortcut it goes to the latest liked song, but when i am on the latest liked song the shortcut works fine

### Expected Behavior

That the sortcut plays and pauses the current song

### Steps To Reproduce

dont know

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by Kevlnnn** [comment]
yeah thats been happening for me, im trying to ask someone and they say turn off play/pause 2x to show/hide main window but it didnt work for me so yeah.

**Comment by NathanSikkema** [comment]
Agreed, It is very frustrating.

All details the same, but I have Windows OS Version 11

**Comment by BlacRyu** [comment]
Same problem here. Started happening yesterday.

**Comment by AngryTwitches** [comment]
I'm not the brightest crayon and you YTMD from you guys to play my YTM on stream. What was the solution? I saw someone say there was no solution? Are we borked now?

**Comment by BlacRyu** [comment]
> I'm not the brightest crayon and you YTMD from you guys to play my YTM on stream. What was the solution? I saw someone say there was no solution? Are we borked now?

Disabling this option worked for me and some others:

![Screenshot 2023-12-09 142004](https://github.com/ytmdesktop/ytmdesktop/assets/10762433/197b7488-5fd4-4a05-8667-93c9773fe9a0)

**Comment by AngryTwitches** [comment]
> > I'm not the brightest crayon and you YTMD from you guys to play my YTM on stream. What was the solution? I saw someone say there was no solution? Are we borked now?
> 
> Disabling this option worked for me and some others:
> 
> ![Screenshot 2023-12-09 142004](https://private-user-images.githubusercontent.com/10762433/289315575-197b7488-5fd4-4a05-8667-93c9773fe9a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjQ0ODUsIm5iZiI6MTcwMjIyNDE4NSwicGF0aCI6Ii8xMDc2MjQzMy8yODkzMTU1NzUtMTk3Yjc0ODgtNWZkNC00YTA1LTg2NjctOTNjOTc3M2ZlOWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDE2MDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZDYxZDMzOWUwMWM1MjE5ZTU0MzdkMTZmOGIwMjNhYzcxOTczMTZmN2JmY2VlZjM0YjVlYWVlNzA2ZTllZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7KETK0oCYoetCrbeZWhDwuFkfeenh9H5TPsxLt4kQ_g)
> 
> Also it looks like it should be fixed in the next update if/when they release one.

Thanks for the effort friend, that solution did not seem to work for me. T_T I appreciate you.

**Comment by Mayhem93** [comment]
I have the same issue with the latest version running on windows 11. The workaround from @BlacRyu works for me though.

**Comment by RileyXX** [comment]
> > I'm not the brightest crayon and you YTMD from you guys to play my YTM on stream. What was the solution? I saw someone say there was no solution? Are we borked now?
> 
> Disabling this option worked for me and some others:
> 
> ![Screenshot 2023-12-09 142004](https://private-user-images.githubusercontent.com/10762433/289315575-197b7488-5fd4-4a05-8667-93c9773fe9a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzE5MTEsIm5iZiI6MTcwMjI3MTYxMSwicGF0aCI6Ii8xMDc2MjQzMy8yODkzMTU1NzUtMTk3Yjc0ODgtNWZkNC00YTA1LTg2NjctOTNjOTc3M2ZlOWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA1MTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NzE2ZGI4MDU4ZWIyM2RhNDJjMWI0ZmQwZmUzOTEwODIyMGIyY2ZhZGNlZjI3NTYxMWRlNjUyN2Y4OGRmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hqdSa6QskJtGnHbMXmvHD82G15izU1BsM2JEbXKo9mI)
> 
> Also it looks like it should be fixed in the next update if/when they release one.

Thank you this worked for me

**Comment by Hank3** [comment]
Thank you to the OP for posting this issue.  I also started experiencing this issue a couple days ago.  The fix posted by BlacRyu worked for me on Windows 10.

**Comment by mingjun97** [comment]
Just release a hot patch 1.14.3 to avoid the issue. You may retrieve the nightly release from the following link:

https://github.com/ytmdesktop/ytmdesktop/actions/runs/7173791546

**Comment by Kevlnnn** [comment]
hello im very sorry but ive tried downloading the 1.14.3 and its still not working even with the setting turned off

https://youtu.be/yP4s96L4Myc
its a unlisted video of the problem shown from my perspective

**Comment by Kevlnnn** [comment]
hello im so sorry but ive tried downloading 1.14.3 and im still getting the play/pause problem where it goes to the first playlist or liked songs and ive turn off the setting play/pause 2x hide/show main window.

https://youtu.be/yP4s96L4Myc
that is a video of the problem from my perspective with showing that ive done all the things but yet.

**Comment by shrilex** [comment]
> hello im so sorry but ive tried downloading 1.14.3 and im still getting the play/pause problem where it goes to the first playlist or liked songs and ive turn off the setting play/pause 2x hide/show main window.
> 
> https://youtu.be/yP4s96L4Myc that is a video of the problem from my perspective with showing that ive done all the things but yet.

ive also downloaded 1.14.3 and i still have the same issue, was so excited for a possible fix, and i have same things as is in the vid, and stream deck pause/play button just plays the liked playlist

**Comment by mingjun97** [comment]
> hello im so sorry but ive tried downloading 1.14.3 and im still getting the play/pause problem where it goes to the first playlist or liked songs and ive turn off the setting play/pause 2x hide/show main window.
> 
> https://youtu.be/yP4s96L4Myc that is a video of the problem from my perspective with showing that ive done all the things but yet.

@Kevlnnn @shrilex Temporarily fixed in this nightly build: https://github.com/ytmdesktop/ytmdesktop/actions/runs/7201491778
