### ISSUE TITLE
When I use shortcut for play/pause, it is reverting to my liked auto playlist

### ISSUE THREAD

**Issue by bdboesch** [ytmdesktop/ytmdesktop#1219]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Whenever I use the hotkey for Play/Pause, no matter what I am listening to, it starts playing from my "Liked Music" auto playlist.

![image](https://github.com/ytmdesktop/ytmdesktop/assets/97469507/4387b16c-4ff1-4652-92e4-fab2bf7fb78f)

### Expected Behavior

It should just start/stop listening to whatever was currently in my queue.

### Steps To Reproduce

Use Play/Pause shortcut key.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by michaelcosta** [comment]
https://github.com/ytmdesktop/ytmdesktop/issues/1217 
https://github.com/ytmdesktop/ytmdesktop/issues/1214
https://github.com/ytmdesktop/ytmdesktop/issues/1212
https://github.com/ytmdesktop/ytmdesktop/issues/1211

**Comment by amilo2003** [comment]
I experience the same issue

**Comment by Alipoodle** [comment]
Closing this issue as v1 of YTMD is no longer suported.
