### ISSUE TITLE
Shuffle all no longer clickable

### ISSUE THREAD

**Issue by amilo2003** [ytmdesktop/ytmdesktop#1220]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When clicking on Shuffle all in Library/Songs, nothing happens

![image](https://github.com/ytmdesktop/ytmdesktop/assets/22910072/76ab96d4-f6f7-405d-848d-a0823d56d0aa)

### Expected Behavior

Songs should start playing 

### Steps To Reproduce

Go to library, click songs, click Shuffle all

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by bdboesch** [comment]
This same behavior is happening for me as well. Just realized this morning and was going to post an issue, but this summarizes the same issue I am seeing.

**Comment by TheOnlyXBK** [comment]
Same here.

**Comment by LiquidMechanix** [comment]
Same issue.

YTMDesktop: v1.13.0
OS: Windows
OS Version: 10
Arch: x64
Installation way: .exe

**Comment by IOEggception** [comment]
Same here, windows client.  This worked for me on my Mac client, but now windows.
