### ISSUE TITLE
scroolbar always showing

### ISSUE THREAD

**Issue by harsh251004** [ytmdesktop/ytmdesktop#1225]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

the scrollbar shows all the time
![Screenshot (243)](https://github.com/ytmdesktop/ytmdesktop/assets/146340558/7b89bc75-1edf-4fba-b7e5-eff5a88b2021)

### Expected Behavior

it shouldn't show while i am on the song page.

### Steps To Reproduce

play any song see the sroll bar is still there.

### YTMDesktop

v2 rc 5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

na

**Comment by Alipoodle** [comment]
> ### Steps To Reproduce
> play any song see the sroll bar is still there.

Please can you provide some actual steps. I suspect that this is a bug with YTM and not YTMD.
I am unable to cause this issue while doing what I would suspect and:
- Play a song
- Open the Player UI
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/52e42a58-60d6-426a-94fc-d846bc84a954)

**Comment by Alipoodle** [comment]
I'm able to reproduce this via Opening / Closing the left menu.
And I see little reason that we have to do with this.

Closing this as a YTM Bug.
