### ISSUE TITLE
Please add option to disable double click full screen

### ISSUE THREAD

**Issue by harsh251004** [ytmdesktop/ytmdesktop#1231]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

HI THERE,
PLEASE ADD OPTION TO DISABLE DOUBLE CLICK FULL SCREEN WHEN PLAYING A SONG

### Solution

N/A

### Alternatives

N/A

### Anything else?

N/A

**Comment by Alipoodle** [comment]
Duplicate of #935
