### ISSUE TITLE
Mac OS: Uncaught Exception When I disable tray icons

### ISSUE THREAD

**Issue by sfaber03** [ytmdesktop/ytmdesktop#1237]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Hi! First off, I love the project, thanks for all the work.  I noticed this bug just today so I thought I'd report because I don't see it in the issues.  Sorry if I missed it.

When I disable tray icons on mac OS I get an uncaught exception and application crashes.  I redownloaded and reinstalled the app but still get this exception.

```
Uncaught Exception:
ReferenceError: error is not defined
at Object.updateImage (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/src/providers/trayProvider.js:219:45)
at IpcMainImpl.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/main.js:1739:22)
at IpcMainImpl.emit (events.js:310:20)
at WebContents.<anonymous> (electron/js2c/browser_init.js:157:8362)
at WebContents.emit (events.js:310:20)
```

Let me know if you need more info.  Thx

### Expected Behavior

The tray icons to be disable and the app continues to function normally

### Steps To Reproduce

Go to settings.
Click to disable tray icons.
App will now crash randomly with uncaught exception

### YTMDesktop

1.13.0

### OS

MacOS

### OS Version

14.1.1

### Arch

x64

### Installation way

.dmg

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
