### ISSUE TITLE
Last.fm won't authenticate.

### ISSUE THREAD

**Issue by mckenna654** [ytmdesktop/ytmdesktop#124]
Hi,

When filling out the username and password field for the Last.fm integration, nothing happens once I click "Save and Authorize".

Any one else experiencing this issue?

**Comment by adlerluiz** [comment]
Could you tell me which platform you use, operating system, system version, and YTMDesktop version

**Comment by gfairchild** [comment]
Same issue here. I'm on macOS 10.15.4, YTMDesktop 1.9.0. When I hit "Save and Authorize", nothing happens. It just sits there.

**Comment by jimmyc802** [comment]
Same issue here. Credentials entered, save and authorize does nothing. Tried fully restarting the app, it's saving my credentials when I got back to try and configure the last.fm integration but still wont save and authorize. Logging into my last.fm account, my credentials are fine. Checking my list of applications in last.fm, ytmdesktop is not listed :(

**Comment by petrov85** [comment]
Same happening here. Tried on two windows pc's. Can confirm that the userdetails I am entering are correct.

Platform/System: Windows 10 1909
YTMDesktop Version: v1.9.0

**Comment by adlerluiz** [comment]
Fixed, will be available on next release.

**Comment by dadi11** [comment]
I have v1.10 and it still wasn't fixed for me
