### ISSUE TITLE
[2.0.0] Stuck on Checking for Updates

### ISSUE THREAD

**Issue by gabuch2** [ytmdesktop/ytmdesktop#1247]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Opening the recently released stable version of 2.0.0 displays an endless message of "Checking for Updates" at the start, preventing you from using the app.

### Expected Behavior

If the update process fails after a while, it should stop and let you use the app as is. 

### Steps To Reproduce

1. Open the app

### YTMDesktop

2.0.0

### OS

Ubuntu

### OS Version

22.04

### Arch

x64

### Installation way

.deb

**Comment by NovusTheory** [comment]
This will come out in a patch build

**Comment by NovusTheory** [comment]
If you'd like an immediate fix the CI build here https://github.com/ytmdesktop/ytmdesktop/actions/runs/7688358807 should resolve the issue

**Comment by Edu4rdSHL** [comment]
Is a new bugfix release going to be made for it? Thanks in advance.

**Comment by Alipoodle** [comment]
> Is a new bugfix release going to be made for it? Thanks in advance.

We plan to make a full release with this fix in it soon, however now that we've released the application to the masses, we're more likely to get a few edge case issues show up which were missed in the 6 months or so of RC we've had.

**Comment by Edu4rdSHL** [comment]
Hello, can we get a bug fix release now so that we can start using the new release on Linux? Thanks!
