### ISSUE TITLE
When opening Windoows Copilot in Windows 11, the minimised tab opens up when it's supposed to stay minimised

### ISSUE THREAD

**Issue by sryu1** [ytmdesktop/ytmdesktop#1249]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Opening the Windows Copilot will cause the screen of my minimised YTM to show on screen, but nothing is clickable. I have to click the icon from the taskbar for the tab to resize itself, then I can press the x button to minimise again. Same thing happens with when closing the Copilot. I think it's some sort of bug that is caused when Windows' screen resolution changes, I haven't yet tested it with  changing the resolution through the windows settings though. Occurs with both v1.x and v2.

### Expected Behavior

Program to stay minimised.

### Steps To Reproduce

1. Open YTM and play some music and press x to minimise it (may have to change YTM settings to minimise)
2. Open Windows Copilot (Win+c)

### YTMDesktop

v2.0.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Do you have a picture as an example of this?
And `press x to minimise it` 😕 don't quite understand this~

My work laptop appears to not have Copilot button currently on it (and run Win10 on my home PC) so I'm currently unable to test this.

**Comment by sryu1** [comment]
Oh, I meant x as in the exit button (The button on the top right), I'll try to record a video and upload it.

**Comment by sryu1** [comment]
https://github.com/ytmdesktop/ytmdesktop/assets/95025816/66b24c7b-e30c-499f-988c-1a7ac2c1abda
Sorry for rushing the video, I accidentally pressed the top bar and made the app size change again after changing it to work from pressing the YTM button from taskbar.

**Comment by Alipoodle** [comment]
👍 When I get a chance or see the Co-pilot button appear on my Work laptop I will try and reproduce this, but for the time being this might be a strange issue with the fact that Co-pilot force re-sizes the Windows shown to split view once it's opened.

**Comment by sryu1** [comment]
Sorry, I just realised that the error does not exist in v2.0.0
What happened was after I installed YTMDesktop, I opened it but turns out that v1.1.3 wasn't removed and everytime I opened the program, 1.1.3 opened. This bug does not exist in v2.0.0. Sorry for the confusion.
