### ISSUE TITLE
Too much CPU 

### ISSUE THREAD

**Issue by SSuarezBrooktec** [ytmdesktop/ytmdesktop#125]
The app consumes soooooo much processor, check this picture

<img width="862" alt="Captura de pantalla 2020-03-26 a las 10 19 39" src="https://user-images.githubusercontent.com/56263935/77630436-50f9cd00-6f4b-11ea-923e-9c096ba36c44.png">

**Comment by adlerluiz** [comment]
Some changes were made to improve the performance of the app, I hope they don't cause any more problems, if it occurs, please reopen this issue

**Comment by SSuarezBrooktec** [comment]
Where i can download the Mac Version?

**Comment by adlerluiz** [comment]
@mingjun97 can you generate the mac version?

**Comment by yasiel2110** [comment]
![Annotation 2020-06-08 221654](https://user-images.githubusercontent.com/66655740/84098642-cbc47700-a9d5-11ea-8e6a-c91d1f00ecd5.png)
Put my computer to sleep after it wake up the app start using to much CPU. I am using windows 10 v2004 build 19041.264 
After force closing the app and open it again the problem went away.

**Comment by SergioSuarezDev** [comment]
How about macos app? @adlerluiz @mingjun97

**Comment by adlerluiz** [comment]
I don't have a mac to do the build and the mingjun97 doesn't respond, I'm running after someone who can help

**Comment by SergioSuarezDev** [comment]
I can do it if you give me the instructions or commands to build ;-)

**Comment by adlerluiz** [comment]
we managed to build v1.10 but we will need help for 1.11

**Comment by SergioSuarezDev** [comment]
Let me know and next version i can build it

**Comment by SergioSuarezDev** [comment]
I think this version is not right compiled:

<img width="1309" alt="Captura de pantalla 2020-06-17 a las 9 23 05" src="https://user-images.githubusercontent.com/3636232/84867951-392e7280-b07c-11ea-97f7-103a14e1fcd4.png">

**Comment by adlerluiz** [comment]
unfortunately there were some bugs in this version, it is fixed for version 1.11, I believe it will come out today

**Comment by rickinbsb** [comment]
v1.11 is out! the problems you had on 1.10 are gone

**Comment by SergioSuarezDev** [comment]
Downloading now!

**Comment by SergioSuarezDev** [comment]
working perfect :D

**Comment by renanrfranca** [comment]
Can we get 1.11 on Snapcraft? This is a bit wild.

![2020-06-19_11-19](https://user-images.githubusercontent.com/12504550/85143679-6d429880-b220-11ea-9f49-a8f71d7d39df.png)

**Comment by jnr2820** [comment]
Version 1.13.0 is still driving up the mac "WindowServer" process to 20% to 30% as long as is open. (Normally 5% to 10% with app closed. Music doesn't have to be playing) I'm observing this on Big Sur (OS XI). I don't think this is an issue with the Youtube website as another Youtube desktop app does not have the behavior.

**Comment by Alipoodle** [comment]
Could I ask for what commit you are running on for V2 (should show in the Settings -> About) and what Mac you are running on? (I.e. MacBook 2022, M2 Pro)

Given that we aren't exactly doing anything to "visually process" anything this might be a side effect of YTM/Electron.
