### ISSUE TITLE
macOS Ventura: Insta-crash on load

### ISSUE THREAD

**Issue by ranvel** [ytmdesktop/ytmdesktop#1252]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Instantly crashes on Startup and provides the details (attached to this issue). 

### Expected Behavior

Loads GUI

### Steps To Reproduce

1. Click on the .app to start up. 
2. Instantly crashes. 

### YTMDesktop

v2.0.0

### OS

macOS

### OS Version

13

### Arch

x64

### Installation way

.dmg

### Anything else?

I had data from the previous version and I clicked "Migrate"  for my settings. 

Data from crash log: 
YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0
    Electron 28.2.0
    macOS 13

Name: TypeError
Message: Error processing argument at index 0, conversion failure from disabled
Cause: Unknown

TypeError: Error processing argument at index 0, conversion failure from disabled
    at X (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/.webpack/main/index.js:8:405625)
    at App.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/.webpack/main/index.js:8:429100)

**Comment by NovusTheory** [comment]
Seems like this is an issue with something that was improper with the old v1 settings. The migration script didn't have much testing and I went off what was in my old config file. I wouldn't recommend sharing your config.json file publicly but I'd be curious what setting is showing `disabled`. You can fix this by, unfortunately, deleting your config.json. You won't get prompted to migrate your settings again as that's only on first run and you will lose your previous settings so you'll have to manually configure them again but this should make the application launch fine after.

**Comment by ranvel** [comment]
Amazing!

It was this section from the previous version:
	"settings-accelerators": {
		"media-play-pause": "disabled",
		"media-track-next": "disabled",
		"media-track-previous": "disabled",
		"media-track-like": "disabled",
		"media-track-dislike": "disabled",
		"media-volume-up": "disabled",
		"media-volume-down": "disabled",
		"miniplayer-open-close": "disabled"
	},
	
This got mapped to the "shortcuts" section, which, upon deleting, allowed the program to load perfectly. 

Thank you!
