### ISSUE TITLE
Feature Request: Integration with Visual Studio Code?

### ISSUE THREAD

**Issue by jos3s** [ytmdesktop/ytmdesktop#127]
Would it be possible to integrate the YTM Desktop playback controls within vscode? Maybe with an extension for vs code that does this integration.

**Comment by mingjun97** [comment]
It's possible via Companion Server API.

**Comment by jos3s** [comment]
Could this be in the planning of the application at some point?

**Comment by adlerluiz** [comment]
Yes, will be available in the next release and will be accessed by http://localhost:9863/query

![image](https://user-images.githubusercontent.com/2112638/83206403-37c9f400-a127-11ea-9eca-d90dc6239b2d.png)

**Comment by jos3s** [comment]
Any date when it will be available?

**Comment by adlerluiz** [comment]
we have the date in mind first of June

**Comment by adlerluiz** [comment]
Api available and doc is here - https://github.com/ytmdesktop/ytmdesktop/wiki/Remote-Control-API

**Comment by sedders123** [comment]
I've made https://github.com/sedders123/vscode-ytmusic which I've been using for the past few days. Potentially a little rough around the edges but seems stable enough for me.

**Comment by Alipoodle** [comment]
Closing this as solved by the community made Extension above.
Will add this to the remote desktop tools by the community in the WIki! 😎
