### ISSUE TITLE
Start playback indicator detached from play/pause button

### ISSUE THREAD

**Issue by IndefiniteBen** [ytmdesktop/ytmdesktop#1271]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I am not sure what caused it, but I opened the app and moved it to another monitor, then looked at it and saw this: 
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17594572/6a0bc75d-c036-490a-b1be-d48b27b79abb)

I quit the app and started it, and moved the app to different screens. In all cases it stayed in the top left of the window. 

It disappeared as soon as I pressed play, so it's a very minor issue. 
After I had started music to clear the indicator, then later closed the app, it returned to the wrong position on the next start of the app.

It does block clicking on the top left menu flyout.

### Expected Behavior

I expect the "start playback" to be pointing at the play button as it has previously. 

### Steps To Reproduce

Open the app???

### YTMDesktop

v2.0.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by A-Matt** [comment]
Size of the app looks tiny and the scaling of the app looks giant.
I think this is something strange you've done with that~

**Comment by IndefiniteBen** [comment]
Oh sorry it's not clear; that is just a cut-out of the top left of the window. The entire window is filling the screen and looks normal. 

I only included the bug in my screenshot instead of the entire app.

**Comment by IndefiniteBen** [comment]
Here is another screenshot to make it clear: 
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17594572/ac00b12c-52eb-4c5e-881a-795be7e51a2e)

**Comment by NovusTheory** [comment]
This would be a YTM issue. We only tell YTM to refit that popup on startup once to fix a previous issue where it was located wrongly (context: different behavior from the app causing it to be positioned over the player bar) but if you move or resize the window and it screws up like that then YTM is to blame as we don't touch that popup.

I'm going to close this since without more context this just seems to be an issue with YTM and nothing we can do.

**Comment by IndefiniteBen** [comment]
Oh okay! I thought the tooltip was added by the app, not by YTM itself.

I will just ignore it if I see it again, thanks.
