### ISSUE TITLE
Can't paste email or password - Electron Menu issue

### ISSUE THREAD

**Issue by jaredkotoff** [ytmdesktop/ytmdesktop#1276]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Trying to paste my email or password into Google login page does nothing

### Expected Behavior

I should be able to paste my email and password into the login screen

### Steps To Reproduce

1. Download and open
2. Hit sign in

### YTMDesktop

v2.0.0

### OS

MacOS

### OS Version

14.4

### Arch

ARM (Apple silicon)

### Installation way

dropped into Applications folder

### Anything else?

Double annoying because of https://github.com/ytmdesktop/ytmdesktop/issues/1227 where I have to log in each time I close the app.

The form for this bug submission only has dropdowns for `x64` and `x86` for the Arch section

**Comment by Alipoodle** [comment]
🤔 Curious to what is going on and if this is some Apple "protection" going on or something.

But regarding the Arch #1182 it's already prepared but I need them to move which branch it is on ❤
I also need to remove x86 as that's no longer supported.

**Comment by jaredkotoff** [comment]
> 🤔 Curious to what is going on and if this is some Apple "protection" going on or something.

That kind of what i thought at first but i dont think that's the case. I can't ctrl-a or right-click on the page at all. 
It's less to do with the text inputs and more to do with i think how this page is embedded in the app

**Comment by jaredkotoff** [comment]
looks like its an electron config issue with macos
this is pretty old but i think something like this needed to be added https://github.com/electron/electron/issues/2308#issuecomment-127609678

**Comment by Alipoodle** [comment]
😆 Ok... that's a silly one. I will borrow a MacBook from work for this weekend and will add + validate this.
Both myself and Novus are Windows users so MacOS fixes are a little harder to process for us, as we don't know the normal Program Lifecycle that Mac OS has compared to Windows and the other silly querks of Electron.

**Comment by jaredkotoff** [comment]
@Alipoodle same, my work macbook is my only apple product.
If you put changes on a new branch I can test probably test them for you
