### ISSUE TITLE
companion app doesnt exist on android 14

### ISSUE THREAD

**Issue by Atomikul** [ytmdesktop/ytmdesktop#1278]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

YTMDesktop Remote doesnt work on android 14 

### Expected Behavior

i expected it to exist 

### Steps To Reproduce

search the app on an android 14 device

### YTMDesktop

v2.0

### OS

Android

### OS Version

Android 14 

### Arch

x64

### Installation way

google play

### Anything else?

![Screenshot_20240204_133718_Google Play Store](https://github.com/ytmdesktop/ytmdesktop/assets/146031110/85ccbdb6-7319-42cc-9eae-457e60af9d9d)

**Comment by Alipoodle** [comment]
The app is no longer supported on the V2 of the application.
We plan to make a Web based version first and then Adler (original project owner) has said to recreate an android app again
