### ISSUE TITLE
Missing OBS integration in 2.0

### ISSUE THREAD

**Issue by DeFlanko** [ytmdesktop/ytmdesktop#1279]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When launching OBS, and YTMD 2.0 is launched the following error appears:
![image](https://github.com/ytmdesktop/ytmdesktop/assets/5233969/4809b1f0-a5ea-42c9-945c-ff17cd178441)

### Expected Behavior

no errors

### Steps To Reproduce

1. Launch YTMD 2
2. Launch OBS
3. popup box appears

### YTMDesktop

Version: 2.0.0  Branch: HEAD  Commit: 6d0abf5

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

YouTube-Music-Desktop-App-2.0.0-Setup.exe

### Anything else?

Im unable to find the "Remote control" in settings

**Comment by DeFlanko** [comment]
also creating a ticket over at the widget repo

**Comment by Alipoodle** [comment]
🤔 This is probably more of a ticket for the Widget Repo rather than here.
But it's one of the basic things which we want to do to allow for a basic Web based Reader for you to import into OBS.

**Comment by topik** [comment]
Everytime I do GET request to `http://127.0.0.1:9863/api/v1/state`, I get `{error: "UNAUTHORIZED"}`.  

Companion authorization is disabled in the settings.
![image](https://github.com/ytmdesktop/ytmdesktop/assets/3578443/7583b675-8b27-41ba-ad41-629f268d5077)

What am I doing wrong?

**Comment by Alipoodle** [comment]
Please see https://github.com/ytmdesktop/ytmdesktop/wiki/v2-%E2%80%90-Companion-Server-API-v1

The API has heavily changed due to security & issues in the v1 API!
Get state now requires the user to authorise the application and get a token in return!

**Comment by topik** [comment]
Cool, what is the point of having this toggle in the settings then?

**Comment by Alipoodle** [comment]
**Companion server** turns on the feature as a whole.
Otherwise the server isn't running

**Allow browser communication** allows for a URL based connection to be made. Localhost/Internal IP are allowed without that settings on.

**Enable companion Authorisation** turns on the ability to allow a new connection for 5 minutes or a successful connection.

And the table is for Authorisation companions you've previously done. ☺️
You can also deny requests from there as well.

**Comment by topik** [comment]
OK got it, thanks.

**Comment by NovusTheory** [comment]
> Allow browser communication allows for a URL based connection to be made. Localhost/Internal IP are allowed without that settings on.

Clarification. This is specifically for CORS. The companion server by default, without that toggled on, doesn't specify CORS which defaults to deny on browsers preventing access to it. This is a very browser specific issue as most networking libraries outside a browser doesn't respect CORS headers and will communicate with it regardless. For example a browser source in OBS *will* respect CORS and thus needs this turned on if you were talking to the companion server from one.

**Comment by DeFlanko** [comment]
Thank you @topik for checking in on this.

**Comment by topik** [comment]
Fixed on my side. Thanks for your help. You can close the ticket.

**Comment by DeFlanko** [comment]
Confirmed. Fixed.
