### ISSUE TITLE
Can't sign in in google account, browser is untrusted

### ISSUE THREAD

**Issue by hotmule** [ytmdesktop/ytmdesktop#128]
![image](https://user-images.githubusercontent.com/37577810/79063061-05b02000-7ca8-11ea-8f9e-a907852ead4a.png)
Manjaro 19, downloaded from AUR

**Comment by mingjun97** [comment]
Is this the same problem as #67 ? @rickinbsb 
I'm not sure which version is delivered through the AUR.

**Comment by mingjun97** [comment]
Could you see the version in [settings]->[about]?
Thanks!

**Comment by rickinbsb** [comment]
@mingjun97 I believe it is the same error, but this seems dated. It was fixed since v1.6..

what package are you using @hotmule? [this  one?](https://aur.archlinux.org/packages/ytmdesktop-git)

**Comment by hotmule** [comment]
It's true, I downloaded outdated AUR package, 1.8.1 works fine, sorry
