### ISSUE TITLE
It wont save the theme 

### ISSUE THREAD

**Issue by lukyluke112** [ytmdesktop/ytmdesktop#129]
Hi,
I changed the the background color and I pressed ctrl + s and with the save icon on the bottom right and it wont save

**Comment by adlerluiz** [comment]
Still have this problem?

**Comment by lukyluke112** [comment]
yes I do

**Comment by lolrepeatlol** [comment]
I have the same issue

**Comment by rickinbsb** [comment]
when you guys close the custom css window and open it again, the code is reset or it stays?

**Comment by lolrepeatlol** [comment]
It’s reset

**Comment by adlerluiz** [comment]
in the new release when trying to save the file it will force the read and write permission of the css file, hopefully there will be no problems again

**Comment by rickinbsb** [comment]
I'm closing this as it was fixed by [v1.10](https://github.com/ytmdesktop/ytmdesktop/releases/tag/v1.10.0)

**Comment by lolrepeatlol** [comment]
Thank you!
