### ISSUE TITLE
Can't connect streamdeck plugin

### ISSUE THREAD

**Issue by MihneaXB** [ytmdesktop/ytmdesktop#1291]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I can't connect the streamdeck plugin to the app, because i can't find the button to go to the site where i can see the ip i get from the app. And when i try to open the https::localhost:9863 it gives me error 404

### Expected Behavior

I expected to see the button like the other versions

### Steps To Reproduce

1. I go to settings
2. I click on "Integration"
3. I enable" Companion Server"
4. I can't find the button to go to the site where to find the ip
5. Try to enter the localhost:9863 site and gives me error 404

### YTMDesktop

v2.0.0

### OS

Windows 

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by 8KIN** [comment]
Experiencing the same issue

Localhost:9863 - Gives this message
" {"message":"Route GET:/ not found","error":"Not Found","statusCode":404} "

**Comment by chanichanel** [comment]
Unfortunately came on here to say the same. The "enable remote control" isn't even popping up.

**Comment by A-Matt** [comment]
![image](https://github.com/ytmdesktop/ytmdesktop/assets/47449129/81230084-8de8-4de5-ba47-620f8822c56f)
https://github.com/XeroxDev/YTMD-StreamDeck/issues/85
