### ISSUE TITLE
Cannot start companion server: safeStorage unavailable

### ISSUE THREAD

**Issue by cortesi** [ytmdesktop/ytmdesktop#1295]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

On MacOS, I cannot start the companion server because safeStorage is unavailable.

![image](https://github.com/ytmdesktop/ytmdesktop/assets/22544/e2d43779-7839-4cb9-8205-fcb8ac8eefd8)

### Expected Behavior

Expected behaviour is to be able to  activate the companion server.

### Steps To Reproduce

Simply start the app

### YTMDesktop

v2.0.0

### OS

macOS 

### OS Version

14.3

### Arch

ARM64

### Installation way

Package downloaded from the latest release on Github

### Anything else?

- I've confirmed that this works starting the project with "yarn start" from source. I've not been able to confirm whether built packages from source succeed, because they crash immediately on my system when run, and I haven't had time to troubleshoot this.
- I've noticed a related issue report #1186. That issue seems Linux-specific.
- #1287 is also possibly related, but approving keychain access had no effect for me. 
- Possibly relevant: I had to use "xattr -c" to get around an error starting the app from the release packages after installation.

**Comment by NovusTheory** [comment]
This issue is pertaining to keychain access. You might need to double check you did everything for that correctly and quit the application fully and restarted it for it to detect access.

> Possibly relevant: I had to use "xattr -c" to get around an error starting the app from the release packages after installation.

We don't have signed and notarized builds for mac. This is clearing the quarantine flag mac puts on the application which is what throws the "App is damaged and can't be opened" popup. Many other issues are related to it not being signed and notarized as well.

**Comment by cortesi** [comment]
I've confirmed that keychain access is unrestricted, fully restarted the application, etc.

I see the following when starting the app manually from the command-line:

```[main][info] Application launched
[main][info] Created memory store
[main][info] Created electron store
[4858:0209/142953.477578:ERROR:keychain_password_mac.mm(113)] Keychain lookup for suffixed key failed: Error Domain=NSOSStatusErrorDomain Code=-67030 "(null)" (-67030)
2024-02-09 14:29:53.487 youtube-music-desktop-app[4858:54685] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
[main][info] Application ready
[main][info] Setup IPC handlers
[main][info] Setup permission handlers
[main][info] Unregistered shortcuts
[main][info] Registered shortcuts
[main][info] Created tray icon
[main][info] Created main window
[main][info] Created YTM view
[main][info] Setup taskbar features
[main][info] Integration update: Zoom Factor
[main][info] Starting enabled integrations
[renderer][info] LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.```

If we look up the error code 67030 we get for keychain access we see this:

https://www.osstatus.com/search/results?platform=all&framework=all&search=67030

And if we then look it up in the header file here:

https://opensource.apple.com/source/libsecurity_codesigning/libsecurity_codesigning-55032/lib/CSCommon.h.auto.html

... the matching comment is "invalid Info.plist (plist or signature have been modified)"

This looks like a code-signing error on plist access to me. So I think the fact that keychain access is denied is probably due to the fact that the application is unsigned. I'm sorry, but I don't have time to sign up for a developer account and test this at the moment, but perhaps it can provide a direction to look in for someone down the track.

**Comment by Alipoodle** [comment]
Duplicate of #1287 but this does have some helpful information so will share some of it in that  issue :)

**Comment by synmux** [comment]
`xattr -c /Applications/YouTube\ Music\ Desktop\ App.app` gets the app running.

`codesign --force --sign "Developer ID Application: Your Name" /Applications/YouTube\ Music\ Desktop\ App.app` enables safeStorage and thus the API etc.

You do of course need a developer ID cert but I'm fairly sure you can get one of those without being the Apple developer program.

**Comment by ephe-ply** [comment]
> `xattr -c /Applications/YouTube\ Music\ Desktop\ App.app` gets the app running.
> 
> `codesign --force --sign "Developer ID Application: Your Name" /Applications/YouTube\ Music\ Desktop\ App.app` enables safeStorage and thus the API etc.
> 
> You do of course need a developer ID cert but I'm fairly sure you can get one of those without being the Apple developer program.

This will work without a developer ID, just omitting the developer ID will do.

I did this and the companion settings were enabled.
```
codesign --force --deep --sign - \
"/Applications/YouTube Music Desktop App.app"
```
