### ISSUE TITLE
Removed songs from playlist are still visible

### ISSUE THREAD

**Issue by jsandr** [ytmdesktop/ytmdesktop#1297]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When removing one or more songs from a playlist, they still show in the playlist.
Only on a reload the page shows that they were removed.
See screenshot sequence:
1. selected multiple songs
![Screenshot_2](https://github.com/ytmdesktop/ytmdesktop/assets/61015242/273411f1-9ab0-4415-a6a8-6e85ae9418ec)
2. Removed them from the playlist
![Screenshot_3](https://github.com/ytmdesktop/ytmdesktop/assets/61015242/f2d9d2a0-6494-4cf8-bdda-51be636deeb9)
3. They are still there
![Screenshot_4](https://github.com/ytmdesktop/ytmdesktop/assets/61015242/e04c139d-fa14-4c53-965c-7a26009f1b3c)
4. After reloading the playlist, they are gone
'No screenshot'

### Expected Behavior

When clicking on the trash icon, songs are removed and the page is auto-reloaded to display changes.

### Steps To Reproduce

Go to any playlist.
Trash one song in it.
Select multiples songs, then trash them.
Go on any other YT desktop page.
Go back to the modified playlist.

### YTMDesktop

Version: 2.0.0  Branch: HEAD  Commit: 6d0abf5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Can you test this on a YTM Window in Browser?
Cause we do no additional processing on this page and I suspect that this is a YTM issue with caching the data when you go back a page.

**Comment by jsandr** [comment]
![Screenshot_5](https://github.com/ytmdesktop/ytmdesktop/assets/61015242/ea4460d1-38fc-474d-99e8-900f8418c100)
![Screenshot_6](https://github.com/ytmdesktop/ytmdesktop/assets/61015242/038e1293-c3f3-462f-84e3-7b8d421b408a)

OK issue on YTM browser as well.
