### ISSUE TITLE
Now Playing Information

### ISSUE THREAD

**Issue by aero31aero** [ytmdesktop/ytmdesktop#130]
Hey! Thanks for this app, and I love using it. A small feature request/help request:

Add a command line flag like `youtube-music-desktop-app --status` that gives the now playing information and preferably more (like the current queue) to the user.

If you don't have time to work on something like this, maybe a note on how this feature can be implemented could also help.

# Usecase

I'm switching from cmus to youtube music, and in cmus land I could do something like:

```
$ cmus-remote --query
status playing
file /home/rohitt/Music/blackbox/Death Cab for Cutie/Kintsugi/10 Ingenue.mp3
duration 271
position 177
tag artist Death Cab for Cutie
tag album Kintsugi
tag title Ingenue
tag date 2015-03-27
tag originaldate 2015-03-27
tag genre Indie Rock
```

Which could then be wrapped in a helper script to create beautiful desktop notifications like (see bottom left corner):

![image](https://user-images.githubusercontent.com/8033238/79177698-1c2db700-7e21-11ea-97b4-dff5d875b6ac.png)

**Comment by mingjun97** [comment]
You may use the companion server to retrieve the song info.
It uses websocket to communicate. Upon connected with the companion server via the websocket, you will get notified every 500 miliseconds with the corresponding track information and so on.

**Comment by aero31aero** [comment]
Hey thanks for the quick reply. Is there a link to the companion server? I couldn't locate any other repo here or anything on the website.

**Comment by adlerluiz** [comment]
Hello, thank you for using YTMDesktop.

As @mingjun97 said you can use the companion server, a WS server to receive information and control the music, you can make the connection using port 9863.

https://github.com/ytmdesktop/ytmdesktop/blob/master/providers/companionServer.js#L114

**Comment by adlerluiz** [comment]
@aero31aero I'm developing an http query api for the player and track

will be available in the next release and will be accessed by http://localhost:9863/query

![image](https://user-images.githubusercontent.com/2112638/82760538-77f94180-9dca-11ea-8000-17a53f169a8c.png)

**Comment by VolatilePulse** [comment]
In case anyone else stumbles across this thread in the future, I'll try to save you some headaches. While it's true that YTMD does use a websocket for the remote control app, you can't use a websocket to connect to it. You must use the npm (JavaScript) [Socket.IO](https://www.npmjs.com/package/socket.io) or another language implementation of it.

If you're not comfortable using Socket.IO, you can always use the HTTP API by fetching the data on a loop.

*I'll post some sample code this evening when I'm back at my computer for anyone unfamiliar with the process.*
