### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by redruum** [ytmdesktop/ytmdesktop#1301]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When selecting the full screen view while listening to an album it's just blank instead of showing the album on the left and the "next, lyrics, and history" tabs.
![Screenshot 2024-02-12 032900](https://github.com/ytmdesktop/ytmdesktop/assets/37255045/7b090008-fcd8-4181-b913-61663f279d99)

### Expected Behavior

When clicking on the arrow on the bottom right of the currently playing song I expected it to open in full screen mode with the playlist on the right side and the options to see the lyrics and the play history as well.

### Steps To Reproduce

Play a song from any album or playlist
Then click on the arrow on the bottom right hand side of the currently playing song.
the full screen with the currently playing album cover should pop open.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
As this is on the v1.13 we are not longer supporting this version anymore.
Please update to v2 if you would like to have support.
