### ISSUE TITLE
Link to currently playing song

### ISSUE THREAD

**Issue by arkyfinity** [ytmdesktop/ytmdesktop#1306]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

For the companion server:
In the `video` object in `/state`, it would be nice to have a `link` with the link for the song

We should have access to this as this is already in the share dialog in the player?  

### Solution

Example:

```json5
{
  "player": {
    // ...
  },
  "video": {
    "author": "Celine Dion",
    "channelId": "Something",
    "title": "My Heart Will Go On",
    "album": "Titanic OST",
    // ...
    "id": "99999",
    "link": "https://music.youtube.com/watch?v=string"
  }
}
```

**Comment by arkyfinity** [comment]
Nevermind, I just realised that we have the `id` and can just construct a URL from this.

**Comment by A-Matt** [comment]
Additionally you might want to consider adding the `playlistId` to the link depending on your use-case

```js
`https://music.youtube.com/watch?v=${data.video.id}${data.playlistId !== null ? `&list=${data.playlistId}` : ''}`
```
