### ISSUE TITLE
32 Bit (x86) Support?

### ISSUE THREAD

**Issue by croxydad** [ytmdesktop/ytmdesktop#131]
In website download button says "x86 Windows". My PC is Windows 8.1 32 bit and when i click the setup exe, it says me "Requires 64 bit". If it's requires 64 bit, why you write "x86 Windows"?

**Comment by adlerluiz** [comment]
The x86 version was previously supported and has been updated to 64 bits, the site has not been updated, thanks for reporting

**Comment by croxydad** [comment]
> The x86 version was previously supported and has been updated to 64 bits, the site has not been updated, thanks for reporting, I will fix the page.

Can i download the previous version?
