### ISSUE TITLE
Windows - Last.fm fail last.fm integrations

### ISSUE THREAD

**Issue by MasamuneDate99** [ytmdesktop/ytmdesktop#1316]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Last.fm wont integrated and authorize for windows version of Youtube Music Desktop App

### Expected Behavior

Authenticated immediately through last.fm authorization

### Steps To Reproduce

1. Enable last.fm through settings

### YTMDesktop

2.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

So before this happened, i'm using a older version of ytmdesktop prior to version 2.0. I authorize first on my ubuntu laptop, and it went without any problem. After that, i updated my windws ytmdesktop, and try to authenticate, but it just wont authorize. I have already try delete the authorization from ubuntu, and try to authorize it again using windows which didnt help at all.

Last.fm integration work before im updating it. 

![image](https://github.com/ytmdesktop/ytmdesktop/assets/24244933/56624d26-2108-4869-aa65-847ec8ea5a35)

this one is from the ubuntu one
![image](https://github.com/ytmdesktop/ytmdesktop/assets/24244933/9ff69c5e-d06e-4e92-8c40-ce43e8d54580)

**Comment by Alipoodle** [comment]
I'm not quite sure I understand the problem here~ 

You appear to have successfully linked it.
if you see that it says `Authenicated: No` in Settings, it's to do with the fact that we haven't TRIED to get your session updated. If you play a song and it opens up a new window to authenticate, and the **Authenticated: No** is still there then it means it has failed.

I need to get a refresh button to attempt to get the updated information if you have authenticated or not.

**Comment by MasamuneDate99** [comment]
> I'm not quite sure I understand the problem here~
> 
> You appear to have successfully linked it. if you see that it says `Authenicated: No` in Settings, it's to do with the fact that we haven't TRIED to get your session updated. If you play a song and it opens up a new window to authenticate, and the **Authenticated: No** is still there then it means it has failed.
> 
> I need to get a refresh button to attempt to get the updated information if you have authenticated or not.

I do able to link it, but its only from my Ubuntu laptop ( the bottom screenshot ). The upper part of the screenshot is the result when i click the authorize button. It does show it's succesfully authorize, but whenever i start youtube music it will keep asking the same prompt, without actually linking it.

![image](https://github.com/ytmdesktop/ytmdesktop/assets/24244933/92f96c4f-c81f-4a28-8fd9-51061a8b9e29)

*I only have this problem on my windows laptop

**Comment by Krose115** [comment]
Hello,

I can also confirm I'm having this same issue. I go to authenticate on last.fm's website, says it was successfully, however, the YTM desktop app doesn't reflect the connection, and for some reason, on last.fm's website, it doesn't add YTM desktop as a connection. Please let me know if you need anything to help solve this bug.

**Comment by TheArgentinian** [comment]
You have to restart the app to see "Authenticated: Yes" !

**Comment by MasamuneDate99** [comment]
> You have to restart the app to see "Authenticated: Yes" !

That's the first thing that i try. No, restarting both application and tried restarting my laptop didnt do anything.

**Comment by Alipoodle** [comment]
👍  Possibly one of the random issues of the Key not saving correctly.
Will close this issue for now. But it's on my list to add a refresh button next to the Yes to be able to do a check for if the key is valid
