### ISSUE TITLE
Advertisements are scrobbled to Last.FM

### ISSUE THREAD

**Issue by nattadasu** [ytmdesktop/ytmdesktop#132]
# Comment
It's kind of annoying me tbh, everytime when advertisement appears on YouTube Music (not premium user), the app will scrobbling the advertisement instead ignoring it.
# Version
I'm using YTMD ver. 1.9.0, downloaded through Website.
# Screenshot
## App when showing any advertisement
![](https://media.discordapp.net/attachments/589128995501637661/700159698610946179/unknown.png)
## Last.FM scrobble
![](https://media.discordapp.net/attachments/589128995501637661/700159910008193054/unknown.png)

**Comment by adlerluiz** [comment]
Thanks for the report, i will fix this problem.

**Comment by adlerluiz** [comment]
fixed on https://github.com/ytmdesktop/ytmdesktop/commit/e723b3887d3b8fe9d1f47b5abf0babb08caad062
