### ISSUE TITLE
Disable update check on startup.

### ISSUE THREAD

**Issue by TheArgentinian** [ytmdesktop/ytmdesktop#1327]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Wouldn't that make the splash screen time shorter?

**Comment by Alipoodle** [comment]
The startup of the application isn't that slow~
And the application during the Release candidate had no checks for updates, and it was the same speed as it is now really.
