### ISSUE TITLE
Support media casting

### ISSUE THREAD

**Issue by Andret2344** [ytmdesktop/ytmdesktop#1331]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I have a Google Nest Mini speaker that works fine with YT music mobile app as well as https://music.youtube.com website. It'd be great if I could control the speaker also using this app .

### Solution

Adding a button as ytm did. 

<img width="167" alt="image" src="https://github.com/ytmdesktop/ytmdesktop/assets/40674613/efd73eb7-6ef1-4ed3-9595-b99de3910fb9">

### Alternatives

using website.

**Comment by Alipoodle** [comment]
#29
