### ISSUE TITLE
Support media player on touch bar

### ISSUE THREAD

**Issue by MinSeungHyun** [ytmdesktop/ytmdesktop#135]
I use Play/Pause Button on touch bar, but ytmdesktop doesn't support touch bar. I want to control music using touch bar like this image.
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/44062683/79976683-fdda5200-84d7-11ea-8728-f4040325ea29.png">

Thanks to all contributors, I'm using this app very usefully 😊

**Comment by adlerluiz** [comment]
My intention was to have already created this integration, but I don't have a macbook to perform the tests.

**Comment by MinSeungHyun** [comment]
I looked at the code and found that it already supports media keys. So I upgraded the Electron version to latest release 8.2.3 and it worked very well.
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/44062683/80047377-387bd300-8548-11ea-9b44-26827b08f187.png">

**Comment by adlerluiz** [comment]
Great I updated and is already in branch development, thanks

**Comment by MinSeungHyun** [comment]
Thank you. I'll be waiting for the new version😊
