### ISSUE TITLE
Digital signature warning Windows 10

### ISSUE THREAD

**Issue by meow81** [ytmdesktop/ytmdesktop#138]
Should I be concerned about this warning?  Are there plans to add a valid signature?

![image](https://user-images.githubusercontent.com/22875048/80132406-a08ee100-8569-11ea-8463-46691aa0a577.png)

**Comment by meow81** [comment]
related to #155

**Comment by tobimori** [comment]
You shouldn't. This is because the developers can't or don't want to spend 100$ per year for a macOS developer account **and** > 300$ per year for a Windows Code Signing certificate.

**Comment by adlerluiz** [comment]
unfortunately it's really expensive

**Comment by meow81** [comment]
No prob, just wanted to ask. appreciate the responses.
