### ISSUE TITLE
How do you switch to Music video playback?

### ISSUE THREAD

**Issue by mkanet** [ytmdesktop/ytmdesktop#139]
One of the main features of YouTube Music is the ability to switch to playing music videos of almost any song (as long as it's on youtube.com).  I can do that on the official YouTube Music mobile apps.  How do you tell this app to prefer music videos instead of displaying just an album cover?

![YouTubeMusic-MusicVideos](https://user-images.githubusercontent.com/811008/80268839-7cadc700-865f-11ea-95d6-c92aed39c4e4.png)

**Comment by MrDvorak** [comment]
As I understand it, this is available neither in the web client nor in [GPMDP](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-). That's a big problem because it's an important feature of YTM

**Comment by rickinbsb** [comment]
yeah, this is only available on the mobile version currently
