### ISSUE TITLE
Miniplayer dragging/moving usability

### ISSUE THREAD

**Issue by meow81** [ytmdesktop/ytmdesktop#140]
I'm struggling a bit on dragging to move the miniplayer.  It has a tiny drag area in the left corner and the hover event is so fast, then it disappears from view making it really hard to move this thing around the screen.

I'd expect any area that isn't already a dedicated function on the miniplayer (play/pause, next,previous, or thumbs up/down) to be able to clicked and dragged to move the miniplayer.  there's no need for a tiny drag area in the upper left corner. Just make the entire thing enabled to be grabbed with the exception of the zones around the elements I mentioned earlier.

edit 5/4: going to open a new issue for mini player and lyrics windows unresponsiveness when moved.

**Comment by adlerluiz** [comment]
@rickinbsb

**Comment by NNowakowski** [comment]
I've done a bit of digging and unfortunately this is currently not possible the way it is implemented.
If you mark a region as draggable, all mouse events are being omitted by the OS, eliminating the current hover feature of showing the song title etc.

The only way around this would be to mark all those elements as non draggable which kinda defeats the purpose as you would also have to mark the mentioned song title etc. as non draggable for them to show correctly, leaving you with very little regions where you can actually still drag the window (mostly a tiny area below the buttons and the gap between the song information and the buttons).

This wouldn't be a problem if the song informations are always shown (which there is a setting for I think), but with the current reliance on the hover effect for showing all the controls this is not possible.

Source:
https://stackoverflow.com/questions/47063878/change-cursor-on-draggable-region-in-electron

**Comment by meow81** [comment]
Got it, thanks for looking into it.  Is it possible to make the drag area stay visible and be a little bigger of a square in the corner similar to the right upper corner that's for restoring the full size player?

**Comment by NNowakowski** [comment]
> Got it, thanks for looking into it. Is it possible to make the drag area stay visible and be a little bigger of a square in the corner similar to the right upper corner that's for restoring the full size player?

That should indeed be possible. The reason why it currently gets hidden when hovering over it is because of the mentioned underlying OS function; once your mouse is over it the original hover event, which would make that thing visible in the first place, gets eaten by the OS hence you dont see the icon anymore but can still drag the window.

To work around that it might be a good idea to have that icon visible at all times, while everything else stays hidden unless hovered, just to make the drag corner more visible in general.

**Comment by rickinbsb** [comment]
I've toyed with alternative options too, like handling position entirely manualy instead of passing it to the OS but had a hard time with it, expanding the draggable area and keeping the icon always on is a good option, I'll implement it

**Comment by NNowakowski** [comment]
> I've toyed with alternative options too, like handling position entirely manualy instead of passing it to the OS but had a hard time with it, expanding the draggable area and keeping the icon always on is a good option, I'll implement it

That would have been my last resort aswell but I don't think that's really worth the effort. I'll leave the changes up to you then; maybe just have the entire "topbar" draggable with the "close miniplayer" icon being the only thing excluded from the drag area, that way it atleast doesn't matter where you place your mouse on the top area.

**Comment by adlerluiz** [comment]
was in error in the code, every time you drag it he was trying to save the position.

Now fixed!

**Comment by rickinbsb** [comment]
updated drag are on v1.12, It is way easier to move the screen around (and less buggy) now, thank you!

**Comment by RCalabraro** [comment]
When I turn on the miniplayer, it seems like it's so far to the left that it's off the screen. I can't move back into the area of the screen where I can use it. Please help.
