### ISSUE TITLE
Error Message keep appearing

### ISSUE THREAD

**Issue by TotallyNotInUse** [ytmdesktop/ytmdesktop#145]
I was playing music as usual when this error appeared:
![image](https://user-images.githubusercontent.com/56458705/80655077-07653c00-8a3b-11ea-8a24-91005776c478.png)
 And just kept appearing when I closed the error. Though it got fixed when I closed the app but I feel like I have to let you know about this.

Also I can't seem to make web companion work, I don't where is the console that says where the port opened or what.

**Comment by adlerluiz** [comment]
Hello, in the integration settings, is there an option checked?

**Comment by TotallyNotInUse** [comment]
> Hello, thank you for the contact.
> 
> In the integration settings, is there an option checked?

Hi, all of this is checked
![image](https://user-images.githubusercontent.com/56458705/80985098-fece8600-8deb-11ea-8d62-886eeecad451.png)

**Comment by adlerluiz** [comment]
several corrections and improvements were made, I hope that in the next version you will no longer have this problem, if it occurs, please contact us again
