### ISSUE TITLE
ublock integration

### ISSUE THREAD

**Issue by randomstuff69** [ytmdesktop/ytmdesktop#1468]
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

ublock origin intergration

### Solution

add the chrome extension ublock origin in it to block ads

### Alternatives

use ublock on browser

**Comment by Alipoodle** [comment]
Duplicate of #114
