### ISSUE TITLE
Mini player and lyrics windows become unresponsive and lock up desktop when moved

### ISSUE THREAD

**Issue by meow81** [ytmdesktop/ytmdesktop#151]
When I move the lyrics or mini player window, my windows 10 system becomes unresponsive.  It's reproducible every time.   The full size player window is not impacted by this. I can move it around fast and a lot without any issues.

Some basic specs of my machine:
Windows 10 Pro 64-bit 1809
AMD FX-8370 Eight Core @ 4.00Ghz
16 GB RAM
256 GB Samsung SSD
GeForce  GTX 1660Ti
nothing exceptional in my build or OS configuration, but my specs shouldn't be the issue.

Some screen shots below of when it happens.  

![image](https://user-images.githubusercontent.com/22875048/81002045-a06acd00-8e16-11ea-99bb-1ea17a35a8a9.png)
![image](https://user-images.githubusercontent.com/22875048/81002061-a82a7180-8e16-11ea-9154-c46090a9b4b0.png)
![image](https://user-images.githubusercontent.com/22875048/81002075-ac568f00-8e16-11ea-8875-1a3c7b0e5aac.png)

**Comment by adlerluiz** [comment]
Hi @meow81 

I found the problem and already made the correction, thanks for reporting.
