### ISSUE TITLE
multiple lyric windows can be opened

### ISSUE THREAD

**Issue by meow81** [ytmdesktop/ytmdesktop#153]
You can open multiple lyric windows by clicking the lyric button.   Expected behavior is that you can only have one open at a time.  If it's open and the lyric button is pressed again, it just brings the already open window to the forefront or does nothing.

![image](https://user-images.githubusercontent.com/22875048/81029931-e21a6880-8e54-11ea-8caf-4d618afb4ea1.png)

**Comment by NNowakowski** [comment]
Thanks for the report, I'll look into it

**Comment by NNowakowski** [comment]
Adressed in #154 
The settings window showed the same kind of behavior so I also went ahead to fix it aswell.

**Comment by meow81** [comment]
thanks!
