### ISSUE TITLE
Lyrics at times do not advance to the next/previous songs

### ISSUE THREAD

**Issue by meow81** [ytmdesktop/ytmdesktop#156]
I can't find the pattern on this one but can pretty easily see it happen in a given session.   

Basically I like to leave the lyrics window open so I can horribly sing along and when the next song advances either at the end of the previous (or I manually advance) I'll notice that it appears to attempt to go change to the correct lyrics, but sometimes gets stuck on a previous song's lyrics. 

And it will autoscroll the wrong lyrics.  From what I can see I think this happens when I want to hear a song again and click previous to go back to a song and it seems to get stuck on a certain song and won't go back any further to display the lyrics.

Closing the lyrics window and reopening corrects the issue.

**Comment by NNowakowski** [comment]
I could imagine the cause being when you advance to a song where no lyrics can be found; can you check whether that's the case?

**Comment by adlerluiz** [comment]
https://photos.app.goo.gl/u5Q6Hw8fcVRLAac5A

**Comment by meow81** [comment]
I'll take a look now, I'm pretty sure the songs I noticed on have lyrics available, as closing the lyric window and opening corrected it.  Let me see if I can grab a video real quick.

**Comment by adlerluiz** [comment]
yes, it happened when going back to 'good news'

**Comment by meow81** [comment]
https://youtu.be/8W4M4FADqx8
Was able to show it getting stuck.  I close and reopen the lyrics window and it resolves.

**Comment by adlerluiz** [comment]
this is probably occurring through this line of code to update the lyrics screen:

```if (artist != lastArtist && song != lastSong) {```

and as I saw, the artist is the same so he is not entering the function.

I'll fix it, thanks

**Comment by meow81** [comment]
you guys are awesome!  Hope my bug reports aren't annoying.  Loving this app and appreciate your responsiveness / engagement.  Just sent over a $10 donation.

**Comment by adlerluiz** [comment]
I thank you, each report helps to correct and improve the experience with the app.

**Comment by NNowakowski** [comment]
> you guys are awesome! Hope my bug reports aren't annoying. Loving this app and appreciate your responsiveness / engagement. Just sent over a $10 donation.

Not at all, every help is appreciated!

**Comment by adlerluiz** [comment]
The bug happens when the author was the same, and when he did not find the new lyric, the correction was made and will be available in the next release. 

thank you
