### ISSUE TITLE
Add an option to remove the download bar

### ISSUE THREAD

**Issue by lolrepeatlol** [ytmdesktop/ytmdesktop#158]
Hello! Thank you for the work on the app. However, the download bar (on the taskbar) really irks me. Could it be possible for you to add a feature for removing that?

**Comment by adlerluiz** [comment]
Yes, it will be done, thanks =)

(as a matter of curiosity, why would you want to disable it?)

**Comment by lolrepeatlol** [comment]
Thanks! I don't know why it bothers me so much. I think I'm just used to it being only for downloads.

**Comment by adlerluiz** [comment]
Done, will be available in the next release :)

**Comment by lolrepeatlol** [comment]
Thanks!
