### ISSUE TITLE
Feature request: Adblocker

### ISSUE THREAD

**Issue by jigar007** [ytmdesktop/ytmdesktop#160]
The app is really awesome, just one feature which I have currently in browser and missing is adblocker. 
I am iOS developer, know very little about node and javascript, still if I can contribute something in that I am more than happy to do.

**Comment by gnahum12345** [comment]
bump this feature request.

**Comment by deprale** [comment]
this app is so getting DMCA'd if they do add adblocker lol
just block them yourselves its not that hard

**Comment by rickinbsb** [comment]
I'm closing this as it is a duplicate of #114
