### ISSUE TITLE
Lyrics not working on Mac Catalina

### ISSUE THREAD

**Issue by Koyaanisqatsi42** [ytmdesktop/ytmdesktop#162]
Hello, Great app. Except for the fact that lyrics are not working. it is just displaying a black popup while loading, but nothing ever loads. In settings, Lyrics provider is empty and i cannot enter anything. Please advice,

many thanks

**Comment by adlerluiz** [comment]
Hello @Koyaanisqatsi42 

thanks for the information, which version are you using?

**Comment by Koyaanisqatsi42** [comment]
I am using 1.9.0

Thank you, much appreciated

**Comment by adlerluiz** [comment]
this problem was fixed in version 1.10.0, but the person who generated the mac image for us has been out of contact for a while. We are looking at other ways to generate the installer

**Comment by Koyaanisqatsi42** [comment]
Hello, thanks. Maybe I can help with that?? I am a dev and own a Mac so I
can create the installer (I think)

**Comment by adlerluiz** [comment]
if you can build the new version and test it, it would be very good for us

**Comment by rickinbsb** [comment]
Hello, I believe this is fixed on 1.11, can you confirm @Koyaanisqatsi42

**Comment by Koyaanisqatsi42** [comment]
> if you can build the new version and test it, it would be very good for us

Sorry I just saw this :(

**Comment by Koyaanisqatsi42** [comment]
> Hello, I believe this is fixed on 1.11, can you confirm @Koyaanisqatsi42

Thanks, its excellent!

**Comment by rickinbsb** [comment]
Awesome! thank you :D

**Comment by rickinbsb** [comment]
and don't worry, we found a way to build it
