### ISSUE TITLE
Add function to mediaProvider to manually set the value of the volume slider bar.

### ISSUE THREAD

**Issue by joe-habel** [ytmdesktop/ytmdesktop#166]
MRPIS has the ability to send and receive volume inputs similarly to its timeline scrolling. 

If there was a function like `mediaChangeSeekbar`, but rather `mediaChangeVolumeBar`, that sets that value of the volume slider element, syncing the volume control via the player and a mpris client would be as simple as how syncing the timing control was.

If anyone could point me to a way that I could "Inspect Element", on an electron app, I should be able to work this into place.

**Comment by adlerluiz** [comment]
Hello @joe-habel 

the mediaProvider already has the methods volumeUp and VolumeDown

but if you need a better control, like mediaChangeSeekbar

that would probably be it

```
var slider = document.querySelector('#volume-slider');
slider.value = VALUE_BETWEEN_0_AND_100
```

**Comment by adlerluiz** [comment]
https://github.com/ytmdesktop/ytmdesktop/blob/development/providers/infoPlayerProvider.js#L274
