### ISSUE TITLE
Feature request: Sound Volume Leveling

### ISSUE THREAD

**Issue by ahmetcanaydemir** [ytmdesktop/ytmdesktop#168]
I know youtube music doesn't support volume leveling but can you add a simple volume bar and maybe shortcuts to ytmdesktop?

**Comment by adlerluiz** [comment]
Could you explain this idea better?

**Comment by ahmetcanaydemir** [comment]
@adlerluiz I am sorry this is my mistake. Youtube Music has this feature that I have not seen.

![YouTube_Music_Desktop_App_k1Dl2EHRop](https://user-images.githubusercontent.com/8572957/82758053-e18a4780-9dec-11ea-804e-8e3de9e4c3eb.png)
