### ISSUE TITLE
Feature request: show album artwork in Discord Rich Presence

### ISSUE THREAD

**Issue by TotallyNotInUse** [ytmdesktop/ytmdesktop#171]
I don’t really know if this is possible but it would look really nice that instead of the YTMD icon it showed the artwork.

**Comment by adlerluiz** [comment]
it would be ideal, but currently it is not possible, discord allows only pre-defined images

**Comment by TotallyNotInUse** [comment]
Ok, thanks anyway.

**Comment by Alipoodle** [comment]
Discord has recently allowed for people to now use URLs for the Large Artwork allowing for us to now do this:
Track the stuff in #888 (Likely be in Development before reaching a public release for a bit)

As this is the first item, I'm re-opening this ticket as the tracking ticket for the time being! 😸
