### ISSUE TITLE
Feature Request: Possibility to change custom audio output

### ISSUE THREAD

**Issue by Kryptox95** [ytmdesktop/ytmdesktop#172]
Title pretty much says it ^^

Would be awesome to select between all my available audio outputs.

**Comment by adlerluiz** [comment]
has already been developed and will be available in the next release

![image](https://user-images.githubusercontent.com/2112638/83327592-65ac5700-a253-11ea-9e05-75e97e0e432f.png)

**Comment by Kryptox95** [comment]
Awesome! Thank you for the information. Any approximate date when the next update will eventually come out ? Anyways, a huge 'thank you' (and all who worked on this) for doing this project! Absolutly love it!

**Comment by adlerluiz** [comment]
thank you very much =),
is scheduled for June 1st
