### ISSUE TITLE
Lyrics Does not show from the package in aur.

### ISSUE THREAD

**Issue by Da-Viper** [ytmdesktop/ytmdesktop#173]
before  you install it from the aur it shows 1.8.1... after installing it, it shows 1.9.2..........

if i used the snap version(it on version 1.8.1) and the lyrics shows 

tested song "all of me"  tried it on the aur version it show "loading......" till the song ends even for songs that dont have lyrics, i also noticed in the settings there is a new lyrics tab but it currently does nothing. 

OS information 
Manjaro kde 
kernel version 5.7.0-1

**Comment by adlerluiz** [comment]
Hello, lyrics are being redone, currently you must select which provider the system will try to get the lyrics to, but now it will automatically get from 2 servers (if there is not one, it tries on the other) and will be available in the next release

**Comment by rickinbsb** [comment]
Lyrics rework fixed this
