### ISSUE TITLE
Respect custom DNS settings

### ISSUE THREAD

**Issue by AlexIsOK** [ytmdesktop/ytmdesktop#175]
This app does not appear to respect my custom DNS settings that I have set in my Ubuntu WiFi settings.  Is there any way to either reset DNS cache or only use the DNS that I have set?  I don't want my DNS requests going to some external server.

Version 1.8.2 installed via snap on Ubuntu 20.04.

**Comment by rickinbsb** [comment]
Thanks for reporting this, we'll look into it

**Comment by Alipoodle** [comment]
Can I ask if this is still an issue?
I'm not aware of any code which would specifically be doing this, and would like to investigate more into this.

**Comment by AlexIsOK** [comment]
Forgot I even made this.  I'll check and see if it's still happening.

**Comment by Alipoodle** [comment]
No response in over 6 months, considering this as stale.
