### ISSUE TITLE
Suggestion - engine Lirycs

### ISSUE THREAD

**Issue by borut1** [ytmdesktop/ytmdesktop#176]
I suggest add engine:
https://www.musixmatch.com/

Good database

**Comment by adlerluiz** [comment]
Thanks for the sugestion, the use of this api was initially considered, but it is paid (https://developer.musixmatch.com/plans),

lyrics will be updated and we will use KSoft.Si API

**Comment by rickinbsb** [comment]
I'm closing this as we unfortunately can't follow the suggestion because it depends on a premium subscription

**Comment by borut1** [comment]
Ok, Understand
