### ISSUE TITLE
Tray icon becomes invisible after updating to v1.10.0

### ISSUE THREAD

**Issue by ariel-levin** [ytmdesktop/ytmdesktop#177]
After updating to v1.10.0, when I start YTM the icon is visible:
![visible](https://user-images.githubusercontent.com/8328635/83499169-97c4ef80-a4c5-11ea-907e-30b90773f169.png)

But when I start playing something, it becomes invisible:
![invisible](https://user-images.githubusercontent.com/8328635/83499180-9bf10d00-a4c5-11ea-81c7-ca248e48bd5d.png)

Operation system:
![image](https://user-images.githubusercontent.com/8328635/83499263-c17e1680-a4c5-11ea-9554-d66dbdd34922.png)

**Comment by adlerluiz** [comment]
Fixed

it's will available on 10.0.1 but download again the installer to fix now

**Comment by ariel-levin** [comment]
Thanks!
