### ISSUE TITLE
Icon in tray - dissapear

### ISSUE THREAD

**Issue by borut1** [ytmdesktop/ytmdesktop#179]
The system tray icon disappears from time to time.
![icon](https://user-images.githubusercontent.com/32434982/83507992-985f8500-a4c9-11ea-9504-fb4fcd0606e0.png)

**Comment by ariel-levin** [comment]
[https://github.com/ytmdesktop/ytmdesktop/issues/177](https://github.com/ytmdesktop/ytmdesktop/issues/177)

**Comment by adlerluiz** [comment]
Fixed

it's will available on 10.0.1 but download again the installer to fix now

**Comment by borut1** [comment]
Thanks, ;)
