### ISSUE TITLE
Bug: Mouse wheel for volume not working after updating to 1.10

### ISSUE THREAD

**Issue by andrescirulo** [ytmdesktop/ytmdesktop#180]
After updating to version 1.10 scrolling the mouse wheel in the playing bar does not change the volume anymore

**Comment by adlerluiz** [comment]
Thank you

this happened because the way the processes communicate were modified, and it was not changed in this part, it will be corrected and will be available in the next release

**Comment by adlerluiz** [comment]
Please, download again 1.10.0 version has fixed
