### ISSUE TITLE
Bug: Clicking app icon hides it instead of bringing it to focus

### ISSUE THREAD

**Issue by prog666** [ytmdesktop/ytmdesktop#184]
other apps bring them to focus, ytmdesktop toggles "show/hide" state instead. The problem is that you have to click twice to bring it on top of other windows.

**Comment by adlerluiz** [comment]
what OS do you use?

**Comment by prog666** [comment]
Oh, sorry! MacOS

**Comment by rickinbsb** [comment]
maybe we could do
one click: Focus if is open/ nothing if is closed
double-click: close if is open/ open if is closed
right-click : bring up menu

**Comment by prog666** [comment]
> one click: Focus if is open/ nothing if is closed

I'd say 
focus if open / open and focus if closed

**Comment by adlerluiz** [comment]
I believe this will correct
https://github.com/ytmdesktop/ytmdesktop/pull/196

**Comment by rickinbsb** [comment]
fixed on v1.11
