### ISSUE TITLE
Bug: Pause between songs

### ISSUE THREAD

**Issue by cjinahat** [ytmdesktop/ytmdesktop#185]
There is a pause between songs. Please remove this to allow for listening to electronic music.

**Comment by adlerluiz** [comment]
@rickinbsb and??

**Comment by rickinbsb** [comment]
can confirm the problem still happens on `development`

**Comment by rickinbsb** [comment]
I'm changing this to bug, as gapless playback is the supposed behaviour, thanks @cjinahat for bringing this up

**Comment by adlerluiz** [comment]
could you check if this problem still continues?

**Comment by guaycuru** [comment]
This is still happening on 1.12.1

**Comment by rickinbsb** [comment]
I wonder if we can fix this by manipulating the user agent

**Comment by sigma67** [comment]
Can confirm that it works fine in the web app, but not in ytmdesktop. Gapless playback is a must have for some albums

**Comment by azumukupoe** [comment]
I'm noticing gaps between tracks recently
Was it disabled by Google perhaps?

**Comment by rickinbsb** [comment]
It still works fine to me, are you experiencing this on the web version too?

**Comment by azumukupoe** [comment]
> 
> 
> It still works fine to me, are you experiencing this on the web version too?

Checked right now, yes.
