### ISSUE TITLE
Cannot login. Not available in your area.

### ISSUE THREAD

**Issue by gramirez897** [ytmdesktop/ytmdesktop#186]
Would love to try the app, but when I open it there's the message that "YouTube music is not available in your area". I know why it's showing the message, but even though it's not available in my area I do have a YouTube Music account due to my Google Play Music subscription, which I can access if I log into Google first and then navigate to music.youtube.com. 

Is there any way to emulate this in the app, some way that I could navigate to Google first, login and then come back to the app?

**Comment by gramirez897** [comment]
It seems it just became available in my country because I just opened it and was able to login no problem. I wasn't even able to get to the settings page. It just showed a message saying it wasn't available. 

![image](https://user-images.githubusercontent.com/6840501/84465570-58c13780-ac45-11ea-8f35-95b74dba7fcf.png)

I do get what you're saying maybe it would've worked if I went into the site through a browser and changed the location but I won't know now cause it's working. Thanks for the help and for the app of course!

**Comment by adlerluiz** [comment]
if your country is any of these, it is now available

https://www.androidpolice.com/2020/06/10/youtube-music-and-premium-expand-to-14-new-markets/

**Comment by gramirez897** [comment]
Yeah Puerto Rico. What are the chances it became available just after I posted the issue. Thanks!

**Comment by gramirez897** [comment]
> if your country is any of these, it is now available
> 
> https://www.androidpolice.com/2020/06/10/youtube-music-and-premium-expand-to-14-new-markets/

Yeah Puerto Rico. What are the chances it became available just after I posted the issue. Thanks!
