### ISSUE TITLE
Feature Request: Controls on notification

### ISSUE THREAD

**Issue by andrescirulo** [ytmdesktop/ytmdesktop#193]
I don't know if this is posible. 
When the notification popups, could there be controls, for example to skip the song?

![image](https://user-images.githubusercontent.com/13123832/84308385-d2b5cb80-ab34-11ea-81f6-05d1d2e7bc6f.png)

**Comment by adlerluiz** [comment]
I will take a look at the documentation, but I believe that there is no such option

**Comment by adlerluiz** [comment]
Integration with the windows media system has been implemented, and you can control it

![image](https://user-images.githubusercontent.com/2112638/89724509-56c3ec80-d9da-11ea-88d3-08e6228a0159.png)
