### ISSUE TITLE
MacOS menu bar icon incorrect render/scaling

### ISSUE THREAD

**Issue by manastalukdar** [ytmdesktop/ytmdesktop#195]
The menu bar icon is showing up incorrectly as shown in the screenshot below.

<img width="653" alt="Screenshot at Jun 11 12-21-17" src="https://user-images.githubusercontent.com/2075466/84430213-2fb98c00-abde-11ea-980c-5c39253c038d.png">

**Comment by adlerluiz** [comment]
thanks, let's fix this, unfortunately we don't have mac to test

**Comment by manastalukdar** [comment]
@adlerluiz , I am happy to test it out on a mac once a commit has been made.

**Comment by adlerluiz** [comment]
@manastalukdar PR was done on development and can be tested

**Comment by manastalukdar** [comment]
@adlerluiz , Confirming that it is now fixed with latest on `development`.

**Comment by rickinbsb** [comment]
cool! this PR will come out on 1.11

**Comment by adlerluiz** [comment]
Thank you for your feedback
