### ISSUE TITLE
Add a slot for U2F-Devices

### ISSUE THREAD

**Issue by mightywomble** [ytmdesktop/ytmdesktop#198]
Would it be possible to update the yaml on the snap to have a slot for u2f-devices and map this to the u2f-plugin so I can use my Google hardware authentication token to login?

Happy to test and feedback if you dont have one.

**Comment by rickinbsb** [comment]
Hello there, I'm closing this as it duplicates #110, but yes, we do not own auth tokens, so help with implementing this is highly appreciated
