### ISSUE TITLE
Feature Request: Guest Mode

### ISSUE THREAD

**Issue by rickinbsb** [ytmdesktop/ytmdesktop#2]
It would be nice to have an option to listen to songs without tracking them on your google/yt user, kinda like logging with incognito mode on a browser, for the times you don't want songs suggested to you in the future based on that session.
Possible name suggestions: Guest Mode; Party Mode; Incognito Mode

**Comment by mingjun97** [comment]
Maybe you can try to switch account in youtube music.
Just click your avatar located the top right corner and choose switch account. So the flavor of your main account won't change during that session.

**Comment by rickinbsb** [comment]
@mingjun97 Yes, this is a good alternative, the only problem is that it would require me signing-in with another account
