### ISSUE TITLE
YTMDesktop window shows Google Account Help instead of the player

### ISSUE THREAD

**Issue by Yirg** [ytmdesktop/ytmdesktop#200]
###### (Describe the problem here) 

YTMDesktop window doesn't show the player, but Google Account Help page. I uninstalled then re-installed the program but the result is the same.

![YTMDesktop](https://user-images.githubusercontent.com/17637862/84581210-6c0c0880-ade7-11ea-920c-04fb5709cd66.png)

System tray options behavior:
- Play/Pause, Previous, Next - all do nothing
- Lyrics - loads, but displays "Lyrics not found" (which makes sense, as nothing is playing)
- Settings - window is displayed and seems to be functional
- Guest - loads the program with Google Account Help page, but signed out
- Miniplayer - mini player is displayed, but buttons don't do anything

![YTMDesktop-mini](https://user-images.githubusercontent.com/17637862/84581220-8514b980-ade7-11ea-857f-9b9ef7af0cd6.png)

#### Environment 
 * YTMDesktop: - 
 * Platform: win32 
 * Arch: x64 
 * Version: 10.0.18362 
 * Memory: 16 GB 
 * Node: 12.8.1 
###### (if possible)

**Comment by adlerluiz** [comment]
Hello, go to settings

![image](https://user-images.githubusercontent.com/2112638/84581247-9e9d0d80-adb5-11ea-96f1-70e2d35af4fd.png)

and verify if this option is checked

![image](https://user-images.githubusercontent.com/2112638/84581253-b1afdd80-adb5-11ea-9ebf-b79bbbc13d6a.png)

if yes, uncheck, close and try again

**Comment by Yirg** [comment]
Thanks adlerluiz. This helped!

I hope there's a plan to fix this so that the app itself can automatically recover from this situation, because most users probably aren't going to discover this workaround.

**Comment by adlerluiz** [comment]
Yes, I want to improve this, thank you for report.

**Comment by adlerluiz** [comment]
Now show back button on any page

![image](https://user-images.githubusercontent.com/2112638/84583709-f0ec2780-add1-11ea-90a4-55802bf1f3c6.png)

**Comment by adlerluiz** [comment]
Now live

https://github.com/ytmdesktop/ytmdesktop/releases/tag/v1.11.0
