### ISSUE TITLE
macos binaries missing for 1.10 release

### ISSUE THREAD

**Issue by AlJohri** [ytmdesktop/ytmdesktop#202]
hi! thanks for making this app. looks like the macos binaries are missing for v1.10:

<img width="1266" alt="Screen Shot 2020-06-16 at 6 48 18 PM" src="https://user-images.githubusercontent.com/2790092/84835603-f29c3200-b001-11ea-90c2-5e31b9b0a185.png">

<img width="1287" alt="Screen Shot 2020-06-16 at 6 48 25 PM" src="https://user-images.githubusercontent.com/2790092/84835609-f760e600-b001-11ea-8ba6-6fb88511c9df.png">

p.s. would you consider adding this to homebrew cask for easy install on macos?

**Comment by adlerluiz** [comment]
now live https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.10.0/YouTube.Music.Desktop.App-1.10.0.dmg

**Comment by adlerluiz** [comment]
it's a good suggestion, I'll research how to add it to the homebrew, thanks

**Comment by adlerluiz** [comment]
@AlJohri now on brew cask - https://github.com/Homebrew/homebrew-cask/pull/84606

**Comment by AlJohri** [comment]
thank you!
