### ISSUE TITLE
Bug: (Catalina) Track Info in Top Menu Bar not Updating

### ISSUE THREAD

**Issue by github-ronk** [ytmdesktop/ytmdesktop#203]
- Version 1.11.0 (1.11.0)
- Catalina 10.15.5
- Darwin rk-mbp.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

Dunno if "menu bar" is the correct term, this refers to the top bar on the macOS screen (see screenshot)

While playing an album, the track info indication in the top bar stop updating and keeps showing the same info from before.

![Screen Shot 2020-06-18 at 9 33 12](https://user-images.githubusercontent.com/6041369/84986491-50866200-b147-11ea-9f14-bc0cca162233.png)

**Comment by adlerluiz** [comment]
thanks for the info, i will fix

**Comment by rickinbsb** [comment]
Fixed on v1.12, thank you!
