### ISSUE TITLE
Feature Request: Do we really need custom shiny-tray popup menu?

### ISSUE THREAD

**Issue by zagoruev** [ytmdesktop/ytmdesktop#207]
Shiny tray can be enabled only on macOS, but custom popup menu looks like it's not from macOS and don't add any additional features comparing to system popup menu.

So I think it's possible to get rid of it and just use system-looking menu.

<img width="241" alt="Screenshot 2020-06-19 01 58 29" src="https://user-images.githubusercontent.com/986243/85080537-1ada8b00-b1d2-11ea-9f6d-ab5e5528bfbd.png"><img width="272" alt="Screenshot 2020-06-19 01 59 13" src="https://user-images.githubusercontent.com/986243/85080539-1c0bb800-b1d2-11ea-9cc8-c2915c9acc09.png">

**Comment by rickinbsb** [comment]
I agree for consistency
