### ISSUE TITLE
Feature Request: Disabling album thumbnails in playlists & pre-loading playlists & find function

### ISSUE THREAD

**Issue by ALiAvkaya** [ytmdesktop/ytmdesktop#209]
Hello all,

This is my first time writing a request so I apologize beforehand if I make or made a mistake. For example I wasn't sure if I should open a seperate issue for all three things I mentioned in title but I think they are all somehow related to each other (at least in my usage scenario) and I thought it would be less clustered this way.

I don't know if many people use YTM like I do but I don't use different playlists, I only use one which consists of more than 1500 songs. I used to use Spotify before and I migrated, this is where the need for the feature requests come in.

As I migrated from Spotify, some songs are not the ones they were supposed to be. So when I shuffle play my big playlist and come across them, I find the correct version, add it to my list, then open up my list, press End key for about a minute so that I reach to the end of the list, I press Ctrl-F and write the songs name which is going to be replaced, memorize it's position in the list, go to the end of the list again, move the new song to its supposed place, delete the different version.

Before ytmdesktop, I used YTM's own Chrome extension / app thing and it's advantage was I could use media keys but as Chrome on my computer has several addons, it was better to edit my list using Firefox, which I use daily, since it somehow worked and loaded lists faster even though it having more addons than Chrome.

Spotify loads the whole playlist at once without their album thumbnails on playlist itself, so I could instantly find a song no matter where in the list it is. And I know this is Youtube's fault for not loading whole lists, but I figured I might have a shot asking you guys since I thought it could be possible putting an option to block thumbnails in the lists from loading, and forcing the lists to load in the background (which are playing ATM or some selected ones everytime the app is opened) and you would be definitely faster than Google delivering such features if are they feasible of course.

I must say, ytmdesktop works flawlessly when dragging a song in a list IF that section's thumbnails are loaded already. And its loading times are also great comparing to both Firefox and Chrome in my case, still it could be better.

Best case scenario for me would be like this: There would be an option to tell the app to load my playlist everytime I open the app or start shuffle playing the list, there would be another option to block the thumbnails, and when I come across with a song that needs to be replaced, I could use the Find function like I can on browsers.

I don't know if I used way more sentences than I needed to but as I'm not a native speaker I sometimes feel like I might have trouble making myself clear. So I apologize for my blabbering on about such a trivial issue and thanks for bearing with me up until this point. Best wishes.

**Comment by adlerluiz** [comment]
Hello @ALiAvkaya thank you for contacting us, I understand your problem, well for now what’s in development and I believe it can help you, it’s the queue list in the api, it’s going to look like this:

![image](https://user-images.githubusercontent.com/2112638/85318077-c49d6e80-b495-11ea-8e0d-b1e75cef2a50.png)

but for now it is only the queue that is playing, but I intend to make modifications to have more control in the playlists like exporting too

**Comment by Alipoodle** [comment]
As these are all Server side stuff, I am closing this issue as a Won't Fix/Add
