### ISSUE TITLE
winget shows latest version as v1.9.0 instead of v1.11.0

### ISSUE THREAD

**Issue by sasawatc** [ytmdesktop/ytmdesktop#210]
Just tryout installing using `winget install Ytmdesktop.Ytmdesktop` but it installed v1.9.0 instead of v1.11.0.

`winget show Ytmdesktop.Ytmdesktop`
![image](https://user-images.githubusercontent.com/8133231/85339143-645bfc00-b498-11ea-8aec-5defb718b68b.png)

**Comment by adlerluiz** [comment]
I already did the update, just waiting to accept

https://github.com/microsoft/winget-pkgs/pull/1982

but no problem, when you start it will upgrade by autoupdate
