### ISSUE TITLE
Bug: The application won't build from the aur 

### ISSUE THREAD

**Issue by Da-Viper** [ytmdesktop/ytmdesktop#211]
when you try to build from the aur  it shows  

npm ERR: missing script: pack:x64 

i am using a 64 bit system  the build file does not work any more for the latest version 
But the latest [comment](https://aur.archlinux.org/packages/ytmdesktop-git/) on the aur page it works [here it is](https://github.com/yochananmarqos/pkgbuilds/blob/master/ytmdesktop-git/PKGBUILD)

would it be possible to  update the pkgbuild file ? with that or a working one, as currently it does not work

**Comment by rickinbsb** [comment]
oh, this is because it should now use publish:lin instead of pack:x64, I'll check with the mantainer, thanks

**Comment by rickinbsb** [comment]
oh, the mantainer actually patched it already, can you try again please?

**Comment by rickinbsb** [comment]
@garfunkel can you update the PKGBUILD to the new build method? There is an updated version of it on the issue description

**Comment by rickinbsb** [comment]
As changes are only merged to master when there is a new release, I believe it makes more sense to use the `development` branch on `ytmdesktop-git`. Otherwise it won't be that different from `ytmdesktop`

**Comment by rickinbsb** [comment]
fixed by @yochananmarqos
