### ISSUE TITLE
Bug: Multiple instances of YTMDesktop

### ISSUE THREAD

**Issue by TotallyNotInUse** [ytmdesktop/ytmdesktop#213]
If you look into Task Manager you will see multiple instances of YTM Desktop and I can close almost all of them without crashing the app. I thought Single Instance was implemented.

![image](https://user-images.githubusercontent.com/56458705/85607406-51b90280-b611-11ea-9491-77483c397015.png)

**Comment by adlerluiz** [comment]
Hello @TotallyNotInUse 

these are subprocesses that some libraries use to function like this fakebrowser to work the notification on the desktop.

![image](https://user-images.githubusercontent.com/2112638/85634403-aed4a880-b651-11ea-8c50-388f605adf96.png)
