### ISSUE TITLE
Song lists doesn't load, takes ages with the spinning status

### ISSUE THREAD

**Issue by letshopeandtry** [ytmdesktop/ytmdesktop#216]
#### Problem 
I just had my google music transferred over and my custom uploads of songs takes ages to load or nothing loads at all.

Also, where are the Title of the columns. I can't sort my tracks or positions in the list anymore?

#### Environment 
 * YTMDesktop: - 
 * Platform: win32 
 * Arch: x64 
 * Version: 10.0.18362 
 * Memory: 8 GB 
 * Node: 12.14.1 
###### (if possible)

**Comment by rickinbsb** [comment]
Hello there. I believe this is a problem on google`s end, as the app is just a wrapper for their web version
