### ISSUE TITLE
Taskbar Flashing with second Monitor

### ISSUE THREAD

**Issue by churchymayer** [ytmdesktop/ytmdesktop#218]
I'm using a triple monitor setup and have Display Fusion installed. When i move the application on a secondary monitor the app is constantly "opening and closing" on the taskbar of my main monitor.

I have it set up so that only the monitor that has the app open will show it on the taskbar.

**Comment by rickinbsb** [comment]
Can you check if this still happens if you change the titlebar style from Nice to System?

**Comment by churchymayer** [comment]
Still happens if I change the titlebar style to system

**Comment by tophattwaffle** [comment]
I also have this issue. Here is a gif of what the issue in action looks like.

![2020-07-14_01-13-50](https://user-images.githubusercontent.com/6774125/87390898-5d904880-c56f-11ea-97af-0aa4fc69a42a.gif)

**Comment by Silky322** [comment]
Having the same issue, also using Displayfusion. Seems to only happen when there is a song selected (paused or playing). When I first open the application and it has the name "YouTube Music" in the taskbar I can move the window to another monitor without issue, but when I start a song it will start behaving as in the gif, even if I pause it. Issue persists with Nice, System, and Disabled Titlebar.

**Comment by adlerluiz** [comment]
This is happening, because every 500ms it is updated to recreate the buttons according to the status of like/dislike and play/pause, I modified the code and this update will only happen if you paused the song or gave like/dislike

**Comment by rickinbsb** [comment]
Fixed on v1.12, thank you!

**Comment by tophattwaffle** [comment]
Hello!

Just went to check back in on this project as I hate Spotify so much... When moving the player to another window, the program stays on the windows Taskbar. I can use DisplayFusion to remove it from the windows taskbar, but when the same changes it comes back. Ideally the program should never re-add itself to the windows taskbar.
