### ISSUE TITLE
Restore window typo

### ISSUE THREAD

**Issue by NesseSmit** [ytmdesktop/ytmdesktop#219]
When hovering over the maximize/restore button in the right hand corner of the YTMdesktop app it shows 'restaure' instead of 'restore'. (Language = English) 
![YTMD_typo](https://user-images.githubusercontent.com/51516947/85934723-6afad100-b8e7-11ea-9067-8df48b23e8e0.jpg)

I know it is a very small issue but still ;-)

P.S. Great work on the app by the way! It works great!

**Comment by adlerluiz** [comment]
Has been resolved and will be fixed in the next release, thanks
