### ISSUE TITLE
Can't order tracks

### ISSUE THREAD

**Issue by BernieCook** [ytmdesktop/ytmdesktop#225]
#### Environment 
 * YTMDesktop: - 
 * Platform: win32 
 * Arch: x64 
 * Version: 10.0.18362 
 * Memory: 16 GB 
 * Node: 12.14.1 
###### (if possible)

**Comment by dstutzman1** [comment]
I think that's more a YouTube Music UI issue, not an issue with the desktop player app. To my knowledge, the YTM Desktop app is basically just a wrapper for the web version of YouTube Music. So I think YouTube Music would have to implement this natively in their UI

**Comment by rickinbsb** [comment]
Hey there, thanks for the sugestion!
But as @dstutzman1 pointed, this would have to be implemented on google's side
