### ISSUE TITLE
Sometimes window title does not update to playing track after an ad

### ISSUE THREAD

**Issue by dotcomboom** [ytmdesktop/ytmdesktop#227]
![image](https://user-images.githubusercontent.com/38927017/86502247-cb19c900-bd66-11ea-845e-ac64570b9a3b.png)

I don't think this happens all the time, but sometimes when the ad finishes the window title doesn't update to the playing track, instead staying as ` - Video will play after ad`. In these cases it seems to be necessary to change tracks.

Seeing as the window title is updated to the playing track before an ad is run (if I'm observing correctly), would it be possible to perhaps prevent the window title from changing when an ad is playing?

**Comment by adlerluiz** [comment]
Thanks for reporting, I also saw this problem and it has been fixed, it is in branch development and will be available in the new release.

https://github.com/ytmdesktop/ytmdesktop/commit/addc687a610c8aa6f34098a685d148e3b44546f5#diff-7a9076d6d94e62c13d641aa71f19ae8eR364
