### ISSUE TITLE
Icons are sometimes not loaded (encircled in red)

### ISSUE THREAD

**Issue by debmaj2** [ytmdesktop/ytmdesktop#231]
![image](https://user-images.githubusercontent.com/22155707/86844935-680d9680-c0c6-11ea-8090-a45d99df84e3.png)

**Comment by adlerluiz** [comment]
Hello, do you use any vpn or is your internet connection a little slower than normal?

**Comment by debmaj2** [comment]
How to capture logs?

I use an optical fibre broadband and Adguard Premium.

Adguard doesn't block YouTube Music Web Cosmetic Elements, though the buttons in question seem to be local assets.

This happens on only on startup or when System wakes from sleep. I would be happy to assist if there's a log capture method.

**Comment by rickinbsb** [comment]
you can debug the app by downloading the source, installing the dependencies with `npm i` and launching it with `npm start`, as long as you have node installed

**Comment by adlerluiz** [comment]
Could you confirm that this is still happening with the new version?

**Comment by debmaj2** [comment]
Hi, I updated to the latest version, and the above bug did not appear yet. I would report back if it occurs again.

**Comment by adlerluiz** [comment]
Right, thanks
