### ISSUE TITLE
Alternate keyboard shortcuts interference

### ISSUE THREAD

**Issue by chitza** [ytmdesktop/ytmdesktop#235]
`Ctrl` + `Shift` + `Space` is one example - I use it for code completion in various IDEs (Visual Studio, Rider).
When I press `Ctrl` + `Shift` + `Space` the player pauses.

It would be nice to have a toggle for alternate shortcuts (i.e.: handle only media keys) - I'd like to disable those.
Or at least a flag in a config file I could modify.

**Comment by rickinbsb** [comment]
Thanks for the suggestion! I'm closing this as a duplicate of #3 and it is already being worked on
