### ISSUE TITLE
Can't move window when titlebar is hidden

### ISSUE THREAD

**Issue by Innarel** [ytmdesktop/ytmdesktop#239]
#### Environment 
 * YTMDesktop: - 
 * Platform: win32 
 * Arch: x64 
 * Version: 10.0.18363 
 * Memory: 8 GB 
 * Node: 12.14.1 
###### 
![image](https://user-images.githubusercontent.com/51493189/87212491-29115800-c2f5-11ea-9b67-007c83d732a5.png)

**Comment by rickinbsb** [comment]
I believe this could be done by adding a draggable area on some corner of the window, as the current version of the miniplayer

**Comment by Innarel** [comment]
You can make all the topbar dragable, except where it has buttons or links.

**Comment by adlerluiz** [comment]
Done, will be available in the next release (this week)
