### ISSUE TITLE
Multiple Miniplayers

### ISSUE THREAD

**Issue by Innarel** [ytmdesktop/ytmdesktop#242]
#### Environment 
 * YTMDesktop: - 
 * Platform: win32 
 * Arch: x64 
 * Version: 10.0.18363 
 * Memory: 8 GB 
 * Node: 12.14.1 
###### 
![image](https://user-images.githubusercontent.com/51493189/87219042-71993780-c32e-11ea-9791-d8283319f59f.png)

**Comment by adlerluiz** [comment]
@Innarel Thank you for report this problem, has just been fixed, and will be available in the next release.
