### ISSUE TITLE
Remove the youtube music popup's

### ISSUE THREAD

**Issue by vexii** [ytmdesktop/ytmdesktop#246]
we know that YouTube music is going to be forced apron us at some point. but i don't know why we are getting the popup messages to change.  
the goal of the application should be to allow users to play music and control play lists. nether are features of you tube music and as such should not be a annoying message in the application

**Comment by rickinbsb** [comment]
I'm not sure what pop up are you talking about, but this app is just a wrapper for the web version of Youtube Music web version, which is provided by google
