### ISSUE TITLE
Show more buttons to actions instead of all under the 'more options' button.

### ISSUE THREAD

**Issue by wardboumans** [ytmdesktop/ytmdesktop#247]
It would great to have direct access to 'add to playlist' and 'add to library' actions in grids and player view. We have plenty of space :)

![image](https://user-images.githubusercontent.com/9028898/87278483-da2a1500-c4e4-11ea-9dfe-6b4cc6256004.png)

**Comment by adlerluiz** [comment]
![image](https://user-images.githubusercontent.com/2112638/90855924-232c7f00-e357-11ea-9ab4-33b2fc738792.png)

**Comment by wardboumans** [comment]
Awesome! Thanks 👍

**Comment by adlerluiz** [comment]
![image](https://user-images.githubusercontent.com/2112638/92402983-f45c2a00-f106-11ea-8878-725215a89fa3.png)
