### ISSUE TITLE
Feature Request: Sorted Playlists

### ISSUE THREAD

**Issue by cip314** [ytmdesktop/ytmdesktop#248]
In the Android App, playlists can be sorted by date added or alphabetically. 
This function, or any sorting function, would be really helpful for users who organize their music in playlists.

**Comment by motobyte** [comment]
In general, the lack of sorting by artist, album, and song title is very frustrating for users with large libraries.  I find it very hard to use the app in it's current state.

**Comment by rickinbsb** [comment]
Hi there, this would be really interesting, but It would need to be implemented on youtube's side, not on the app itself.
