### ISSUE TITLE
YT Music app is very slow. Slowing down system, having to use web version.

### ISSUE THREAD

**Issue by DenneyLewis** [ytmdesktop/ytmdesktop#249]
YT Music app is very taxing on my system. I'm not sure if there's something I'm doing wrong, but the app hogs a lot of resources, and causes my entire system to run slowly, whereas using the web version is just fine. App lags when hitting next song, has loading issues, and sometimes just blanks out all together.

PC Specs:
Windows 10
AMD Ryzen 5 3550H @ 2.10 GHZ, overclocked up to 3.70 GHZ
8GB Ram

Normally have no problems doing heavy activities. (I play World of Warcraft on high setting frequently with no issue) so i'm not exactly sure why YT music is taxing my system so badly.

**Comment by alexaandru** [comment]
I came here to report the same. It's unusable unfortunately. I have `Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz` and `16GB` of RAM and use `Ubuntu 20.04 LTS`. Looks great though! Thank you! :)

**Comment by adlerluiz** [comment]
thanks for reporting, are you using version 1.11.0?

**Comment by alexaandru** [comment]
Yes, I am.

**Comment by adlerluiz** [comment]
the problem of slowness already happens when opening, or while using the app?

**Comment by mrmichaelbeck** [comment]
I have a similar issue.  I let the player play all day at work as I'm working.  After a day or two of this, the player becomes very slow.  It's a gradual build.  I'm on a dual-xeon machine with 40GB of RAM in Windows 10.  And I'm running 1.11.0.  Turning off the player and then starting it up again seems to speed things up again, but gradually it slows down again.

**Comment by adlerluiz** [comment]
I believe that the use also happens through the youtube music site, since many people are complaining about it

https://www.reddit.com/r/YoutubeMusic/comments/hi9i9v/in_the_time_it_took_me_to_write_this_post_memory/

**Comment by rhwendt** [comment]
I think this is related to https://github.com/ytmdesktop/ytmdesktop/issues/260#issue-659446882

**Comment by adlerluiz** [comment]
Could you confirm that this is still happening with the new version?

**Comment by mrmichaelbeck** [comment]
It's significantly reduced, but still occurs.

**Comment by DenneyLewis** [comment]
I've been in this conversation since the beginning but haven't said
anything. From my side, everything is all good now, but I did just recently
buy a new gaming desktop so that very well could've fixed the issue, but I
did also download the new update. Either way, I'm not having any problem
now.

**Comment by adlerluiz** [comment]
I apologize, but I am always improving the code and updating the electron version when there is a question of performance involved, I hope these problems will end soon

**Comment by DenneyLewis** [comment]
I think a lot of it seriously may be on YouTube Music itself. It's a very
inferior alternative to Google Play. The app is working fine for me now. I
appreciate your hard work.

**Comment by alexaandru** [comment]
Sorry, I haven't used it in a while. I just tried it now for ~20 minutes and it seems to be working fine! :-) I have the latest version, v1.12.1. This is awesome, thank you! :-)

**Comment by vernzimm** [comment]
I have two issues with performance. Using Win10 and V1.13.0.

I am seeing a lot of RAM usage over time... when started it spawns 5 processes with approx 225MB of RAM total, but over time, several hours while I work, the main app process will climb to over 700MB of RAM by itself.

Second, possibly related. I have "Keep YTMD on background when window close" enabled (not sure if related). With main window closed, and music playing, it takes an extremely long time to exit. This can happen two ways... if I log out of Windows, or if I right-click tray icon and "Exit". Think 10-20 seconds. If open the main window and pause the track that is playing, it will shut down almost instantly. Maybe there is a buffer that it is playing to the end of before allowing it to close?

**Comment by azumukupoe** [comment]
It ate 15/32 GB today...

**Comment by lehades** [comment]
If it is really a YTM problem, instead of saying it's-happening-to-me-too i would like to propose a workarround

@adlerluiz maybe it would be possible to implement an API command to "reload the player" lowering tha RAM usage and/or slugishness

**Comment by Ranarrr** [comment]
Getting some problems with RAM usage after time as well. All I am able to say is that I listen to a lot of long "radios" of songs (you know, the first option when right-clicking a song). It seems to keep the songs I listen to on the app, or YTM. This could be either as far as I know, since I don't know how this app operates.
![image](https://user-images.githubusercontent.com/7990338/102432960-c3e43000-4013-11eb-987b-234ecfd84a39.png)
Had the app up for a few days (not listening constantly).

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
