### ISSUE TITLE
Feature Request: Native Notifications

### ISSUE THREAD

**Issue by TotallyNotInUse** [ytmdesktop/ytmdesktop#251]
Hello,
I have seen other JS apps use Native Windows 8.1 notifications instead of the old Windows 7 ones like this:
![image](https://user-images.githubusercontent.com/56458705/87455669-0ae07c00-c5c3-11ea-80ef-cdeaf855b4fb.png)
instead of this:
![image](https://user-images.githubusercontent.com/56458705/87455749-251a5a00-c5c3-11ea-83ef-10a680392fdc.png)

So I looked at the source code of the other app and found they use this [Electron Notification](https://www.electronjs.org/docs/api/notification), unfortunately I don't know how to use JavaScript or Electron so I've made this issue in hopes that you may read this and think about it.

Excuse me if I'm wrong or not possible.

**Comment by rickinbsb** [comment]
what version of windows are you using?

**Comment by adlerluiz** [comment]
strange because we use [electron-native-notification](https://www.npmjs.com/package/electron-native-notification) which is just to generate native notifications

**Comment by TotallyNotInUse** [comment]
> what version of windows are you using?

Windows 8.1

**Comment by Daniel9132** [comment]
It would be nice if you could use Windows 10 notifications in the Volume Menu Overlay like the Spotify App does.
This way i can see cover art and song when you are inside a fullscreen app.
![spotify notification](https://user-images.githubusercontent.com/33548848/88458904-87137300-ce91-11ea-9f3c-76f0a74ccb45.jpg)

**Comment by TotallyNotInUse** [comment]
It's already reported in issue #61

**Comment by TotallyNotInUse** [comment]
Anyways I upgraded to Windows 10 so it no longer matters
