### ISSUE TITLE
Corsair K70 Media keys not working

### ISSUE THREAD

**Issue by jondominguezv** [ytmdesktop/ytmdesktop#252]
I have a Corsair K70 lux keyboard and I when I have ytmdesktop open the media keys on the keyboard don't work with it. The media keys work with other music apps that I've used. I'm on Windows 10.

**Comment by rickinbsb** [comment]
might be related to #100

**Comment by kirebyte** [comment]
I discovered something weird, Kubuntu user here, cooler master keyboard in my case.
If I keep the options window open and press the multimedia keys while focused on that window they work. But I lose the focus, close that window or switch desktop it stops working. Might be related to the way it's listening to keys.

@jondominguezv would you mind trying these steps for me?
1) Open the program and play a song.
2) Open the settings menu (top right cog button)
3) Press pause.
4) Song actually pauses.

**Comment by rickinbsb** [comment]
I believe this can be caused by some other app taking over control of mediakeys when ytm is not focused

**Comment by jondominguezv** [comment]
> I discovered something weird, Kubuntu user here, cooler master keyboard in my case.
> If I keep the options window open and press the multimedia keys while focused on that window they work. But If I lose the focus, close that window or switch desktop it stops working. Might be related to the way it's listening to keys.
> 
> @jondominguezv would you mind trying these steps for me?
> 
> 1. Open the program and play a song.
> 2. Open the settings menu (top right cog button)
> 3. Press pause.
> 4. Song actually pauses.

I tried this and it did not pause.

**Comment by jondominguezv** [comment]
I enabled Start on Boot and now the media keys seem to work every time.

**Comment by rickinbsb** [comment]
Can you please check if this is fixed on v1.12?
We added deeper media integration with the system

**Comment by jondominguezv** [comment]
Looks like its working good.

**Comment by jondominguezv** [comment]
> Can you please check if this is fixed on v1.12?
> We added deeper media integration with the system

Looks like its working good.

**Comment by rickinbsb** [comment]
awesome!
