### ISSUE TITLE
App for Remote Control

### ISSUE THREAD

**Issue by lucas-luchack** [ytmdesktop/ytmdesktop#253]
Information about the application.

Edit: [v1.0.3](https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0/app-release-1.0.3.apk)

> Hello, I already sent the app to google play, I'm waiting for them to review, I already have the link but it's not available yet
> 
> https://play.google.com/store/apps/details?id=app.ytmdesktop.remote
> ![image](https://user-images.githubusercontent.com/2112638/87452234-5866e400-c5d7-11ea-994b-78ca44442b2c.png)
> 
> Apk:
> [app-release.zip](https://github.com/ytmdesktop/ytmdesktop/files/4920041/app-release.zip)
> 
> Prints
> ![1](https://user-images.githubusercontent.com/2112638/87452329-7af8fd00-c5d7-11ea-97ef-18db2896f0d1.png)
> ![2](https://user-images.githubusercontent.com/2112638/87452333-7c2a2a00-c5d7-11ea-9f4d-72e46c64741a.png)
> ![3](https://user-images.githubusercontent.com/2112638/87452335-7cc2c080-c5d7-11ea-8f24-1e6c34173785.png)
> ![4](https://user-images.githubusercontent.com/2112638/87452336-7d5b5700-c5d7-11ea-920e-9d3d1a739ced.png)

_Originally posted by @adlerluiz in https://github.com/ytmdesktop/ytmdesktop/issues/74#issuecomment-658286439_

**Comment by lucas-luchack** [comment]
Hello!
First feedback from me and I couldn't test very far beacause the application firmly refuses to connect to my computer.

I activated the server on the desktop app, I scanned the QR code with the phone app but the connection is not etablished.

**Information about my configuration**:
- PC wired to the internet
- Xiaomi Mi 8 Lite
- MIUI Global 11.0.2
- Android 10 QKQ1.190910.002
- Security fix of 2020-04-01
- No password for the companion server

**Screen**:
![IMG_20200715_115429.jpg](https://user-images.githubusercontent.com/39491773/87532695-d5579380-c693-11ea-89c5-698ebcc76764.jpg)
![IMG_20200715_115454.jpg](https://user-images.githubusercontent.com/39491773/87532712-d983b100-c693-11ea-882b-9bc7ad8b2c9f.jpg)
![IMG_20200715_115928.jpg](https://user-images.githubusercontent.com/39491773/87532720-dc7ea180-c693-11ea-985a-c3159636050e.jpg)

**NOTE**:
- I installed with the APK you provided.
- The web page works perfectly whether locally or on another network device. 

_Originally posted by @lucas-luchack in https://github.com/ytmdesktop/ytmdesktop/issues/74#issuecomment-658678868_

**Comment by rickinbsb** [comment]
oh, I believe the current version of app depends on stuff that is on the development branch (to be released on 1.12). which operating system are u using?

**Comment by lucas-luchack** [comment]
I use Windows 10 Pro 2004 build 19041.329

**Comment by adlerluiz** [comment]
Sorry, my bad, the app works for now only with development branch, but i will build pre-release version with the data which is required from app to work correctly

**Comment by lucas-luchack** [comment]
Thanks, I've installed version 1.12.0 ![image](https://user-images.githubusercontent.com/39491773/87569995-3b5e0e00-c6c8-11ea-8bda-157772db0ac2.png) And I've seen some bugs (normal it's a pre-release) so here it is :

- The http://localhost:9863/ page has a display problem and duplicates the QR Code and information.
![Capture d’écran (2)](https://user-images.githubusercontent.com/39491773/87570228-9132b600-c6c8-11ea-8adc-b5bfe8fe07a8.png) **! EDIT ! After a few restarts of the software the bug does not appear anymore. To be checked...**

- I don't think the problem is with you, but the app still doesn't work for me. I don't send back images or information, it's exactly the same as this morning with the only difference that the version of ytmdesktop is there 1.12.0.
So I will wait wisely for a stable version or the Play Store version because maybe Play Protect blocks the communication of the application in case it's a malicious application...

If I encounter bugs other than the application I'll let you know!

P.S. I love the new logo, great!

**Comment by adlerluiz** [comment]
I performed the installation out of play on 3 phones and it worked normally, the prerequisites are:

- Access the camera to scan the qrcode (can be added manually);
- Be connected with the cell phone on the same wifi network as the computer;

Can you send a print of this connection attempt?

**Comment by lucas-luchack** [comment]
I didn't understand... What do you want me to send you?
And how do I get what you're asking for?

**Comment by adlerluiz** [comment]
it was screen share, but I read that you informed that you did not connect, what could be done is to remove the install again to try to connect

**Comment by adlerluiz** [comment]
https://play.google.com/store/apps/details?id=app.ytmdesktop.remote

**Comment by dadi11** [comment]
I am getting this error after opening companion server link from settings
![image](https://user-images.githubusercontent.com/7272087/87857083-3ac1b380-c924-11ea-95ab-701f8846da63.png)

**Comment by adlerluiz** [comment]
hello, thanks for letting me know, I updated the beta version, could you download and install again? thank you

**Comment by dadi11** [comment]
It's fixed now, the server's page opens fine in browser, but still I can't connect. After scanning qr code these are the credentials, which I guess are wrong 
![Screenshot_20200718-210803](https://user-images.githubusercontent.com/7272087/87860133-39e84c00-c93b-11ea-8a4c-865b55ff8a44.jpg)

**Comment by adlerluiz** [comment]
by default when you activate the companion server, it generates a password, do you have protection enabled?

![image](https://user-images.githubusercontent.com/2112638/87861505-478ed900-c91d-11ea-9ad9-ef11b6768541.png)

**Comment by dadi11** [comment]
I've tried with this feature enabled and disabled but it doesn't work neither way for me

**Comment by adlerluiz** [comment]
do you have any firewall that may be blocking the connection?

**Comment by dadi11** [comment]
no, I use windows defender only. my pc is connected by ethernet cable and phone connected to the same network by wifi. I tried to put the wifi name into 'name' field instead 'ethernet' but it didn't work too

**Comment by adlerluiz** [comment]
the name part is only for a future implementation to add multiple locations, but what is really needed is just the ip the password and if it is protected.

when you save, on the player screen is he trying to connect?

**Comment by dadi11** [comment]
yes, it's Reconnecting... (1-5) then says Disconnected

**Comment by adlerluiz** [comment]
I will test here with a smartphone that was never installed

**Comment by adlerluiz** [comment]
what version of your android?

**Comment by dadi11** [comment]
Android 10 OnePlus 6

**Comment by ZombieAnidata** [comment]
Having the same error on the 1.12.0 beta version of the desktop application on Windows 10 2004. (Ethernet)
![Annotation 2020-07-26 214556](https://user-images.githubusercontent.com/64793241/88487485-1b630000-cf8e-11ea-90cc-314be1b6c419.png)

**Comment by ZombieAnidata** [comment]
I just found the error i think.
![Annotation 2020-07-27 155206](https://user-images.githubusercontent.com/64793241/88543844-392d7500-d021-11ea-8f88-c956ab8bb59f.png)

**Comment by adlerluiz** [comment]
Interesting because I installed on 2 computers with clean win 10 and there was no problem, how did you get this error log?

**Comment by ZombieAnidata** [comment]
In event viewer in Computer management applications logs.

**Comment by adlerluiz** [comment]
Please, try with this version (under review in the play store)

[app-release.zip](https://github.com/ytmdesktop/ytmdesktop/files/5003279/app-release.zip)

**Comment by ZombieAnidata** [comment]
> Please, try with this version 1.0.3 (under review in the play store)
> 
> ![image](https://user-images.githubusercontent.com/2112638/88962327-a8eb6c00-d27c-11ea-9f30-24e4dc583e01.png)
> 
> [app-release.zip](https://github.com/ytmdesktop/ytmdesktop/files/5003279/app-release.zip)

The problem i can't acess the offline website with the QR code.

**Comment by adlerluiz** [comment]
I updated the beta, can you download and install again?

https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0-beta/YouTube.Music.Desktop.App.Setup.1.12.0.exe

**Comment by ZombieAnidata** [comment]
> I updated the beta, can you download and install again?
> 
> https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0-beta/YouTube.Music.Desktop.App.Setup.1.12.0.exe

Same error it is a problem with ms edge (chromium version)?
![image](https://user-images.githubusercontent.com/64793241/88965182-0dc1b900-d2b3-11ea-96ec-49fe7280cb12.png)

**Comment by adlerluiz** [comment]
No

![image](https://user-images.githubusercontent.com/2112638/88965687-7f810f00-d281-11ea-9175-d489b3c830b9.png)

**Comment by rickinbsb** [comment]
I got it working on the newer beta

**Comment by adlerluiz** [comment]
Please, check if this url has the same problem http://localhost:9863/info

**Comment by ZombieAnidata** [comment]
It gived me my network adaptors.
![image](https://user-images.githubusercontent.com/64793241/88966277-b6244d00-d2b4-11ea-95b8-c9e872eed768.png)

**Comment by adlerluiz** [comment]
I redid the build with a small adjustment can you please test again?

https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0-beta/YouTube.Music.Desktop.App.Setup.1.12.0.exe

**Comment by ZombieAnidata** [comment]
It works now i will test the apk now.
![image](https://user-images.githubusercontent.com/64793241/88967442-81b19080-d2b6-11ea-93ef-cfac2423e9bc.png)

**Comment by ZombieAnidata** [comment]
The APK works too.

**Comment by adlerluiz** [comment]
Great, thanks for testing

**Comment by ZombieAnidata** [comment]
For nothing.

**Comment by Cheerpipe** [comment]
Hi. The app in the play store is not working. I think it is an older version (july 13th).

Can someone upload the apk here to test?

Thanks in advance

**Comment by adlerluiz** [comment]
Hi @Cheerpipe , yes the play store version is older, I'm having some problems with the play store to send the app, but as soon as I solve it.

the latest version: [1.0.3](https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0/app-release-1.0.3.apk)

**Comment by Cheerpipe** [comment]
@adlerluiz thanks for your amazing work.

**Comment by adlerluiz** [comment]
The app has released - https://play.google.com/store/apps/details?id=app.ytmdesktop.remote

**Comment by lucas-luchack** [comment]
It's work properly now.
Thanks!
