### ISSUE TITLE
custom theme Appearance color

### ISSUE THREAD

**Issue by andre-w** [ytmdesktop/ytmdesktop#254]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
When opening the appearance color functionality of the custom theme the window is empty

**To Reproduce**
Go to Setting 
appearance
custom theme toggle on
edit color
the opened window is empty

**Expected behavior**
choose a color of appearance?! 

**Screenshots**
![image](https://user-images.githubusercontent.com/1253959/87554400-60488600-c6b4-11ea-8ac7-2c4945f526a3.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.11.0***
 * OS: ***Windows*** 
 * OS version: ***2004***
 * Build: ***19041.329***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by adlerluiz** [comment]
Hello, thanks for reporting, it has just been fixed and will be available in the next release, for now you can manually edit the file, it is located at:

```C:\Users\{YOUR_USER}\Documents\youtube-music-desktop-app\custom\css\page.css```

**Comment by andre-w** [comment]
Thanks!
