### ISSUE TITLE
Bug_rep: Youtube music x google play music

### ISSUE THREAD

**Issue by moesac0970** [ytmdesktop/ytmdesktop#255]
#### Environment 
 * YTMDesktop: - 
 * Platform: win32 
 * Arch: x64 
 * Version: 10.0.18363 
 * Memory: 32 GB 
 * Node: 12.14.1 
#### Prints 
![image](https://user-images.githubusercontent.com/42092816/87686634-0237a380-c785-11ea-8f24-af84e4324a0c.png)

###### (if possible)

**Comment by adlerluiz** [comment]
unfortunately it's a problem with the YouTube Music platform, not the app
