### ISSUE TITLE
feature request: sort + select within playlists

### ISSUE THREAD

**Issue by luckybuzz** [ytmdesktop/ytmdesktop#256]
hi all, great work on this app!

one of my favourite features of the google play music desktop app was how within playlists, you could click the column headers to sort the playlist alphabetically by title, artist, album, play count etc.

also, you could multi-select several songs in the playlist using Ctrl-click or Shift-click, and perform actions on your multi-selection, instead of on one song at a time.

would be great if either/both of these features could be incorporated in the YTM desktop app... cheers!

**Comment by rickinbsb** [comment]
Hi there, this would be really interesting, but It would need to be implemented on google's side, before being implemented on the app itself.
