### ISSUE TITLE
Thumbs up behavior

### ISSUE THREAD

**Issue by rsxchin** [ytmdesktop/ytmdesktop#259]
Action: Pressing Thumbs up on a song that is already liked
Expected behavior: Ignore Thumbs up action and leave song liked
Actual behavior: Song is removed from like songs

If I Thumbs up a song while the app isn't visible, sometimes I will accidently remove a song I liked in the past.

**Comment by Bo0sted** [comment]
Pretty sure this default behavior on YouTube/YT Music itself. And remember, this app is only a software wrapper for the web version of YT Music

**Comment by rsxchin** [comment]
Then I guess I'm requesting a new feature.

**Comment by ZombieAnidata** [comment]
It gived me my network adaptors.
![image](https://user-images.githubusercontent.com/64793241/88966103-78bfbf80-d2b4-11ea-9cf1-996102d6bf99.png)

**Comment by adlerluiz** [comment]
it's a good suggestion, but if you are indifferent to the song, I mean you don't want to like it (or like it unintentionally and want to revert) or dislike

**Comment by rsxchin** [comment]
For clarification, I'm talking about using the hot key to like a song while the app is minimized or hidden.

**Comment by adlerluiz** [comment]
Done, available in the next release
