### ISSUE TITLE
Companion server crashes when you try to access it

### ISSUE THREAD

**Issue by Lunarixus** [ytmdesktop/ytmdesktop#261]
#### Problem 
In the most recent update accessing the companion server throws a null js error.

#### Environment 
 * YTMDesktop: - 
 * Platform: win32 
 * Arch: x64 
 * Version: 10.0.19041 
 * Memory: 15 GB 
 * Node: 12.14.1

**Comment by adlerluiz** [comment]
thanks, has been fixed and will be available in the next release
