### ISSUE TITLE
Request: (macOS) Add the option to turn off track progress on dock

### ISSUE THREAD

**Issue by bentert** [ytmdesktop/ytmdesktop#267]
I noticed the Windows version has this option but not the MacOS one.

YTMDesktop version: 1.9.0
OS: macOS Mojave 10.14.6

**Comment by adlerluiz** [comment]
hello, this option was added in v1.10.0 and you can update your app by downloading the latest version v.1.11.0

https://github.com/ytmdesktop/ytmdesktop/releases/tag/v1.11.0
