### ISSUE TITLE
Media Keys not working on Mac

### ISSUE THREAD

**Issue by shriyanshagro-fk** [ytmdesktop/ytmdesktop#271]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Next or Previous keys are not working with Mac's Task Bar Panel and Notifications Panel.
Neither it is working with Headphone's double top to move to next.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Notifications Panel on Mac
2. Click on Next on music player while playing music from YTM
3. Song doesn't change.

**Expected behavior**
Next song should be played

**Environment (please complete the following information):**
 * YTMDesktop version: ***vX.Y.Z***
 * OS:***Mac***
 * OS version: ***10.14.6***
 * Arch: ***x64*** 
* Installation way: .DMG installation

**Comment by max-was-here** [comment]
Looks like a duplicate of #205 
Waiting for that fix too, I like using those media and having iTunes open when I hit play/pause is annoying.

**Comment by shriyanshagro-fk** [comment]
Thanks for the reply, looks same to me as well. So closing this ticket now.
