### ISSUE TITLE
Unable to change details of uploaded songs

### ISSUE THREAD

**Issue by johannesreitergit** [ytmdesktop/ytmdesktop#274]
#### Problem 
Unable to change details of uploaded songs. 

###### (Describe the problem here) 
I uploaded my own music but unfortunately I cannot change the title artist or any other details about the song as is was possible with Google Music player.

#### Environment 
 * YTMDesktop: - 
 * Platform: linux 
 * Arch: x64 
 * Version: 4.15.0-112-generic 
 * Memory: 8 GB 
 * Node: 12.14.1 
###### (if possible)

**Comment by adlerluiz** [comment]
unfortunately youtube music still doesn't allow this type of editing.
