### ISSUE TITLE
Feature request: Blur album background on miniplayer

### ISSUE THREAD

**Issue by error7404** [ytmdesktop/ytmdesktop#275]
changing the `background-image` of the miniplayer and putting a simple `div` with `filter: blur(8px);`
so the Texte is more readable

I just made a test: if it doesn't load [click here](https://imgur.com/a/qPBJHRp)
![image](https://user-images.githubusercontent.com/48163201/88466017-70d4d980-cec8-11ea-9bc0-679baae9a40c.png)
![image](https://user-images.githubusercontent.com/48163201/88466014-69adcb80-cec8-11ea-96b8-9e175450dc8a.png)

**Comment by rickinbsb** [comment]
it used to have blur, but it stopped for some reason, I'll try to fix it tomorrow

**Comment by rickinbsb** [comment]
Implemented on v1.12, thank you!
