### ISSUE TITLE
Asus ROG Strix Flare Media Keys not Working

### ISSUE THREAD

**Issue by DSBD** [ytmdesktop/ytmdesktop#279]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The media keys on my Asus ROG Strix Flare keyboard do not work in the app. On laptop media keys also do not function.

**To Reproduce**
1. Open App
2. Play Music
3. Try Using Media Keys
4. See Error

**Expected behavior**
Media keys should function as stated. Might be integration issue with Windows 10 Media Interface.

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.10.0***
 * OS: ***Windows*** 
 * OS version: ***Version 1909 (Build: 18363.959)***
 * Arch: ***x64***
* Installation way: ***.exe from official website***

**Comment by rickinbsb** [comment]
Can you please check if this is fixed on v1.12?
We added deeper media integration with the system

**Comment by DSBD** [comment]
Media Key are working as expected on Version 1.12.
Closing the issue as it no longer present.
Thank You
