### ISSUE TITLE
Yubikey security device doesn't work for 2fA

### ISSUE THREAD

**Issue by flaviocpontes** [ytmdesktop/ytmdesktop#280]
My google account is protected by a security key.

I can't finish login because the security key dialog never appears

**Comment by notmike101** [comment]
Also happens with my Titan security key and my phone's built in security key.

Just seems like an issue with security key authentication overall.

**Comment by WorkingFerus** [comment]
Same. I have tried with both a Titan and Yubiko keys, and they're not recognized.

**Comment by rickinbsb** [comment]
Hi there,
I'm closing this as duplicate of #110
