### ISSUE TITLE
Distribution Request: Chocolatey Package Manager for Windows

### ISSUE THREAD

**Issue by jaybaldwin** [ytmdesktop/ytmdesktop#281]
Similar to AUR on Arch, apt-get on other Linux distros, chocolatey is a package manager for Windows: 

Here's an example of a package: https://chocolatey.org/packages/GPMDP

Once chocolatey is installed, installation of your app is easy: `choco install ytmdp` (or whatever unique keyword you choose).  Almost everything I install on Windows these days comes from chocolatey.

**Comment by adlerluiz** [comment]
I used the choco but I switched to winget, thanks for showing interest, I already added, awaiting for approval =D

https://chocolatey.org/packages/ytmdesktop

**Comment by jaybaldwin** [comment]
https://chocolatey.org/packages/ytmdesktop#testingResults
Looks like it needs comments removed from a template to pass automated validation?

**Comment by felipecrs** [comment]
The package is awaiting a response from the author, it seems.

https://chocolatey.org/packages/ytmdesktop
