### ISSUE TITLE
shortcuts unable to be turned off

### ISSUE THREAD

**Issue by aitaDev** [ytmdesktop/ytmdesktop#282]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
App has no way to turn off shortcuts or ignore keystokes, this becomes a problem when playing a game that you gotta do the magic 3 keys, keeps pausing and playing music. makes app not really usable while gaming.

**To Reproduce**
No error, feature request, great app

**Expected behavior**

**Screenshots**
NA

**Environment (please complete the following information):**
Windows

**Comment by adlerluiz** [comment]
Added customization, will be available in the next version #3
