### ISSUE TITLE
Suggestion - Add song art to discord rich presence.

### ISSUE THREAD

**Issue by doomsdaymatrix** [ytmdesktop/ytmdesktop#284]
Adding a song banner rather than the default YT Music Desktop icon. 

Current appearance:
![image](https://user-images.githubusercontent.com/33496590/89135251-1697d200-d4e1-11ea-8233-c01c5bc49d0e.png)

Suggestion concept:
![ConceptYTRichPresense](https://user-images.githubusercontent.com/33496590/89135312-8908b200-d4e1-11ea-8f14-a8012713b27b.png)

**Comment by Alipoodle** [comment]
Sadly this is not possible!
Discord RPC doesn't allow for uploading images on the fly or using of Third Party Assets within Discord Rich Presences images.

**Comment by adlerluiz** [comment]
correct, unfortunately it is not possible

**Comment by Alipoodle** [comment]
Discord has recently allowed for people to now use URLs for the Large Artwork allowing for us to now do this:
Track the stuff in #888 (Likely be in Development before reaching a public release for a bit)
