### ISSUE TITLE
Custom theme tab doesn't work

### ISSUE THREAD

**Issue by doomsdaymatrix** [ytmdesktop/ytmdesktop#285]
Custom theme tab doesn't work. The save icon doesn't seem to work and the rest of the page is empty. 

**To Reproduce**
Open YTM Desktop settings. 
Go to Appearance > Custom Theme > Pencil/Edit

**Expected behavior**
The custom theme tab should open to be editable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/33496590/89135754-970c0200-d4e4-11ea-9ed8-2e21b2fe5182.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.11.0***
 * OS: ***Windows 10 Pro x64 | Version May 2004***
* Installation way: ***.exe***

**Comment by adlerluiz** [comment]
hello, this issue has already been fixed and will be available in the next release (this week)

https://github.com/ytmdesktop/ytmdesktop/issues/254
