### ISSUE TITLE
Miniplayer always ontop not always working with other always on top and full screen apps

### ISSUE THREAD

**Issue by c9806961** [ytmdesktop/ytmdesktop#286]
**Describe the bug**
Miniplayer always ontop not always working with other always on top and full screen apps. This was introduced in electron v7 as per https://github.com/electron/electron/issues/20933

**To Reproduce**
See https://github.com/electron/electron/issues/20933

**Expected behavior**
Miniplayer should stay ontop of all other windows

**Environment (please complete the following information):**
 * YTMDesktop version: Latest
 * OS: Windows 10
 * Arch: X64

This will likely not be fixed until fixed in electron, but there may be some way around it.

**Comment by adlerluiz** [comment]
Two implementations are already underway that can help, the first is the widget on the xbox game bar and the other is integration with windows media service.

![image](https://user-images.githubusercontent.com/2112638/89215161-828c4000-d59e-11ea-822f-67d33deb2bec.png)

and

![image](https://user-images.githubusercontent.com/2112638/89215179-891ab780-d59e-11ea-9a50-9a889f6c3274.png)

**Comment by c9806961** [comment]
There are some cases where these aren't valid. I use rdp for work a lot and neither of these are available when I'm in a full screen rdp session. It's good to have the miniplayer over the top of my rdp while working to have playback control without having to minimise my rdp.

**Comment by rickinbsb** [comment]
I'll see if there is a possible workaround for this

**Comment by c9806961** [comment]
Thanks! Don't waste too much time on it. I've had a play around and I'm pretty certain it will be an issue until it's fixed in electron.

**Comment by RCalabraro** [comment]
When I turn on the miniplayer, it seems to be stuck off the screen to the left. I can't get my pointer that far over to drag it back into the area of the screen where I can use it. Please help.

**Comment by Alipoodle** [comment]
As Miniplayer is no longer included with YTMDv2 and will likely get entirely re-worked.
I'm closing this issue
