### ISSUE TITLE
Show Windows Volume Media Pop-Up when switching songs with Media Keys

### ISSUE THREAD

**Issue by DSBD** [ytmdesktop/ytmdesktop#287]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
It would be nice to see the artist and song title when changing songs with the media keys.

**Describe the solution you'd like**
A solution similar to the Spotify Desktop app, where the volume media pop is momentarily displayed when a song is Play/Pause'd or changed to the Previous/Next Track.

**Describe alternatives you've considered**
N/A

**Additional context**
Seeing as the app already integrates with the Windows with the Windows 10 Volume menu player I believe it would be easy to integrate

![image](https://user-images.githubusercontent.com/12722293/89241614-710e5c80-d5cd-11ea-86a2-f8cba8ff7889.png)

This menu would be the one to pop up momentarily.

**Comment by rickinbsb** [comment]
it shows up everytime there is a new song, along the notification?

**Comment by DSBD** [comment]
It shows up if you change the volume but does not appear when a new song is played by advancing the track with the media keys when the app is minimized

**Comment by roskad** [comment]
Please, make a switch in settings to turn this off/on. I don't like this feature and always disable in every app.

**Comment by adlerluiz** [comment]
I tested Spotify and it didn't happen, could I show myself? because the notification that appears when the music is changed

**Comment by djohannes** [comment]
@rickinbsb The Win10 integration is not behaving like it does with other apps using it. Normally if you have more than one media app playing, the media key always work with the "latest" one you used and you can switch between the apps in the media pop-up. So for example, if you pause media app 1 and switch to media app 2 to play something, the media keys would interact with media app 2.
But with YTMdesktop the media keys still only control YTMdesktop, even if you paused the media and switched to a different media app to play something. So this is probably also why the media pop-up doesn't show up if you switch with media keys, like it does with other media apps.. it's just not the "Windows 10 way" of handling media keys yet :)

**Comment by djohannes** [comment]
Fun fact, some games' anti-cheat programs do block the "old way" of handling media keys while you're in game (e.g. Rainbow 6 Siege in game). When I'm in such a game and hit play/pause, it still works and now actually brings up the media pop-up! It's probably using the "windows 10" way now as the "old way" is blocked :) So maybe this can be fixed by just allowing me to disable the "old way"?

**Comment by TotallyNotInUse** [comment]
Maybe because it's listening for the shortcuts of the app, not the ones by Windows

**Comment by RedBlood12** [comment]
This a feature I would love to have, is there any update about it?

**Comment by NovusTheory** [comment]
Fix by me merged in (the issue should've been closed on merge)

**Comment by rickinbsb** [comment]
> Fix by me merged in (the issue should've been closed on merge)

I believe it will auto-close when development merges with master

**Comment by Alipoodle** [comment]
This issue should be fixed now with using the RAW Media Integration from the Electron app now.
