### ISSUE TITLE
Error Opening main Window

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#288]
I just updated to version 1.12 on Windows.
I can't open the main Window double clicking the tray icon, see error.

If I use the right mouse button, choose Miniplayer and then expand it, the main window shows.

![image](https://user-images.githubusercontent.com/5813131/89263973-7782ef80-d632-11ea-8e39-53aa4b75a07e.png)

**Comment by adlerluiz** [comment]
Thanks for reporting, has been fixed, could you please download the [v1.12.0](https://github.com/ytmdesktop/ytmdesktop/releases/v1.12.0) version again
