### ISSUE TITLE
Add option to disable current playing song next to Windows 10 volume slider

### ISSUE THREAD

**Issue by TheDutchMC** [ytmdesktop/ytmdesktop#289]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Currently YTMusic Desktop app shows the currently playing song in the Windows 10 volume slider in the top left of the primary display. I have as of yet found no way to disable this. So I would like this added.

**Describe alternatives you've considered**
I've considered finding a way to rip this feature out of Windows itself, but I thought I'd start with the only app which uses it :)

**Additional context**
A photo of the feature I would like to have a ON/OFF option for [Imgur](https://imgur.com/a/0ExuXXE)

**Comment by adlerluiz** [comment]
Hello, it was a quick implementation because this integration was requested a lot and other bugs were corrected, but this disable option will be inserted and will be available in the next release =)

**Comment by TheDutchMC** [comment]
Damn that is quick indeed! Any ETA on the next release? (If its before September I'm happy, because Google Music is going out then)

**Comment by adlerluiz** [comment]
![image](https://user-images.githubusercontent.com/2112638/89427930-2fd39500-d712-11ea-8780-e0729fe60f7d.png)

Done, the launch is estimated until the 12th

**Comment by TheDutchMC** [comment]
Sweet! Thank you. To the 12th I can wait :D I'd compile myself, but I've got absolutely no idea how to go from a Node.js app to binaries.
