### ISSUE TITLE
When minimized, i get an error when trying to show the app

### ISSUE THREAD

**Issue by dbvasconcelos** [ytmdesktop/ytmdesktop#290]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
When minimized, if i try to show the app using either the shortcut or right clicking the tray icon and selecting the first option, it pops up an error message. It was working fine on the previous version.

**To Reproduce**
1. Start the application minimized or close the window with the background option enabled.
2. Try to show it using the shortcut or tray option.
3. See error

**Expected behavior**
Show the app

**Screenshots**
![ytmdapp-error](https://user-images.githubusercontent.com/1173513/89436139-3109bf80-d71c-11ea-931c-44b4670984ec.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.12.0

***
 * OS: ***Arch Linux***
 * OS version: ***5.7.12-arch1-1***
 * Arch: ***x64***
 * WM: ***dwm***
 * Installation way: ***snapcraft***

**Comment by adlerluiz** [comment]
thanks for reporting, we are working on the fix and it will be available as soon as possible
