### ISSUE TITLE
Play Youtube and Uploaded Music

### ISSUE THREAD

**Issue by pjp94** [ytmdesktop/ytmdesktop#293]
If I go to my library, I can filter the songs by "YouTube Music" and "Uploads". I want to be able to play both collections of songs together like I currently can with Google Play Music. Can an "All" filter be added so I can play all my music instead of just one set or the other?

**Comment by adlerluiz** [comment]
Unfortunately we have no way to do this, as it is something from the youtube server side.

Maybe that helps a little - https://www.androidpolice.com/2020/08/06/youtube-music-now-lets-you-see-which-songs-from-an-artist-youve-added-to-your-library/
