### ISSUE TITLE
remote control

### ISSUE THREAD

**Issue by thib3113** [ytmdesktop/ytmdesktop#296]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
opening the remote controle webpage produce an error . ( reloading page, reproduce the error each time )

**To Reproduce**
1. Go to settings
2. enable remote control
3. click on the link button  ![image](https://user-images.githubusercontent.com/5489218/89651794-bc25b980-d8c4-11ea-9b1b-71990e15cfda.png)
4. see the popup error

**Expected behavior**
more details about the error ?

**Screenshots**
![image](https://user-images.githubusercontent.com/5489218/89651726-a2847200-d8c4-11ea-82e5-ed3e9ecd39d3.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.12.0***
 * OS: ***Windows***
 * OS version: ***19041.388***
 * Arch: ***x64***
* Installation way: ***.exe***

Another question, is it a documentation available for this remote control ? ( I just want to retrieve the current played song title )

**Comment by ZombieAnidata** [comment]
Hello this problem was solved try this version of the application. https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0-beta/YouTube.Music.Desktop.App.Setup.1.12.0.exe

**Comment by ZombieAnidata** [comment]
Original post: https://github.com/ytmdesktop/ytmdesktop/issues/253#issuecomment-666615378

**Comment by thib3113** [comment]
> Hello this problem was solved try this version of the application. https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0-beta/YouTube.Music.Desktop.App.Setup.1.12.0.exe

404 not found for me .

**Comment by ZombieAnidata** [comment]
> > Hello this problem was solved try this version of the application. https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0-beta/YouTube.Music.Desktop.App.Setup.1.12.0.exe
> 
> 404 not found for me .

I don't have the original file right now but i will give you an an copy later.

**Comment by ZombieAnidata** [comment]
> > Hello this problem was solved try this version of the application. https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0-beta/YouTube.Music.Desktop.App.Setup.1.12.0.exe
> 
> 404 not found for me .

I have a beta that worked for me i will give it to you later.

**Comment by adlerluiz** [comment]
https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0/YouTube.Music.Desktop.App.Setup.1.12.0.exe

**Comment by thib3113** [comment]
> v1.12.1 final has fixed it https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.1/YouTube.Music.Desktop.App.Setup.1.12.1.exe

404 not found for me .


Did you have a documentation for this api ? or just a way to retrieve the current song played ?

**Comment by adlerluiz** [comment]
Try again, now live.

I'm creating the documentation for the API

**Comment by thib3113** [comment]
@adlerluiz same error with v1.12.1 ...

**Comment by ZombieAnidata** [comment]
> @adlerluiz same error with v1.12.1 ...

Try this http://localhost:9863/info

**Comment by adlerluiz** [comment]
> > @adlerluiz same error with v1.12.1 ...
> 
> Try this http://localhost:9863/info

please access this link and send the screenshot

**Comment by thib3113** [comment]
I try ... but now I got this when enabling the remote control
![image](https://user-images.githubusercontent.com/5489218/89713223-9cf75c80-d996-11ea-81b5-3d2c5fc0c67a.png)
same if I run it with administrator mode ... I'll retry after a reboot

**Comment by adlerluiz** [comment]
have you checked your firewall?

**Comment by adlerluiz** [comment]
Maybe this can help you - https://medium.com/@myolisi/how-to-fix-error-eacces-permission-denied-8080-in-nodejs-66d6cd5b2ed5

**Comment by thib3113** [comment]
> Maybe this can help you - https://medium.com/@myolisi/how-to-fix-error-eacces-permission-denied-8080-in-nodejs-66d6cd5b2ed5

I can't check for the firewall for the moment, but seems strange, in general if firewall lock the port, the app can listen, but others computer can't talk to this port. I'll check when I'm back .

About the link, I already check, no other other programs listen on this port ...

**Comment by adlerluiz** [comment]
right, I wait

**Comment by thib3113** [comment]
Ok, so finally, it's the firewall ... When I will try to add an exception, I see youtube music desktop is already here ... two times ... removing the two, restarting youtube music desktop, the app ask the firewall rights ... and thats fine ( for this error ) .

So, always the undefined undefined error, and the /info return : 
```js
{
   "app":{
      "version":"1.12.1"
   },
   "server":{
      "name":"PC-TO-TSE",
      "listen":[
         {
            "name":"Hamachi",
            "ip":"25.55.228.68"
         },
         {
            "name":"Ethernet 2",
            "ip":"192.168.9.100"
         },
         {
            "name":"VMware Network Adapter VMnet1",
            "ip":"192.168.252.1"
         },
         {
            "name":"Wi-Fi",
            "ip":"192.168.9.101"
         },
         {
            "name":"Hamachi",
            "ip":"25.55.228.68"
         },
         {
            "name":"Ethernet 2",
            "ip":"192.168.9.100"
         },
         {
            "name":"VMware Network Adapter VMnet1",
            "ip":"192.168.252.1"
         },
         {
            "name":"Wi-Fi",
            "ip":"192.168.9.101"
         }
      ],
      "port":9863,
      "isProtected":true,
      "connections":0
   }
}
```

**Comment by adlerluiz** [comment]
I made some changes, can you test it for me? I'm building and I'll give you the download link

**Comment by adlerluiz** [comment]
https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.2-RC1/YouTube.Music.Desktop.App.Setup.1.12.2-RC1.exe

**Comment by thib3113** [comment]
> https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.2-RC1/YouTube.Music.Desktop.App.Setup.1.12.2-RC1.exe

it's work now . Just  it do a strange visual with multi interfaces ... But I'll open another issue I think :)
