### ISSUE TITLE
Start minimized not working

### ISSUE THREAD

**Issue by Vimerum** [ytmdesktop/ytmdesktop#297]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The option "Start minimized" has no effect. The app opens and doesn't get minimized with the option on or off.

**To Reproduce**
1. Go to 'Settings'
2. Enable 'Start minimized'
3. Close the app, or restart the computer
4. When it opens again, it won't be minimized

**Expected behavior**
It is expected that when opened, after a few seconds, the app gets minimized automatically with the option "Start minimized" active.

**Environment:**
 * YTMDesktop version: ***v1.12.0***
 * OS: ***Windows 10***
 * OS version: ***1909***
 * Arch: ***x64***
* Installation way: ***YouTube.Music.Desktop.App.Setup.1.12.0.exe***

**Comment by adlerluiz** [comment]
you could test with the new versions, because here it works correctly.

**Comment by Vimerum** [comment]
Tested with version 1.12.1 and reinstalling from scratch, still didn't work. But closing the app and deleting the "youtube-music-desktop-app" folder from "C:\Users\[user]\AppData\Roaming" worked.

**Comment by adlerluiz** [comment]
great, if it happens again, please let me know
