### ISSUE TITLE
Lyrics keep scrolling back to top.

### ISSUE THREAD

**Issue by NickV1302** [ytmdesktop/ytmdesktop#298]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
If the lyrics is longer then the window of the lyrics the scroll will keep scrolling up

**To Reproduce**
1. Go to a song that has a long lyrics
2. Click on the lyrics button
3. Scroll down and it will normally in my case scroll up

**Expected behavior**
Just let me scroll down

**Screenshots**
Gif; https://i.imgur.com/Mykwsik.gif

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1***

**Comment by Colin11200** [comment]
not fixed yet for me

**Comment by NickV1302** [comment]
> not fixed yet for me

The fixed updated hasn't deployed yet.

**Comment by adlerluiz** [comment]
fix available on RC3

**Comment by meow81** [comment]
Can I add to this issue?  Lyrics don't auto scroll with the music any longer.  Did something change?  Noticed that at the time of the last update, when the lyrics keep scrolling to top issue surfaced.
