### ISSUE TITLE
Feature request: option to customize and disable certain hot key combinations

### ISSUE THREAD

**Issue by dukeofcool199** [ytmdesktop/ytmdesktop#3]
it would be nice to choose to disable/re-assign certain hotkey combos. for example when i'm using the app and coding in vscode, the ctrl+shift+p to pause/play the music prevents me from using the vscode command pallet

**Comment by adlerluiz** [comment]
Hello @dukeofcool199 , I want to redo this part of the shortcut keys and leave it free for the user to assign the combination you want, just like you said, and I also had this problem with Intellij and VSCode.

**Comment by Quezako** [comment]
Hello, great app!
So could be so great! The ability to thumb down with global hotkey would be great!

**Comment by bars949** [comment]
A very necessary function. It is not comfortable. It is impossible to switch a song in the background with one hand. My opinion is a paramount task, almost all competitors have taken care of this. The rest of the application is my dream :)

**Comment by grantwilk** [comment]
Bumping because the `CTRL + SHIFT + NUMPAD_MINUS` and `CTRL + SHIFT + NUMPAD_PLUS` hotkey conflicts with all JetBrains IDEs code folding functionality. Would love to see this feature implemented!

**Comment by adlerluiz** [comment]
Done, will be available in the next release!
