### ISSUE TITLE
[Bug] App front end stops working after music played for long time

### ISSUE THREAD

**Issue by owenmcgrath** [ytmdesktop/ytmdesktop#30]
When you minimize or maximize the youtube music window after playing music for a while (4hr+), the app will stop displaying the front end, it looks like it gets hung up and stays gray, sometimes if you give it 1-2 minutes it will load, other times its permanently gray and the app must be restarted.

I'll attach screenshots the next time this occurs

**Comment by adlerluiz** [comment]
@owenmcgrath Thank you for contact,

I am investigating this problem.

**Comment by Dikyx** [comment]
Hello,
I've experienced the same problem multiple times.
1- I listen to music for a long time with the app maxed on my left screen
2- I try to interact with the window to skip a song
3- The app grays out (music continues)
4a- The app comes back to normal after waiting a little bit
or
4b- The app stays grayed out and I have to kill the process and start it again

Screenshots : 
https://ibb.co/QQSp54w
https://ibb.co/ySbtjW6

**Comment by adlerluiz** [comment]
@owenmcgrath @Dikyx 
there is a new release available, and @mingjun97  has made some corrections, if it occurs again please let us know

**Comment by rickinbsb** [comment]
Please reopen if the fix doesn't work
