### ISSUE TITLE
remote control webpage, strange visual with multiples interfaces

### ISSUE THREAD

**Issue by thib3113** [ytmdesktop/ytmdesktop#300]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
opening the remote controle webpage produce a strange visual for my multiples interfaces .

**To Reproduce**
1. Go to settings
2. enable remote control
3. click on the link button  ![image](https://user-images.githubusercontent.com/5489218/89651794-bc25b980-d8c4-11ea-9b1b-71990e15cfda.png)
4. see the multiples interfaces

**Expected behavior**
maybe a list ?

**Screenshots**
![image](https://user-images.githubusercontent.com/5489218/89721047-0730f100-d9d9-11ea-9c69-9653104d6a0f.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.12.2-RC1***
 * OS: ***Windows***
 * OS version: ***19041.388***
 * Arch: ***x64***
* Installation way: ***.exe**

**Comment by adlerluiz** [comment]
thank you very much for the report, I made the correction and I will create a new build

**Comment by adlerluiz** [comment]
https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.2-RC2/YouTube.Music.Desktop.App.Setup.1.12.2-RC2.exe

**Comment by thib3113** [comment]
really better . thank you

**Comment by dalbitresb12** [comment]
Hi @adlerluiz, today I had the same problem. I guess this fix hasn't been released yet?

**Comment by adlerluiz** [comment]
hello this fix would go in version 1.12.2, but it will come out in v1.13.0, the windows build is done, I'm just waiting for the linux and mac build to make it available

**Comment by dalbitresb12** [comment]
@adlerluiz Is there going to be a way to select the Network Interface to use?

**Comment by thib3113** [comment]
@dalbitresb12 not sure, but I think the app listen on all interfaces ( 0.0.0.0 ), that's easier ... ( but maybe less secure )

**Comment by dalbitresb12** [comment]
I was asking that just in case it shows the wrong Network Interface (for example, in case it shows Hyper-V Virtual Switch instead of Built-in WiFi).

**Comment by adlerluiz** [comment]
exactly, it hears at 0.0.0.0, but there is an option to enable token to connect (to prevent anyone on LAN from sending commands)

and with the correction of v1.13.0 it will demonstrate all available networks, excluding

(Loopback|lo|virtual|wsl|vEthernet|Default Switch|VMware|Adapter|Hamachi)

**Comment by thib3113** [comment]
> exactly, it hears at 0.0.0.0, but there is an option to[ enable token](https://github.com/ytmdesktop/ytmdesktop/wiki/Remote-Control-API#if-server-is-protected-with-password-you-need-set-header-authorization-bearer-password) to connect (to prevent anyone on LAN from sending commands)
> 
> and with the correction of v1.13.0 it will demonstrate all available networks, excluding
> 
> (Loopback|lo|virtual|wsl|vEthernet|Default Switch|VMware|Adapter|Hamachi)

just hidding this interfaces ? and no "stop to listen with then" ( I think about some strange configurations, where Hamachi can be usefull ) .

**Comment by adlerluiz** [comment]
just not to appear in the listing
