### ISSUE TITLE
Feature request: disable shortcuts setting

### ISSUE THREAD

**Issue by sisisin** [ytmdesktop/ytmdesktop#301]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

Custom Shortcuts is very nice feature!
But I want to disable unused shortcut setting because I don't want to consider not conflicted key setting if I don't need the shortcut.

related #3

**Describe the solution you'd like**

It is enable to disable shortcut in the `Shortcuts` setting

**Comment by jurgenweber** [comment]
beat me to it; https://github.com/ytmdesktop/ytmdesktop/issues/308

**Comment by adlerluiz** [comment]
will be available in the next release

![image](https://user-images.githubusercontent.com/2112638/89958563-81978600-dc10-11ea-95f6-4150c9cccd55.png)
