### ISSUE TITLE
Tray icon double-click exception

### ISSUE THREAD

**Issue by kirichenec** [ytmdesktop/ytmdesktop#302]
Can't open from tray

**To Reproduce**
1. Minimaze window
2. Double-click tray icon
3. See error
![image](https://user-images.githubusercontent.com/7500203/89761491-29209580-daf7-11ea-87b8-0c78d86aefab.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.0***
 * OS: ***Windows 10***
 * OS version: ***2004***
 * Arch: ***x64***
* Installation way: ***like .exe***

**Comment by adlerluiz** [comment]
Hello, v1.12.1 has fixed it - https://github.com/ytmdesktop/ytmdesktop/releases/tag/v1.12.1
