### ISSUE TITLE
Error upon clicking the note or gear icons

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#303]
Latest Windows build.

When I click the note icon in the lower right of the main window, I get

![image](https://user-images.githubusercontent.com/5813131/89786249-ed4bf700-db1b-11ea-98e6-5fc1119601fc.png)

and a black window.

Same with the gear icon for settings:

![image](https://user-images.githubusercontent.com/5813131/89786315-05bc1180-db1c-11ea-9513-e04213be520f.png)

**Comment by mingjun97** [comment]
Do we have this problem right now? :)

**Comment by pdario** [comment]
Not at all! It has been fixed months ago

**Comment by mingjun97** [comment]
Cool! Thanks for your feedback!
