### ISSUE TITLE
missing OSX rls of 1.12.1

### ISSUE THREAD

**Issue by jurgenweber** [ytmdesktop/ytmdesktop#307]
- [ x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x ] I verified that there is no open issue for the same subject.

**Describe the bug**

**To Reproduce**
https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.1/YouTube.Music.Desktop.App-1.12.1.dmg
does not exist; 404.

**Expected behavior**
a download

**Screenshots**

**Environment (please complete the following information):**
on the latest 0sx.
Check releases, nothing there. https://github.com/ytmdesktop/ytmdesktop/releases/tag/v1.12.1

**Comment by jurgenweber** [comment]
orr.... are they all Windows and Linux fixes and so an OSX rls wasn't necessary... rriigghtt.

**Comment by adlerluiz** [comment]
I don't have a mac, I need a friend who does the build for me, but i'm looking to improve it and automate it.

**Comment by haiGodzilla** [comment]
I have the same issue. Can't download the OS X release. Tried to find older releases but they also seem to be unavailable on the server. 
Where can I get an OS X release now?

**Comment by DameO211** [comment]
Happy not to be the only one experiencing this issue.

**Comment by haiGodzilla** [comment]
seems like we are the only three osx user ^^

**Comment by adlerluiz** [comment]
sorry, but my friend who does the build is out of time for now, but as I said I'm running behind to do this build

**Comment by glennschler** [comment]
I just built on my old OS X mac using the NPM instructions in the readme. Up and listening to my music in less than 15 minutes. Thanks for all the work!

**Comment by jurgenweber** [comment]
what do you need to do an OSX build? Happy to help.

**Comment by glennschler** [comment]
To build on OSX, you need Node.js. Perhaps there are some Xcode CLI native libraries, though best to first try the NPM build since it might download all dependencies. This will make a local app for you. I think there is more required to bundle a re-distributable.

Then Clone this repo and follow the few instructions in the readme.
https://github.com/ytmdesktop/ytmdesktop#to-contribute

[Node.js LTS 12.x version](https://nodejs.org/en/download/)
[Apple Developer Tools minimal command line tools](https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_11.5/Command_Line_Tools_for_Xcode_11.5.dmg)

**Comment by jurgenweber** [comment]
yeah, I hvae all of that...

```
 $ node --version
v14.8.0
```

```
$ npm install

> bufferutil@4.0.1 install /Users/jurgen.weber/checkouts/random/ytmdesktop/node_modules/bufferutil
> node-gyp-build


> husky@4.2.5 install /Users/jurgen.weber/checkouts/random/ytmdesktop/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> register-scheme@0.0.2 install /Users/jurgen.weber/checkouts/random/ytmdesktop/node_modules/register-scheme
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/14.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jurgen.weber/checkouts/random/ytmdesktop/node_modules/register-scheme
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.storage.streams@0.2.96 (node_modules/@nodert-win10/windows.storage.streams):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nodert-win10/windows.storage.streams@0.2.96: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.media.playback@0.2.96 (node_modules/@nodert-win10/windows.media.playback):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nodert-win10/windows.media.playback@0.2.96: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.media@0.2.96 (node_modules/@nodert-win10/windows.media):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nodert-win10/windows.media@0.2.96: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @nodert-win10/windows.foundation@0.2.96 (node_modules/@nodert-win10/windows.foundation):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @nodert-win10/windows.foundation@0.2.96: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abstract-socket@2.1.1 (node_modules/abstract-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for abstract-socket@2.1.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! register-scheme@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the register-scheme@0.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jurgen.weber/.npm/_logs/2020-08-14T00_22_36_584Z-debug.log
```

but the CLI tools are instlaled:
```
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by glennschler** [comment]
I do not develop any native OSX or IOS, though I do update my XCode sometimes. I found suggestions to run `softwareupdate --list` based on the error you received from `xcode-select --install`. Do not bother to chase node-gyp errors which are shown in your log.

Since this application is an Electron app, these instructions might help:
https://www.electronjs.org/docs/development/build-instructions-macos

**Comment by son1112** [comment]
Having this issue as well. I have a little time to look into it.

**Comment by son1112** [comment]
> seems like we are the only three osx user ^^

osx_users =+ 1

:)

**Comment by adlerluiz** [comment]
Waiting - https://github.com/Homebrew/homebrew-cask/pull/87601

**Comment by son1112** [comment]
@adlerluiz I jumped the gun and approved, but considering it's just an update to the url, I'm guessing those checks will pass. We shall see...

**Comment by adlerluiz** [comment]
@son1112 done, cask merged into master

**Comment by mingjun97** [comment]
I could build a package for v1.12.1 now. But as far as I test the media key still doesn't work on v1.12.1. Kind of awkward. Maybe skipping these releases until media keys work properly? I'm using spotify recently due to the inconvenience.

**Comment by rickinbsb** [comment]
I don't thing skipping it is a good idea, media keys doesn't work on 1.12.0 too

**Comment by mingjun97** [comment]
Well, I'll build and upload it now.

**Comment by son1112** [comment]
Thanks @adlerluiz . Download is working now. :)

**Comment by adlerluiz** [comment]
Thank you @mingjun97
