### ISSUE TITLE
Toggle Mini-player shortcut is missing in settings

### ISSUE THREAD

**Issue by caboose16** [ytmdesktop/ytmdesktop#310]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The shortcut for toggling miniplayer is missing from settings. It is currently set to Ctrl + m. The user should be able to change this as Ctrl + m works when the miniplayer is active and not in focus. It prevents me from using Ctrl + m in Visual Studio when the miniplayer is toggled.

**To Reproduce**
1. Go to Shortcuts in Settings
2. See that there is no shortcut for miniplayer
3. Press ctrl + m to toggle miniplayer

**Expected behavior**
The shortcut toggle miniplayer should be in shortcuts and be rebindable.

**Environment (please complete the following information):**
 * YTMDesktop version: v1.11.0
 * OS: Windows 10 Pro
 * OS version: 1909
 * Arch: x64
* Installation way: Chocolatey

**Comment by adlerluiz** [comment]
implemented, will be available in the next release.
