### ISSUE TITLE
Unable to create certain shortcuts on MacOS

### ISSUE THREAD

**Issue by giperball** [ytmdesktop/ytmdesktop#313]
- [ ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ ] I verified that there is no open issue for the same subject.

 **Describe the bug**
I unable to create shortcuts like cmd + alt + letter, meta + alt + letter or cmd + meta + letter

 **To Reproduce**
 1. Go to settings and try to record these combinations
 
 **Environment:**
 * YTMDesktop version: ***v1.12.0***
 * OS: ***darwin***
 * OS version: ***10.15.5***
 * Arch: ***x64***
 * Installation way: ***like .exe or snapcraft or another way***

**Comment by eaigner** [comment]
Have the same issue, can't create shortcuts. All that is recognized is `META` and sometimes `SHIFT`, but no letter keys whatsoever.

On a separate note, is there no way to reset the shortcuts to defaults?

**Comment by rjzheng** [comment]
Same here, this is a crucial feature to me, I even tried searching for a config file, but couldn't find any.

**Comment by Alipoodle** [comment]
#751 Adds support for Meta Keys (in development build) which should help with fixing the issue with that.
`CMD + ALT + <Letter>` - I will have to get a mac user to verify if this is still an issue

If possible can you confirm that manually setting it within the `config.json`
I do not know Mac's Directory layout but I'd assume it will be in `~/Library/Application Support` and a YouTube Music folder.
And should be able to manually edit one of the keybinds to be `CmdOrCtrl+Alt+A` for example for `CMD + ALT + A`

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
