### ISSUE TITLE
Notifications on hotkey actions (Like, dislike)

### ISSUE THREAD

**Issue by cotneit** [ytmdesktop/ytmdesktop#314]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
I imagine it would be frustrating to like/dislike a song when trying to do something with the same hotkey in a different application and not know about it.

**Describe the solution you'd like**
I would suggest adding notifications on like, dislike, and any other future shortcuts that have no obvious effect so that user can quickly troubleshoot the problem if hotkey mixup occurs. I would also suggest letting the user turn those on or off individually for each hotkey. 

Aside from the described problem, I think it would be good to have this feature even if conflict never occurs since it gives user more control over his environment.

**Comment by adlerluiz** [comment]
Thanks for the sugestion, I also realized this problem, yesterday I was already implementing and testing.

![image](https://user-images.githubusercontent.com/2112638/90149265-b0217800-dd5a-11ea-9999-b1aa9cea45b7.png)

**Comment by adlerluiz** [comment]
The option to disable the shortcut key has also been implemented and will be available in the next release

![image](https://user-images.githubusercontent.com/2112638/90150446-0e9b2600-dd5c-11ea-8302-1d5335d3aa0f.png)
