### ISSUE TITLE
No possibility to manage YTMDesktop via bluetooth devices

### ISSUE THREAD

**Issue by KPOCT** [ytmdesktop/ytmdesktop#315]
**Environment:**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***linux*** (ubuntu 20.04)
 * OS version: ***5.4.0-42-generic***
 * Arch: ***x64***

**Comment by guaycuru** [comment]
Possible duplicate of https://github.com/ytmdesktop/ytmdesktop/issues/304 ?

**Comment by Alipoodle** [comment]
This issue lacks a lot of information so I'm closing it...
Please re-open a new ticket with more information explaining what you are needing help with / what features you want.
