### ISSUE TITLE
Better application icon

### ISSUE THREAD

**Issue by spozdnyakov** [ytmdesktop/ytmdesktop#319]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
The icon currently used by the application looks a bit ugly (for example, the triangle inside red circle on taskbar icon looks a bit off center). But most importantly, it is not the right icon used by the web version of the official app (or by official Android app). Check mini-icon in browser tab when YouTube Music is open, or just google "YouTube music" and check the output on the right side of the search results :) 

**Describe the solution you'd like**
The link to the correct icon: https://commons.wikimedia.org/wiki/File:YouTubeMusic_Logo.png 
The license is Creative Commons, so I suppose the icon can be reused?

**Describe alternatives you've considered**
None

**Additional context**
Please consider updating the icon to a better looking (and official) one, your app would be just perfect then :)

**Comment by spozdnyakov** [comment]
Checked other icon-related issues - seems to be impossible to use official icon due to copyright issues.

**Comment by rickinbsb** [comment]
there is a feature to add your own custom icon planned, this could be a good solution (#123)
