### ISSUE TITLE
Full Screen not hiding the titlebar

### ISSUE THREAD

**Issue by Innarel** [ytmdesktop/ytmdesktop#320]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

 **Describe the bug**
The titlebar keeps visible when in full screen mode.

 **To Reproduce**
Activate full screen video

 **Expected behavior**
 The video must fill 100% of the screen area

 **Screenshots**
Not needed

 **Environment:**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***win32***
 * OS version: ***10.0.19041***
 * Arch: ***x64***
 * Installation way: ***like .exe or snapcraft or another way***

**Comment by TotalChris** [comment]
I added a fix to the dev branch that fixes it, will most likely be fixed in next release.

**Comment by Alipoodle** [comment]
#392 In Development Build

**Comment by Alipoodle** [comment]
This issue is now fixed with YTMD v2 :)
