### ISSUE TITLE
Unable to update/install

### ISSUE THREAD

**Issue by furquim87** [ytmdesktop/ytmdesktop#321]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
I was using the app on version 1.11.0 or 1.12.0 (I'm really not sure) up until yesterday. Today I tried to update to the new version (the pre-release, 1.12.2-RC3) but I encountered some bugs which made me unable to update, and now even use the older version of the app.

First I got an error message telling me that the installer couldn't run the uninstaller on the AppData/Local/Programs/youtube-music-desktop, I clicked on try again a few times but to no avail, so I decided to click on "Ignore", the error message was gone but the progress bar was still stuck.

I thought that maybe it was because I was trying to install a RC version, and tried the version 1.12.1, but had the same results. Then I tried to uninstall the app via Revo Uninstaller, but couldn't find it on the list. I decided to run the uninstaller myself and tried to get into AppData/Local/Programs/youtube-music-desktop, but was denied access. After trying to Take Ownership of the folder, delete via CMD among other things (I also deleted the other folders of the app because it wasn't even working anymore at this point), I booted on Safe Mode and tried to delete the folder again, but I couldn't find it anymore. I got back to normal mode and tried to install the app again, but it always starts up quickly and then get stuck in the same place over and over again.

I tried installing on Safe Mode, running as administrator, etc, etc, but I couldn't make it work. I even tried installing older versions, but the result is the same.

**Screenshots**
![installer](https://user-images.githubusercontent.com/40681962/90303790-713d1080-de87-11ea-85c0-705bbf62773d.png)
(unfortunately I didn't screenshot the initial issue since I thought it could be solved by me)

**Environment (please complete the following information):**
 * YTMDesktop version: [was] ***1.11.0*** or ***1.12.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by adlerluiz** [comment]
can you try the latest version? [v1.12.1](https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.1/YouTube.Music.Desktop.App.Setup.1.12.1.exe)

**Comment by OlegKoneff** [comment]
@furquim87 i have the same issue. A few days ago I got an error AppData/Local/Programs/youtube-music-desktop and when I tried to reinstall the app caught an endless installation process.
![image](https://user-images.githubusercontent.com/23294856/90308978-e8f15680-deec-11ea-8fe5-5a05038f49b3.png)

**Comment by adlerluiz** [comment]
You can try remove

```AppData/Local/Programs/youtube-music-desktop-app/resources``` - this is where the YTMDesktop files are located.

```AppData/Roaming/youtube-music-desktop-app``` - here are the files needed to run the electron application.

**Comment by furquim87** [comment]
> You can try remove
> 
> ```AppData/Local/Programs/youtube-music-desktop-app/resources``` - this is where the YTMDesktop files are located.
> 
> ```AppData/Roaming/youtube-music-desktop-app``` - here are the files needed to run the electron application.

I did that, and just to confirm I deleted everything related to the app I could find via search. Same result, unfortunately.

**Comment by Alipoodle** [comment]
Does this issue need to stay open?

_Assuming this issue is fixed, and will close if no response is given within a week_

**Comment by Alipoodle** [comment]
No more information has been provided.
More will be investigated when a new update is released soon.
