### ISSUE TITLE
Crash to start page when starting to play song

### ISSUE THREAD

**Issue by franzkuben** [ytmdesktop/ytmdesktop#322]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
Sometimes when I play a song or the next song gets automatically played the application freezes for a short moment and resets to the start/home page. I'd say it happens once in 20min. The bug started to happen when I updated to the 1.12.x versions.

**To Reproduce**
Since it doesn't happen all the time its hard to reproduce. Try to play a few songs.

**Expected behavior**
The song should be played normally.

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***Windows***
 * OS version: ***Version	10.0.18362 Build 18362***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by franzkuben** [comment]
I tried to find something in the logs and I found this line, which appears periodically:
`[2020-08-13 18:36:28.665] [warn] error on createRightContent`

**Comment by DenneyLewis** [comment]
Also having this issue. It's a app deleting issue for me. Will be listening to a shuffle and then suddenly it'll try and play the next song and just stop and crash to the home page. Having to use the online app as it doesn't have this problem.

**Comment by minimar** [comment]
I'm also experiencing this. It's extremely annoying.

**Comment by Alipoodle** [comment]
Anyone still experiencing this issue on 1.13 / 1.14 Builds.
I've not experience this issue within the full month.

"createRightContent" seems to not even be anything to do with us, and this may have been a YouTube Music issue all along.

_No response for this issue will assume that it has been solved and will close._

**Comment by Alipoodle** [comment]
Closing due to no further information being provided.
Please open a new issue if this still occurs.
