### ISSUE TITLE
Changelog always shows on startup

### ISSUE THREAD

**Issue by Bo0sted** [ytmdesktop/ytmdesktop#323]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Every time the app starts up, the Changelog window shows regardless if you've already exited out the window in the past.

**To Reproduce**
1. Have start on boot enabled? (This may or may not affect this issue)
2. Start up app as usual

**Expected behavior**
 - Changelog window appears

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.12.0***
 * OS: ***Windows***
 * OS version: ***2004***
 * Arch: ***x64***
* Installation way: ***regular old binary installation***

**Comment by adlerluiz** [comment]
664a59040863debb8a2394162c17cd641147bcf6
