### ISSUE TITLE
A JavaScript error occurred in the main process - unable to enter preferences

### ISSUE THREAD

**Issue by jurgenweber** [ytmdesktop/ytmdesktop#324]
- [ x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x] I verified that there is no open issue for the same subject.

**Describe the bug**
A JavaScript error is popping up all the time.

**To Reproduce**
Not sure what hte trigger is, maybe it is every new track?

```
Uncaught Exception:
TypeError: Cannot read property 'send' of null
    at WebContents.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/main.js:334:37)
    at WebContents.emit (events.js:228:7)
```

It also seems I am unable to go into the 'cog' or preferences menu.

**Expected behavior**
no error popup

**Screenshots**
![image](https://user-images.githubusercontent.com/3013734/90455955-ce142180-e13a-11ea-9bf6-c3051dba1640.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.12.1***
 * OS: OSX 
 * OS version: 10.15.6
 * Arch: 
```
$ uname -m
x86_64
```
* Installation way: brew using dmg

**Comment by JoshCooley** [comment]
I was getting the exact same error from the brew cask and master branch when a new track started, and also unable to open preferences. On development branch I no longer encounter this error and can open preferences again.

Thanks for the quick fix!

**Comment by jurgenweber** [comment]
I went to master and built it;

I still get the same error and am still unable to use the preferences.

**Comment by jurgenweber** [comment]
ok, my mistake.. I went to 'v1.13.0-RC2' and built it.. much better. Thanks

**Comment by jurgenweber** [comment]
note, the shortcuts page does not seem to work at all.
