### ISSUE TITLE
Taskbar location changes when app opens up

### ISSUE THREAD

**Issue by Hank3** [ytmdesktop/ytmdesktop#326]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
I have moved the YouTube Music app down to my taskbar; when I open up the app, the app opens in the rightmost slot in the taskbar while the icon stays in the same place. Shouldn't the app open where the icon is positioned in the taskbar instead of another window?

**To Reproduce**
1. Move YTMDesktop to taskbar
2. Open YTMDesktop and it will open another window on the right

**Expected behavior**
I expect YTMDesktop to open in the same location on the taskbar.

**Screenshots**

![image](https://user-images.githubusercontent.com/24571086/90558731-8a391080-e16a-11ea-9d7e-a1c2234c8709.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1***
 * OS: Windows 
 * OS version: 10
 * Arch: 64-bit
* Installation way: .exe

**Comment by Hank3** [comment]
> I believe this is an issue to do with the Electron Shortcut VS the Electron Application. Pinning the application once it has opened will fix this issue.
> 
> However looking at some electron stuff if the following is added to the code:
> 
> ```js
> app.setAppUserModelId('<name-of-your-app-goes-here>');
> ```
> 
> It maybe possible to fix this issue. So I'll leave this issue open for now, and will investigate this more in the future

This fixed the issue...thank you!

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
