### ISSUE TITLE
Error on changing next track button combo

### ISSUE THREAD

**Issue by Sarquamon** [ytmdesktop/ytmdesktop#327]
- [x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x] I verified that there is no open issue for the same subject.

**Describe the bug**
Hello, the bug I found was not listed in the bug reports so what I found may be new.

When changing the shortcuts on version 1.12.1 to something else other than CTRL + SHIFT + PageUp throws an error:

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from MediaTrackNext at IpcMainlmpl.<anonymous>
(C:\Users\{yourUser}\AppData\Local\Programs\youtube-music-desktop-app\resources\app...:32)
at IpcMainImpl.emit(events.js223:5)
at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
at WebContents.emit(events.js:223:5)
```

**To Reproduce**
1. Go to the config cog
2. Click on 'Shortcuts'
3. Click on 'Change the next track button combo to your keyboard combo preference' (my case fn + f6 )
4. Click 'Save'
5. See error

**Expected behavior**

I thought I was gonna be able to change my button combo layout

**Screenshots**

[Screenshots](https://imgur.com/a/Vi467mY)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***Windows***
 * OS version: ***2004 (OS build 19041.450)***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by adlerluiz** [comment]
this problem happens because the ```MediaNextTrack, MediaPreviousTrack, MediaStop and MediaPlayPause``` keys are already registered by default and you are trying to register again, but it has already been fixed in RC4 and will be available in the next release

![image](https://user-images.githubusercontent.com/2112638/90645276-2535f700-e20c-11ea-9104-41e11f773934.png)
