### ISSUE TITLE
Feature Request: Mini Player

### ISSUE THREAD

**Issue by rb28z2** [ytmdesktop/ytmdesktop#33]
A mini version of the player (with something like just album art and media controls) that can be kept always on top would be amazing.

**Comment by adlerluiz** [comment]
Hello @rb28z2 the mini player already in the roadmap, today I developed a missing part, and now can be created, @rickinbsb will develop the it.

**Comment by rickinbsb** [comment]
I'll start working on it later this week

**Comment by nathan-fiscaletti** [comment]
How's it looking? Literally this is the only thing stopping me from downloading this right now. I use youtube with Chromes' built in PiP, so having a mini player is a must for me to switch to a desktop application.

**Comment by rickinbsb** [comment]
Will be released in the next version

![feef6ad1-b4c1-4c13-8f2e-26e3c6efa37e](https://user-images.githubusercontent.com/4140033/71599892-8305b980-2b2b-11ea-9c90-d0bf18fc0453.jpeg)
