### ISSUE TITLE
Accessibility issues with vol up/down shortcuts in v1.12.1

### ISSUE THREAD

**Issue by uptownbrent** [ytmdesktop/ytmdesktop#330]
- [ x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x ] I verified that there is no open issue for the same subject.

**Describe the bug**
Using CMD+Shift+arrow left/right is the default shortcut used to select text via the keyboard while in any application. The default shortcuts for vol+ and vol- in YTMDesktop interfere with this default behavior which could be an accessibility issue for user who do not use a mouse. I suggest having these shortcuts set to a different key combo that does not interfere with basic default keyboard behavior. Having the vol+/- shortcuts disabled by default or giving the option to disable them with a toggle would be nice.

**To Reproduce**
While using version 1.12.1, attempt to use the CMD+Shift+arrow left/right to select text while YTMDesktop is playing.

**Expected behavior**
I would expect that text would be highlighted, not for the volume of my music player to go up/down.

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.12.1***
 * OS: ***Mac***
 * OS version: ***10.15.6***
 * Arch: ***x86***
* Installation way: DMG

**Comment by adlerluiz** [comment]
thanks for reporting, we are already working on it and it will be available in the next release
