### ISSUE TITLE
Feature Request: Skip songs marked with thumb down

### ISSUE THREAD

**Issue by a-r-m-i-n** [ytmdesktop/ytmdesktop#334]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Songs I don't like (e.g. interview parts in a radio shows) are still playing, even I don't like them.

**Describe the solution you'd like**
It would be cool, if there would be an option I can enable, to skip songs during playback, marked with thumb down (👎).

**Describe alternatives you've considered**
Those unwanted "interview parts" are mostly <35s. A second option to skip all songs during playing, shorter than n seconds.

**Additional context**
An alternative player https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL- got this feature.

**Comment by andrewjmetzger** [comment]
@adlerluiz  Thank you for the commit! However, this feature is not currently present in any released build. Could you please update the builds on the Releases page?

Alternatively: What is the timeline for release?

**Comment by adlerluiz** [comment]
sorry, i just forgot to update the build i will create 1.13.0-RC2.

The new version was supposed to be released yesterday, but I found a problem in linux and I am seeing a workaround

**Comment by andrewjmetzger** [comment]
No worries, thank you very much! I'm glad to see a published release is on the way, although I'd be happy to test the development branch if needed. :)

**Comment by adlerluiz** [comment]
Done, [1.13.0-RC2](https://github.com/ytmdesktop/ytmdesktop/releases/tag/v1.13.0-RC2) if you can test it would be great.

**Comment by andrewjmetzger** [comment]
Thanks for the quick publication. Testing now. 

Some notes from the setup process:
* My account couldn't sign in with v1.13.0-RC2 (00aebea) because the browser was "insecure"; I had to temporarily checkout master, sign in, and checkout the tag again. 
* The version number in Settings > About is still `v1.12.1`, not `v1.13.0-RC2`. Is this intentional?

**Comment by adlerluiz** [comment]
I will check this login problem, thanks

You generated local, it takes the version of package.json, and it is 1.12.1

**Comment by adlerluiz** [comment]
I rebuilded and I hope it works now - https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.13.0-RC2/YouTube.Music.Desktop.App.Setup.1.13.0-RC2.exe

**Comment by andrewjmetzger** [comment]
Thanks. I'll pull from git. If I can help test anything for Linux (AppImage etc.), let me know. :)

**Comment by andrewjmetzger** [comment]
Success! Development branch commit b0e6a5d fixed the login problem. Skipping disliked tracks works exactly as expected, too. Thanks for your help with a quick resolution on this issue!

**Comment by adlerluiz** [comment]
> Thanks. I'll pull from git. If I can help test anything for Linux (AppImage etc.), let me know. :)

the problem with linux is with node and electron-store package, it uses fs.watch to monitor config file, but he only warns me the first time... I am trying a workaround, but if you are going to test and find a problem, just let me know

**Comment by adlerluiz** [comment]
@andrewjmetzger can you please test and generate a new version from master?

**Comment by andrewjmetzger** [comment]
Pulled master (e4c5e308e345765fb7e42d149bb4abf39f7ae4bd). After using if for the weekend, it seems fine. Is there anything specific you'd like tested?

**Comment by a-r-m-i-n** [comment]
Thanks for releasing this feature that quick!
Is there the possibility existing, to skip the song before it starts playing? Currently when a playlist got e.g. 5 songs in a row with < 50s each song starts playing and get interupted after <1s. 

Basically it works, but of course it would be nice if this "gap" wouldn't appear.

**Comment by adlerluiz** [comment]
I understand, I will try to improve it because there is a time for the app to find out which song and have the information, usually around 500ms
