### ISSUE TITLE
 Integration with Last.fm

### ISSUE THREAD

**Issue by jos3s** [ytmdesktop/ytmdesktop#34]
Click to get music scrobble directly from app to last.fm

**Comment by adlerluiz** [comment]
@jos3s last.fm integration is now done, will be available in the next release

**Comment by restinginlove** [comment]
I know this was closed, I was just wondering if next update, it can scrobble album and album artist too? I've noticed it just scrobbles with just artist and track.

**Comment by petrov85** [comment]
I am also experiencing this bug.
