### ISSUE TITLE
Disable `nodeIntegration` for remote content

### ISSUE THREAD

**Issue by MarshallOfSound** [ytmdesktop/ytmdesktop#341]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
As per the [Electron Security Guidelines](https://www.electronjs.org/docs/tutorial/security) `nodeIntegration` should be disabled for remote content.

Refs: https://github.com/ytmdesktop/ytmdesktop/blob/master/main.js#L223

Ideally `nodeIntegration` would be disabled on **all** windows for enhanced security

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***macOS***
 * OS version: ***10.15***
 * Arch: ***x64***
* Installation way: Any

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
