### ISSUE TITLE
Enable contextIsolation for all renderers

### ISSUE THREAD

**Issue by MarshallOfSound** [ytmdesktop/ytmdesktop#342]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
As per the [Electron Security Guidelines](https://www.electronjs.org/docs/tutorial/security) `contextIsolation` should be enabled for all renderers.  This means every `BrowserWindow` and `BrowserView`.

Refs: https://github.com/ytmdesktop/ytmdesktop/blob/master/main.js#L223

The technically correct way of doing this is by exposing a minimal API surface area through the `contextBridge` module from Electron --> https://electronjs.org/docs/api/context-bridge

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***macOS***
 * OS version: ***10.15***
 * Arch: ***x64***
* Installation way: Any

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
