### ISSUE TITLE
Lyrics autoscroll to top of page

### ISSUE THREAD

**Issue by Nicholas428** [ytmdesktop/ytmdesktop#345]
- [ X ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ X ] I verified that there is no open issue for the same subject.

**Describe the bug**
When using the Lyrics Window while listening to a song, it'll scroll to the top of the page inside of that window when trying to scroll down.

**To Reproduce**
1. Listen/Play a Song
2. Click on the Lyrics button on footer
3. Bug will be found when scrolling down the lyrics page

**Expected behavior**
I should be able to scroll through the window without it autoscrolling to the top of the page.
**Screenshots**
![GIF File](https://user-images.githubusercontent.com/46852538/91387595-9fb1d880-e803-11ea-89db-b6452e52d700.gif)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x86***
* Installation way: ***.exe Installer***

**Comment by adlerluiz** [comment]
hello, it has already been fixed and will be available soon in the new release

**Comment by Nicholas428** [comment]
I'll close the issue when that release is made public, thank you.

**Comment by edwin-snowplow** [comment]
Hey @adlerluiz I have just downloaded 1.12.1 and this is still an issue.

Do we have visibility to the version roadmap?

**Comment by adlerluiz** [comment]
@edwin-snowplow in version 1.13 it is already corrected, but the MAC version has not yet been generated, do you use MAC?

**Comment by Nicholas428** [comment]
I can confirm that it is fixed on the latest Release for Windows, but I do _not_ use MacOS.

**Comment by edwin-snowplow** [comment]
HI @adlerluiz ,

Thank you. It took a bit to get the update triggered, but its now all dandy and sparky. Great job.

@Nicholas428 please dispose, thanks!
