### ISSUE TITLE
Error when autoplaying next track for the first time

### ISSUE THREAD

**Issue by MaxMatti** [ytmdesktop/ytmdesktop#347]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
A popup box (see screenshot below) appears whenever YTMDesktop plays a track until the end for the first time:

**To Reproduce**
1. Start ytmdesktop
2. Click play on any playlist
3. Wait for first song to finish
4. As ytmdesktop starts to play the second track, this popup appears

**Expected behavior**
ytmusic starts to play the second track without displaying any annoying popups

**Screenshots**
![image](https://user-images.githubusercontent.com/1584478/91454626-7f286380-e881-11ea-8339-9cd7b45cd3bf.png)

**Environment (please complete the following information):**
 * YTMDesktop version: 1.12.1 (from AUR)
 * OS: Linux (Archlinux)
 * OS version: rolling release
 * Arch: 64 bit
* Installation way: AUR

**Comment by adlerluiz** [comment]
thanks for reporting, i will check and fix this error

**Comment by atcq** [comment]
This seems like the same issue as in #367

**Comment by Alipoodle** [comment]
#367 has been the main ticket for discussion of this bug and is fixed in Development build of YTM But not a public release.
Please use that ticket for information regarding this issue.
