### ISSUE TITLE
Disable webviewTag, use content injection or BrowserView instead

### ISSUE THREAD

**Issue by MarshallOfSound** [ytmdesktop/ytmdesktop#348]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
As per the [Electron Security Guidelines](https://www.electronjs.org/docs/tutorial/security) `webviewTag` isn't super ideal and should probably be disabled.  You can't use it and `conextIsolation` in the same renderer securely for instance.  We should use content injection (injecting window controls into a target renderer) or some other strategy like using a `BrowserView` for layered content.

Refs: https://github.com/ytmdesktop/ytmdesktop/blob/master/main.js#L223

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***macOS***
 * OS version: ***10.15***
 * Arch: ***x64***
* Installation way: Any

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
