### ISSUE TITLE
Feature Requests - Multiple :)

### ISSUE THREAD

**Issue by mortyobnoxious** [ytmdesktop/ytmdesktop#36]
Hi, thank you for this app. 

I've a few suggestions:

1. **Gestures** to use by holding down right mouse button as in below:
swipe left - go left
swipe rigt - go right
swipe down - minimize window
swipe up - maximize window
(if gesture thing is somewhat difficult, a right-click **context menu** with the options above would be great.)

2. Scrolling anywhere on the player-bar at the bottom to change volume
![image](https://user-images.githubusercontent.com/42044258/61976455-7e752c00-aff4-11e9-8578-bb8e77a077a1.png)

3. Being able add **CSS** to change layout of YT Music(not app).

4. Lyrics window should remember its' position and size. (now it's centered)

Thank you again for this.

**Comment by adlerluiz** [comment]
@mortyobnoxious Thenk you for using YTMDesktop =D

All your suggestions are already being analyzed, the 4 will be implemented, the 3 soon.

**Comment by adlerluiz** [comment]
Hello, 3 and 4 is now on development branch, and will be available in upcoming releases.

**Comment by andrescirulo** [comment]
Number 2 would be really useful
