### ISSUE TITLE
Open links of youtube music directly in app

### ISSUE THREAD

**Issue by huehnerlady** [ytmdesktop/ytmdesktop#364]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the solution you'd like**
I would like to be able to open youtube links in the app. So if I get a link send from a friend and the app is installed it would be great if that app would be opening by itself instead of the default browser.
Unfortunately I haven't found anything about this so far

**Additional context**
I have MAC OSX 10.15.5 and The app is at version 1.9.0

**Comment by adlerluiz** [comment]
We have this option, you need activate on settings, integrations tab

![image](https://user-images.githubusercontent.com/2112638/92250965-857e9700-eea2-11ea-8629-9dc07ebb3e74.png)
