### ISSUE TITLE
JavaScript Errors: electron-native-notification, js2c

### ISSUE THREAD

**Issue by andrewjmetzger** [ytmdesktop/ytmdesktop#367]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The native notification package generates odd JavaScript errors. Notifications do not work. Errors do not interrupt playback in any noticeable way, but should not appear regardless.

**To Reproduce**
1. Play any songs for a few minutes.
1. Errors appear seemingly at random

**Expected behavior**
System-level notifications should appear when a song changes, when a song is liked/disliked, or skipped. 

**Screenshots**
![image](https://user-images.githubusercontent.com/590246/92431357-50ee3200-f165-11ea-802c-3e9864bc6697.png)
![image](https://user-images.githubusercontent.com/590246/92431410-75e2a500-f165-11ea-9c25-c0be3fdcbc7f.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0*** (master e4c5e30)
 * OS: ***Linux***
 * OS version: ***Pop!_OS 20.04 LTS***
 * Arch: ***x64***
* Installation way: ***git***

I can provide logs if needed, just let me know where to find them.

**Comment by adlerluiz** [comment]
I'm checking here and it seems that electron-native-notifications is not compatible with the new electron serialization and the last update of this library is from 2017, I will have to look for another library for notification

**Comment by andrewjmetzger** [comment]
That doesn't sound good. Any promising alternatives?

**Comment by atcq** [comment]
unfortunately i have no experience with elctron or js in general, but i found https://www.electronjs.org/docs/api/notification#notification and it seems like there is a notification api directly implemented in electron that is supposed to use the native notification system of either Mac/Win and Linux. Maybe that helps?
Notifications are the feature i wanted out of ytmdesktop (the most :) ) and it's a bummer it's not working on linux right now.
Anyways, ytmdesktop is a beautiful app and thx for creating it <3

**Comment by atcq** [comment]
Ok, it seems quite easy, got it working again, have some strange behaviour that might not be strange but intended? i've got more time tomorrow might have a talk in Discord to see if we can iron out why every notification has an extra `(A)` at the start of the `title` that doesn't even seem to be part of the title string (title should be bold with my dunst config).
Might be something with my system, not sure o_O though i don't get that artifact when sending other notifications!

![ytmdesktop_notify](https://user-images.githubusercontent.com/925270/92999815-4bf1ff80-f524-11ea-921d-e587f72f3c1e.png)

**Comment by adlerluiz** [comment]
thanks for PR @atcq before this api was experimental and for that reason it was not implemented, I hope that now it works correctly

**Comment by aedalzotto** [comment]
PR #383 fixed the issue for me, but the notifications don't appear when app is closed to tray nor does any error appears even in the process output

**Comment by andrewjmetzger** [comment]
Glad to hear it @aedalzotto, sounds like this is a step in the right direction.

Unfortunately, even after pulling development again (I'm on 05cc9ea) , I still don't have notifications, even with the app running maximized in the background. Song information does appear in the process output, abut that is normal for  me, and happened well before this update. One new output is hue/sat info below each song--presumably for notification colors like on recent versions of Android--but I cannot verify this, as I see no notifications.

There are persistent media controls (with previous/play-pause/next, but no cover art) at the top of my notification area, although those have existed since well before this update.

**Comment by Alipoodle** [comment]
Re-opening this issue as the Master/Original ticket for this Linux Issue.
This issue is Fixed in Development build, but not in a public build, so will leave this open until a PR is made to a Public build!

**Comment by IgnisDa** [comment]
I get this error the first time when the song changes after I start up ytmd. It pops up only once.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/60938164/210136150-d39d1c97-2b52-4b42-a4d9-aff175a19a1f.png">


I should also mention that I do not get any notifications at all. I am uisng i3 WM.

**Comment by Alipoodle** [comment]
> This issue is Fixed in Development build, but not in a public build, so will leave this open until a PR is made to a Public build!

Can I confirm which version of YTMD you are running on?
Presuming it's the release 1.13, the message above applies. And pre-release 1.14.1/1.14.2 should have this issue fixed

**Comment by IgnisDa** [comment]
> > This issue is Fixed in Development build, but not in a public build, so will leave this open until a PR is made to a Public build!
> 
> Can I confirm which version of YTMD you are running on? Presuming it's the release 1.13, the message above applies. And pre-release 1.14.1/1.14.2 should have this issue fixed

It is 1.13. I am using https://aur.archlinux.org/packages/ytmdesktop-bin package.

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
