### ISSUE TITLE
Unable to open Yt music app

### ISSUE THREAD

**Issue by AnkitArora99** [ytmdesktop/ytmdesktop#369]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Yt music shows black screen when opened i also tried reinstalling it and even installed 1.12.1 version but it doesnt start. It just shows black screen and after some time it stops responding

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/70193077/92587164-e815cf80-f2b4-11ea-8b39-14b606aa8239.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Windows*** 
 * OS version: **19041.450****
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by adlerluiz** [comment]
did you try to uninstall and install again?

**Comment by AnkitArora99** [comment]
> did you try to uninstall and install again?

yes multiple times

**Comment by adlerluiz** [comment]
please, remove all from C:\Users\{your-username}\AppData\Local\Programs\youtube-music-desktop-app and reinstall

**Comment by AnkitArora99** [comment]
> please, remove all from C:\Users{your-username}\AppData\Local\Programs\youtube-music-desktop-app and reinstall

Already tried it but i found the solution changing compatibility mode to window 8 fixes the issue. Thanks for the help
