### ISSUE TITLE
Missing .dmg download for version 1.13.0

### ISSUE THREAD

**Issue by suschizu** [ytmdesktop/ytmdesktop#370]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The Mac download is missing for this version - on purpose? 

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 * YTMDesktop version: ***vx.x.x***
 * OS: ***Windows*** or ***Linux*** or ***Mac***
 * OS version: ***X***
 * Arch: ***x64*** or ***x86***
* Installation way: ***like .exe or snapcraft or another way***

**Comment by adlerluiz** [comment]
I don't have a mac to build, I need someone to do it for me

**Comment by suschizu** [comment]
thanks for the information!

**Comment by ryanpcmcquen** [comment]
You can use GitHub Actions to build it.

**Comment by ryanpcmcquen** [comment]
@adlerluiz, where are the build instructions, I can do it.

**Comment by ryanpcmcquen** [comment]
I built it locally: https://github.com/ytmdesktop/ytmdesktop/issues/409
