### ISSUE TITLE
On mouse over of library status icon, please change popup from "Add to library" to "Remove from library"

### ISSUE THREAD

**Issue by anthonyhersh** [ytmdesktop/ytmdesktop#372]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
When a track is already in your library, the "+" icon is replaced by a checkmark icon. When that state is true, on mouse over, it should popup with "Remove from library," but instead says "Add to library" just like if the track wasn't already in the library.

**To Reproduce**
1. Go to 'Main Window'
2. Mouse over "<is in library?>" check mark icon
3. See popup

**Expected behavior**
Popup text should be "Remove from library"

**Screenshots**

I tried, but keyboard presses remove the mouse over popup.

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***.exe**

**Comment by anthonyhersh** [comment]
I don't know JS, but I love this app!  Thank you.

I tried digging around /src/providers/mediaProvider.js but I don't know JS enough to debug. I'm barely starting with python.

Thanks for your time!

**Comment by adlerluiz** [comment]
thanks, fixed, will be available in the next release
