### ISSUE TITLE
Media buttons in the keyboard are not working as expected (play/pause)

### ISSUE THREAD

**Issue by marcosalcazar** [ytmdesktop/ytmdesktop#376]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Media keys are not working for ytmdesktop

**To Reproduce**
1. Open the app
2. Hit the "play/pause" button in the keyboard
3. ERROR: Music doesn't start
4. Play music (clicking in the play icon in the app)
5. Music starts
6. Hit the "play/pause" button in the keyboard
7. ERROR: Music doesn't pause.

**Expected behavior**
When having the app opened, I should be able to use the media keys in my keyboard to control the music playback (play, pause)

**Screenshots**
No screenshots.

**Environment (please complete the following information):**
 * YTMDesktop version: 1.13.0
 * OS: Linux
 * OS version: Kubuntu 20.04
 * Arch: x64
* Installation way: snapcraft

**Comment by tkoopa** [comment]
Same Issue with
    YTMDesktop version: 1.13.0
    OS: Linux
    OS version: Ubuntu 16.04
    Arch: x64
    Installation way: snapcraft

**Comment by Fwank49** [comment]
I have a similar Issue (media keys for play/pause and forward/back don't work, but custom hotkeys work for those actions) with the following platform:

YTMDesktop version: 1.13.0
OS: Windows
OS version: Windows 10 2004
Arch: x64
Installation way: .exe binary installer

**Comment by aristov** [comment]
Same issue with

- YTMDesktop version: 1.12.1
- OS: Mac OS
- OS version: Catalina 10.15.6
- Arch: x64
- Installation way: .dmg binary installer

**Comment by brianredbeard** [comment]
I was experiencing this... turns out it was Google Chome.  In Chome version 73 direct support for hardware media keys was added.

After disabling "Hardware Media Key Handling" and relaunching Chome everything worked great in ytmdesktop.

[chrome://flags/#hardware-media-key-handling](chrome://flags/#hardware-media-key-handling)

![image](https://user-images.githubusercontent.com/57542/93733884-eb9a3800-fb8b-11ea-9805-9f4377240653.png)

**Comment by Fwank49** [comment]
> I was experiencing this... turns out it was Google Chrome. In Chrome version 73 direct support for hardware media keys was added.
> 
> After disabling "Hardware Media Key Handling" and relaunching Chrome everything worked great in ytmdesktop.
> 
> chrome://flags/#hardware-media-key-handling
> 
> ![image](https://user-images.githubusercontent.com/57542/93733884-eb9a3800-fb8b-11ea-9805-9f4377240653.png)

This does work, (I also had to remove the extension streamkeys from chrome) but other apps (eg GPMDP) have no problem using media keys without having to turn this off in chrome.

**Comment by tkoopa** [comment]
> I was experiencing this... turns out it was Google Chrome. In Chrome version 73 direct support for hardware media keys was added.
> 
> After disabling "Hardware Media Key Handling" and relaunching Chrome everything worked great in ytmdesktop.
> 
> chrome://flags/#hardware-media-key-handling
> 
> ![image](https://user-images.githubusercontent.com/57542/93733884-eb9a3800-fb8b-11ea-9805-9f4377240653.png)

This only partially works for me, I can now use assigned shortcuts again but actual media keys still don't respond

**Comment by aristov** [comment]
> I was experiencing this... turns out it was Google Chrome. In Chrome version 73 direct support for hardware media keys was added.
> 
> After disabling "Hardware Media Key Handling" and relaunching Chrome everything worked great in ytmdesktop.
> 
> chrome://flags/#hardware-media-key-handling
> 
> ![image](https://user-images.githubusercontent.com/57542/93733884-eb9a3800-fb8b-11ea-9805-9f4377240653.png)

Doesn't work for me.

**Comment by psbrowand** [comment]
Same issue here. I had to disable Hardware Media Key Handling in Chrome as stated above. I also had to remove the Google Music Extension.

**Comment by seckela** [comment]
Same issue. Touch Bar Media Controls on my macbook pro.

- YTMDesktop version: 1.12.1
- OS: Mac OS
- OS version: Catalina 10.15.6
- Arch: x64
- Installation way: .dmg binary installer

**Comment by fronders** [comment]
I had the same issue until I removed Google Play App from Chrome and restarted Chrome - now it works without disabling Hardware Media Key Handling

**Comment by TheDutchMC** [comment]
Confirmed for me as well. No G Play App installed on Chrome. Tried with HW Media Key Handling disabled and enabled.

- YTMDesktop Version: 1.13.0
- OS: Windows
- OS Version: Windows 10; 10.0.18363 build 18363; (1909)
- Arch: x64
- Installation: .exe installer, updated through app's build-in updater

**Comment by Nassoo** [comment]
Same issue. 

I've disabled Chrome's Hardware Media Key, but the media keys still don't work (and they work everywhere else except in this app).

YTMDesktop version: 1.13.0
OS: Mac OS
OS version: Mojave 10.14.6
Arch: x64
Installation way: .dmg binary installer

**Comment by Erj4** [comment]
As a summary for those having issues now and in the future, these were the changes I needed to make:

- Ensure that the hardware media key handling is disabled as mentioned by @brianredbeard  (https://github.com/ytmdesktop/ytmdesktop/issues/376#issuecomment-695899061)
- Disable any chrome extensions that consume the media keys (eg Streamkeys)
- Make sure "Enable Windows 10 media service" is on in ytmdesktop settings - Integrations

**Comment by remorsecodex** [comment]
> As a summary for those having issues now and in the future, these were the changes I needed to make:
> 
> * Ensure that the hardware media key handling is disabled as mentioned by @brianredbeard  ([#376 (comment)](https://github.com/ytmdesktop/ytmdesktop/issues/376#issuecomment-695899061))
> * Disable any chrome extensions that consume the media keys (eg Streamkeys)
> * Make sure "Enable Windows 10 media service" is on in ytmdesktop settings - Integrations

Just chirping in to say, doing all of these solved the issue for me right away.

**Comment by iamhenry** [comment]
Tried the steps mentioned here but still doesn't work.

Same issue with

YTMDesktop version: 1.13.0
OS: Mac OS
OS version: Catalina 10.15.7
Arch: x64
Installation way: .dmg binary installer

**Comment by remorsecodex** [comment]
Seems the fix above only works for Windows users.

**Comment by tkoopa** [comment]
Yes, it doesn't work on Linux either

**Comment by gdold** [comment]
I had the same issue under Windows 10, app v1.13.0, the play/pause media keys worked for other software but not in YTMD.

I got it working by enabling **both** _Enable Windows 10 media service_ **and** _Show track information next to the Windows 10 volume bar_, and now play/pause works as expected.

I'm guessing this isn't particularly helpful for our Linux/Mac comrades! 😐

**Comment by chadxz** [comment]
Same issue with

YTMDesktop version: 1.13.0
OS: Mac OS
OS version: Big Sur 11.0.1
Arch: x64
Installation way: homebrew

When I press my play/pause key on my keyboard, Apple Music pops up instead. I tried disabling the "hardware media key handling" in Chrome as mentioned above but it did not make a difference.

**Comment by janacm** [comment]
After trying all the solutions, none of which works on Mac, I found a working alternative here - https://ytmusic.app/

**Comment by BongoEADGC6** [comment]
Still having the lack of media key issue with Kubuntu 20.04 with YTMDesktop 1.13

Any plans to release the newer version with the Electron update?

**Comment by victor-roswell** [comment]
@chadxz worked perfectly thanks! 

@BongoEADGC6 What version of MacOs are you running?

**Comment by BongoEADGC6** [comment]
@victor-roswell I am not using Mac. I am using Kubuntu Linux (Ubuntu with KDE)

**Comment by AndrazP** [comment]
Solution that worked for me on macOS Montery 12.2.1:
Enable Accessibility for the app in system settings:
<img width="671" alt="Screenshot 2022-02-26 at 09 45 11" src="https://user-images.githubusercontent.com/1963904/155836742-5ed63c59-2108-4446-ab11-bc5cac2d2ead.png">

**Comment by MaxMatti** [comment]
Same issue with:

* YTMDesktop version: 1.13.0
* OS: Linux
* OS version: Ubuntu 20.04 with KDE
* Arch: x64
* Installation way: snapcraft

Also there is no "Windows 10 media controls" settings under integrations (or anywhere) so I am not able to use that fix (which makes it work fine on my Archlinux-machines with KDE, it also integrates nicely into kdeconnect and KDEs media controls)
![Screenshot_20220926_105000](https://user-images.githubusercontent.com/1584478/192241971-69f3e4c3-1370-439b-aee6-bb7c1308f276.png)

**Comment by hazzery** [comment]
I believe I am having a similar issue

    YTMDesktop version: 1.13.0
    OS: Linux
    OS version: Ubuntu 22.04.2 LTS
    Arch: x64
    Installation way: snap store

However when I press <kbd>play</kbd>/<kbd>forward</kbd>/<kbd>backward</kbd> I get the following on my screen.
![image](https://user-images.githubusercontent.com/66008198/235296339-3b01e203-456d-40b0-ac1c-6c80e3db65de.png)

Using the other keyboard shortcuts (e.g.<kbd>ctrl</kbd><kbd>shift</kbd><kbd>space</kbd> to pause) works fine however.

**Comment by hazzery** [comment]
This error still occurs on YTMD v2.0.0 on Ubuntu

**Comment by igorsantos07** [comment]
If you're having this issue and end up here, #1363 may be the new issue (although it seems macOS-focused).
