### ISSUE TITLE
Streamline application window on macOS

### ISSUE THREAD

**Issue by domoritz** [ytmdesktop/ytmdesktop#387]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

I would like it if the window put the different categories in line with the window icons. This suggestion is inspired by the design of https://ytmusic.app/. 

**Describe the solution you'd like**

Now:
<img width="1033" alt="Screen Shot 2020-09-15 at 07 42 09" src="https://user-images.githubusercontent.com/589034/93225833-85468d00-f727-11ea-83c6-7d36195cfb53.png">

Proposed:
<img width="979" alt="Screen Shot 2020-09-15 at 07 42 08" src="https://user-images.githubusercontent.com/589034/93225844-87a8e700-f727-11ea-8df0-997503689631.png">

Screenshot taken with https://ytmusic.app/ (https://github.com/steve228uk/YouTube-Music). 

* The logo isn't needed anymore
* The back and forward icons also look nicer in the proposed screenshot

**Comment by Alipoodle** [comment]
This is something which was considered for YTMD v2 however we decided we want as little things to interact with the YTM View as possible and we are not injecting things which are unnecessary.
