### ISSUE TITLE
Wrong way to sign in to google

### ISSUE THREAD

**Issue by MarkoShiva** [ytmdesktop/ytmdesktop#388]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**

Application tying to login to the google account as the different computer which is stange and annoying as we cannot be sure that thee is no poxifaying sevice installed. 

Every app signing from a device should ask for a granular permissions and access only to things it need. 
In case of you tube to which I have connected quite a few apps it do need only access to the youtube full to the email identity and that is all that is needed for the app to work. 
however app is asking access to whole account and as well  represent self as Windows NT which mean it try to still the data for whichever reason. 

**To Reproduce**
1. Start app 
2. Click on sign in 
3. check your phone and your account for amount of signed in devices and access level. There will be another one beside owned.

**Expected behavior**

Oauth only the needed perms like access to the youtube and to the email of the account. 
**Screenshots**

**Environment (please complete the following information):**
 * YTMDesktop version: YouTube-Music-Desktop-App-1.13.0.AppImage
 * OS:  ***Linux*** 
 * OS version: Archlinux 5.8.3
 * Arch: ***x64***
* Installation way: appimage from website.

**Comment by adlerluiz** [comment]
the youtube app just opens the music.youtube.com website in an encapsulated chrome, which is electron, the login part is direct with google because you are accessing a google service, and the project is open source, with this can be fully verified
