### ISSUE TITLE
Select Multiple Songs to Perform Actions (like "Add to playlist")

### ISSUE THREAD

**Issue by azwarners** [ytmdesktop/ytmdesktop#397]
- [√] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [√] I verified that there is no open issue for the same subject.
I went through the existing issues and I don't recall seeing it. I hope I didn't overlook it (I'm getting old and tend to do dumb things like that).

**Is your feature request related to a problem? Please describe.**
I'm new to YouTube Music and would like a way to build playlists quickly. I've discovered it is very easy to thumbs-up music as I'm listening. Going into the "Your Likes" playlist later and sorting them into various custom playlists by genre is not so easy. I have over five hundred liked songs and my only option for a personalized experience ("Your Mix") is hearing every kind of music that I like all at once. This is not ideal when the audience varies such as my coworkers at work, my family at home, my brother on Friday nights and my headphones when I'm doing dishes or jogging. The only way to move songs to another playlist is one-at-a-time.

**Describe the solution you'd like**
It would be nice to be able to click and select multiple items using the SHIFT key or the CTRL key (or by checking boxes) and then perform an action like "Add to playlist" on all selected items. This is not implemented in the web version. I'm hoping it might be feasible to do on this project.

**Describe alternatives you've considered**
I tried adding "&disable_polymer=1" to the URL in the web app as suggested below, but it did not seem to allow me to select multiple items.
[https://www.reddit.com/r/YoutubeMusic/comments/gna1aw/how_to_select_multiple_songs_in_ytm/](url)

**Additional context**
Without using image manipulation software I can't think of a way to provide a screenshot. I believe I've explained pretty thoroughly what functionality I feel is missing so I'm not sure I can think of any additional context. I can, however, say that there are at least 625 users (134 of whom have been vocal about it) who also want this feature implemented. You can see this at the Google support thread below. I'm guessing there are many more who would want it, but don't know that they want it.
[https://support.google.com/youtubemusic/thread/652125?hl=en](url)

Despite this request I love the work you all have done here and I think this app is an overall much better experience than just going to music.youtube.com on a web browser.

**Comment by TotalChris** [comment]
I'm running through this idea in my head and I can't think of a way that we could implement this without a serious level of control on the backend logic of YouTube Music. If we dug into the existing code of the site we could probably turn up a few functions that can be manipulated or recursively called, but it would be a large undertaking.

**Comment by azwarners** [comment]
Oh, okay. I hadn't had a chance to fork this project and see how it all works. I was originally thinking of writing a script to do this for me on the web browser using Tampermonkey or something like I had done in the past for pandora.com. I was imagining adding checkboxes next to each song and text box somewhere for the playlist name. Then simulating the clicks required to add each item individually to the specified playlist when the user says go thus automating the currently tedious process. I was hoping it might be easier to implement, though, in a project like this where you've already created your own interface.

**Comment by TotalChris** [comment]
Basically, the internal logic of the YTM context menu operates off of the one item that the user has right-clicked. Even if multiple elements are selected by the user, the context menu only sees the one it was activated over. All the functions that I can tell handle this are minified and impossible to read.

Just to be clear, we haven't made this interface. This is a wrapper application that loads music.youtube.com in a window. We make some changes to it, but everything we do works around existing code that Google has written.

**Comment by Alipoodle** [comment]
This feature appears to be added by YTM themselves now. (and was kinda what I suspected would eventually happen)
![image](https://user-images.githubusercontent.com/17199186/177009313-e3b9fff4-6fa5-4a5a-9b3d-34a2bebce744.png)

**Comment by Alipoodle** [comment]
![image](https://user-images.githubusercontent.com/17199186/177009329-38de1db9-b70e-41da-b220-c6dd3a451deb.png)
Loving the need for Add to Playlist and Play Next showing up twice... 👏
