### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by kkrrssnnaa** [ytmdesktop/ytmdesktop#404]
Yes, checked all options...cannot the app could be a bit more...say fluid? It is less fluid and crisp but more laggy even tho it isn't actually lagging but just loading. The ui is okayish for what it does, but a sudden revamp or little bit ease of use would be better...I suppose I have conveyed what I wanted to.

But, great and just great work tho. ;)

**Comment by kkrrssnnaa** [comment]
> Yes, checked all options...cannot the app could be a bit more...say fluid? It is less fluid and crisp but more laggy even tho it isn't actually lagging but just loading. The ui is okayish for what it does, but a sudden revamp or little bit ease of use would be better...I suppose I have conveyed what I wanted to.
> 
> But, great and just great work tho. ;)

**Comment by TotalChris** [comment]
> Huh, going to post on gplaystore then

I read your issue before it was closed. Could you re-file this using the template? You can just ignore some of the fields if you would like.
