### ISSUE TITLE
UiUx Suggestion

### ISSUE THREAD

**Issue by BrajBliss** [ytmdesktop/ytmdesktop#411]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

Cannot the app could be a bit more...say fluid? It is less fluid and crisp but more laggy even tho it isn't actually lagging but just loading. The ui is okayish for what it does, but a sudden revamp or little bit ease of use would be better...I suppose I have conveyed what I wanted to.

P.S. Thanks for  response 💯

**Comment by debmaj2** [comment]
It would be cool if you point out exact elements where you would like to see optimizations

**Comment by RadheShyamDasa** [comment]
> It would be cool if you point out exact elements where you would like to see optimizations

Like...the queue, the animation of opening and closing queue...connection ui, and sometimes even when the music is added to library it still doesn't show in the button when clicking on album art

**Comment by Alipoodle** [comment]
These issues are to do with YTM and not YTMD.
If you wish to change how some of these are done, you can use the Custom CSS Feature.
