### ISSUE TITLE
Invalid Pointer JavaScript Error on changing playlists

### ISSUE THREAD

**Issue by debosmit-git** [ytmdesktop/ytmdesktop#413]
- [Yes] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [Yes] I verified that there is no open issue for the same subject.

**Describe the bug**
Please see screenshot.
A square placeholder border around the icon is also noticed. ( I couldnt take a screenshot)

**To Reproduce**
1. On Playing a Playlist and changing to another before the Previous one loads

**Expected behavior**
it should switch to new playlist

**Screenshots**
![image](https://user-images.githubusercontent.com/22155707/94301484-41a21d80-ff88-11ea-8ebf-3d4a27015c48.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.1.30***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***exe***

**Comment by debmaj2** [comment]
Might be related:
#371

**Comment by debmaj2** [comment]
![image](https://user-images.githubusercontent.com/22155707/94302552-030d6280-ff8a-11ea-82e8-a15468b2eeb8.png)

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
