### ISSUE TITLE
Close button when tray icon is not available

### ISSUE THREAD

**Issue by andia89** [ytmdesktop/ytmdesktop#418]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

There are several Linux distros now that don't have tray icons anymore (mainly Gnome distros with the exception of Ubuntu), so I the tray icon will not show either if it is enabled. As far as I can see this means that there is no way (except the command line) to close the app completely if the keep running in background option is enabled. 

Would it be possible to have a "OFF" switch somewhere that really closes the app?

**Comment by Alipoodle** [comment]
Fixed in the #457 
Although on Windows using this shutdown button is broken although this is another issue.
