### ISSUE TITLE
Discord Rich Presence Image

### ISSUE THREAD

**Issue by Bo0sted** [ytmdesktop/ytmdesktop#422]
- [ X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
On Discord, the rich presence doesn't show the image/cover art of the song that's playing. It only shows the YT Music Desktop icon.

**Describe the solution you'd like**
Shows the cover art for each song that plays

![Discord_E2k59HWbbh](https://user-images.githubusercontent.com/43390612/94702398-b7511500-030b-11eb-81d8-ccd5c78a5749.jpg)

**Comment by armoredmeat** [comment]
just found this and downloaded. came here looking for info on this very thing. I would go further and say a nice youtube red background would work well too.

**Comment by Bo0sted** [comment]
> 
> 
> just found this and downloaded. came here looking for info on this very thing. I would go further and say a nice youtube red background would work well too.

Discord Rich Presence already exists, you can find this in the Settings menu by clicking on the gear icon. I want the discord rich presence to show the cover art for the current song im playing

**Comment by TotallyNotInUse** [comment]
They say it's not possible, only Spotify allows it #171

**Comment by Block81838** [comment]
Impossible

**Comment by rickinbsb** [comment]
I'm closing this as this as it's not doable.
With discord's current rich presence API, we can only use images uploaded to their control panel

**Comment by Alipoodle** [comment]
Discord has recently allowed for people to now use URLs for the Large Artwork allowing for us to now do this:
Track the stuff in #888 (Likely be in Development before reaching a public release for a bit)
