### ISSUE TITLE
More custom theme options

### ISSUE THREAD

**Issue by NinjaShuriken** [ytmdesktop/ytmdesktop#428]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem?**
Its more of a QoL feature to be honest but I would like to suggest for there to be more options that are editable in the custom appearances tab

**Describe the solution you'd like**
The solution would be to add more things that can be edited like the progress bar, the control buttons, text color etc.

**Describe alternatives you've considered**
I honestly don't really see an alternative to this, this is the only app I know to offer any customizability, I would just like the developers to hopefully expand upon it if possible

**Comment by KiranWells** [comment]
As an addition or alternative, the app could provide a library of custom CSS files to choose from instead of only allowing manual changes.

**Comment by julianfortune** [comment]
[Spicetify](https://github.com/khanhas/spicetify-cli) does this for Spotify.

**Comment by Alipoodle** [comment]
#419 Seems like a better way of implementing this.
A collection of Themes which a user is able to add/remove (some of which can be small additions like Removing of Premium button, or Changing the accent colour to a user selectable option)
And then some more full on themes can change the UI completely.

**Comment by NinjaShuriken** [comment]
Yeah that definitely sounds like a better overall idea and addition but I am assuming it is more difficult to implement as well?

**Comment by Alipoodle** [comment]
As noted, the noted issue sounds better.
