### ISSUE TITLE
Remote connect broken on Windows 10 x64 ytmdesktop 1.13

### ISSUE THREAD

**Issue by b1ackse7en** [ytmdesktop/ytmdesktop#438]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Hello,
when I try to connect to the desktop app with the Android app, this error message appears in the desktop app and no connection is established. if this error message is not confirmed, the music will stop playing a short time later.

**To Reproduce**
1. Go to 'Android App and Connect to Desktop App'
3. See error on Windows and not connect on Android App

**Expected behavior**
Remote Connect to Desktop App

**Screenshots**
![image](https://user-images.githubusercontent.com/36388261/95365144-067de380-08d2-11eb-8832-803fda42fa48.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: Windows 10 x64 Enterprise
 * OS version: 2004   Build: 19041.546
 * Arch: x64
* Installation way: .exe

**Comment by b1ackse7en** [comment]
I installed the beta version of the android app. The error message in Windows is still coming. But he is connected afterwards. However, I can only play and pause, nothing more is possible. I don't see which title is running, I can't choose another one, forward and backward. The buttons in the android app simply do not react except for play / pause

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
