### ISSUE TITLE
Problem with scalling

### ISSUE THREAD

**Issue by Zuberix666** [ytmdesktop/ytmdesktop#44]
On my hd screen there's no way to make it show everything(tried to set it manually)
![Zrzut ekranu (29)](https://user-images.githubusercontent.com/29493031/63165459-d0c1cf80-c02b-11e9-876b-5b80642ad187.png)
![Zrzut ekranu (30)](https://user-images.githubusercontent.com/29493031/63165460-d0c1cf80-c02b-11e9-8012-b8a37d8439fd.png)
![Zrzut ekranu (31)](https://user-images.githubusercontent.com/29493031/63165461-d15a6600-c02b-11e9-8502-8eb1d9864547.png)

**Comment by Zuberix666** [comment]
I called "everything" every element of the interface. Some of them aren't displayed or they are cut like missing account icon, cut subtitles or half of the slider next to the autoplay word(it's "autoodtwarzanie" on my screenshot bcs it's polish language)

**Comment by adlerluiz** [comment]
When you navigate on browser in the YouTube Music website, is it like this too?

**Comment by rickinbsb** [comment]
actually, aa1bfa is the one that fixes this, my commit is suposed to fix a similar issue exclusive to linux, my bad
