### ISSUE TITLE
mpris/dbus interface doesn't allow to just pause or stop track

### ISSUE THREAD

**Issue by christofdamian** [ytmdesktop/ytmdesktop#440]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
I am using a script to pause all music players when I am in a video call. This script currently sends the "Pause" event to the player. On YTM this is mapped to "PlayPause", which means music starts playing if it wasn't playing before. 

**Describe the solution you'd like**
Support an "Pause" or "Stop" event and make it  separate from "PlayPause". You probably also want to do this for "Play"

**Describe alternatives you've considered**
An alternative for my script to first check the status and then conditionally do "PlayPause", but this is not necessary for any other player like GTM or Rhytmbox. 

**Additional context**
This is probably the context in the code: https://github.com/ytmdesktop/ytmdesktop/blob/master/src/providers/mprisProvider.js#L57-L59

This is how Rhythmbox maps them: https://github.com/GNOME/rhythmbox/blob/master/remote/dbus/rb-client.c#L107-L110

And GTM: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/main/features/linux/mprisService.js#L33-L47

**Comment by christofdamian** [comment]
I might be able to do a PR along the lines of what GTM does, but my JavaScript is quite rusty.

**Comment by gaganpreet** [comment]
This particular issue has also been affecting me. If I put my desktop to sleep, the default action is to pause all players. If it's already paused state the player resumes right before it goes to sleep and continues playing when it wakes up.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
