### ISSUE TITLE
MPRIS interface doesn't work on Ubuntu snap version

### ISSUE THREAD

**Issue by Davies-Owen** [ytmdesktop/ytmdesktop#443]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
When installed via snap, events such as media key presses are not received by the `mpris-service` handlers.

**To Reproduce**
1. Install ytmdesktop via snapcraft.
2. Use snappy-debug.scanlog to watch for attempts to break snap confinement.
3. Observe that the mpris registrations are failing.

**Expected behavior**
MPRIS registrations should not error.

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Ubuntu***
 * OS version: ***20.04***
 * Arch: ***x64***
* Installation way: ***snapcraft***

**Comment by Davies-Owen** [comment]
I've traced this issue to a Snap confinement permissions problem. Electron-builder doesn't include the `mpris` plug in snaps by default, and `mpris` doesn't autoconnect.

**Comment by Davies-Owen** [comment]
For context: I noticed this issue when I register and connect a new bluetooth device. For some reason (I think it's unrelated), registering and connecting a new bluetooth device makes Electron's `globalShortcut` listeners stop working. This means that handling media keys falls back onto the `mpris-service`. This works fine on AppImage or unpacked versions of ytmdesktop, but fails on the snapped version because of the confinement issue. 
I'm trying to find a fix, but can't figure out how to make electron-builder add the `mpris` interface to the snap properly.

**Comment by Davies-Owen** [comment]
This error gets spit out when starting youtube-music-desktop-app from the command line:
```
(node:37718) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([
  'Connection ":1.306" is not allowed to own the service "org.mpris.MediaPlayer2.youtubemusic" due to AppArmor policy'
])
    at Player.emit (events.js:299:17)
    at emitError (/snap/youtube-music-desktop-app/6/resources/app.asar/node_modules/mpris-service/src/index.js:211:10)
    at /snap/youtube-music-desktop-app/6/resources/app.asar/node_modules/mpris-service/src/index.js:225:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

As you can see, the snap confinement is preventing the `mpris-service` from registering it's handler. I haven't yet figured out how to add the MPRIS slot to electron-builder's snap config in a way that makes it work.

**Comment by MartinCura** [comment]
Any progress with this? Or at least a manual fix?

Maybe the only reason i still use Spotify instead of YTM is simply being able to use playerctl to control playback. (Or is there another way?)

**Comment by Davies-Owen** [comment]
Yeah I have a fix for this, but I'm on vacation and can't make a PR. The
issue is naming of the mpris slot. Snap only gives access to the mpris slot
named 'youtube-music-desktop-player', but the app tries to access mpris via
a slot called 'youtubemusic'. That's the source of the issue, along with
mpris not being included the electron builder config. I can have a PR up
when I return to a computer on Wednesday.

**Comment by Davies-Owen** [comment]
Opened PR #462 addressing this issue.

**Comment by adlerluiz** [comment]
merged!
