### ISSUE TITLE
QUICK FIX - Window Title includes something static so window handlers can find it reliably (like -YTMD at the end or something)

### ISSUE THREAD

**Issue by TheKuroiKaze** [ytmdesktop/ytmdesktop#446]
- [x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

I use window handlers to arrange windows but since this uses a common class and the window title is always changing with the track name there's nothing to "grab" on to so that I can arrange it.  

**Describe the solution you'd like**

Please allow an option to put a small bit of static text on the end of the window title or something.
Perhaps something like -YTMD after the track etc...

**Describe alternatives you've considered**

ClassName is Chrome_WidgetWin_1 just like every other webapp program I use (Slack, Teams, etc)

**Additional context**

Since this is such a small one here's hoping it can get done by someone in a few minutes.

**Comment by Dieterbe** [comment]
@TheKuroiKaze how do you find the class name?  I'm hopeful your workaround would work for me as I don't use chromium or any of the other mentioned chrome-based apps, but mapping on class `Chrome_WidgetWin_1` doesn't work for me.

**Comment by Dieterbe** [comment]
i found out i can run my window manager (i3) in debug mode, which told me the class of the window. In my case it's "youtube-music-desktop-app". Matching on that works fine for me.

**Comment by TheKuroiKaze** [comment]
@Dieterbe when I run my window manager I still see the class name is Chrome_WidgetWin_1 the same as Discord and other Chromium programs.  The manager I use is AutoSizer.  FireFox for instance is MozillaWindowClass.  So if the Window Name had something identifiable in it I could just match off of that like I do with most programs (Chrome, Slack, Teams, etc..).

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

This should now be a thing.
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/effe8c2d-63a5-494c-bbe3-38a128efb88b)
