### ISSUE TITLE
Discord Rich Presence requires restart

### ISSUE THREAD

**Issue by TotallyNotInUse** [ytmdesktop/ytmdesktop#448]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Toggling Discord Rich Presence should ask for a restart

**Describe the solution you'd like**
A button that asks you to restart the program

**Describe alternatives you've considered**
Restarting it manually

**Additional context**
If you disable Rich Presence it will still appear until you restart the program which I believe could be fixed with a variable check. I would fix it by myself but I haven't installed VS.

**Comment by Block81838** [comment]
##### Atom discord rich presence got the same problem, I don't know if it a matter of discord

**Comment by adlerluiz** [comment]
I will check this problem, thanks for reporting

**Comment by CorvetteCole** [comment]
can confirm, app requires a restart to enable it as well. At least on Arch Linux it does. A banner should pop up asking to restart at least if an easy fix for this isn't found

**Comment by TotallyNotInUse** [comment]
Merged pull request with fix
