### ISSUE TITLE
Internet connectivity on start

### ISSUE THREAD

**Issue by olcw78** [ytmdesktop/ytmdesktop#449]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

----> <-----
Hope you are safe under these period!

1. When I start this app without the internet connection and reopen with having internet connected,
   The app doesn't recognize any connection.

![image](https://user-images.githubusercontent.com/7125433/95835025-acb96580-0d78-11eb-935b-d3de4a940328.png)

2. but it's resolved after I quit this app manually and restart the app

3. I think it's the matter of internet connection timing! hope it helps out

**Comment by adlerluiz** [comment]
I will check and try to reproduce this problem, Thank you

**Comment by Mizumaky** [comment]
Yup, I wanted to create a new n clean issue on this but didnt want to spam if there are already other.  
I run into this quite often since my PC is not yet connected to the internet when I start it up (and the app starts as well on the background).  
The only solution is to restart the app manually to make it work again.

**Comment by olcw78** [comment]
I'm really thanksful for you to take the time to test and to reanimate the
situation!
okay! that's not a big issue

anyway, I also thank for this service and I use it many time!
hope you have great rest of the first month 2021!!

good work!



2021년 1월 14일 (목) 오후 5:22, Mizumaky <notifications@github.com>님이 작성:
