### ISSUE TITLE
No MPRIS Media Controls in Notification Area (Fedora AppImage install)

### ISSUE THREAD

**Issue by cmcinroy** [ytmdesktop/ytmdesktop#454]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
There are no media controls in the GNOME notification area when ytmdesktop is running.
Running from the command line shows no errors.

**To Reproduce**
1. Install ytmdesktop from AppImage.
2. Launch ytmdesktop app.
3. Observe no MPRIS widget in notifications area.

**Expected behavior**
Other media players render media controls in the notification area. Typically, album art for the current track and player basic controls (prev, play/pause, next) are shown.

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: **v1.13.0**
 * OS: **Linux**
 * OS version: **Fedora 32**, GNOME 3.36.7
 * Arch: **x64**
* Installation way: **AppImage**

DISCLAIMER: I really don't understand enough about MPRIS controls in GNOME to articulate what should be a happening where -- it all seems like a dark science, really -- I am only going on experience with other players. I should probably try installing it in Ubuntu and see what happens there.
I really love this app and have fully transitioned to using it daily, would really love to have the same integrated desktop experience that I have relied upon with other players.  Thanks!

**Comment by cmcinroy** [comment]
Ooh. It works beautifully in Ubuntu (20.04 with GNOME 3.36.4), all other environment info same as above.

**Comment by andia89** [comment]
I have the same issue with Ubuntu 20.04. Often it helps to restart the GNOME shell while the player is running (Alt+F2 and command `r`), then the player shows up and media keys work, seems to be quite arbitrary if and when it works though

**Comment by cmcinroy** [comment]
@andia89 Wow!! That worked!
I've done that in the past to resolve similar issues, but it never ocurred to me to try it in this case. Awesome. Thank you!

**Comment by cmcinroy** [comment]
@adlerluiz Is there no remedy in code that you feel should be explored?
Other software is able to properly integrate with GNOME notifications at launch, without having to restart the shell.

**Comment by andsmedeiros** [comment]
@adlerluiz The same happens to me with Ubunutu 20.10, fresh install. Restarting gnome-shell while running doesn't help tough.
Other programs (e.g. rhythmbox, vlc) work just fine.

**Comment by MexHigh** [comment]
I still have this problem on Fedora Workstation 42. I using this extension to use MPRIS: https://extensions.gnome.org/extension/4470/media-controls/
