### ISSUE TITLE
Miniplayer bug

### ISSUE THREAD

**Issue by gleam-ru** [ytmdesktop/ytmdesktop#461]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**
Miniplayer size is changing every second.
I think that it is related to the 4k-display with upscaling.

 **To Reproduce**
 1. Open application
 2. Open miniplayer
 3. Move miniplayer
 3. See error
 4. If you go to fullscreen-mode you will see an related to js error

 **Expected behavior**
1. Miniplayer has permanent size
2. No js-errors

 **Screenshots**
![image](https://user-images.githubusercontent.com/6701480/96708337-c7579400-13a1-11eb-85d6-e28c8beab697.png)

https://i.imgur.com/k9HzprZ.gifv

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.19041***
 * Arch: ***x64***
 * Installation way: ***like .exe or snapcraft or another way***

**Comment by adlerluiz** [comment]
Thank you for informing
