### ISSUE TITLE
Page zoom option displays undefined

### ISSUE THREAD

**Issue by Block81838** [ytmdesktop/ytmdesktop#463]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**

Page zoom option shows as undefined

**To Reproduce**
1 go to option
2 change the page zoom option

**Expected behavior**

**Screenshots**
![Screenshot_20201021180806](https://user-images.githubusercontent.com/22847876/96806377-c84fec00-13c8-11eb-8709-a6231e521216.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: linux
 * OS version: ***Archlinux***
 * Arch: ***x64***
* Installation way: ***Aur package makepkg***

**Comment by adlerluiz** [comment]
Thank you, I just corrected it now
