### ISSUE TITLE
Opening the application from shortcut with Remote Control on - javascript error: EADDRINUSE

### ISSUE THREAD

**Issue by ajaxovic** [ytmdesktop/ytmdesktop#464]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
After application starts or after bringing it from tray, alert window appears. After click on OK, app continues in regular way

**To Reproduce**
After reboot, open app

**Expected behavior**
No popup with error

**Screenshots**
![image](https://user-images.githubusercontent.com/11288002/96862999-82e1fc00-1466-11eb-93f3-77d3457b6b5f.png)

**Environment (please complete the following information):**
 * YTMDesktop version: v1.13.0
 * OS: Windows
 * OS version: 10
 * Arch: x64
* Installation way: exe from pages

**Comment by ajaxovic** [comment]
It looks like it colliding with locally installed MySQL server :)

**Comment by adlerluiz** [comment]
this usually occurs when you try to open the app twice, as the remote control server is already started and when opening the second instance this message occurs

**Comment by ajaxovic** [comment]
Hmm, understand... It is in case when app is in tray and I click on desktop icon again...  It is expected behaviour?

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
