### ISSUE TITLE
Convert Queue to Playlist

### ISSUE THREAD

**Issue by ptrstr** [ytmdesktop/ytmdesktop#468]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
When I start a radio using the "Start Radio" option it's really annoying when a good queue comes on but you can't save it unless you do it one by one.

**Describe the solution you'd like**
A button to save the queue as a playlist or a way to control select songs and then add them to a playlist.

**Describe alternatives you've considered**
Adding each song one by one to a playlist. Could be solved using a regular for loop.

Thanks!

**Comment by gignsky** [comment]
This would be great! This feature was finally added to the mobile app [see here](https://9to5google.com/2022/03/28/youtube-music-save-queue-playlist/#:~:text=The%20YouTube%20Music%20version%20involves,your%20current%20playlist%20or%20album.) and we are one step closer now to being back to the greatness of google play music RIP.

**Comment by Jeremy-Freeman** [comment]
This is one of the most frustrating features to not have in the desktop app!! I often start a radio from a song, find out the queue is a banger and want to save it at a playlist, but NOPE. :'(

**Comment by Alipoodle** [comment]
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/6f9e8c49-2085-4c3a-ae2c-febd6b328a32)

This is now a Native YTM feature
