### ISSUE TITLE
Problem: Clicking on ContextMenu and page goes blank

### ISSUE THREAD

**Issue by sp0ok3r** [ytmdesktop/ytmdesktop#47]
Hello, i go to Settings and Lyrics and the window goes blank.

![bug](https://user-images.githubusercontent.com/7952298/65908573-9edbb100-e3be-11e9-96f6-e2e26dfecc87.png)

**Comment by mingjun97** [comment]
Hi sp0ok3r,
    Thanks for your report. Are you running under stable/release version or development version?

**Comment by sp0ok3r** [comment]
I'm using the stable version.

**Comment by mingjun97** [comment]
It seems work in my environment. 
Some more questions:
1. Is it the latest release(v1.5.0)? 
2. If it is, did this problem occur after upgrade?
3. Does this problem occur through lyric button(the lyric button on the top-right cornor of main window?)

PS: You may see the version at [Settings] -> [About]

Thanks for your reply!

**Comment by sp0ok3r** [comment]
1. Yes;
2. I tryed 1.4.1 and it works;
3. No, the buttons works inside main window.

**Comment by mingjun97** [comment]
Thank you so much for your response! I'll investigate it.

**Comment by mingjun97** [comment]
I've fixed this issue and commit to development branch. But it is not merged into master yet.

**Comment by rickinbsb** [comment]
781cf27 only fixes it for the lyrics window

**Comment by mingjun97** [comment]
Sorry, I missed the Settings window. 😂

> [781cf27](https://github.com/ytmdesktop/ytmdesktop/commit/781cf2786c437ff2cecaa2b440c77090f967a01b) only fixes it for the lyrics window

**Comment by rickinbsb** [comment]
yep haha, I've pushed a fix for it now

**Comment by mingjun97** [comment]
Thx, I appreciate it. :)
