### ISSUE TITLE
Switch between song and video like in the android app

### ISSUE THREAD

**Issue by BigicecreamTaken** [ytmdesktop/ytmdesktop#471]
- [ v] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ v] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
When playing a song I sometimes want to see the video too, so want I have to do is find the video version and play it instead

**Describe the solution you'd like**
Like in the android app, an toggle to switch between the versions(in the android version it also continues from where the song left)

**Comment by adlerluiz** [comment]
it is a question that we have tried to implement but without much success, as the ideal would be google to implement this directly in ytmusic
