### ISSUE TITLE
YouTube Music is not available in your country

### ISSUE THREAD

**Issue by ytmdesktop-issue** [ytmdesktop/ytmdesktop#472]
- [okay] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [yeah i didnt see any] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

yes, YouTube Music is not available in my country. if i try to open music.youtube.com i see this
![image](https://user-images.githubusercontent.com/73463283/97145706-8fb06980-175e-11eb-89ec-b6c8f1cb6ec3.png)

**Describe the solution you'd like**

someway so i can enjoy music from youtube too.

**Describe alternatives you've considered**

i am watching music on youtube. spotify isnt available either.

**Additional context**

**Comment by adlerluiz** [comment]
this is google’s decision to launch the product in several countries, i believe it’s a matter of time before it arrives at your
