### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by mmorales99** [ytmdesktop/ytmdesktop#48]
Availeable ytmdesktop version here : https://ytmdesktop.app/
is outdated, also when trying:
_sudo snap install youtube-music-desktop-app_1.4.1_amd64.snap_ 
shows:
_error: cannot find signatures with metadata for snap
       "youtube-music-desktop-app_1.4.1_amd64.snap"_

Trying to use .appimage results in other failure. After runing:
_chmod +x YouTube.Music.Desktop.App.1.4.1.AppImage && ./YouTube.Music.Desktop.App.1.4.1.AppImage_
gives:
_/home/usr/.local/share/applications/appimagekit-youtube-music-desktop-app.desktop: warning: value "YouTube Music Desktop App" for key "Comment" in group "Desktop Entry" looks redundant with value "YouTube Music Desktop App" of key "Name"
/home/usr/.local/share/applications/appimagekit-youtube-music-desktop-app.desktop: error: (will be fatal in the future): value item "Audio" in key "Categories" in group "Desktop Entry" requires another category to be present among the following categories: AudioVideo
/tmp/.mount_YouTubPW7hRe/youtube-music-desktop-app: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory_

So as i read in electron web page and here, the last version is 1.5.0. Could you add the .appimage and the .snap file to github repo¿?

Using the github packege and running npm install && npm start it works within the expected behavior.

Im running a newly installed Ubuntu 18.04.3 with acpi=off as launch param, running over MSI GL62M 7RDX with the standard manufacturing hardware.

**Comment by rickinbsb** [comment]
Fixed on 1.5.3
