### ISSUE TITLE
x64

### ISSUE THREAD

**Issue by UnExPeCtEdFuZzBaLl** [ytmdesktop/ytmdesktop#486]
please make a 32 bit x64 version. 

- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Venipa** [comment]
replace publish:win with
```
"publish:win": "npx electron-builder --win -p always --config electron-builder.yml",
```

anyways you can remove the 64 suffix from the config parameter to build x86 versions

**Comment by Alipoodle** [comment]
Considering that all modern Windows and Linux Systems now a days are running in 64bit or more platform specific code, I'm closing this as something which is no longer needed.
