### ISSUE TITLE
Problem: After 1 hour i can't open ContextMenu

### ISSUE THREAD

**Issue by sp0ok3r** [ytmdesktop/ytmdesktop#49]
After 1 hour with the app on the background, i can't open the context menu.

**Comment by rickinbsb** [comment]
What Operating System are you using? and which version of ytm?

**Comment by sp0ok3r** [comment]
Windows 10 (1903) | 1.5.0

**Comment by mingjun97** [comment]
Does this happen every time?

**Comment by sp0ok3r** [comment]
no

**Comment by adlerluiz** [comment]
@sp0ok3r there is a new release available, and @mingjun97 has made some corrections, if it occurs again please let us know
