### ISSUE TITLE
Reload doesn't work, Developer tools hidden behind main page

### ISSUE THREAD

**Issue by meteorsquare** [ytmdesktop/ytmdesktop#493]
Not sure if this/these problem/s only happen/s on mine.

**Describe the bug**
Reloading does nothing.
When opening developer tools, the window opens but only the top and side parts are showing (screenshot below). 

**Expected behavior**
Black screen and loading icon when reloading.
Developer tools open in front of the page completely(?).

 * YTMDesktop version: 1.13.0
 * OS: Mac
 * OS version: 10.15.7

<img width="1436" alt="Screenshot 2020-11-08 at 16 37 45" src="https://user-images.githubusercontent.com/58662679/98470950-c9628500-21e0-11eb-90aa-89f2939873cc.png">

**Comment by jnr2820** [comment]
This should be re-opened. Mine does it too. (multiple Mac's, both on Catalina and BigSur)
The reload hot-key problem is especially bothersome, as something occasionally breaks and certain elements become not clickable. (Might be an issue with YTM itself and/or Mac sleep function) Reload would fix this but instead I have to close and re-open the whole app. :|

App Version: 1.13.0
MacOS 11.1
