### ISSUE TITLE
Reduce ways to open up queue, remove bottom-right cover art on page

### ISSUE THREAD

**Issue by meteorsquare** [ytmdesktop/ytmdesktop#494]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution (idea) you'd like**
- When I select a track to play, the queue window doesn't pop up, it only plays the song. Also when clicking on the player bar, I would like the queue not to open up as well, unless I press the arrow on the right-hand side.
- Prevent cover art on the bottom right of the page from showing when the queue is not opened. It is blocking some parts that I may need to click on (such as removing tracks from playlists).

**Describe alternatives you've considered**
Maybe if there's a way the queue doesn't take up all of the window.

**Comment by Alipoodle** [comment]
Closing this as this seems more of a personal preference.
I've provided some CSS regarding some of the things he's requested.
