### ISSUE TITLE
Player control in volume control widget in Windows 10

### ISSUE THREAD

**Issue by BexaGal** [ytmdesktop/ytmdesktop#495]
You all know, that in Windows 10 there is a volume control widget. It can control music playing if there is a running player. So, it would be awesome if there was such a good feature in the ytmdesktop.
![Снимок экрана 2020-11-09 120830](https://user-images.githubusercontent.com/50549190/98521862-0e3ff780-2285-11eb-9219-7af7c4dc4376.png)
![Снимок экрана 2020-11-09 121156](https://user-images.githubusercontent.com/50549190/98521873-113ae800-2285-11eb-9c71-51bb0befca27.png)

**Comment by agc93** [comment]
Also @BexaGal that's already available: check in the Settings.

**Comment by BexaGal** [comment]
Thank you, @agc93
