### ISSUE TITLE
Opening the application when already open gives error message EADDRINUSE

### ISSUE THREAD

**Issue by tarekalzein** [ytmdesktop/ytmdesktop#498]
- [x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x ] I verified that there is no open issue for the same subject.

**Describe the bug**
Opening another instance of the application while one is already open gives an error message (without crashing)
"JavaScript error occurred in the main process.....address already in use xxxxxx"
![Untitled](https://user-images.githubusercontent.com/43130672/98810570-bab5e100-241f-11eb-90b3-e49013875ada.png)

**To Reproduce**
1. Open the desktop application.
2. Reopen the application from start (again)
3. See error

**Expected behavior**
Show the first instance of the application

**Screenshots**
Attached 
**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***exe installer***

**Comment by tarekalzein** [comment]
Now i found it in the reported issues....different description :)

**Comment by kudlav** [comment]
Duplicate of https://github.com/ytmdesktop/ytmdesktop/issues/371
