### ISSUE TITLE
Replace Discord Rich Presence "Playing" with "Listens to"

### ISSUE THREAD

**Issue by LeonPro12** [ytmdesktop/ytmdesktop#499]
- [ x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x ] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Like with Spotify. It'd fit better.

**Comment by TotallyNotInUse** [comment]
That's because Spotify and Discord got a partnership. The developers of YTMD can't do the same.

**Comment by mingjun97** [comment]
Duplicated.
