### ISSUE TITLE
Settings doesn't save

### ISSUE THREAD

**Issue by sneakyevilSK** [ytmdesktop/ytmdesktop#50]
I wanted to use this for discord rich presence but simply I can't since settings doesn't save. Everytime I open settings and enable something and close it and reopen settings they're reseted to default. I tried even running program as administrator.

I'm using Windows 8.1

**Comment by adlerluiz** [comment]
@sneakyevilSK Is this your first time using or already using the app and did this happen after an update?

**Comment by sneakyevilSK** [comment]
Yeah, first time.

**Comment by adlerluiz** [comment]
@sneakyevilSK We have a new release please try now

**Comment by rickinbsb** [comment]
I'm closing this per the settings page rework, please reopen this issue if the error happens to you on 1.6
