### ISSUE TITLE
Shuffling problem

### ISSUE THREAD

**Issue by shamazuka** [ytmdesktop/ytmdesktop#500]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

Describe the bug
The shuffle button, when clicked second time shuffles the songs even more instead of going back to the original order.

To Reproduce
1. Go to any playlist
2. Click the shuffle button once
3. Click it second time
4. You now see the "up next" tab is messed up even more

Expected behavior
Once I click it for the second time it should go back to the original order.

Screenshots
-

 YTMDesktop version: 1.13.0
 OS: Windows
 OS version: 19041.572
 Arch: x86
Installation way: .exe

**Comment by Alipoodle** [comment]
This is sadly YTM Behaviour and not a Bug from us.
Please provide feedback to YTM regarding make this a feature.
