### ISSUE TITLE
Turkish Language 

### ISSUE THREAD

**Issue by C8rtex** [ytmdesktop/ytmdesktop#502]
- [y] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [y] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
I translated the settings not translated in Turkish for you <3

**Describe the solution you'd like**
[https://media.discordapp.net/attachments/756085517182828634/777463700092878848/dsfasfd.PNG?width=827&height=504](url) [https://media.discordapp.net/attachments/756085517182828634/777463706372145152/sgrtew.PNG?width=853&height=504](url) [https://media.discordapp.net/attachments/756085517182828634/777463708435087400/fsafdsf.PNG?width=829&height=504](url)

youtube music is not really for desktop but I believe you will achieve it. <3

**Comment by Alipoodle** [comment]
Closing this as no response in 6 months.
