### ISSUE TITLE
Clipboard monitoring doesn't work

### ISSUE THREAD

**Issue by chickenphaal** [ytmdesktop/ytmdesktop#506]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
When copying URL to clipboard, YTMD responds erratically. Either failing to recognise the copy (it's in the clipboard), throwing up a java error, or occasionally a popup asking if I want to play the URL, before doing nothing when saying yes.

**To Reproduce**
1. Go to YTM
2. Click share on an album/playlist
3. YTMD reacts like above

**Expected behavior**
Should play or prompt to play compatible YTM URLs

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: v1.13.0
 * OS: Windows
 * OS version: 10 (1909)
 * Arch: x64
* Installation way: .exe

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
