### ISSUE TITLE
App crushes

### ISSUE THREAD

**Issue by achertovsky** [ytmdesktop/ytmdesktop#507]
- [+] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [-] I verified that there is no open issue for the same subject.

**Describe the bug**
Sometimes application crushes. Just did in the beginning of a song, usually crushes on song change

**To Reproduce**
Launch the application, launch a song/playlist

**Expected behavior**
Song changes without crush

**Screenshots**
No screnshots

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Linux***
 * OS version: ***16.04***
 * Arch: ***x64*** 
* Installation way: ***snap***

**What i get if launch application from terminal**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/youtube-music-desktop-app/6/data-dir/icons/Adwaita/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)

**Comment by Alipoodle** [comment]
Closing based upon the issue no longer being required.
