### ISSUE TITLE
Audio Output does not update when connecting a new output device

### ISSUE THREAD

**Issue by timtmok** [ytmdesktop/ytmdesktop#509]
- [ x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x ] I verified that there is no open issue for the same subject.

**Description**
When audio outputs change, the selection when switching audio outputs does not update.

**To Reproduce**
1. Start YTM Desktop
2. Connect a new audio output such as a bluetooth speaker
3. Look at the audio outputs

**Expected behavior**
I expect the new audio output to be shown and selectable from the list. Reloading does not update the list. The app has to be restarted to get the correct list of audio outputs.

**Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Mac***
 * OS version: ***10.15.7 (Catalina)***
 * Arch: ***x64***
* Installation way: ***dmg***

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
