### ISSUE TITLE
Windows 10 Media Service popup is not showing up and YT Music Desktop is always forcing priority

### ISSUE THREAD

**Issue by Pawel-Dymek** [ytmdesktop/ytmdesktop#512]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**
Whenever I use my media control keyboard keys, they work, but there is no Windows media service popup in the upper left corner on my screen. But interestingly if I press vol+/- I can see Windows media service popup and then I can see there all details on the song, as it should be.
What worse, YT Music Desktop App seems to force some kind of priority over any other media source. So with my media keys I can only control YT Music, even when this app is only in the background and no music is playing from it, and I am watching YT video in Chrome, my play/pause button will not pause said video but it will star whatever music was paused in YT Music Desktop.
ofc I've tried turning "Enable Windows 10 media service" and "Show track information" on (and even off :P ) in the options 

 **To Reproduce**
1. Have YT Music Desktop open
2. Press any of the keyboard media control keys (except vol+/-)

 **Expected behavior**
Windows 10 media service popup will show up when any of the media control keys is pressed.
And YT Music Desktop will respect order in which I engage with media from other sources. E.g. if I start YouTube video after pausing my music from the app, app will not start playing it again, after pressing the play key on my keyboard (behavior like in Spotify app)

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.19042***
 * Arch: ***x64***
 * Installation way: ***.exe***

**Comment by Cyberdroid1** [comment]
I am also facing the issue. 

Maybe if we can disable the hotkeys, it can fix the issue.

**Comment by Parth-Mawai** [comment]
In the settings>shortcuts, there are 3 pre defined hotkeys which are making this issue, add an ablility to disable them also. 
regrads
![image](https://user-images.githubusercontent.com/76217236/106036949-019ca400-60fc-11eb-92cd-eaa124d62742.png)

**Comment by Parth-Mawai** [comment]
Pls fix this ASAP !!!

**Comment by NovusTheory** [comment]
Fix by me merged in (the issue should've been closed on merge)

**Comment by ofsaleem** [comment]
I'm also experiencing this issue. The nightly release doesn't fix it, which makes sense since it was published 1 day before NovusTheory's fixes got merged in haha

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2
