### ISSUE TITLE
Ability to play local files, maybe?

### ISSUE THREAD

**Issue by arcade-master** [ytmdesktop/ytmdesktop#519]
- [x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x ] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
I know it's an app for Youtube Music but pretty please :'))

**Comment by debmaj2** [comment]
Fork Off :D
I mean it is certainly not in the roadmap but you may try yourself.

**Comment by arcade-master** [comment]
i wish i could code, hehe
