### ISSUE TITLE
Music occasionally plays from default output rather than selected output

### ISSUE THREAD

**Issue by thesupremecommander** [ytmdesktop/ytmdesktop#520]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
Occasionally, when the app switches between songs, the new song will play on the default audio output rather than the one selected in the settings. The settings don't show that any change has occurred, but reselecting the same audio output will force the music to play on the correct audio device again.

**To Reproduce**
Unknown

**Expected behavior**
The music always plays on the selected audio output.

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***10, 1909***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by HawkyYT** [comment]
Also encountering this issue with a Voicemeeter setup. My default audio device is the "Voicemeeter Input" but I prefer to send my music to "Voicemeeter Aux Input" device so I can adjust things separately in Voicemeeter.

The issue most often occurs when I already have a queue (whether playlist, album, or radio) but have had it paused for an extended period of time, and start another playlist, album, or radio from the home screen recommendations. I've also had it happen when just resuming after having it paused for a while and it, notably, needs to re-buffer the song.

The app still shows "Voicemeeter Aux Input" as the set audio device even though I can clearly see in Voicemeeter that it is coming through "Voicemeeter Input". Changing it to another device then back to what I want fixes it for a while.

**Comment by NovusTheory** [comment]
Have ran into this issue. Didn't bother enough to try and look into the issue. But I might now. Not sure what the issue lies and why it resets.

**Comment by tconley** [comment]
I also have this same issue. very jarring when my player is going to voicemeeter and then all of a sudden the next song comes on some audio device that it should not.....

**Comment by tvandinther** [comment]
On my system, I've narrowed down the trigger to be when it switches from a "regular" track to one sourced from a YouTube video.

I also use Voicemeeter as my selected Audio Output. I usually exit the app and restart it to reset the output.

**Comment by flleeppyy** [comment]
*bump*

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
