### ISSUE TITLE
StreamDeck Integration

### ISSUE THREAD

**Issue by Maskime** [ytmdesktop/ytmdesktop#523]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
No

Basically I've made a StreamDeck integration of the REST API.
For now I just produced a build for window only : https://github.com/Maskime/ytmda-streamdeck/releases/tag/v1.0.0-rc1
But I could produce a mac version if people ask for it.

This is done with .Net Core 3.1 and built as a self-contained app, which remove the necessity of having the .Net Core runtime installed.

It may not be perfect but I'm using it for a while now without facing any issue.

Feedback is more than welcome. 

PS: I apologize in advance if this self promotion was seen as inappropriate.

Best Regards

**Comment by XeroxDev** [comment]
Hey. I've created a StreamDeck Plugin too. I've added most actions, passwort protection is working and it's super slim. (16KB I think).

The code is open source, everyone is allowed to fork and create merge requests. If something is missing or something needed to be changed, don't hesitate to create a issue.

Repo: https://github.com/XeroxDev/YTMD-StreamDeck

Kind regards.

**Comment by Alipoodle** [comment]
Closing this ticket as I've added the Repo link above into a section on the Wiki.
❤️ Thank you for this tool for the API!
