### ISSUE TITLE
Logitech G-Keyboards Media Keys do not work

### ISSUE THREAD

**Issue by ZaeGitHub** [ytmdesktop/ytmdesktop#538]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**

This is similar to Issue #100 in that it affects Logitech keyboards, but is different because these keyboards do not use Logitech Options.

I have a Logitech G810, and the media keys do not work. Previously, I had a G910v2, and they also did not work on that keyboard. This keyboard does **not** use Logitech Options or Logitech Setpoint, so the typical GPMDP fix does not work. The Chrome flag suggested in [this comment](https://github.com/ytmdesktop/ytmdesktop/issues/100#issuecomment-658887511) also does not fix the issue. Downloading the keyboard test application from MarshallOfSound in that same issue shows the keys properly:
MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1306

The comment [here](https://github.com/ytmdesktop/ytmdesktop/issues/376#issuecomment-695899061) also didn't fix the problem. I removed the one Chrome extension I had, I disabled the flag, I restarted Chrome. I even tried force closing all Chrome processes from taskkill in Windows.

Finally, I tried the Windows Media Integration. Also no luck. This leads me to believe this is something with YTMDesktop. Please let me know how I can assist, as I imagine this affects other users as well! 

**To Reproduce**
1. Open the app
2. Play music (clicking in the play icon in the app)
3. Music starts
4. Hit the "play/pause" button in the keyboard
5. ERROR: Music doesn't pause.

**Expected behavior**
1. Open the app
2. Play music (clicking in the play icon in the app)
3. Music starts
4. Hit the "play/pause" button in the keyboard
5. Music pauses.

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0
 * OS: ***Windows***
 * OS version: ***Windows 10 2004***
 * Arch: ***x64*** 
* Installation way: ***Binary executable***

**Comment by crborga** [comment]
It works fine for me on the Logitech G213 keyboard. Not sure how different it is from your model.

**Comment by ZaeGitHub** [comment]
> It works fine for me on the Logitech G213 keyboard. Not sure how different it is from your model.

I'm not really sure, either, as I think all the G-Series keyboards use G Hub now... but this issue has persisted for me across 2 keyboards, 2 motherboards, and 2 Windows installs, so it's definitely something related to quirkiness with the keyboard and YTM.

As a side note, GPMDP worked fine.

**Comment by PolarGoose** [comment]
@ZaeGitHub, there is also a similar [problem](https://github.com/ytmdesktop/ytmdesktop/issues/100#issuecomment-688688452) with Autohotkey's media buttons. An interesting thing that it looks like "Amazon Music for Windows" app has exactly the same problem with handling media buttons. It can be that it is a bug in the framework which is used.

**Comment by ZaeGitHub** [comment]
I'm not entirely sure why or what changed, but media keys now work from my Logitech G810. I recently reinstalled Windows, multiple versions of Logitech G Hub have released since I filed this bug, and the application has been updated several times. Unclear what the resolution was, but looks good now.
