### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Chrys4lisfag** [ytmdesktop/ytmdesktop#54]
https://i.imgur.com/ekrKuPo.png
After ~4h of music listening 
i5-8600k

**Comment by Chrys4lisfag** [comment]
Also app windows becomes laggy and about to crash.

**Comment by slimakovec** [comment]
Same issue here. Although I believe this more like youtube music problem itself, they have to have some serious memory + performance leaks, same thing happens to me on all "container" apps for youtube music.

**Comment by Chrys4lisfag** [comment]
Still my browser can handle that so might be that it can be fixed on the app side

**Comment by mingjun97** [comment]
I have the same problem before on my mac. But it never happened after I reinstall my laptop's operating system. For my windows laptop, it has the same problem after a long sleep.
I noticed this problem may first appeared after we add the online/offline checker but I'm not sure if does be that.
Do you mind try a version without commit 39f162a? I can compile it for you guys.

**Comment by mingjun97** [comment]
Btw, if it does be the problem of youtube music, I guess we may do a positive refresh to avoid high CPU utilization.

**Comment by Chrys4lisfag** [comment]
Yeah, if you give me compiled version, I can check

**Comment by JamesParkDev** [comment]
I can agree after some hours it does jump it looks like for some reason it starts multiple processes of youtube music application? Anyone know the fix?

**Comment by mingjun97** [comment]
Hi all, it looks like adlerluiz disabled the connection checker at v1.5.2, could you guys try it out?

**Comment by rickinbsb** [comment]
I'm closing this, as we had a lot of performance tweaks and improvements, please reopen this if anyone have new feedback on it
