### ISSUE TITLE
Unable to resize window from top-left corner

### ISSUE THREAD

**Issue by VapidLinus** [ytmdesktop/ytmdesktop#541]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Re-sizing the application by dragging the top-left corner of the window does not work. The other three corners are able to resize the window.

**To Reproduce**
1. Hover over top-left corner.
2. No "resize" cursor will appear.
3. Dragging to resize will not work.

**Expected behavior**
The "re-size" cursor should appear when hovering over the top-left corner. This works in the majority of other Windows applications.

**Screenshots**
See this video for a quick explanation:
https://streamable.com/e8sixh

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows 10.0.19041 x64***
* Installation way: ***.exe installer***

**Comment by VapidLinus** [comment]
Oh it's also not possible to re-size the window using the top-edge of the window.

**Comment by stealthgyro** [comment]
Noticed the streamable link was down, hoping this [imgur link ](https://imgur.com/rwJpQKy) will remain.  https://imgur.com/rwJpQKy 

- **YTMDesktop version**: v1.13.0
- **OS**: Windows 10.0.19044.1586 x64
- **Installation way**: .exe installer (Originally, then I believe WinGet)

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
