### ISSUE TITLE
Provision back button action

### ISSUE THREAD

**Issue by AkarshSatija** [ytmdesktop/ytmdesktop#55]
While navigating over various playlists/searches, there's a need of going back.
But it's not possible right now.
Generic mac shortcuts or touchpad gestures also does not do that.

**Comment by adlerluiz** [comment]
@mingjun97 Do you know anything about this?

**Comment by mingjun97** [comment]
> @mingjun97 Is the same #64 ?

I believe they are talking different things. This issue is talking about page navigation.

**Comment by mingjun97** [comment]
I add a status bar menu to help you navigate back/forward with shortcut key `cmd+[`/`cmd+]` as a workarond. I believe it is not very convenient to use. But I didn't come up with a elegant place to add it right now. We will be very happy if you have better idea.

Thanks for loving our apps!

**Comment by mingjun97** [comment]
@adlerluiz did a great job at commit 2d4a8f6. Now we have navigate back button just in the right-click popup menu in YTMD now. 🎉

**Comment by adlerluiz** [comment]
![image](https://user-images.githubusercontent.com/2112638/70558342-77922480-1b63-11ea-9c17-f60ca3a6e014.png)
