### ISSUE TITLE
Audio only 

### ISSUE THREAD

**Issue by Justxd22** [ytmdesktop/ytmdesktop#550]
- [ ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ ] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

please add the audio only setting like the android app it will drop memory usage and save your data please consider looking at this feature

**Describe the solution you'd like**

Switch between audio and video only

**Comment by vodkapmp** [comment]
Already requested in issue #46

**Comment by Justxd22** [comment]
yeah i saw it thx
