### ISSUE TITLE
Language setting does not work

### ISSUE THREAD

**Issue by TheHippo** [ytmdesktop/ytmdesktop#552]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**I'm getting German language UI no matter what**
It does not matter which language I chose in the settings.

- Ubuntu is set to English
- My Google Account is set to English
- I do live in Germany

This is literally the only thing in German on my computer.

**To Reproduce**
1. Go to Setting
2. Select any language and restart the app
3. Most of the UI is still in German

**Expected behavior**
Not seeing German all over the place.

**Screenshots**
![Screenshot from 2020-12-30 08-58-32](https://user-images.githubusercontent.com/199056/103338260-1430a880-4a7e-11eb-92cb-1ed60cc42b24.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Linux***
 * OS version: ***X***
 * Arch: ***x64*** (As if this matters, this is just some JS + Electron)
* Installation way: ***Appimage***

**Comment by niknetniko** [comment]
Have you tried the YouTube Music language settings? Those contain a language selector as well. That did it for me:
![image](https://user-images.githubusercontent.com/1756811/103647502-b7406100-4f5b-11eb-89ba-dd69bb370267.png)

**Comment by TheHippo** [comment]
That indeed worked. Still strange, but I got my English.
