### ISSUE TITLE
YTM android app connection problems.

### ISSUE THREAD

**Issue by erdemozor** [ytmdesktop/ytmdesktop#553]
- [ X ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ X ] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
I got frustrated trying to connect YTM android app to my PC.
First It wouldn't connect at all.
Then I allowed YTM desktop through the windows firewall (only as an app.)
The mobile app connected but couldn't display any information about what was playing and the desktop app would get crash errors.
The issue was solved when I went into the advanced settings of windows firewall and manually allowed the port 9863 through.

**Describe the solution you'd like**
Maybe a f.a.q. section would be helpful for connectivity issues I can imagine other people also being frustrated with this.

Maybe a way for the app to allow its ports through automatically? 
I don't know if windows can be forgiving like that.

**Additional context**
Adding port 9863 TCP for Inbound and Outbound rules to windows firewall was enough.
Win 10 pro Version	10.0.19041 Build 19041

p.s. I really like the app. the keyboard shortcuts are a really big thing for me even Spotify's native desktop app doesn't allow for volume adjustment keys that work alt-tabbed. Thanks for the efforts gone into this!

**Comment by erdemozor** [comment]
Just realized this issue (#438) is going through exactly my problem.
"However, I can only play and pause, nothing more is possible." can be solved by allowing those ports through.

**Comment by adlerluiz** [comment]
Thanks for your review, i will create a FAQ to help people who are experiencing these problems

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
