### ISSUE TITLE
Apple silicon support

### ISSUE THREAD

**Issue by phu54321** [ytmdesktop/ytmdesktop#556]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

- App consumes a lot of battery on M1 mac (d/t Rosetta translation of JITed code, of course)
- I tried building app with `yarn`, but due to electron dependency problem `yarn` fails. **Electron should be updated.**

```
@ ~/gitclones/ytmdesktop/ [master*] yarn
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info @nodert-win10/windows.media@0.2.96: The platform "darwin" is incompatible with this module.
info "@nodert-win10/windows.media@0.2.96" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nodert-win10/windows.media.playback@0.2.96: The platform "darwin" is incompatible with this module.
info "@nodert-win10/windows.media.playback@0.2.96" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nodert-win10/windows.storage.streams@0.2.96: The platform "darwin" is incompatible with this module.
info "@nodert-win10/windows.storage.streams@0.2.96" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nodert-win10/windows.foundation@0.2.96: The platform "darwin" is incompatible with this module.
info "@nodert-win10/windows.foundation@0.2.96" is an optional dependency and failed compatibility check. Excluding it from installation.
info abstract-socket@2.1.1: The platform "darwin" is incompatible with this module.
info "abstract-socket@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
warning " > discord-rpc@3.1.3" has incorrect peer dependency "register-scheme@github:devsnek/node-register-scheme".
[4/4] 🔨  Building fresh packages...
[6/6] ⠄ electron
[2/6] ⠄ register-scheme
[3/6] ⠄ bufferutil
[4/6] ⠄ utf-8-validate
error /Users/whyask37/gitclones/ytmdesktop/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/whyask37/gitclones/ytmdesktop/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v10.2.0/electron-v10.2.0-darwin-arm64.zip
    at EventEmitter.<anonymous> (/Users/whyask37/gitclones/ytmdesktop/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:376:20)
    at module.exports (/Users/whyask37/gitclones/ytmdesktop/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/whyask37/gitclones/ytmdesktop/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:483:26)
    at ClientRequest.emit (node:events:388:22)
    at ClientRequest.origin.emit (/Users/whyask37/gitclones/ytmdesktop/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:648:27)
```

**Describe the solution you'd like**

1. **At least update Electron to 11.0.0**, so one who wants to build for M1 mac could compile for themselves. yarn requires `yarn install` before `yarn upgrade`, so dependency couldn't be upgraded within M1 mac itself. I haven't confirmed if Electron is the only problematic dependency, as boostraping crashed at electron.
2. If possible, provide two version of build (Apple silicon, X86-64). Universal binary would be better but I doubt if there's a tool support for that.

**Additional context**

- I'm using macOS Big Sur, 11.1 on MBP 13' M1 (8gb)

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

M1 / ARM support should be now included in the latest release.
Due to some issues with GitHub Actions we can't fully build them from the automatic process just yet 🤞
but they can still be built
