### ISSUE TITLE
Something wrong with the "Downloader" plugin on Win10

### ISSUE THREAD

**Issue by 4thrun** [ytmdesktop/ytmdesktop#558]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The "Downloader" plugin doesn't work on Win10. 

**To Reproduce**
1. Click the three-dot button
2. Click the "Download" button in the list
3. See error. "No video id found: (the official url)" comes first. Then "Error: connect ETIMEDOUT".

**Expected behavior**
select the path for downloads. Then download.

**Screenshots**
![2](https://user-images.githubusercontent.com/65476356/103479075-fceb1580-4e05-11eb-9851-745f75b968a2.JPG)

**Environment**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***20H2***
 * Arch: ***x64*** 
* Installation way: ***.exe***

**Comment by Dedigraz** [comment]
It seems as if you have the wrong app.
You are using youtube music by th-ch

**Comment by 4thrun** [comment]
> It seems as if you have the wrong app.
> You are using youtube music by th-ch

Stupid me. I was trying quite a few third-party apps for yt music and I mistook that by th-ch for this one. And finally I would like to use this one in the long run.
