### ISSUE TITLE
Bug: Settings won't save after closing the settings window

### ISSUE THREAD

**Issue by ariestai** [ytmdesktop/ytmdesktop#57]
![image](https://user-images.githubusercontent.com/56472203/67155152-08a30700-f33c-11e9-8903-2b06485ca991.png)

So this is the setting menu.
No matter which setting I change (page zoom here, for example. Also, the sign-in button can't show up and I need to zoom off the page to show it.) When I drag the slider to 80 and then close the settings window, nothing happens.

**Comment by adlerluiz** [comment]
Hello @ariestai are you using windows, mac or linux?

**Comment by ariestai** [comment]
Windows v1903

**Comment by mingjun97** [comment]
Does this bugs occur in the latest release?

**Comment by rickinbsb** [comment]
I'm closing this per the settings page rework, please reopen this issue if the error happens to you on 1.6
