### ISSUE TITLE
Add support for ARM platforms - arm64 and armhf

### ISSUE THREAD

**Issue by aharish** [ytmdesktop/ytmdesktop#572]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
The feature request is not related to a problem I am facing yet. I am coming from the standpoint of where the humble ARM architecture is now gaining a lot of support, especially with the launch of the M1 Macs. I own a few Raspberry Pi devices and I would like to run this project on these machines. Since the project only offers support for `amd64` on the Snapstore, I thought I could pitch in by helping build a suitable version for both `aarch64/arm64` and `armv7l/armhf`

**Describe the solution you'd like**
A native build on ARM machines that will help package the application for the `aarch64/arm64` and `armv7l/armhf` platforms. I am okay with building these on my Pis and submitting it to the project maintainers so that it can be made available as a`.deb` in the releases page, and as a package for Snap. I will build this over the weekend on my Pi. Please let me know how I can proceed further.

**Describe alternatives you've considered**
Alternatives can also be someone from the team who has a Pi or another ARM powered device that can build suitable versions on the Pi

**Additional context**
None

**Comment by mingjun97** [comment]
Thanks for contributing! It would be very nice if you could build a distribution version for us on arm platform. :)

I currently held an Apple Silicon Mac. But the build tool we are using ([electron-builder](https://github.com/electron-userland/electron-builder)) doesn't have a released version for build an arm64 bundle for macOS. (Though they have [prerelease version](https://github.com/electron-userland/electron-builder/releases/tag/v22.10.4), I still have some problem building :( ). 

Cheers!

**Comment by aharish** [comment]
Thank you! I will build it over the week and send across a `.deb` package for both the architectures.

**Comment by aharish** [comment]
@DIYglenn hey there! I did try building it back in January, but there were underlying issues with some of the dependencies this project relies on not being available for ARM, so all the builds failed. I will try to look over this since support seems to have somewhat improved in the last couple of months and let you know.

**Comment by AaronCompNetSys** [comment]
I would also love to run this app on my RPi

**Comment by gnomeria** [comment]
I think some of the problems could also refer to the latest k8s lens successful electron upgrade and arm support
https://github.com/lensapp/lens/issues/1756

**Comment by baozitao** [comment]
Is there any progress on arm version?

**Comment by Alipoodle** [comment]
No progress has been made on this.
A few discussions regarding it have gone on in the discord, however without any of our Developers having a M1 Mac/Arm system we cannot know that we have successfully built for the platform.

A PR Request is greatly appreciated, likely needing a new electron-builder file.

**Comment by kylemart** [comment]
Thanks for the update @Alipoodle. I have an M1 MacBook, so I might be able to look into this. Have a Discord server invite link?

**Comment by Alipoodle** [comment]
check the first badge on the README of the project 😁

**Comment by Alipoodle** [comment]
Added. Currently the CI might not work fully, but waiting on GitHub to give access to this.
