### ISSUE TITLE
Music wouldn't play...

### ISSUE THREAD

**Issue by 4ronse** [ytmdesktop/ytmdesktop#575]
- [ x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x ]  I verified that there is no open issue for the same subject.

**Describe the bug**
I can't listen to music because the get_video_info request gets blocked because of CORS

**To Reproduce**
I've installed the "Allow CORS: Allow-Control-Allow-Origin" extension on chrome, now YTM works on chrome.

**Screenshots**
![image](https://user-images.githubusercontent.com/24609051/104451917-e766b000-55aa-11eb-8e79-70e060e1fc62.png)
![image](https://user-images.githubusercontent.com/24609051/104451963-f8172600-55aa-11eb-9d06-210159544ba4.png)
(We'll kindly ignore the adblocker)
**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***20H2 (OS Build 19042.685)***
 * Arch: ***x64***
* Installation way: ***from website***

**Comment by adlerluiz** [comment]
do you use any vpn?

**Comment by 4ronse** [comment]
> do you use any vpn?

Nope...

**Comment by Alipoodle** [comment]
Does this issue still occur?
CORS issue shouldn't be something that we touch in any way. 😅
So this seems like something else is getting in the way.

_No response within a week and I'll assume that this issue is solved_

**Comment by Alipoodle** [comment]
Closing as no response (should have been done a while ago)
