### ISSUE TITLE
Google Podcasts integration

### ISSUE THREAD

**Issue by Leomm04** [ytmdesktop/ytmdesktop#580]
- [ x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x ] I verified that there is no open issue for the same subject.

Hi,
It'd be cool if you could add a Google Podcasts button into YTMDesktop, so that it opens in the same window.

**Comment by autoferrit** [comment]
As a user of both, would love this.

**Comment by Alipoodle** [comment]
Google Podcast is dead.
YTM now should have native support
