### ISSUE TITLE
Streamline login and feedback for last.fm authorisation

### ISSUE THREAD

**Issue by IndefiniteBen** [ytmdesktop/ytmdesktop#584]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
I have had problems with getting last.fm integration working on multiple Windows PCs now. I input my username and password, click "save and authorise", click "allow connection" on the pop-up window, then I'm left with all these windows on top of one another so I close them, but then it's not scrobbling music. There's no errors and everything appeared to work but it doesn't work.

**Describe the solution you'd like**
1. I'd like to not need to input my password and username into the "save and authorise", especially considering I need to enter those details again in the pop-up web browser. [GPMDP](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-) didn't require you to input your username and password and just opened a page in your default browser to authorise the connection.
2. Some kind of error indication if some part of the connection is broken.
3. Auto-close the browser?
4. Auto-close the "save and authorise" window after you successfully approve the connection in the browser pop-up (or a message that you can close it now) 
5. If I've already authorised the connection to ytmdesktop in last.fm, don't show the pop-up to "allow connection" when I can see the connection in last.fm settings. This might not be possible, but it'd be nice.

**Describe alternatives you've considered**
Just use YTM in the browser and an extension for scrobbling.

**Additional context**
I still haven't figured out a reliable workaround as evidenced by my comments on #356 
Just do a bunch of turning on and off, reauthorising and trying to authorise without password, restarting the app etc. until it works. I don't know what actually caused it to be fixed, which is part of my annoyance.

**Comment by melindachang** [comment]
Currently having the same problem, haven't managed to find a fix either

**Comment by melindachang** [comment]
I've got the same issue, haven't gotten it to work, either

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

Last.Fm has entirely been re-worked in this latest update with a smoother flow.
Some changes are still needed to be made to display that you have authenticated once completed. This will only show AFTER you first play a song / restart the app.
