### ISSUE TITLE
Player controls disappear when playback of certain songs begins

### ISSUE THREAD

**Issue by rosspayn3** [ytmdesktop/ytmdesktop#586]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The controls at the bottom of the window disappear when playback of certain songs begins. Issue occurs whether the window is maximized or not. Does not occur in the album art / up next / lyrics view. Does not occur when playing the song previous to the problem song, then clicking the 'next song' button to begin playback of the problem song. Happened to me with multiple songs before I recorded a video.

**To Reproduce**
1. Open a playlist
2. Click the album art icon of the song to begin playback (https://music.youtube.com/watch?v=h7qNDb8M5hw is one example. there were others but I didn't note which songs until the issue happened multiple times)
3. Controls disappear until another song is played.

**Expected behavior**
Controls should remain visible after playback begins.

**Screenshots**
Video of issue (at 0:40): https://www.youtube.com/watch?v=4yJ2UAK9ygc

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows 10*** 
 * OS version: ***20H2 build 19042.746***
 * Arch: ***x64***
* Installation way: ***.exe***

Windows Specifications from settings:
* Edition: ***Windows 10 Pro***
* Version: ***20H2***
* Installed on: ‎***7/‎29/‎2020***
* OS build: ***19042.746***
* Experience: ***Windows Feature Experience Pack 120.2212.551.0***

**Comment by rosspayn3** [comment]
This may actually be an issue with YouTube Music itself. This happens on the music.youtube.com player as well.

**Comment by adlerluiz** [comment]
as @rosspayn3 said, this is unfortunately a problem on youtube music = (
