### ISSUE TITLE
Feature Request : Add WebNowPlaying support for Rainmeter

### ISSUE THREAD

**Issue by AbyadhX** [ytmdesktop/ytmdesktop#59]
I think it would be great if you add this feature in next versions.
WebNowPlaying is used by using a BrowserExtension, and it can be added to the official Spotify Player using Spicetify, so I think it will be usefull if you add it.
Thank you

Links : 
https://github.com/tjhrulz/WebNowPlaying

https://github.com/tjhrulz/WebNowPlaying-BrowserExtension
https://github.com/khanhas/spicetify-cli/blob/master/Extensions/webnowplaying.js

**Comment by adlerluiz** [comment]
@AbyadhX thanks for the suggestion, we are analyzing and prioritizing, but it will enter the development roadmap
