### ISSUE TITLE
Javascript error in the main process on Shutdown button

### ISSUE THREAD

**Issue by kudlav** [ytmdesktop/ytmdesktop#593]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
After shutting down App an error dialog appears, see first screenshot. When accepting dialog using OK, another dialog appears. When pressing OK on the second dialog, it brings the second dialog back in infinite loop, so only task manager can kill this app.

**To Reproduce**
1. Open YTM v1.14.0
2. Press _Shutdown_ button
3. Error occures

**Expected behavior**
App should close.

**Screenshots**
1.
![obrazek](https://user-images.githubusercontent.com/11516259/105819595-a9a95480-5fb8-11eb-9d3b-bbe66f71b233.png)
2.
![obrazek](https://user-images.githubusercontent.com/11516259/105819792-effeb380-5fb8-11eb-8922-afeea7134a91.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.14.0***
 * OS: ***Windows***
 * OS version: ***Windows 10 20H2 (19042.746)***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by mingjun97** [comment]
Sadly, I cannot address which lines of code cause this problem. The shutdown button works well on my Mac. Anyone can investigate this?

**Comment by flleeppyy** [comment]
I'll see what I can do about it

**Comment by flleeppyy** [comment]
the shutdown button works fine on MacOS and Linux, but not windows.
I'll work on figuring out that issue. Its probably just calling something electron doesnt support on windows

**Comment by flleeppyy** [comment]
Found the culprit 
https://github.com/ytmdesktop/ytmdesktop/blob/c50eee3526591773ca6c1ac0f66d355e5557dee9/main.js#L324

**Comment by kudlav** [comment]
Hi @flleeppyy, so are you able to use the button on macOS?
I have YouTube Music Desktop App 1.14.0 and macOS 11.2.1 (20D74) and the shutdown button doesn't work.

1. open the app
2. hit the shutdown button -> nothing happened
4. hit the settings button -> nothing happened
5. try to close the app window using red X or `cmd+W`
6. following error occures every time I hit close window or press `cmd+W`, so I have to quit the app using `cmd+Q`

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'hide' of null
at BrowserWindow.<anonymous> (/Applications/YouTube Music.app/Contents/Resources/app.asar/main.js:674:28)
at BrowserWindow.emit (events.js:315:20)
```

**Comment by flleeppyy** [comment]
Hmm... it seems to vary from computer to computer...
I don't have a Mac nor do I have a MacOS VM so I couldn't test this

**Comment by FrankieGuns** [comment]
I'm experiencing this issue currently, could someone help me with it? I don't know what to do even by reading the ways you've done it.
![Help](https://user-images.githubusercontent.com/25517845/165411861-bb142632-46ef-4e7c-bbe4-701b179d4c10.png)

**Comment by kudlav** [comment]
Hi, just downgrade to v1.13.0. Nightly version is very unstable. Or don't use features that are broken - don't use this button 🙂

**Comment by Alipoodle** [comment]
1.14.1 has a check for Windows which removes this button for now 😄 
The PR 776 is intended to fix this for Windows and improve Quitting correctly but not checked it out yet.

@FrankieGuns Can you check if you have the Last.FM feature on, but not signed in correctly.
This is typically the reason for this Issue for happening.
