### ISSUE TITLE
macOS: App should not quit when closing window with CMD+W

### ISSUE THREAD

**Issue by eaigner** [ytmdesktop/ytmdesktop#595]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**

Closing a window should not cause the app to quit on macOS, just dismiss the UI.

**To Reproduce**

- Open app
- Hit <kdb>CMD+W</kbd>

**Expected behavior**

The window should close, but the app should keep running and the window should reopen when the dock icon is clicked.

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.14.0***
 * OS: ***Mac***
 * OS version: ***11.1 (20C69)***
 * Arch: ***x86***
* Installation way: ***DMG***

**Comment by mingjun97** [comment]
Looks like you didn't check the [Keep YTMDesktop on background when window close].

Navigate to [Settings] -> [General], then check [Keep YTMDesktop on background...] should solve this issue.

Let me know if this got fixed by configuring properly.

Thanks!

**Comment by eaigner** [comment]
Oh that's what that means. I would recommend to remove this setting, make the `ON` state default on macOS, as this is how all mac apps usually behave.

In any case, renaming it to "Keep application running when closing window" would also clarify that a bit.
