### ISSUE TITLE
Mini-player causing high network usage

### ISSUE THREAD

**Issue by zeroone80** [ytmdesktop/ytmdesktop#599]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

 **Describe the bug**
When I switch to mini-player the network usage of YTM Desktop App jumps up to 1.5 Mbps and then hovers around, sometimes it fluctuates between 1.0 Mbps to 3.5 Mbps even when nothing is playing. As soon as I come out of mini-player, the network usage drops down again.

This is a huge problem as it is sucking down a huge portion of my data cap every month now that Comcast is putting data caps in place.

 **To Reproduce**
Switch YTM Desktop App to mini-player

 **Expected behavior**
I expect the network usage to not change between the regular player and the mini-player, especially when nothing is playing

 **Screenshots**

![Mini-player - nothing currently playing](https://user-images.githubusercontent.com/46075580/106292900-626ece00-621b-11eb-97c3-60672d24d3e6.jpg)
![Regular player - nothing currently playing](https://user-images.githubusercontent.com/46075580/106292904-63076480-621b-11eb-9e1b-30d03f1e0c5d.jpg)

 **Environment:**
 * YTMDesktop version: v1.13.0
 * OS: Windows 10 Pro
 * OS version: 19042.746
 * Arch: 64-bit
 * Installation way: Installed from .exe

**Comment by cw1998** [comment]
This also occurs on Linux. Paused music with the miniplayer open will continue to keep network utilisation around 150KiB/s.

![image](https://user-images.githubusercontent.com/1470412/111993658-c7092380-8b0e-11eb-8342-9ba9342e6f45.png)

`iftop` confirms that the traffic is coming from a Google service.

![image](https://user-images.githubusercontent.com/1470412/111993790-f029b400-8b0e-11eb-9de3-7bca3fea49bf.png)

**Comment by Gizmokid2005** [comment]
I ran into this as well.

This *ONLY* happens if you have the "Paint colors with album color" option enabled. Network usage is normal without this option. So the bug must be in that part of the code.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
