### ISSUE TITLE
Feature Request: Windows 10 Volume menu integration

### ISSUE THREAD

**Issue by SynneK1337** [ytmdesktop/ytmdesktop#61]
I found this feature really useful in web version of YT Music.

![image](https://user-images.githubusercontent.com/26191968/68486539-8e321c80-0241-11ea-8d3a-9458ee0ff0d7.png)

**Comment by adlerluiz** [comment]
@SynneK1337 thanks for your suggestion, will enter the development roadmap.

**Comment by rensatsu** [comment]
It would be better if this integration will be optional. This popup takes a lot of space and messes with input.

**Comment by mcao** [comment]
Hello, is there any ETA on implementing this? I am currently using the miniplayer, but it seems to be slow to change the song, oftentimes having several seconds lag.

**Comment by adlerluiz** [comment]
I'm on It now, ETA 1 month

**Comment by adlerluiz** [comment]
Finally - https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.0-rc1/YouTube-Music-Desktop-App-Setup-1.12.0-rc1.exe
![image](https://user-images.githubusercontent.com/2112638/89146218-77e39380-d529-11ea-81e7-4fae16e0d50b.png)

**Comment by rickinbsb** [comment]
Implemented on v1.12, thank you!
