### ISSUE TITLE
the window for the app not showing

### ISSUE THREAD

**Issue by rado92** [ytmdesktop/ytmdesktop#610]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
after installing and running the app the music will auto play and the app will show in the system tray/taskbar but the window will not appear on my monitor. clicking the app on the taskbar will show me the minimize animation and the app will seemingly minimize from off screen. i tried windows 10 "cascade windows" feature and i tried shift+right click the app on taskbar to move it but neither worked. 
right clicking the system tray icon and using the miniplayer will work and i can also access the settings using this method but not the app itself

**To Reproduce**
1- download
2- install
3- run app

**Expected behavior**
when running the app i expect it to show a window with the app UI

**Screenshots**

**Environment (please complete the following information):**
 * YTMDesktop version: 1.13 and 1.14
 * OS: Windows 10
 * OS version: windows 10 build: 19042.789
 * Arch: ***x64***
* Installation way: .exe

**Comment by tomscott50** [comment]
I have the same issue except I can't access the settings window from the task bar, but it is on my start menu when opened, nested with the app. I've downloaded 1.14 but not installed it yet as 1.13 does still work just about - if I press play on my keyboard media buttons it plays something from my recent plays.

**Environment (please complete the following information):**

YTMDesktop version: 1.13
OS: Windows 10 Pro
OS version: windows 10 build: 19041.746
Arch: x64
Installation way: .exe

**Comment by sunian** [comment]
I was having this issue too for months. I just figured out a fix. Go to
`C:\Users\YOUR_NAME\AppData\Roaming\youtube-music-desktop-app`
and delete that entire "youtube-music-desktop-app" folder, and now relaunch the app. This essentially clears out all saved data, so you'll need to log in again. Hope that works for you too.
