### ISSUE TITLE
Layout is broken for certain width

### ISSUE THREAD

**Issue by kudlav** [ytmdesktop/ytmdesktop#615]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
When resizing the window the layout became broken for some width. And even when the layout looks fine it can break after restarting the app.

**To Reproduce**
1. Change width of window

**Expected behavior**
UI like music.youtube.com

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/11516259/107494862-9806a600-6b8f-11eb-9ffe-804568787b39.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.14.0***
 * OS: ***Windows***
 * OS version: ***20H2 19042.746***
 * Arch: ***x64***
* Installation way: ***.exe***

simillar to: https://github.com/ytmdesktop/ytmdesktop/issues/548

**Comment by Alipoodle** [comment]
[Video - Unable to reproduce](https://puu.sh/Hfor1/293a98b0f4.mp4)
Are you able to potentially provide a few more steps for this, as simply "change width of Window" isn't really enough to be able to reproduce this issue?

**Comment by kudlav** [comment]
Ok, then set width to 1438 px and quit the app. Launch the app and it should be broken.

**Comment by kudlav** [comment]
Or stop at 1170 px and it will break the app immediately

**Comment by Alipoodle** [comment]
After doing some investigation with this, this issue effects YouTube Music as a whole, and can be reproduced on the Web Browser.
Due to this, I feel that this is not an issue best suited for YouTube Music rather than here.

**Comment by kudlav** [comment]
Hi, you are right. Sorry, I am closing this issue. And unfortunately there is no way ho to report it to Google so there is nothing to do.
