### ISSUE TITLE
"A JavaScript error occurred in the main process" when next song plays

### ISSUE THREAD

**Issue by felisep** [ytmdesktop/ytmdesktop#617]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
When the next song plays a pop window from YouTube Music Desktop appears showing:

Uncaught Exception:
Error: Failed to serialize arguments
at WebContents._.send (electron/js2c/browser_init.js:157:2252)
at sendMsg (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/node_modules/electron-native-notification/index.js:49:46)
at BrowserWindow.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/node_modules/electron-native-notification/index.js:55:40)
at BrowserWindow.emit (events.js:322:22)

The song does not get interrupted, nor does it stop. The error just pops up. 

**To Reproduce**
1. Open YouTube Music Desktop App
2. Play a song
3. Wait until the song is about end and the next song is about to start
4. When next song starts to play see error A JavaScript error occurred in the main process

**Expected behaviour**
A warning should not pop up.

**Screenshots**
<img width="245" alt="Screenshot 2021-02-11 at 11 00 19" src="https://user-images.githubusercontent.com/32464471/107624615-71ae3c80-6c5b-11eb-82c7-b876c6494abe.png">
![Screenshot 2021-02-11 at 11 16 24](https://user-images.githubusercontent.com/32464471/107624624-74109680-6c5b-11eb-9ac7-1ec9cecd067b.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: Macbook pro 2019
 * OS version: ***11.2.1***
 * Arch: ***x64***
* Installation way: ***x86 dmg-From the [website](https://ytmdesktop.app)***

**Comment by zware** [comment]
This is a duplicate of #516.

**Comment by felisep** [comment]
@zware Thanks! I didn't find it. I'll close this then
