### ISSUE TITLE
When trying to install the 1.13.0 Windows version I get stuck on an infinite installation screen. 

### ISSUE THREAD

**Issue by Gongfin** [ytmdesktop/ytmdesktop#619]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
I recently had to System Restore Windows 10, and this ended up uninstalling my current version of YTMDesktop. I decided to reinstall, but when I run the installer, the bar gets about 1/3 of the way through and freezes. I have let it sit for quite a while now, and tried restarting it multiple times. No error report, and I'm not sure where the log/install location is so I can't check that. I'm not sure if it is a system specific issue although I don't see why it would be since I had it correctly installed pre System Restore. Are there files in the install location that I could delete to fix it? Any help is appreciated. 

**To Reproduce**
1. Go to https://ytmdesktop.app/
2. Click on Download
3. Go to Downloads folder. 
4. Click on YouTube-Music-Desktop-App-Setup-1.13.0.exe
5. Installation progress bar freezes 1/3 of the way through.

**Expected behavior**
In the past version the progress bar went all the way through and completed the setup. 

**Screenshots**
![Progress Bar](https://user-images.githubusercontent.com/79015828/107855042-21b3af00-6dee-11eb-9a97-a2985c833f2b.PNG)
![System and OS specs](https://user-images.githubusercontent.com/79015828/107855332-92a79680-6def-11eb-9ab7-8032c1a226b0.PNG)
LINK TO VIDEO: https://www.youtube.com/watch?v=9NewtbefKR8&feature=youtu.be

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows*** 
   * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by mingjun97** [comment]
How about using [this one](https://github.com/ytmdesktop/ytmdesktop/releases/tag/v1.14.0)?

**Comment by Gongfin** [comment]
Ah it seems that one works. Perhaps I was on 1.12.0 before the system restore or something.

**Comment by mingjun97** [comment]
Cool. Thanks for your feedback!
