### ISSUE TITLE
Privacy and Security

### ISSUE THREAD

**Issue by Transkohmer** [ytmdesktop/ytmdesktop#62]
Hi, would this software/app steal/misuse our youtube account password/information? in terms of privacy and security, im worried. TQ

![1](https://user-images.githubusercontent.com/58098813/69473503-e8111580-0def-11ea-855d-a3a26319431e.JPG)

**Comment by adlerluiz** [comment]
Hello @Transkohmer 

The app just opens a new window with youtube music, it does not capture any information from your account, all code is available on github, you can use it without fear =)

**Comment by indeed-a-genius** [comment]
The Google login page opens inside the app though, so the Google login page could easily be imitated in order to capture user's password.
Not saying it does that, but the current method might scare some users off.

**Comment by Alipoodle** [comment]
> The Google login page opens inside the app though, so the Google login page could easily be imitated in order to capture user's password. Not saying it does that, but the current method might scare some users off.

While this is old. This method is not possible due to being a OFFICIAL Google product and needing permissions not possible via the standard OAuth methods.
