### ISSUE TITLE
A better shuffler

### ISSUE THREAD

**Issue by TotallyNotInUse** [ytmdesktop/ytmdesktop#627]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

Is it possible to add a custom shuffler? The one that comes with YT is awful and I always end up listening to the same 20 songs in my 200+ song playlist.

**Comment by christophrus** [comment]
For me the Youtube AI shuffler is fine, please do not replace it. Maybe add an option for a local shuffler for people that do not like the AI shuffler by Youtube.

**Comment by Alipoodle** [comment]
I'm deeming this issue as simply to far fetched for what is possible with what Access we have to YTM.
