### ISSUE TITLE
Properties names inside settings.

### ISSUE THREAD

**Issue by SynneK1337** [ytmdesktop/ytmdesktop#63]
![image](https://user-images.githubusercontent.com/26191968/69545100-635dfd00-0f91-11ea-94fd-b2e0678c162e.png)

Issue exists since v1.5.1

**Comment by adlerluiz** [comment]
@SynneK1337 which operating system do you use?

**Comment by SynneK1337** [comment]
Windows 10 19030.1 (Insider, fast ring). Issue did not exist on YTMD v1.5.0

**Comment by adlerluiz** [comment]
The new release https://github.com/ytmdesktop/ytmdesktop/releases/tag/v1.5.2 has fixed it
