### ISSUE TITLE
Is there any way to stop video playback and music only

### ISSUE THREAD

**Issue by Psycho2999** [ytmdesktop/ytmdesktop#632]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**

 **To Reproduce**
 3. See error

 **Expected behavior**

 **Screenshots**

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.19042***
 * Arch: ***x64***
 * Installation way: ***like .exe or snapcraft or another way***

**Comment by flleeppyy** [comment]
Duplicate of #46
