### ISSUE TITLE
No revert to default option?

### ISSUE THREAD

**Issue by landon1013** [ytmdesktop/ytmdesktop#640]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

 **Describe the bug**
After attempting to change the keyboard shortcut for thumbs up it just shows 'Meta' instead of the keys I pressed, apparently it can't read the CMD key? So now I have no way to thumbs up a song with my keyboard because there is no option to revert back to defaults.

 **To Reproduce**
 1. Go to 'Keyboard Shortcuts'
 2. Click on 'any option to change the keys and attempt to set up CMD + Shift + W'
 3. See Error

 **Expected behavior**
I expected to be able to set any combination of keys to a shortcut including the one that was set by default 'CMD + Shift + L'

 **Screenshots**

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***macOS Catalina***
 * OS version: ***10.15.7***
 * Arch: ***x64***
 * Installation way: ***like .dmg or snapcraft or another way***

**Comment by Alipoodle** [comment]
Closing due to no response in a month.
