### ISSUE TITLE
App doesn't load upon opening.

### ISSUE THREAD

**Issue by jugxd** [ytmdesktop/ytmdesktop#642]
- [V] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [V] I verified that there is no open issue for the same subject.

**Describe the bug**
On startup, my app does open but it doesn't seem to be loaded. If clicked on the app, the app doesn't appear aka it stays minimized.

I had reinstalled the app, same thing happens.

**To Reproduce**
1. Start Application

**Expected behavior**
To be shown like this
![main_5](https://user-images.githubusercontent.com/66807402/109320052-8ceb8f80-788a-11eb-9ad9-deafa55a8082.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/66807402/109319673-1353a180-788a-11eb-8820-179537b501f8.png)

**Environment (please complete the following information):**
 * YTMDesktop version: YTMDesktop version: 1.13.0
 * OS: Windows
 * OS version: 10
 * Arch: x64
* Installation way: Install from "YouTube-Music-Desktop-App-1.13.0.dmg" available on homepage

**Comment by PancakeIdentity** [comment]
I've having the same issue.

**Comment by Alipoodle** [comment]
Little confused you used a Mac DMG to install on a windows machine.
But I cannot 100% verify that this is the issue and the fix should be:

# Steps
Could you go to `%appdata%/youtube-music-desktop-app` and open the `config.json` file

And look for the following values:
```json
    "window-position": {
        "x": -8,
        "y": -8
    },
    "window-maximized": false,
    "window-size": {
        "width": 960,
        "height": 1040
    },
```

Change the X & Y Values to something like above.
This should set the window in the middle of the main display at a decent size.

_No response within a Week and I'll assume that this issue has been solved or no longer happening_
