### ISSUE TITLE
Disable mouse wheel volume control

### ISSUE THREAD

**Issue by godey4me** [ytmdesktop/ytmdesktop#644]
Could you add an option to disable mouse wheel volume control when in miniplayer mode?

I know it is convenient to use the mouse wheel to control the volume, but it gets annoying sometimes when in minplayer mode on top and i'm scrolling on a webpage only to have the music volume change or muted.
Thanks

**Comment by flleeppyy** [comment]
thanks github actions for closing an informative issue


I do agree with you though. I'll see if I can add that as an option in my fork then make a pull request.
