### ISSUE TITLE
Allow high audio quality

### ISSUE THREAD

**Issue by fadeltd** [ytmdesktop/ytmdesktop#647]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
On music.youtube.com, I found that there's a setting that allows me to play youtube music with High Audio Quality Playback
I can't find this on the app setting  (I use the Mac desktop app)

**Describe the solution you'd like**
I'd like to be able to set the audio quality to high from the app setting

**Describe alternatives you've considered**
Well, I can still be able to modify them by clicking on my avatar > Settings, it's just that it wasn't integrated on app settings, and I find it easier to be able to modify them through the app settings

**Additional context**

![high](https://user-images.githubusercontent.com/4526413/109607651-2355d480-7b5b-11eb-9db0-1e1590ee3ca3.png)
<img width="888" alt="playback setting" src="https://user-images.githubusercontent.com/4526413/109607766-50a28280-7b5b-11eb-86fa-1bedbebee618.png">

**Comment by Niruzoid** [comment]
yo, umm there is a different settings for that, that is actually app settings but if u click ur pfp then go to settings there is a playback tab there, that is the write one. The one u clicked is added for settings of YTMDesktop

**Comment by Alipoodle** [comment]
> Well, **I can still be able to modify them by clicking on my avatar > Settings**, it's just that it wasn't integrated on app settings, and I find it easier to be able to modify them through the app settings

They did say they are know it's from the Avtar -> Settings, however they want it to be added into the YTMD Settings

--------

If it's already a YouTube Music setting I do feel that there's not really much point into Integrating it into the YTMD Settings menu as well 😕. It's something that exists and functions perfectly already no need to complicate it. Those settings in there are meant to really be a set one time, ignore and not bother about them.

**Comment by fadeltd** [comment]
> > Well, **I can still be able to modify them by clicking on my avatar > Settings**, it's just that it wasn't integrated on app settings, and I find it easier to be able to modify them through the app settings
> 
> They did say they are know it's from the Avtar -> Settings, however they want it to be added into the YTMD Settings
> 
> If it's already a YouTube Music setting I do feel that there's not really much point into Integrating it into the YTMD Settings menu as well 😕. It's something that exists and functions perfectly already no need to complicate it. Those settings in there are meant to really be a set one time, ignore and not bother about them.

Alright then, closing this
