### ISSUE TITLE
Keyboard shortcuts break or stop working 

### ISSUE THREAD

**Issue by Dave-Bb** [ytmdesktop/ytmdesktop#649]
- [ X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ ] I verified that there is no open issue for the same subject.

**Describe the bug**
Sometimes the keyboard binded short cuts will just stop working. In my case, I have 5 short cuts 
- Ctrl + LShift + Space -> Pause/Play
- Ctrl + Right -> Next 
- Ctrl + Left -> Previous 
- Ctrl + Up -> Thumbs up 
- Ctrl + Down -> Thumbs down 

So far, about 4 or 5 times this has happened to me. Each time, when I go to the settings, I am still able to see my short cut bindings, however, I will need to "re do them" in order to get them to work again. 

**To Reproduce**
1. Set up some keyboard short cuts (I have some that involve 2 button presses)
2.  Use the app for a while, and the short cuts

**Expected behavior**
When you set a short cut for a given operation, then it is bound for ever and it always works (with in reason) But if the app is in focus at a minimum, they should always work 

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: 1.13.0
 * OS: Windows 10 
 * OS version: 1909
 * Arch: x86
* Installation way:  just the link from the main site

**Comment by janacm** [comment]
Same issue on Mac

**Comment by agzam** [comment]
Same thing in GPMDP. This is another BS strategy of Google to force people to use the Web App.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3920

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
