### ISSUE TITLE
Bug - When picking the miniplayer option from the right-clicking menu of the now playing album art in the queued view.

### ISSUE THREAD

**Issue by baltazarqc** [ytmdesktop/ytmdesktop#650]
- [✓] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [✓] I verified that there is no open issue for the same subject.

When right-clicking on the Album Art for the song playing, I have three options offered:
![image](https://user-images.githubusercontent.com/5393816/110269129-0a9d5280-7f91-11eb-9b72-2e54c1dafb1b.png)

When clicking the middle option (the mini-player option), I have a javascript alert popup:
![image](https://user-images.githubusercontent.com/5393816/110269271-5bad4680-7f91-11eb-9cdb-485618f18e80.png)

 1. Go to 'Queue View Mode' (clicking on the bottom command bar)
 2. Right-click on 'Album Art'
 3. See the error above

 **Expected behavior**
Not sure what it was, as I was testing the new software. I guess it shall open the mini-viewer.

 **Screenshots**
_See them above in the description._

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.19042***
 * Arch: ***x64***
 * Installation way: downloaded from the official website: YouTube-Music-Desktop-App-Setup-1.13.0.exe

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
