### ISSUE TITLE
YTM Remote (BETA) play/pause button not working

### ISSUE THREAD

**Issue by akwebb1** [ytmdesktop/ytmdesktop#653]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

The Android YTM Remote connects fine and everything works except for the Play/Pause button.  It does nothing when you press it.  All other buttons and functionality in the remote app work as expected.

 * YTMDesktop version: v1.13.0 (development branch)
 * OS: Windows
 * OS version: 20H2 build 19042.804
 * Arch: x64
* Installation way: local build of development branch (up to date with no local modifications).
* Remote Version: Latest from Play store

**Comment by kudlav** [comment]
Same here.

Using YTMDesktop v1.14.0
Samsung Galaxy A40 SM-A405FN

**Comment by kudlav** [comment]
Ok, I am able to play music previously paused via computer, but still unable to pause playing music

**Comment by akwebb1** [comment]
I was able to get it working by commenting out the isPaused check in the execCmd function (companionServer.js line 381) for the 'track-play' case.  For some reason it is not detecting the pause state correctly with the css query.  So, this is not fix but a workaround for now.
