### ISSUE TITLE
Send socket events on change instead only on tick (500ms)

### ISSUE THREAD

**Issue by XeroxDev** [ytmdesktop/ytmdesktop#661]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Kind of. I'm the developer of the [YTMD-Stream Deck Plugin](https://github.com/XeroxDev/YTMD-StreamDeck) and I have reached a limit which is a bit annoying.

It happens that the values are incorrectly overwritten and this leads to the following example:
Current volume 50%
Events: tick, tick, user -10, user -10, tick, tick
Volume: 50, 50, 40, 30, 40, 30, 30, 30

Real data: 70%, 60%, 50%, 60%, 50%, 40%, 30%, 60%, 50%, 40%, 50%, 40%, 30% (while "rapidly" lowering and only lowering the volume **not** rising it).

**Describe the solution you'd like**
My plugin communicates with the server via sockets and I think it should be built in so that if something changes (e.g. the volume), this should also be sent back directly to the subscribed sockets. Currently it is only every 500ms over the "tick" event. That would fix the problem I described above, because I don't have to "compete" with the server on the volume.

**Describe alternatives you've considered**
I tried to solve it from my side by overwriting each other, but this leads to the known problem. I also tried to solve it with a complex caching mechanism - no success either. So my suggestions would be:
- Add another "change" event that will be executed as soon as something changes.
- Add specific events (e.g. volumeChange, timeChanged, etc.).
- Send the "tick" event again with each change.

And this feature / event also provides automatically a "success" message / callback.

**Additional context**
If more information is required, please let me know.

**Comment by Venipa** [comment]
its fine, use rxjs or a alternative for your use.
once you are using rxjs you can make an observable from the event and debounceTime(1000) so it will wait until 1000ms has been passed.

**Comment by XeroxDev** [comment]
I already use rxjs, but this wouldn't fix my problem...

**Comment by Venipa** [comment]
> I already use rxjs, but this wouldn't fix my problem... I need a near live experience for this.

add distinctUntilChanged?

**Comment by XeroxDev** [comment]
I use also distinctUntilChanged
```
.pipe(distinctUntilChanged(), takeUntil(this.destroy$))
```

But I repeat, this is not my problem.

**Comment by Venipa** [comment]
> I use also distinctUntilChanged
> 
> ```
> .pipe(distinctUntilChanged(), takeUntil(this.destroy$))
> ```
> 
> But I repeat, this is not my problem.
> 
> My problems are all highlighted values:
> 
> Real data: 70%, 60%, 50%, **60%**, 50%, 40%, 30%, **60%, 50%, 40%, 50%, 40%, 30%**

ah, i see what you mean. 
ye we probably could add a queue worker which handles the changes and pushes it in real time through the socket in the right order.

**Comment by XeroxDev** [comment]
Yes. This is what I'm talking about! Would love this feature. Thank you! :D

**Comment by Alipoodle** [comment]
This change should already be applied with the new WebSocket
