### ISSUE TITLE
Javascript error in the main process when reconnecting Remote Control

### ISSUE THREAD

**Issue by kudlav** [ytmdesktop/ytmdesktop#664]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
After hibernation and smatphone reboot I tried to reconnect smartphone but get exception every time I try to connect.
![obrazek](https://user-images.githubusercontent.com/11516259/111156342-e8f62980-8595-11eb-960f-283a334da2d6.png)

**Environment (please complete the following information):**
 * Desktop:
-  * YTMDesktop version: ***v1.14.0***
-  * OS: ***Windows***
-  * OS version: ***10 (20H2)***
-  * Arch: ***x64***
-  * Installation way: ***.exe***

 * Smartphone:
-  * Samsung Galaxy S3 mini
-  *  YTMDesktop Remote **1.1.1**

**Comment by kudlav** [comment]
Restarting windows application does not help. The problem probably came just after turning Remote control settings off and then turning it on again.

**Comment by kudlav** [comment]
Ok, so after rebooting both devices I am no longer able to connect to YTM Desktop. The above error occurse every time I try to connect.

**Comment by NinjaShuriken** [comment]
Having the exact same issue with the Nov 2021 Nightly build too. Is the issue known or did it pass under the radar by mistake?

**Comment by imabigdipper** [comment]
Getting the same issue here. Tried restarting both app and desktop player. Didn't help. Happening on Windows 11 with Pixel 6 Pro on Android 12

**Comment by NinjaShuriken** [comment]
Uh, so weird funny thing happening on my end if you play with the volume slider a bit, it works? Can you guys confirm this too?

**Comment by pcmnn-id** [comment]
i just run the app as administrator, and no more error pop up

**Comment by imabigdipper** [comment]
Running the app as administrator fixed my issue. Occasionally an error will still pop up, but more importantly, the remote feature works properly

**Comment by Alipoodle** [comment]
Remote Control is no longer a active project and closing this issue.
