### ISSUE TITLE
Crash after a very long Link/Text with a Link is in the Clipboard and YTM Desktop is opened

### ISSUE THREAD

**Issue by TimTrayler** [ytmdesktop/ytmdesktop#672]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Hey, I copied a long html code from YouTube.com. The problem: when I opened YouTube Music, it gave me this popup (refer to Screenshots) and crashed after a minute of no reaction.

**To Reproduce**
1. Make sure to turn on search Clipboard for YouTube Links
2. Copy a long text containing a single YouTube Link
3. Open YouTube Music Desktop

**Expected behavior**
The program should have not accepted it.

**Screenshots**
![](https://i.ibb.co/YLwT96v/Bild-2021-03-23-132116.png) 

**Environment:**
 * YTMDesktop version: ***1.14.0***
 * OS: ***Windows***
 * OS version: ***10 (20H2)***
 * Arch: ***x64***
* Installation way: ***Executable (.exe)***

**Comment by Alipoodle** [comment]
This is to do with the Clipboard Watcher.
This simply checks for if the String contains A YouTube, YouTube Music or a Shortened YouTube Link.
Regex: `/(https?:\/\/)(www.)?(music.youtube|youtube|youtu.be).*/` 

This may need to be discussed if we just check for it being *Just the link* (So if other text exists it fails)
OR
We do a check on length and ignore if it exceeds something like 150 characters long

where we hopefully will reduce the chance of users crashing upon copying something large like this into the clipboard.

**Comment by kudlav** [comment]
Hi, checking max length sounds good, de facto URL max length is 2000. But Google wouldn't use such long url 😃 
https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
