### ISSUE TITLE
Mute status can't be changed

### ISSUE THREAD

**Issue by chen-bowen** [ytmdesktop/ytmdesktop#674]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**

**To Reproduce**
Go to shuffle all, music is always muted. 

**Expected behavior**
Should be able to change the volume

**Screenshots**
How to add screenshot here?

**Environment (please complete the following information):**
 * YTMDesktop version: MacBook Pro (16-inch, 2019)
 * OS: Mac
 * OS version: 11.2.3 Big Sur
 * Arch: ***x86***
* Installation way: download installer

**Comment by Alipoodle** [comment]
No response within a Month. Closing.
