### ISSUE TITLE
Bug: Song title failed to update

### ISSUE THREAD

**Issue by mingjun97** [ytmdesktop/ytmdesktop#68]
Track switch cannot be detected if YTMDesktop runing in background. So the song title/author could not be updated correctly.

**Comment by adlerluiz** [comment]
Seems to be a specific error for mac since in windows i didn't have this problem

**Comment by mingjun97** [comment]
![image](https://user-images.githubusercontent.com/15214491/70095939-c592af80-15da-11ea-98a0-00966b4057c1.png)
Far away from current track. Seems like the track switch in YTMusic won't raise `media-started-play` event anymore. I'll add a complementary hook at `did-navigate-in-page`.

**Comment by mingjun97** [comment]
Or we need a more robust way to retrieve the track's title?

**Comment by adlerluiz** [comment]
Yes, we need a more robust way, but to get track info maybe can see too `page-title-updated`

**Comment by mingjun97** [comment]
From my test, ytmusic might not update track title to the page title. I'm not sure if page-title-updated event will be triigerred. I'm thinking use `MutationObserver` to monitor the modification of the `div` of title. It should works.

**Comment by mingjun97** [comment]
Tried MutationObserver, it seems not gonna to work since the YTM only update innerText which will not observered by MutationObserver. Finally, I add a complementary monitor to the `did-start-navigate` event handler.

**Comment by adlerluiz** [comment]
Testing new feature (LastFM integration) i see the problem too

![image](https://user-images.githubusercontent.com/2112638/70284997-cbd48780-17a4-11ea-96ab-08935f1d0802.png)

**Comment by adlerluiz** [comment]
because updateActivity is called 2 times

![image](https://user-images.githubusercontent.com/2112638/70289728-77390880-17b4-11ea-8e5b-d00d2f49c1fd.png)

**Comment by mingjun97** [comment]
Sorry for that. I didn't notice that the `updateActivity` will incur such problem. Maybe temporarily disable this patch? I'm a little busy recently.

**Comment by rickinbsb** [comment]
Fixed on v1.6
