### ISSUE TITLE
Tooltip for system tray icon shows "electron10" instead of info about the application

### ISSUE THREAD

**Issue by kennykingdev** [ytmdesktop/ytmdesktop#681]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The tooltip for the system tray icon shows "electron10"

**To Reproduce**
1. hover mouse curser over the system tray icon

**Expected behavior**
It should show something relevant to the application.  Ideally the track info if music is playing, but at least it should show the name of the application.

**Screenshots**
![Screenshot_20210329_165127](https://user-images.githubusercontent.com/16931002/112913684-0e635700-90af-11eb-9e4b-05d39dc27f91.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Linux***
 * OS version: ***Arch Linux w/ KDE Plasma***
 * Arch: ***x64***
* Installation way: ***AUR***

**Comment by Alipoodle** [comment]
Closing this issue with the new release of YTMDv2.
Please create a new issue if this still occurs.
