### ISSUE TITLE
Default Volume Up/Down keyboard shortcuts conflict with text editing shortcuts

### ISSUE THREAD

**Issue by jvstein** [ytmdesktop/ytmdesktop#684]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The default keyboard shortcut for volume up and down conflicts with common text editing shortcuts used in many text editors on Linux.

CTRL-SHIFT-UP
CTRL-SHIFT-DOWN

**To Reproduce**
1. Start YouTube Music Desktop with the default settings and start playing some music
2. Open a text editor (e.g. geany or Chrome) and insert the following text.
   ```
   This text is split across
   multiple lines and

   paragraphs

   put your caret >here<
   ```
3. Put your caret or text cursor on the `>here<` and press CTRL-SHIFT-UP.
4. The text editor will likely select the text up to the start of the second paragraph, selecting something like below. This is the common text editing behavior conflicting with the shortcut. Additionally, the volume of YouTube Music Desktop will be increased.
    ```
    paragraphs

    put your caret >here<
    ```

**Expected behavior**
I would expect common text editing keyboard shortcuts to be avoided as volume control bindings. When editing text in various places, I found my music volume being adjusted up and down. It took an embarrassingly long time to figure out it was a default keyboard shortcut in YouTube Music Desktop.

I was able to disable the shortcuts, but it seems like a bad default.

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Linux***
 * OS version: ***Ubuntu 20.04.2 LTS***
 * Arch: ***x64***
* Installation way: ***AppImage***

**Comment by Alipoodle** [comment]
These are simply the Default key binds on the program.
You can disable and reconfigure them (like you have said)... 🤔

Ultimately I agree that common IDEs use stuff like `CTRL + SHIFT + UP` for stuff, but the Demographic for the program is everyone and not just programers.

I don't feel that this is a bug, with any need of a fix or change. You can control the Behaviour of the program to not listen to those Keybinds. They can be changed to something like `CTRL + SHIFT + Page Up/Down` or Disabled completely.

**Comment by jvstein** [comment]
That's fine. I'm documenting a behavior and a grievance against the defaults. I have my solution and you can do what you will with my report.

As mentioned, the keyboard shortcut is not an IDE or programmer specific shortcut. It affects nearly every text field. I noticed it when editing text in Chrome the most.
