### ISSUE TITLE
Suggestion: Icons should change

### ISSUE THREAD

**Issue by Caner3078** [ytmdesktop/ytmdesktop#690]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
No, this is a suggestion. It would be better if the icon for the program was the same as the actual YouTube Music.

For example, the photo in Discord Rich Presence and the desktop icon of the program should be the same as the Youtube Music.

![Ekran görüntüsü 2021-04-11 155206](https://user-images.githubusercontent.com/82318077/114305343-73bc3c80-9ae0-11eb-94da-077793eb2b26.png)
![qweewqewq](https://user-images.githubusercontent.com/82318077/114305401-bb42c880-9ae0-11eb-98f9-70e6206cb856.png)

**Comment by Alipoodle** [comment]
> I understand that YTMDesktop have NO affiliation with Google or YouTube.

> Seems to be impossible to use official icon due to copyright issues.

We're not YouTube or Google. We cannot use their Copyrighted Logo for this, and don't want any issues with using it.
#123 is a Feature Request which is currently open to allow for Custom icons, however for the time being, you'd either need to modify the Shortcut you have to be a different icon, or make your own build of the app to have the modified icon.
