### ISSUE TITLE
Mini Player Keeps growing on Scale and Layout 175% zoom

### ISSUE THREAD

**Issue by MrPandaa** [ytmdesktop/ytmdesktop#691]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**
 The Mini player slowly growing in size (like 2 pixels per second).

 **To Reproduce**
1. Set on windows Display Settings a Scale and Layout zoom for an Display (i have it on 175% its my phone for tracking CPU and ram usage so its small) it only grows in size when the display is set 175%
2. Drag the Mini player to this display
3. Watch it slowly grow

 **Expected behavior**
Staying the same Size

**Screenshot**

![image](https://user-images.githubusercontent.com/50860160/114314219-1c2aca80-9afa-11eb-8c6b-e3e96385e51e.png)

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32*** (Win 10)
 * OS version: ***10.0.19042***
 * Arch: ***x64***
 * Installation way: ***.exe from github***

**Comment by rickinbsb** [comment]
this is possibly already working on the development branch, can you check it?

**Comment by MrPandaa** [comment]
dev branch isn't working either found a workaround though i am using an external player for that monitor with WebNowPlaying Integration and i manually scale things now too its more work but works better. If you cannot replicate the behavior feel free to close the issue.

**Comment by godey4me** [comment]
I have this exact issue, i can't find a way of dealing wit it. it only happens when mini player is moved to second screen which is where i want it.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
