### ISSUE TITLE
Discord presence not working

### ISSUE THREAD

**Issue by crossfire151** [ytmdesktop/ytmdesktop#695]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**
Discord presence simply not working, I've toggled it on and off and restarted the app as well as discord.

 **To Reproduce**
Attempt to use Discord Presence.

 **Expected behavior**

 **Screenshots**

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.19042***
 * Arch: ***x64***
 * Installation way: ***like .exe or snapcraft or another way***

**Comment by Scridgeon** [comment]
This is not working for me either.

Environment:

YTMDesktop version: v1.13.0 and v1.14.0
OS: Windows
OS version: 10.0.19042.867
Arch: x64
Installation way: exe from github repo

**Comment by TheCre8r** [comment]
+1 for not working

Environment:

YTMDesktop version: v1.13.0
OS: Windows
OS version: 10.0.19042.964
Arch: x64
Installation way: .exe from GH

**Comment by sayanjyotidas** [comment]
1) Go to settings by clicking the cog icon left of your profile picture
2) Click on Integrations and turn on the toggle for Discord Rich Presence
3) Open Discord > Open Settings and Add Youtube Music Desktop App in Activity Status
4) After doing all this, if it still doesn't work, restart Discord first and then restart YTM Desktop App; make sure no other app is taking control of Discord's rich presence over YTM Desktop.

**Comment by crossfire151** [comment]
Are you dumb? Of course we’ve toggled that setting on! The obvious pc restart over the multiple days since this post would point out the app was already restarted.

[chris “Crossfire” wolveren - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=11uk11)	[11uk11]

On May 29, 2021 at 7:52 GMT, Sayanjyoti Das ***@***.***> wrote:

- Go to settings by clicking the cog icon left of your profile picture
- Click on Integrations and turn on the toggle for Discord Rich Presence
- Open Discord > Open Settings and Add Youtube Music Desktop App in Activity Status
- After doing all this, if it still doesn't work, restart Discord first and then restart YTM Desktop App; make sure no other app is taking control of Discord's rich presence over YTM Desktop.

**Comment by sayanjyotidas** [comment]
> Are you dumb? Of course we’ve toggled that setting on! The obvious pc restart over the multiple days since this post would point out the app was already restarted.
I was just trying to help, but okay.

**Comment by ProjectRay12** [comment]
For anyone with this issue (on Windows), check to see if you are running Discord as an Administrator. If you are, you will have to run YTMApp as an Administrator as well in order for integration to function. Not sure if this is the _only_ cause for people with this bug, but this is what caused and resolved it for me.

**Comment by Alipoodle** [comment]
Can I ask why people would have Discord in Admin mode?
There's not a need for it to my knowledge to fix and of the issues within Discord.

**Comment by ProjectRay12** [comment]
> 

The primary reason is for hotkey purposes. This goes for any application that uses global hotkeys (hotkeys usable while the window is not focused), if you are in another window that *does* have Admin mode on, then applications *without* Admin mode will not be able to use their global hotkeys.

In my case, I still want to push-to-talk/toggle mute while working/using applications that I do need in Admin mode, which ends up being a few.

**Comment by ionstorm66** [comment]
I rich presence isnt working at all for me. I have tired running both as admin, one or the other as admin, or both as user mode. Only thing I ever get in Discord is the artist name when I add it, it never changes.

**Comment by Xhermp** [comment]
I get no connection between Discord and YTMusic

I can add YTMusic as an app in Discord, but it just says "youtube-music-desktop-app" with no rich presence or anything.

Linux Mint, deb install of Discord with BetterDiscord installed. YTMusic just downloaded through the software manager.

**Comment by Alipoodle** [comment]
To be clear:

The following settings need to be enabled:
**YTM Desktop:**
- Go to Settings -> Integrations -> Discord Rich Presences and Enable the option there. (Click setting to manage what is shown)

**Discord:**
- Go to Settings -> Activity Status and make sure that it is enabled
![image](https://user-images.githubusercontent.com/17199186/170069051-0e75d50a-4ee8-4bd9-bf09-e10f909f2777.png)

**Additional Information:**
- Do not run Discord or YTM Desktop as Admin, as this messes around with Permissions of the RPC connection between the two, and Keybindings ETC. [This is not recommended as a whole for either applicaiton. but can be needed within Discord to allow Keybinds in games which run as Admin.]
- You do not add YTM Desktop as an Application inside of Discord. [This is manually adding a static game] as this will overwrite the Visual displayed game with whatever Discord has been given. [Normally Artist or App name]
- Try Restarting both Discord and YTM Desktop, the Connection for Discord typically needs to be opened first and then YTM Desktop second. 
- Running Multiple Clients [Not supported by Discord] will ALWAYS connect to the first Client opened.
- Discord Linux is basically unsupported for the last 2 years+ and likely has an issue regarding RPC Connections for that platform. [Reviewing the "official" Discord Linux server, it's even said to be very broken on there, and there's a few "hacks" around, but that's for you to do research on and not me.]

**Comment by ionstorm66** [comment]
Yeah I have followed all of that and it has never worked. 

I don't have them running as admin
Rich Presence is enabled in YTD
Activity Status is enabled in Discord, and YTD isn't manually added

Is there anyway to debug this?

**Comment by Alipoodle** [comment]
Using the Console you can see if it's making any connection on Discord side. Going into the console and filtering RPC will let you see on Discord side if a connection is made!

Otherwise can you confirm that other RPC things do work?

**Comment by ionstorm66** [comment]
Games and such show info about them, so that's working. I'm not seeing it reciving anything from YTD though. Also using MultiRPC works fine.

**Comment by Alipoodle** [comment]
If you want to join the discord server and pop me an @ in support I can help you when available with a bit more of a 1-1 help. 
I'm gonna go sleep now so best to try me tomorrow!

**Comment by DarkSona** [comment]
So, I'm facing a similar problem, I already did as in the quoted message, but no success, the Discord app only shows that I'm playing Youtube Music, but there's no information about the song, author or time remaining, even though I toggle all the rich presence's options ON in the YTMDesktop app.

Environment:

YTMDesktop version: v1.13.0
OS: Windows 11
OS version: 22H2 (OS Compilation: 22621.1194)
Installation way: winget

> To be clear:
> 
> ## The following settings need to be enabled:
> ### YTM Desktop:
> * Go to Settings -> Integrations -> Discord Rich Presences and Enable the option there. (Click setting to manage what is shown)
> 
> ### Discord:
> * Go to Settings -> Activity Status and make sure that it is enabled
>   ![image](https://user-images.githubusercontent.com/17199186/170069051-0e75d50a-4ee8-4bd9-bf09-e10f909f2777.png)
> 
> ## Additional Information:
> * Do not run Discord or YTM Desktop as Admin, as this messes around with Permissions of the RPC connection between the two, and Keybindings ETC. [This is not recommended as a whole for either applicaiton. but can be needed within Discord to allow Keybinds in games which run as Admin.]
> * You do not add YTM Desktop as an Application inside of Discord. [This is manually adding a static game] as this will overwrite the Visual displayed game with whatever Discord has been given. [Normally Artist or App name]
> * Try Restarting both Discord and YTM Desktop, the Connection for Discord typically needs to be opened first and then YTM Desktop second.
> * Running Multiple Clients [Not supported by Discord] will ALWAYS connect to the first Client opened.
> * Discord Linux is basically unsupported for the last 2 years+ and likely has an issue regarding RPC Connections for that platform. [Reviewing the "official" Discord Linux server, it's even said to be very broken on there, and there's a few "hacks" around, but that's for you to do research on and not me.]

**Comment by Tx-ID** [comment]
sorry for bumping but this might be relevant since YTM or Discord fails to display rich presence if either: Music title, Artist name is too long

**Comment by Scridgeon** [comment]
> sorry for bumping but this might be relevant since YTM or Discord fails to display rich presence if either: Music title, Artist name is too long

You can work around this by using Vencord or BetterCord. Both of have a plug-in to show music playing via LastFM. Then enable the LastFM extension in ytmdesktop. I've been doing this for awhile now and it works great.

**Comment by Alipoodle** [comment]
> sorry for bumping but this might be relevant since YTM or Discord fails to display rich presence if either: Music title, Artist name is too long

https://github.com/ytmdesktop/ytmdesktop/blob/fad2cea173ce204252f204da788c77fe2392680a/src/main/integrations/discord-presence/index.ts#L80

We have a function to limit this already so this isn't true.

Please see the wikis FAQs or check Discord console and you can probably find out more.

**Comment by Tx-ID** [comment]
> We have a function to limit this already so this isn't true.

sorry...
![Image](https://github.com/user-attachments/assets/b8e5109a-57bd-43ba-98b4-f428df392019)

**Comment by Tx-ID** [comment]
oh my god im so sorry, I was mistaken to another repository
