### ISSUE TITLE
macOS Signing

### ISSUE THREAD

**Issue by samermurad** [ytmdesktop/ytmdesktop#697]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Making the App signed

**Describe the solution you'd like**
Hey, I am an a Mobile and Fullstack developer, and a freelancer, and I have a valid developer certificate to constantly work with apples tools, which I pay for anyways each year, this allows me to create product keys/certs etc, usually for clients and such, I've also worked a lot with electron and currently maintaining an electron app.
I would be more than happy to help signing the product for macOS, in order to avoid the "App not supported" message.
we'll probably have to test if this can be done over a pipeline or I'd have to sign each version (maybe create a script that signs the app)

Let me know if this would be relevant, as the app would then be signed under my name, If I help a bit with the project, I would personally have no problem doing so.

Let me know what you think

**Comment by Venipa** [comment]
![](https://media1.tenor.com/images/3240b08b8c1d722625dfb9e5d73b7b11/tenor.gif?itemid=3535805)

**Comment by samermurad** [comment]
okay, I'll try it the other way around, are you inserted in signing the macOS version? if so, I would be happy to help you achieve that (and Im not asking for money, maybe my comment was a bit confusing, I just wanted to state that I have the required knowledge/experience).

**Comment by Alipoodle** [comment]
There is already #155 regarding Getting the apps Signed.
However I don't think there's any plans currently to get things done just yet.

If you may have noticed there's not been too much work done on the Repo within the last few months (Few PRs, Lack of issues management other than a few comments, lack of versions ETC)
