### ISSUE TITLE
Add Customization For Keyboard Shortcuts When App Is In Background.

### ISSUE THREAD

**Issue by RutvikRana** [ytmdesktop/ytmdesktop#698]
I have laptop and dont have page up/down keys, so how i suppose to change songs from keyboard globally. ???

**Comment by Alipoodle** [comment]
![2021-04-16_16-32-40](https://user-images.githubusercontent.com/17199186/115048438-79939280-9ed1-11eb-9130-15692a16bbf4.gif)

**Comment by RutvikRana** [comment]
Thank you so much...😍
but when I play games these shortcuts are not working, is there anything I
can do about this?

**Comment by Alipoodle** [comment]
It depends on the permissions of the game I think, as some games will prevent Keybinds from being read by lower programs.

I've personally not had issues with using the Media Key Shortcuts on my PC while playing stuff like Rocket League and Rainbow 6 Siege, and never had issues with using my Volume Keybinds either. 🤷‍♀️
