### ISSUE TITLE
Ad-blocker feature

### ISSUE THREAD

**Issue by saurav3199** [ytmdesktop/ytmdesktop#700]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Feature Request**:
It would be better to have **adblocker integration** to the desktop app. For me, I will switch to the browser version just because of it.

**How To Solve**:
Similar to extensions used in Browser, any existing tricks can be added to README.MD or new feature can be brought to the table

**Comment by Alipoodle** [comment]
Hi there. Please can you actually check if there's other issues as #114 Is already open.

### TL;DR
YTMD App will not be adding it directly into the application, a plugin can be made or users can create their own version of the application with it.

**Comment by Venipa** [comment]
Buy youtube premium

**Comment by SpheeresX** [comment]
`ytmdesktop` has no plans to add an adblocker because of potential legal issues. You can use my fork that has ad-blocking built-in: https://github.com/SpheeresX/ytmdesktop
