### ISSUE TITLE
Can't logout or  change account

### ISSUE THREAD

**Issue by danhab05** [ytmdesktop/ytmdesktop#705]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**
I cannot log out of my account or add a new one

 **To Reproduce**
 1. Go to profile
 2.  2. Click on logout or switch account
 3. See error

 **Expected behavior**
 you will not be able to change your account or log out

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.19042***
 * Arch: ***x64***
 * Installation way: *** .exe ***

**Comment by Alipoodle** [comment]
Is it possible to see this Error message?

Swapping or Changing accounts is fine for me on 1.14 version (Win10 64x).
