### ISSUE TITLE
No Uploads collection available

### ISSUE THREAD

**Issue by MikeBeaton** [ytmdesktop/ytmdesktop#707]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Hi,

I just downloaded and installed ytmdesktop 1.13.0 on Windows 10 20H2 (19042.928).

When I go to Albums then unlike https://music.youtube.com/ I do not see any option to choose "Uploads" (i.e. my own music collection, which has migrated from iCloud Music to Google Player to YT Music over the years...!).

I would have maybe assumed this was a feature request for ytmdesktop, except that #293 talks as if "YouTube Music" and "Uploads" collections are both available in ytmdesktop already. Their issue I think was just about playing both collections together, whereas I don't even see any option to play my Uploads collection at all.

Apologies for any misunderstanding on my part - and please do re-label as a feature request if it really is one.

Many thanks,
Mike

**To Reproduce**

Download and install as above.

**Expected behavior**

That both "YouTube Music" and "Uploads" collections can be chosen, as in the Albums tab (and other tabs) of https://music.youtube.com/ .

**Screenshots**

https://music.youtube.com/ :

![image](https://user-images.githubusercontent.com/11946605/115856573-91fd3300-a424-11eb-913d-0ac4fb9cef91.png)

ytmdesktop:

![image](https://user-images.githubusercontent.com/11946605/115856622-a17c7c00-a424-11eb-9e67-5f95bd537a61.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***.exe from https://ytmdesktop.app/***

**Comment by Alipoodle** [comment]
I think is an issue to do with the account you are on, as I have both a Brand + Normal Account.
Due to Brand Accounts not allowed to have Uploaded music, I have my all my music on my normal Account.

Can you confirm you are on the Right account?
![image](https://user-images.githubusercontent.com/17199186/115894942-c5a28200-a451-11eb-8e64-a27dd394ec96.png)

**Comment by MikeBeaton** [comment]
That was it - many thanks! :-)
