### ISSUE TITLE
Show track name in the discord rich presence in discord user list.

### ISSUE THREAD

**Issue by dhanjit** [ytmdesktop/ytmdesktop#708]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
The discord rich presence is something like this: 
![image](https://user-images.githubusercontent.com/2098349/115902727-5a23d900-a480-11eb-8772-1b4aa300f26e.png)

"Youtube Music" is what is shown in the user list sidebar. It should show track name.

**Describe the solution you'd like**
Show the track name instead of "Youtube Music" in the userlist. Her:

![image](https://user-images.githubusercontent.com/2098349/115902938-9fe0a180-a480-11eb-9bfe-58baecbaa131.png)

**Comment by NovusTheory** [comment]
This isn't possible due to the way discord works right now.

**Comment by LastPlayerTR** [comment]
It is not possible.

**Comment by mingjun97** [comment]
Duplicated.
