### ISSUE TITLE
CS:GO lagging while using the app

### ISSUE THREAD

**Issue by alexandruspataru** [ytmdesktop/ytmdesktop#709]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
My CS:GO is freezing while using the application, I use it as I can simple play / pause the clips when I die / I start.

**To Reproduce**
1. Go to CS:GO
2. On the second monitor open the APP
3. Play / Pause some playlist with videoclips

**Expected behavior**
Whenever you start a competitive match, you'll see the game simply lagging

**Environment (please complete the following information):**
 * YTMDesktop version: latest
 * OS: Windows
 * OS version: 10
 * Arch: x64

**Comment by alexandruspataru** [comment]
Yes, I did try and it solved the issue.

**Comment by mingjun97** [comment]
Closed because this issue has been solved.
