### ISSUE TITLE
Bug: Settings disappeared and no way to get them back

### ISSUE THREAD

**Issue by AdityaTD** [ytmdesktop/ytmdesktop#71]
Hey, so during me playing around with the settings. Under the title bar settings, I changed it to "No Title Bar" or something and now there's no way to get it back. I'm wondering if there's a shortcut to the settings page otherwise I'm stuck.

**Comment by adlerluiz** [comment]
Hello, for now have 2 ways to open settings, first is on title bar, and second is right click on tray icon.

on next release, we have implemented right click context menu with 'go back', 'settings' and 'lyrics'
