### ISSUE TITLE
App YTM Não conecta à internet

### ISSUE THREAD

**Issue by jocimar-ep** [ytmdesktop/ytmdesktop#720]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ ] I verified that there is no open issue for the same subject.

 **Describe the bug**

 **To Reproduce**
 3. See error

 **Expected behavior**

 **Screenshots**

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.17134***
 * Arch: ***x64***
 * Installation way: ***like .exe or snapcraft or another way***

**Comment by jocimar-ep** [comment]
O App YTM não conecta à Internet.

**Comment by mingjun97** [comment]
Please use english otherwise the contributors cannot understand. Thanks!
