### ISSUE TITLE
Discord Rich Presence does not seem to work on Linux/Ubuntu

### ISSUE THREAD

**Issue by walter-the-dog** [ytmdesktop/ytmdesktop#722]
-  I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
-  I verified that there is no open issue for the same subject.

**Describe the bug**
Discord Rich Presence does not seem to detect that Youtube Music is playing music. I have tried multiple different songs and none of them are being detected by discord.

**To Reproduce**
1. Go to Youtube Music
2. Click on Enable Discord Rich presence in the settings
3. Install and open discord
4. No Rich presence

**Expected behavior**
Rich presence should show what music is being played

**Screenshots**
![image](https://user-images.githubusercontent.com/68549580/117535487-5a53d500-b039-11eb-95d4-71b8e1fd5c57.png)
^Permissions that i have provided to discord from the software application

![image](https://user-images.githubusercontent.com/68549580/117535520-82dbcf00-b039-11eb-9c40-9f66f4e95bf3.png)
^Discord Rich Presence Settings for Youtube Music Desktop

![image](https://user-images.githubusercontent.com/68549580/117535544-9dae4380-b039-11eb-826c-41d2f949f53d.png)
^Game activity settings

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS:  ***Linux*** - Zorin (Ubuntu based)
 * OS version: ***15.3***
 * Arch: ***x64*** 
* Installation way: Youtube music desktop was installed through snap craft. Discord was installed through "Software" which is an inbuilt "app store" for zorin

**Comment by Alipoodle** [comment]
Had a friend of mine Verify that this is not an issue with the Discord on Linux (as it's basically dead to Discord) and is able to hav e it working on Pop_OS!
![image](https://user-images.githubusercontent.com/17199186/117537297-dd543b80-aff7-11eb-9a2c-df37928fb861.png)

Please note that `Discord-RPC` the library that we use isn't perfect at connecting and may require you to restart the Discord & YouTube Music Desktop App sometimes to connect.
Additional side note, even with it connected it will not display within the Game Activity, it will just display on your profile.

**Comment by walter-the-dog** [comment]
I have figured out a solution.
1. Uninstall all snap versions of discord and youtube music
2. Go to discord and download official package from there
3. Open up a terminal and run these commands
`wget https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.13.0/YouTube-Music-Desktop-App-1.13.0.AppImage && chmod a+x YouTube-Music-Desktop-App-1.13.0.AppImage
./YouTube-Music-Desktop-App-1.13.0.AppImage`
This basically gets the app image from the release 1.13.0 and marks it as executable and executes it.

However this is pretty annoying to do everytime you want to use the application therefore i also got an app image launcher which integrates app images with the os (https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian).

The downfall when using app images is that it does not auto update so be mindful of that.

Running ytmd this way makes the rich presence and the last fm scrobbler work so im certain that this is something to do with snap encapsulation.I'd recommend for the devs to atleast put a warning of sorts that some integrations won't work when installed through the snap store in order to save other users some time.

All of the above works on Zorin OS 15.3 , Stable 84336 Discord installation and release 1.13.0 YTMD.
