### ISSUE TITLE
Shortcut key with Windows + Key / Meta doesn't work.

### ISSUE THREAD

**Issue by cyraid** [ytmdesktop/ytmdesktop#725]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Shortcut key with Windows (meta) + Key doesn't work. For example: Win+Insert

**To Reproduce**
1. Go to Settings..
2. Click on Shortcuts..
3. Click on the button for Play/Pause.
4. Try to hold in Windows key and insert.

**Expected behavior**
The expected behavior is to allows meta/win key + another key.

**Environment (please complete the following information):**
* YTMDesktop version: ***v1.14.0***
* OS: Windows
* OS version: 10
* Arch: x64
* Installation way: .exe

**Comment by Serge777if** [comment]
I have similar issue in **Linux Ubuntu 20.04.1 LTS (Focal Fossa)**
With version **1.13.0** **AppImage**
I can't add shortcuts like Meta+Alt+P through app interface.
But I can edit /home/user/.config/youtube-music-desktop-app/config.json and add shortcuts like **"media-play-pause": "Alt+Meta+P",**
then it's working.
Fix it please.

**Comment by Alipoodle** [comment]
Just tested this and added an implementation which would work.
But by the looks of it it was either forgotten about within the Handling of Keybinding for YTM Desktop or was deliberately forgotten about.

Although I will create a PR which will allow the Meta Key (or Windows Key for Windows devices) to be usable.

**Comment by cyraid** [comment]
Nice, hoping this will land with a new update soon. :)

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
