### ISSUE TITLE
Favicon: Margin and Antialiasing

### ISSUE THREAD

**Issue by vbackeberg** [ytmdesktop/ytmdesktop#73]
Great application!

I adapted the **favicon** to have antialiasing and a margin so it will look just like other Apps such as Chrome.

Before:
![Anmerkung 2019-12-05 223605](https://user-images.githubusercontent.com/19993315/70276483-bc5b3b80-17b0-11ea-8b24-2490652d4836.png)

After:
![withmargin](https://user-images.githubusercontent.com/19993315/70276495-c2e9b300-17b0-11ea-9cf3-a56dcef03ae1.png)

You can acquire the new files from my fork:
https://github.com/vbackeberg/ytmdesktop/commit/8d949979203e7f966dc8aecde52eb1e311b4678a

**Comment by adlerluiz** [comment]
Hi @vbackeberg great work, you can make a Pull Request on branch development so will also become a contributor

**Comment by rickinbsb** [comment]
You can check on how to do it [here](https://help.github.com/pt/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

**Comment by vbackeberg** [comment]
Great,!I opened a PR. :)
