### ISSUE TITLE
pls add toggle for audio quality 

### ISSUE THREAD

**Issue by Abhi-gautam96** [ytmdesktop/ytmdesktop#731]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ ] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Alipoodle** [comment]
![image](https://user-images.githubusercontent.com/17199186/136952016-3061df18-87df-443d-b3fc-6f387fbec91b.png)
There is already an option for this within YouTube Music natively.

Click your profile (top right) and hit settings.
Select the playback option and choose quality.

Is this was you were looking for?

**Comment by Alipoodle** [comment]
Removing due to natively being in YTM and no response in a month.
