### ISSUE TITLE
Add AdBlock together with the App

### ISSUE THREAD

**Issue by jhunrey7870** [ytmdesktop/ytmdesktop#735]
- [ ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ ] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
I hate ads, 

**Describe the solution you'd like**
Maybe block the ads together with the app

**Describe alternatives you've considered**
there's no app that could block ads in any apps sorry

**Additional context**
![download](https://user-images.githubusercontent.com/71703985/120729755-88321980-c512-11eb-8a87-d8bd228388cd.jpg)

**Comment by Venipa** [comment]
Fork the app and implement I urself.
I guess you didn't check any of the checkmarks in the issue template...

**Comment by mingjun97** [comment]
I'll close this issue since we don't have plan for integrating adblockers. We believe ad blockers will somehow break the ToS. You can do it by yourself from host hijacktion or proxy style. I believe there are some easily accessible exsiting codes to do it. HFGL! :)

**Comment by BelgarionNL** [comment]
use this: https://github.com/th-ch/youtube-music
