### ISSUE TITLE
Specific Songs Refuse to Play on the Client

### ISSUE THREAD

**Issue by StaticVOiDance** [ytmdesktop/ytmdesktop#736]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
Certain songs are reliably skipped and won't play on the client. The same songs play normally on the web app and Android app. 

**To Reproduce**
1. Play the album "Ugly is Beautiful: Shorter, Thicker & Uglier (Deluxe)" by Oliver Tree (https://music.youtube.com/watch?v=mzhbRUniU4U&feature=share)

The player will skip songs 1,2, and 5 "Life Goes On",  "Every Type of Friend", and "When Your Around",  but play the other songs "Out of Ordinary" and "Summers Delight (SOS)". The error reads: "Song is unavailable, Skipping to the next one"

**Expected behavior**
All songs from the album play.

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.14.0 and 1.13.0***
 * OS: ***Windows***
 * OS version: ***Windows 10 18363***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by Alipoodle** [comment]
I cannot reproduce this issue on my Custom 1.14 (mainly fixes in Dev currently)
Do they show up as `(!)` when looking at the playlist/Album?

🤷‍♀️ This maybe due to Licensing issues or the song is blocked in specific regions.

**Comment by Alipoodle** [comment]
Using WatanNetwork's tool for checking Restrictions on YouTube Videos they all return the same.
![image](https://user-images.githubusercontent.com/17199186/121066212-88a40c00-c7c1-11eb-8993-59813b0f6759.png)

**Comment by StaticVOiDance** [comment]
Not a bad thought. I'm in the U.S. though, so I don't think it's region issue. That got me thinking about something else, how does the client deal with YouTube restricted mode? Could it be related to that?

**Comment by StaticVOiDance** [comment]
It at least says Restricted Mode is off in the settings.

**Comment by Alipoodle** [comment]
There should be nothing in the Client that should mess with Region or anything similar to this?

Can you confirm you don't have the same issue in a browser both signed in and signed out (use incognito mode)

**Comment by StaticVOiDance** [comment]
Ok, so for some reason this issue also shows up when I sign in to my account in an incognito browser. Super strange. Thanks, I'll close the issue.
