### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by Mizumaky** [ytmdesktop/ytmdesktop#737]
I noticed issues (eg this one #359) were moved to the project "[outdated] Youtube Music Desktop App Closed", which was closed at 25th february. I also see no new releases for nearly a year. I'm wondering whether there are just time issues preventing from working on it or that it was decided not to work on it anymore. If needed, I might be able to at least try lending a hand as a programmer during the summer (still a student, but have a few years of experience already).

**Comment by Alipoodle** [comment]
Project isn't really abandoned?
Ultimately the project is still functioning and is getting updates in the Development Builds, _although slowly._ 😅

However a new release of the Application hasn't been done in a while I agree. (Although there has been some talks about it)


#359 is titled wrong and is RAM usage not CPU usage.
From the research that has taken place, this is a YouTube Music issue and can be reproduced within the native Web Application as well.
Once example found for it was skipping songs within a Radio will start to slowly spike the Memory and not do proper garbage collection to get rid of this unneeded data.

And Creating a Pull Request is greatly Appreciated for fixing or adding any new features for the application

**Comment by Mizumaky** [comment]
Im sorry for bad conslusion 😅 Should have looked at the development branches. Anyway, thanks for letting me know, i might later look at the code, whether i'll be able to do a small fix/feature pull request or not.
Btw the issue is mostly about CPU from what I see. RAM or GPU is also mentioned in the comments, which might be the issue with YTM, but that isnt the main problem talked about here. I mentioned the issue since I also noticed the app uses quite a lot of CPU compared to the web version, even when idle. I have to kill the app when doing more demanding tasks on my laptop with only two cores :/.
