### ISSUE TITLE
[BUG]Volume nob going back and forth

### ISSUE THREAD

**Issue by rogue-agent** [ytmdesktop/ytmdesktop#743]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

 **Describe the bug**
Hovering over the volume bar whilst holding it makes the volume nob to move drastically and randomly.

 **To Reproduce**
 1. Choose a song
 2. Hold audio nob
 3. Move mouse left or right a little

 **Expected behavior**
 The audio nob should not randomly go back and forth.

 **Screenshots**
n/a

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows 10 x64 Pro***
 * OS version: ***10.0.19043 21H1***
 * Arch: ***x64***
 * Installation way: ***ytmdesktop.exe***
 
 This behaviour I have detected on another machine
 * OS: ***Windows 10 x64 Pro***
 * OS version: ***10.0.19043 20H2***
 * Arch: ***x64***
 * Installation way: ***ytmdesktop.exe***

**Comment by flleeppyy** [comment]
Yeah this actually happens on just the web client too, at least for me on Firefox Dev.
