### ISSUE TITLE
Change the sort order in playlists

### ISSUE THREAD

**Issue by andrasfuchs** [ytmdesktop/ytmdesktop#744]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
I have a long playlist with many songs that I like. If I want to listen to the most recently added song(s) I need to scroll down a lot, and wait for the client to load all the songs before I can click on the one I'm interested in.

**Describe the solution you'd like**
It would be great to have a "sort songs" option in the playlists that would allow me to reverse the order and let the client show me the most recently added song first.

**Describe alternatives you've considered**
The only alternative I have now is to scroll down and click on the song.

**Additional context**
I use ytmdesktop v1.13.0 on Windows 10.

**Comment by Brentmeister** [comment]
+1 I think the GooglePlayMusic Desktop app had this feature and it was great!

**Comment by Alipoodle** [comment]
I'm deeming this issue as simply to far fetched for what is possible with what Access we have to YTM and this is better feedback given to them.
