### ISSUE TITLE
Pin Lyrics on top

### ISSUE THREAD

**Issue by DankAlzein** [ytmdesktop/ytmdesktop#746]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
What's the point of having Lyrics with Miniplayer if you can't have the lyrics on top? If i have the Miniplayer on im expecting everything to be always pinned on my screen when im working with other applications, but the Lyrics for some reason aren't pinned on top?

**Describe the solution you'd like**
an option to Pin the lyrics window to be always on top just like the Miniplayer

**Describe alternatives you've considered**

**Additional context**

**Comment by flleeppyy** [comment]
Implemented in #747 
Please close.

**Comment by adlerluiz** [comment]
Merged!
