### ISSUE TITLE
Buttons Not Working

### ISSUE THREAD

**Issue by PooPooSkin** [ytmdesktop/ytmdesktop#754]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Clicking thumbs up, thumbs down, add to library, add to playlist, and more actions buttons will not do anything on any screen and using a playlist or queue. I haven't been able to fix it even after restarting my pc and the app multiple times. When I first downloaded the app it worked fine, then later it randomly stopped working. Then I changed the title bar setting to something different and reset the app, and it worked fine again, but the next time I opened the app again it stopped working and I have not been able to fix since then. 

**To Reproduce**
Not sure, this issue happens as soon as the app is opened. 

**Expected behavior**
Buttons should work normally and be usable.  

**Screenshots**
![AfterClicking](https://user-images.githubusercontent.com/62365093/123531026-94029d00-d6c6-11eb-9891-80be2833e0d4.PNG)
After clicking the thumbs up button. It does that for all the other buttons I mentioned on that bar.

![MoreActionsButtonInQueue_Playlist](https://user-images.githubusercontent.com/62365093/123531064-ef348f80-d6c6-11eb-9e95-85fe62b7fabd.PNG)
Also nothing happens when clicking the more actions( the three dots) button on a song in a queue/playlist

**Environment:**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Windows***
 * OS version: ***20H2***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by PooPooSkin** [comment]
Oh and I tried using the default hotkey for the thumbs up and down and It also didn't work

**Comment by seifer7** [comment]
I haven't used YTMDesktop in a few months.
I tried it tonight and am experiencing the same issue.

**Comment by WangaManga** [comment]
Same issue

**Comment by DurekuRyuu** [comment]
well at least it's not just me.
I would guess it's a google API update issue or smth.

**Comment by Alipoodle** [comment]
Just tested this issue on YTM Web and I can reproduce this issue there.
This appears to be to be a YTM Issue and not to do with YTM Desktop.

**Comment by parnexcodes** [comment]
a workaround for now is to disable ```Options > Resume last song when app starts``` to start on the homepage, this way the error does not happen.

**Comment by edorgeville** [comment]
For me it was under `Options > Playback > Continue where you left off`. Does indeed fix the issue. Thanks @parnexcodes !

**Comment by PooPooSkin** [comment]
Yup that defiantly fixes the issue. Thank you  @parnexcodes ! And same for me @edorgeville

**Comment by adlerluiz** [comment]
I made it available on the wiki, thanks.

https://github.com/ytmdesktop/ytmdesktop/wiki/Know-issues
