### ISSUE TITLE
Trojan Detected in Latest Release build

### ISSUE THREAD

**Issue by riboney** [ytmdesktop/ytmdesktop#758]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Trojan detected by Windows upon installation of latest release of the .exe

**Screenshots**

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***.exe***
![image](https://user-images.githubusercontent.com/14286113/124153200-2a85e400-da62-11eb-9626-1ff7799d98ef.png)

**Comment by NovusTheory** [comment]
This is a false positive. I've downloaded the same executable with no issues

**Comment by riboney** [comment]
> This is a false positive. I've downloaded the same executable with no issues

ok, I can confirm this. Downloaded the same executable twice and windows did not identify it as a threat

**Comment by adlerluiz** [comment]
unfortunately this can happen because we don't have a certificate for the installers, and sometimes windows can validate as a virus
