### ISSUE TITLE
YTMD v1.13 stopped loading

### ISSUE THREAD

**Issue by Darknight1337** [ytmdesktop/ytmdesktop#759]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
One day I loaded the program and it opened the window, and the center circle just keeps spinning.
I've tried uninstalling and reinstalling, and restarts

**To Reproduce**
1. open program

**Expected behavior**
To load my YTM account and listen to mah tunz!

**Screenshots**

![YTMD](https://user-images.githubusercontent.com/86817145/124220559-3ea9ff80-dabb-11eb-9ac3-e5a89ffbf976.jpg)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13***
 * OS: ***Windows 
 * OS version: Pro
 * Arch: ***x64***
 * Installation way: EXE

**Comment by adlerluiz** [comment]
did this happen after any windows update?

**Comment by Darknight1337** [comment]
Honestly, I'm not entirely sure, but it is quite possible. It's been going
on for almost 2 weeks now I believe, and if anything would've been after
the most recent windows update

**Comment by Darknight1337** [comment]
I can view in guest mode, and when I try to sign in on that (browser?) it says that it is not secure and won't allow sign in

![2021-07-12](https://user-images.githubusercontent.com/86817145/125274399-2b710e00-e2cb-11eb-8329-efae55c696c3.png)

**Comment by Darknight1337** [comment]
Looking at the log, it seems hung up on "companion server listening on port 9863"
I've made sure that YTMD is allowed full access to internet/network ports and that specific port

**Comment by eobet** [comment]
I had this happen yesterday, but luckily, an app restart resolved it.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
