### ISSUE TITLE
Bug: Error message after hit Cmd+Q in MacOS

### ISSUE THREAD

**Issue by mingjun97** [ytmdesktop/ytmdesktop#76]
Version: v1.6.0
Error Message:
![image](https://user-images.githubusercontent.com/15214491/70662658-8cca8a00-1c1b-11ea-8d2b-a82f050a50e5.png)
Platform: MacOS 10.15.1

**Comment by adlerluiz** [comment]
How did you get around to generating the release?

**Comment by mingjun97** [comment]
The release v1.6.0 has this problem. It's not a fatal error, just occurs while trying to quit the application.

**Comment by adlerluiz** [comment]
without option to background play?

**Comment by adlerluiz** [comment]
was without the guarder
