### ISSUE TITLE
BPM (beats per minute) detection

### ISSUE THREAD

**Issue by andrasfuchs** [ytmdesktop/ytmdesktop#760]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
It's not a problem per say, it would be just a nice-to-have. If you listen to electronic music or even tried to mixed two songs together, you probably know that an important property of the song is its BPM (beats per minute). To mix two songs properly you must match the two songs' speed (beats per minute) and make the transition between the two by overlapping them.
It would be great if YTMDesktop could calculate and show the song's BPM.

**Describe the solution you'd like**
There is already a working, open-source JavaScript implementation here: https://github.com/dlepaux/realtime-bpm-analyzer
It would be good to see this integrated, because it would open up opportunities for future features like:
(1) sort songs by BPM in a playlist, 
(2) play your songs in a playlist with a pre-defined BPM, to keep the pace 
(3) automatically try to mix the current and next song by overlapping them with matching speeds and beats, so there were no interruption in your music-listening experience.

**Describe alternatives you've considered**
There are surely separate BPM analyzer tools, but it would be good to see this feature built-in.

**Additional context**
I use ytmdesktop v1.13.0 on Windows 10.

**Comment by adlerluiz** [comment]
Thanks for the suggestion, I'll add it to the implementation list, I'll test it and it works and it will be available in the next release

**Comment by andrasfuchs** [comment]
Did you have the chance to test this? Is there a way you think I can help you with this feature?

**Comment by Alipoodle** [comment]
All things considered I see this as a big no for being able to add. I see no way of being able to mass get the BPM and sorting it.
I feel like this should be instead done in more of a LOCAL client like foobar instead of a Online based platform.
