### ISSUE TITLE
Program is not visible upon launching it.

### ISSUE THREAD

**Issue by Gamartto** [ytmdesktop/ytmdesktop#761]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
There is no visible window when the program is launched, the tray/taskbar icon shows up but there is no visible window anywhere in the desktop. The window shows up when doing win+tab but upon selection nothing happens. I reinstalled the software several times and restarted the PC but the issue persists. 

Versions tested:
YouTube.Music.Desktop.App.Setup.1.14.0
YouTube-Music-Desktop-App-Setup-1.13.0

**To Reproduce**
Launch the program. 

**Expected behavior**
Be able to see the program's window and interact with it normally.

**Screenshots**
Win+tab
![image](https://user-images.githubusercontent.com/11033491/124361418-c6475980-dbf4-11eb-9dc7-da1c06a88078.png)
Taskbar
![image](https://user-images.githubusercontent.com/11033491/124361588-5d141600-dbf5-11eb-80b4-204dce43d1fb.png)
Tray
![image](https://user-images.githubusercontent.com/11033491/124361603-669d7e00-dbf5-11eb-81f8-8b9f97389db7.png)

**Environment (please complete the following information):**
 * YTMDesktop version: YouTube.Music.Desktop.App.Setup.1.14.0, YouTube-Music-Desktop-App-Setup-1.13.0
 * OS: Windows 10
 * OS version: 20H2 19042.1052
 * Arch: ***x64*** 
* Installation way: Latest available version downloaded from github (exe).

**Comment by Alipoodle** [comment]
This issue has occurred for a few people.

Please do the following:
- Open the following folder: `%appdata%/youtube-music-desktop-app` (you can use File Explorer or Run to open this)
- Open the `config.json` file.
- Navigate to the area where it says
```json
"window-position": {
```
 
- Replace the following fields displayed below:
 ```json
	"window-position": {
		"x": 230,
		"y": 40
	},
	"window-maximized": false,
	"window-size": {
		"width": 1340,
		"height": 970
	},
```
This will set the Window to be around the middle of the screen for you.
_I used some other numbers in this but used what I put above_
![2021-07-03_18-58-43](https://user-images.githubusercontent.com/17199186/124363028-bb121f00-dc30-11eb-85b9-50e1c4780fa0.gif)


For some reason some people's `"window-position"` seems to be going -32,000, and going WAYYYYY to far of the screen.

**Comment by debmaj2** [comment]
@adlerluiz I can reproduce the bug and the fix works as well

**Comment by Gamartto** [comment]
Awesome! The fix worked!

Thanks.

**Comment by Alipoodle** [comment]
@debmaj2 @Gamartto 
Can I ask what value it was before? Was I right in it being -32,000?

**Comment by Gamartto** [comment]
window-position had its x value set to -2560.

**Comment by Alipoodle** [comment]
I will look into getting a more long term fix.
Check if the application's position is larger/smaller than the user's monitor setup, and revert back to some settings.

**Comment by adlerluiz** [comment]
I even made a change so that if it opens on a second screen and then opens again without this screen, it goes back to the initial position of the first one, but there's nothing to revert if it disappears and gets bigger than the monitor, we can think of a button to "back to center" in the taskbar or something like that
