### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by TimTrayler** [ytmdesktop/ytmdesktop#762]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Hey, while you can download, edit and rebuild ytmdesktop, some sort of plugin support would be amazing.

**Describe the solution you'd like**
Maybe a folder where you can put plugins inside. A plugin should be able to access the current page and have different events like on music change.

**Comment by adlerluiz** [comment]
Hello,

Support for extensions and themes is already under development, and will soon be available in a final version

**Comment by seahindeniz** [comment]
This probably related to #114, and support for extension mentioned over there as well

**Comment by Alipoodle** [comment]
Duplicate of #592
