### ISSUE TITLE
Problem: "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by splishevsky** [ytmdesktop/ytmdesktop#77]
I installed the app on Windows 10 and it got an error right away:

```
Uncaught Exception:
TypeError: Cannot read property 'x' of undefined
  at checkWindowBounds
(C:\Users\user\AppData\Local\Programs\youtube-music-desktop-app\resources\app.a...:24)
  at App.<anonymous>
(C:\Users\user\AppData\Local\Programs\youtube-music-desktop-app\resources\app.as...:3)
  at App.emit (events.js:205:15)
```

Upon pressing "OK" nothing happens, however the process remains open until terminated via taskmgr, which doesn't help. I also tried reinstalling the app - no luck.

**Comment by rickinbsb** [comment]
Can you post a screenshot of your settings screen?

**Comment by adlerluiz** [comment]
@splishevsky Thank you for reporting the bug, the fix has been made and will be available in the next release

**Comment by adlerluiz** [comment]
@splishevsky Thank you for reporting the bug, the fix has been made and will be available in the next release.
