### ISSUE TITLE
A JavaScript error occurred in the main process: A system error occurred: uv_interface_addresses 

### ISSUE THREAD

**Issue by justinspony** [ytmdesktop/ytmdesktop#770]
- [ Y] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ Y] I verified that there is no open issue for the same subject.

**Describe the bug**
When I start the application via terminal, I see the following error:

$ snap run youtube-music-desktop-app
A JavaScript error occurred in the main process
Uncaught Exception:
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 1 (Unknown system error 1)
    at Object.networkInterfaces (os.js:198:16)
    at Object.<anonymous> (/snap/youtube-music-desktop-app/6/resources/app.asar/src/providers/companionServer.js:4:30)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/snap/youtube-music-desktop-app/6/resources/app.asar/main.js:35:25)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

**To Reproduce**
1. Go to terminal
2. run the following command: snap run youtube-music-desktop-app
3. See error

**Expected behavior**
I expected the application GUI to appear. Instead I see the stacktrace shown above

**Screenshots**
No screenshots available.

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: Linux - Debian 10 Buster
 * Arch: x86_64 AMD Ryzen 5 2600X Six-Core Processor
* Installation way: snapcraft

**Comment by techmehow** [comment]
![gmusic error - Copy](https://user-images.githubusercontent.com/43617097/162738080-8151eb34-a2bd-419f-9302-31130e178ba9.png)

I get a similar error whenever i start/restart the application. See screen shot^
YTMDesktop version 1.13.0
OS: Windows 11 Pro
Version 21H2 (OS Build 22000.593)
Installed from exe

**Comment by FrankieGuns** [comment]
![image](https://user-images.githubusercontent.com/25517845/165413370-e7ebac28-7670-46be-abe7-d960af98cd5f.png)
I too have a similar error also same thing I start/restart the application.  See Screenshot

YTMDesktop version 1.13.0
OS:Windows 10 Home
Version 21H2 (OS Build 19044.1645)  AMD Ryzen 7 3700X 8-Core Processor 3.59 GHz
Installed from exe
I can't listen to music or anything at the current moment just makes the application unresponsive.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
