### ISSUE TITLE
Unable to sign-in with my Google account

### ISSUE THREAD

**Issue by superbonaci** [ytmdesktop/ytmdesktop#772]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Open the app and click on `SIGN IN`, nothing happens.

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***YouTube-Music-Desktop-App-Setup-1.13.0.exe***

**Comment by cgiAlexis** [comment]
I had this issue today and ended up resolving accidentally, so the solution isn't efficient;

1. Open up YTMD
2. Click "Sign in", nothing
3. Right-click system tray icon and select Guest
4. Second window opens up with login
5. Sign in via second window, still guest in main window
6. Close YTMD fully and reopen
7. Click "Sign in"
8. Sign in page opens in main window with user account logged out
9. Select account, normal sign in process
10. Signed in - _Success_

**Comment by superbonaci** [comment]
Alright got it working now. Opened 2 guest windows keeping the first one opened. Then clicked `SIGN IN` in all 3 several times, nothing happened. Then from system try Exit and when reopening I could log in. Next time I am already logged in.
Weird bug but worked. Still needs to be fixed in code I would say.

**Comment by uygary** [comment]
The sign in issue continues, but I couldn't replicate the fix mentioned here.
I suspect it was a coincidence.

**Comment by uygary** [comment]
Duplicate of #432.

**Comment by superbonaci** [comment]
@uygary you have to close and open the app several times and click the sign in icon.

**Comment by uygary** [comment]
I did that. It did not work.
Regardless, I believe the conversation should continue on #432.

**Comment by superbonaci** [comment]
ok

**Comment by uygary** [comment]
This issue still exists. It shouldn't be closed.
Is there a way to open up developer console to see what's going on behind the scenes?
