### ISSUE TITLE
API hidden lyrics bug

### ISSUE THREAD

**Issue by KillerBOSS2019** [ytmdesktop/ytmdesktop#773]
- [ x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x ] I verified that there is no open issue for the same subject.

**Describe the bug**
hidden lyrics window keeps exit or out of focus on current thing I am doing here is a example what happened:

I  am in a League of Legend game playing like normal and if you use another PC and do http POST requests for hidden lyrics window it will make your what ever full screen app out of focus which is League of Legend

**To Reproduce**
1. Open a window any window is fine like Chrome and press F11 to full screen
2. Go to another PC and make http POST to the PC with Full screened Chrome. In python would be
```py
import requests
PC = "192.168.29.1" # change to your own
requests.post("http://"+PC+":9863/query", command={"command": "show-lyrics-hidden"}
```
3. And then on the PC it will exit full screen and puts you on your desktop

**Expected behavior**
It should just load the lyrics data without keep exiting your game

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13***
 * OS: ***Windows***
 * OS version: 20H1
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by KillerBOSS2019** [comment]
I made a Plugin for TouchPortal where it uses your Android/IOS device act like Stream Deck. Anyways so I tried to make it so it can show lyrics when your gaming and stuff, so I made it so when ever it changes to a new song it will call show hidden lyrics window to grab data

**Comment by Alipoodle** [comment]
Does this happens upon the first attempt of running the `show-lyrics-hidden`?

What looks to be happening is:
- Running show hidden isn't using Electron's Hide on Display for Browser Window 
- Lyrics window get's data upon load/show causing a change in this to be needed.

The idea for a change would be:
- Edit `windowLyrics()` to take a true/false for showing the Window or not
- Change how Lyrics window updates it's Lyrics via the ipc communication to update the lyrics upon first booting, or subsequent calls to opening the window.

**Comment by KillerBOSS2019** [comment]
Or don't use window system at all and just use the Lyrics API data and just sends it to the web server

**Comment by KillerBOSS2019** [comment]
I made it so it runs `show-lyrics-hidden` Everytime when song is changing is because sometimes it doesn't give data anymore

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
