### ISSUE TITLE
Miniplayer always on top controls still visible

### ISSUE THREAD

**Issue by MemLiveOn** [ytmdesktop/ytmdesktop#775]
- [y] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [y] I verified that there is no open issue for the same subject.

**Describe the bug**
When "always on top" is enabled, and "always show controls" are disabled, the controls are still visible even when I mouse off the miniplayer. Have to mouse to the top edge of the miniplayer to remove controls.

**To Reproduce**
1. Make sure "always on top" is enabled and "always show controls" are disabled.
2. Set player to miniplayer.
3. Mouse over miniplayer then mouse off any side except draggable edge (top).
4. See issue - controls are still visible.

**Expected behavior**
Controls stop being visible when you mouse off **_any_** side of the miniplayer.

**Screenshots**
https://tgb.is-inside.me/i1yL9OEr.png
https://tgb.is-inside.me/VAuCeLVW.png

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***Windows 10***, ***2004***, ***Build: 19041.508***
 * Arch: ***x86***
* Installation way: ***.exe***

**Comment by MemLiveOn** [comment]
Here is what I ***@***.*** Great Beyondhttps://mygreatbeyond.comhttps://youtube.com/thegreatbeyond From: AlipoodleSent: Thursday, October 14, 2021 14:55To: ytmdesktop/ytmdesktopCc: TGB; AuthorSubject: Re: [ytmdesktop/ytmdesktop] Miniplayer always on top controls still visible (#775) I'm unable to reproduce this with the info provided above.Any other steps which may help me, or has this issue been solved?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.  



	
		
			
				
			
		
		
			
				This email has been checked for viruses by Avast antivirus software.
				www.avast.com

**Comment by Alipoodle** [comment]
I realise that I'm running 1.14 which has a number of patches for the Mini-player, so this issue may already be fixed in the next release.

The wiggle after closing setting is me highlighting Chrome to verify always on-top

https://user-images.githubusercontent.com/17199186/137816964-f0141204-3240-41d7-a2c9-4d94ad9abbc4.mp4

**Comment by Alipoodle** [comment]
Presume that this is fixed within the 1.14 update and no repsonse in over 6 months.
Closing the issue

**Comment by MemLiveOn** [comment]
Apologize. Forgot this thread even existed. But it's fine. I stopped using
ytm awhile back. Just use the YouTube chrome app.

James
Kat System
***@***.***
The Great Beyond
https://mygreatbeyond.com
https://youtube.com/thegreatbeyond
