### ISSUE TITLE
New "Start DJ set" feature

### ISSUE THREAD

**Issue by andrasfuchs** [ytmdesktop/ytmdesktop#779]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
It would be great to have an option similar to "start radio" when YTMDesktop starts a new playlist with similar songs to the currently played one. The new, "start DJ set" would be similar to "start radio" with some notable differences:
* The songs would have the same genre (and probably limited to electronic music)
* Their tempo would be similar and they would be matched
* The next track would start with low volume while the current track is still playing and they would slowly crossfade
* Their bass beats would be aligned

**Describe the solution you'd like**
I would like to see a new option next to the start radio button, to start a DJ set:
![YTMDesktop_start_DJ_set_mockup](https://user-images.githubusercontent.com/910321/128017320-4bd43c42-8394-4104-a65e-46df0243fc7b.png)

**Describe alternatives you've considered**
I just had a conversation with one of the founders of [Cyanite](https://cyanite.ai/). They have a nice API service that provides all the metadata needed for a perfect mix, including but not limited to BPM, genre and subgenre, mood, intensity, intensity change over the track, dominant key, voice profile and tracklist generation based on those values. 

Here is an example of the mood profile of a track:
![image](https://user-images.githubusercontent.com/910321/128021851-1392daa6-c3f7-4ec0-9944-8d8f519fcfe3.png)

I'm not affiliated with them, I just like how they use AI to help music lovers. 
Since they have a paid subscription model, we had two choices: 

(A) This feature would be a premium feature of YTMDesktop. Introducing a paid version of YTMDesktop would be a hustle, but it would provide this unique feature without much development effort of YTMDesktop's part.

(B) Cyanite also provides a free package to analyze 30 tracks / week, but that would need a user registration with them. Our users could decide if they wanted to register to get the DJ mixing feature for 30 tracks, or even pay for more tracks when they exhausted their free account.

**Additional context**
If we wanted implement all this without the help of Cyanite, this would require significant development, but it would provide something that only special DJ mixing tools can: gapless playback with intelligent mixing to keep the listener in the flow.

In order to make this a reality YTMDesktop would need a few new subfeatures:
[ ] tempo (BPM) detection (#760)
[ ] genre categorization (#745)
[ ] speed up or slow down the playback of a track (by +/- 15%)
[ ] load and play two tracks simultaneously
[ ] add programmatic control over the high/mid/low frequency bands and volume for the current and next tracks (ideally as a YTMDesktop extension)

**Comment by PvtTyphoon** [comment]
Can you guys also replicate the entirety of foobar2k and itunes, I would really like that as well /s

**Comment by andrasfuchs** [comment]
@PvtTyphoon Could you elaborate what is exactly you think the technical problem with this feature?
