### ISSUE TITLE
player-set-volume doesn't effect volume

### ISSUE THREAD

**Issue by XeroxDev** [ytmdesktop/ytmdesktop#786]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
Hey. I'm the developer of the [YTMD-StreamDeck extension ](https://github.com/XeroxDev/YTMD-StreamDeck/) and I got now multiple bug reports from my users specific to this topic.

If you try to change the volume, nothing in your app happens. It worked at the beginning but broke without any updates.

I investigated it a bit further to look if I can fix it from my side but sadly no.

The only thing I noticed which gives me a headache is the following:
I update the volume with this socket event: [`this.emit({ cmd: 'player-set-volume', value: percentage });`](https://github.com/XeroxDev/YTMD-StreamDeck/blob/ba2a3d5abc0ba08748879efccb84d888a7f1ab12/src/helper/ytmd-socket.helper.ts#L167) and what I noticed. Your tick event send the correct volume back to me but without updating the volume itself. (My extension shows as example: 20% but the volume is still at 50%). If I change the volume with my mouse, the volume and the percentage gets updated correctly. So I think the issue seems to be with your API side to be more precise: With your player-set-volume event which isn't updating the volume in the frontend, only in the backend.

Could you maybe investigate this a bit further?

**To Reproduce**
- Easy method (Stream Deck required)
  - Install extension
  - Add volume keys
  - press volume keys
- "Harder" method
  - listen for tick event
  - send player-set-volume event
  - see in tick event it getting updated but not in the player itself

**Expected behavior**
Let the API update the volume.

**Screenshots**
I created a video where you can see 3 things. Hope this helps.
Left: Your application
Top-Right: tick event
Bottom-Right: Stream Deck

https://user-images.githubusercontent.com/10864620/128840323-9d390aae-8803-4d51-a488-5e859cf2c857.mp4

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: Downloaded from github repository (exe)

**Comment by XeroxDev** [comment]
Update: Now it seems to update the HTML? But still: The volume itself does NOT get updated. And I realized sometimes the volume bar vanishes completely.

**Comment by nblath** [comment]
I submitted #805 as a workaround to the dev branch to help address this issue. It seems it used to only take changing the volume slider's value, but this no longer seems to cause it to update. This workaround changes the sliders step attribute before sending an event to simulate a right arrow key press to trigger the update.

I can confirm this change has fixed the volume control on the YTMD-StreamDeck extension on my deck.

I can also confirm that the volume control's in the TouchPortal YTMD Plugin are working with my TouchPortal setup.

**Comment by TeubyDE** [comment]
Still presend for me. Any Informations about it?
