### ISSUE TITLE
Shortcuts/Hotkeys only work on active window

### ISSUE THREAD

**Issue by zephyrus-ads** [ytmdesktop/ytmdesktop#789]
- [x]  I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
 Once shortcuts are set, they only work on active window. It means that if I open another active window they stop working.

**To Reproduce**

1. Go to Setting->Shortcuts
2. Set any hotkey for Play/Pause and close settings.
3. Use this shortcut with only YTMD open on your desktop
4. Open another window on top on YTMD and use the shortcut once again.

**Expected behavior**
Hotkey should work independently if YTMD window is active or inactive.

**Screenshots**
N/A

**Environment (please complete the following information):**

- YTMDesktop version: v1.13.0
- OS: Linux
- OS version: Ubuntu 21.04
- Arch: x64
- Installation way: snapcraft

**Comment by amcareem** [comment]
What are the implementations and solutions you followed on this?

**Comment by zephyrus-ads** [comment]
I still have this issue. 

Sometimes it even work not being the active window but if I change workspace it doesn't work for sure.

So I fixed this problem removing all the shortcuts into the application itself and set them in the global settings. In this way it works fine.

![Screenshot from 2021-09-04 16-58-05](https://user-images.githubusercontent.com/88966497/132098925-d5b941e8-e196-4945-a4ab-c7f7952be099.png)
