### ISSUE TITLE
Feature Request: Enhance Notifications

### ISSUE THREAD

**Issue by andrescirulo** [ytmdesktop/ytmdesktop#79]
On Windows 10 a few thing that would be good in the notifications:

1. Image of the album of the song playing.
2. Don't play notification sound when it's showed.
3. Make them temporal (let's say 5 seconds) so they don't stay on the notification panel.

**Comment by andrescirulo** [comment]
I realized there are options in Windows for 2 and 3, I suppose there is a way for the app to be the one who sets those options.
![image](https://user-images.githubusercontent.com/13123832/71420264-0bc7b580-2653-11ea-86fe-1995de09f602.png)

**Comment by adlerluiz** [comment]
@andrescirulo Thanks for the suggestions, 1 will certainly be implemented, already 2 I will look for any parameters when launching notification not to touch and 3 also believe there is a way to inform the lifetime of the notification

**Comment by adlerluiz** [comment]
So far I haven't found anything in api for these other modifications, but the album cover in the notification is now available.
