### ISSUE TITLE
Option to disable taskbar integrations (progress, yellow pause color)

### ISSUE THREAD

**Issue by zwamdurkel** [ytmdesktop/ytmdesktop#791]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
When pausing a song the icon in the taskbar turns into this nasty yellow color with a progress bar. (when playing it's a green progress bar). I think this looks very ugly and it distracts me. There are many times you just have to pause a song to go do something else, but then this yellow thing appears. As far as I understand there is no way to "Stop" playing entirely.  YTM doesn't have a stop button and the clear from queue button will just go straight to the next song. 
![image](https://user-images.githubusercontent.com/13705380/130292986-72d89ba8-4901-411c-ab73-3a70db3ac723.png)

**Describe the solution you'd like**
Please make an option to turn of this progress bar and yellow color in the settings. I want to be able to disable this taskbar feedback entirely.

**Describe alternatives you've considered**
Alternatively, a way to completely stop playback, no queue or any song currently playing. A way to clear the entire queue. As when you've just opened the app

**Additional context**
As you can see, no "Clear Queue" or "Stop Playback" option. shame on YT for not implementing such a standard feature.
![image](https://user-images.githubusercontent.com/13705380/130293563-78562a8f-d815-41c9-9c45-80af90cec983.png)

**Comment by IndefiniteBen** [comment]
There is already a toggle to turn off taskbar integrations? Unless you have an older version without this toggle?
![image](https://user-images.githubusercontent.com/17594572/147762397-0121060e-a08d-48ef-89ed-b43301aa1ff8.png)
Settings > Playback > Show track progress on taskbar

**Comment by zwamdurkel** [comment]
I guess I must've had an older version at the time of writing this, or I'm blind. This solves the issue for me. I'll close the issue because the "clear queue" functionality I also mentioned is not related to the core issue, it was an alternative solution.
