### ISSUE TITLE
Bottom part of window cuts off player controls

### ISSUE THREAD

**Issue by bboles** [ytmdesktop/ytmdesktop#800]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
The bottom part of the player controls are cut off by the bottom part of the window.  This issue started occurring after upgrading from MacOS Catalina to Big Sur but with the same version of the app on both MacOS versions.

**To Reproduce**
Execute ytmdesktop.  This behavior is present whether the app is fully maximized or windowed.  This behavior **is not** present with the app in full screen mode.

**Expected behavior**
The player controls should be fully visible regardless if in full screen, maximized or windowed mode.

**Screenshots**
![Screen Shot 2021-08-26 at 11 10 57 AM](https://user-images.githubusercontent.com/6370528/131016102-e17f6d8a-2464-4849-b869-1f4912a0f90e.png)

**Environment (please complete the following information):**
 * YTMDesktop version:  1.13.0
 * OS: MacOS
 * OS version: 11.5.1
 * Arch: x64
* Installation way: `brew install ytmdesktop-youtube-music`

**Comment by Alipoodle** [comment]
Can I ask if this issue is still occuring?

**Comment by joosniz** [comment]
I'm using Windows 10 and have the same issue but only when maximized. It seems related to the titlebar setting, if you enable the 'Disable titlebar' setting it also crops the bottom of the window, 'System' and 'Nice' don't exhibit the same issue.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
