### ISSUE TITLE
Discord Integration Not Functioning 

### ISSUE THREAD

**Issue by ScottDaybreak** [ytmdesktop/ytmdesktop#803]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Click on 'Click on Discord Rich Presence'
3. Doesn't work

**Expected behaviour**
It is supposed to make a status for the Youtube Music Client showing off the music and all that.

**Screenshots**

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.14.0***
 * OS: Windows
 * OS version: 20H2
 * Arch: x64
* Installation way: .exe

**Comment by NovusTheory** [comment]
Try restarting both Discord & ytmdesktop. There's issues where it may not correctly connect. I've tried to debug this problem but it seems like an issues with either Windows (or maybe other OS's too) or Discord

**Comment by ScottDaybreak** [comment]
> Try restarting both Discord & ytmdesktop. There's issues where it may not correctly connect. I've tried to debug this problem but it seems like an issues with either Windows (or maybe other OS's too) or Discord

I tried everything but nothing worked. Does BetterDiscord have anything to do with this? Since I use it all the time.

**Comment by ScottDaybreak** [comment]
Now it suddenly works for some strange reason

**Comment by NovusTheory** [comment]
> Now it suddenly works for some strange reason

This is why I said I don't know why because it's hard to debug.

Anyone coming across that's more technical, the issue is the remote connection keeps getting closed over and over and I have no idea why it does this. It feels like the app can't do anything about it.
