### ISSUE TITLE
Unable to login if 2FA is enabled

### ISSUE THREAD

**Issue by lekoOwO** [ytmdesktop/ytmdesktop#804]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Login stucks at 2FA if Android phone embed Security Key is used as the 2FA security key.

**Expected behavior**
The phone request user to verify their identity, or the 2FA fails and ask user to select another 2FA method if the app or PC cannot communicate with the phone using bluetooth.

**Screenshots**
![image-redacted_dot_app (1)](https://user-images.githubusercontent.com/20151124/131216042-d43ff2e2-8f92-485e-a85e-77cc9f991f21.png)

**Environment (please complete the following information):**
* YTMDesktop version: ***v1.13.0***
 * OS: ***darwin***
 * OS version: ***11.5.2***
 * Arch: ***x64***
 * Installation way: ***brew***

**Comment by kudlav** [comment]
Hi,
same with MacOS and hardware key (Yubikey).
It was working but now both 1.13 and 1.14 versions are broken.

**Comment by oDn** [comment]
I'm having the same issue running v1.13.0 as a snap on Ubuntu 21.04.

**Comment by narthollis** [comment]
I am also stuck on a use security key 2-step verification prompt. Previously I was able to chose an alternate 2FA process (TOTP code for example)

**Comment by Wolfeboi2** [comment]
Same issue on Pop_OS! 21.04

**Comment by Alipoodle** [comment]
Extension of #110
