### ISSUE TITLE
Discord integration not working on Linux Mint 20.2 Uma

### ISSUE THREAD

**Issue by Witherx2** [ytmdesktop/ytmdesktop#808]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Ive been tinkering with it for a while now, reinstalled from various places, restarted discord and the whole jazz, and the status still doesn't update itself.

**To Reproduce**
1. Enable discord integration
2. Start playback of song
3. Select song name from activity list
3. Wait for song to end or skip to next song
4. See that the status has not updated

**Expected behavior**
The integration to change the status

**Screenshots**
https://imgur.com/a/X6akFaO 

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Linux***
 * OS version: ***Mint 20.2 Uma***
 * Arch: ***x86_64***
* Installation way: ***first tried appimage ran as an executable but then used an app image launcher, neither work***

**Comment by Alipoodle** [comment]
Closing this issue due to no response in a long time.
Additionally due to Discord's lack of support for Linux anymore, this is likely a Discord issue than an YTM Issue.
