### ISSUE TITLE
Notification entry in Android app

### ISSUE THREAD

**Issue by zejjnt** [ytmdesktop/ytmdesktop#813]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like the Android app to make a persistent (as long as the app is open) notification like any other media player does. This would in turn make it possible to control YTMD from my Amazfit smartwatch.

**Describe alternatives you've considered**
I guess I could make a notification using Automate and then make it send requests to the YTMD API, (if I could get Amazfit Zapp or Notify for Amazfit to recognize it as a media player) but that would be pretty much the ugliest hack I've done without having a missed deadline at work.

**Additional context**
Every other media player and their remote control has this. I realize that the remote control app has pretty much zero priority but it would be a very nice touch which I wouldn't imagine takes much time to implement (although I don't know Java or whatever Android apps are made in nowadays, but in theory)

**Comment by kudlav** [comment]
If the source code for Remote Player were available, I'm sure it wouldn't be a problem to implement and fix the many other bugs the app has.

**Comment by kudlav** [comment]
Sorry, it is here: https://github.com/ytmdesktop/remote
Cannot promise anything but I will look at it.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
