### ISSUE TITLE
Support for Surround Sound

### ISSUE THREAD

**Issue by LillyWho** [ytmdesktop/ytmdesktop#814]
I understand that YTMDesktop have NO affiliation with Google or YouTube.
 I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Sort of. I've recently acquired a second set of speakers and set them up as quadraphonic in my sound card settings. Google Play Music Desktop Player had the option to enable surround sound streams. Since apparently it's not being updated anymore, I've switched to YTMDesktop, so I'm now missing that feature. Pretty much the only one I lost since making the switch, that I know of.

**Describe alternatives you've considered**
I can only listen to songs that I have locally as MP3 on WMP in surround, the rest is lacking that awesome surround.

**Additonal context**
YTM may not be _the_ audiophile platform, but I'd imagine some people might have even better setups and would enjoy listening to the full spectrum of their songs.

Thank you for your consideration!

**Comment by Alipoodle** [comment]
The way in which GPMDP Achieved it was using a Chromium Option which used a flag to try a new surround sound supported Audio engine, `try-supported-channel-layouts`.
Can be seen in this [PR](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/commit/4b1171f1c52709ba91301f8687647f522ca9850b#diff-058ed77e6ef6675b1b2a49aa203625c7da6205fdaff1b1b69d0a2e8847e6795c)

It appears this feature may still exist [Chromium Bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1110734&q=try-supported-channel-layouts&can=1) as a Flag, but will need to be tested it still works.

Curious to know if YTM Actually sends audio which will work for Surround sound.

**Comment by LillyWho** [comment]
> Curious to know if YTM Actually sends audio which will work for Surround sound.

Whether it was true surround or whether it was the Speaker Fill feature for converting stereo into pseudo surround I don't exactly know, but I do know it sounded quite awesome. Just a footnote, anyway. 👍 
Currently it very distinctly only sends on my front set of speakers.

**Comment by Alipoodle** [comment]
If you want to try this now it might be possible via:

Open a CMD Window and run the following command:
`%localappdata%\programs\youtube-music-desktop-app\YouTube Music Desktop App.exe --try-supported-channel-layouts`
This should start the YTMD with the option enabled. I'm only on headphones so cannot verify if it changes anything.

**Comment by LillyWho** [comment]
Confirmed working, but only when the Speaker Fill effect is enabled. Apparently it's still in some way a stereo only stream? Speaker fill is intended for stereo only playback, to be filled onto all speakers, to get pseudo surround. Using the flag alone without the effect enabled does nothing. Doesn't make much sense, does it?

**Comment by Alipoodle** [comment]
So this flag is what Google Play Music Desktop Player uses for doing speaker fill, but it is on a lot order of a version of electron so it's possible that the flag may no longer function as noted it's been kinda been removed from the chrome flags page but not as a startup options.


So are you able to confirm if my CMD thing does work?
If so then I should be able to copy the code from GPMDP to do the same in YTMD

**Comment by LillyWho** [comment]
> So this flag is what Google Play Music Desktop Player uses for doing speaker fill, but it is on a lot order of a version of electron so it's possible that the flag may no longer function as noted it's been kinda been removed from the chrome flags page but not as a startup options.
> 
> So are you able to confirm if my CMD thing does work?
> If so then I should be able to copy the code from GPMDP to do the same in YTMD

As I said above, it does, the way I described. Not true surround, and I would have hoped at least some songs had data for more than just two speakers, but apparently not (or Electron itself is downmixing back to stereo for some reason)

**Comment by Alipoodle** [comment]
Knowing YouTube music.
It's all Stereo music.

I'll see if I can get a PR in for this so the option is available in next release

**Comment by LillyWho** [comment]
![image](https://user-images.githubusercontent.com/5427724/132913575-abe50b70-4ef6-4b6a-ad07-7c82e469a2ab.png)
It's also possible that for true surround there needs to be more done than just the one flag. I've enabled this flag in my Chromium and some 5.1 sound check videos do actually produce real surround sound according to the speakers that I actually have. Since this flag exists, it might be worth investigating a bit deeper.

**Comment by Alipoodle** [comment]
Well without a 5.1 surround sound setup in my PC this is a little difficult 😅.

I'll see a bit into this flag as well to see if it's a boot option as well, a d stuff.

**Comment by LillyWho** [comment]
To clarify, I don't actually know if this made surround work completely on Chromium in the first place. I just enabled it just to be sure.
I'll check just to be sure. I also don't know if the "default" setting already had it enabled.

**Comment by LillyWho** [comment]
It works, only because of speaker fill. We're getting to a point where I'm doubting Realtek's drivers. Test video used: https://www.youtube.com/watch?v=_ttYSpt8oiw

**Comment by Alipoodle** [comment]
Can I ask which flags worked for Speaker Fill?

**Comment by LillyWho** [comment]
The one you suggested did. But the one with WebRTC makes no difference, and supposed surround sound test videos only operate like a stereo stream stretched onto the rest of the speakers.

**Comment by LillyWho** [comment]
Any updates?

**Comment by Alipoodle** [comment]
Hey, I plan to work on this, this coming weekend.
ALTHOUGH Please note that this will be going into Development and not into a Public released build at the time of finishing it.

I hope that we can finalise a Release soon to provide a lot of fixes and features which have been in Development build for the last year.

**Comment by LillyWho** [comment]
No problem. I'm running my own compiled version right now anyway. 😆

**Comment by LillyWho** [comment]
@Alipoodle I've cherry-picked your commit and it does work, but I don't know if I missed out on a detail. The translation string doesn't seem to be working on the setting: 
![image](https://user-images.githubusercontent.com/5427724/141357402-28594bac-1356-4168-8362-39999ac37f55.png)

**Comment by Alipoodle** [comment]
I've not included the Translation string Natively within the Locale used within 1.13...
I've included a PR over on [ytmdesktop-locale](https://github.com/Alipoodle/ytmdesktop-locales/commit/665dc3342659b0c24d151e706834c1b159734a0f) for this instead though as this is where the future development for locales are.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
