### ISSUE TITLE
'Oops something went wrong' -> No track information when playing radio

### ISSUE THREAD

**Issue by TobiasDeBruijn** [ytmdesktop/ytmdesktop#822]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**

When starting a radio, in the bottom left a small popup will appear 'Oops something went wrong'. No track information will be displayed, however it will show if the track is liked/disliked/in the library. The track plays audio too. Besides this, the music queue is also empty. The window title is not updated either. This behavior is not present when playing an album. 

This is new behavior, started either today or yesterday. No changes to the app or my OS took place since the last time it worked. Perhaps it's a change in the Google API

**To Reproduce**
1. Select a radio
2. Play it
3. Observe

**Expected behavior**
The track and queue information is shown

**Screenshots**

When starting from radio:
![image](https://user-images.githubusercontent.com/28569170/133894875-04b2d7da-0cae-4805-afb9-b5206c03517c.png)

When playing a playlist:
![image](https://user-images.githubusercontent.com/28569170/133894916-07474161-30dc-4e3e-a8bc-06df560050d8.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows**
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***exe***

**Comment by Alipoodle** [comment]
In all cases of what you're saying, this is a YT Music issue and not a Issue with the program.
Please try reporting this to YouTube Music's Support rather than us.

We shouldn't be touching anything which deals with this logic.

**Comment by TheDutchMC** [comment]
I had such a suspicion before opening the issue. However everything works fine at https://music.youtube.com, while in the app it does not

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
