### ISSUE TITLE
Slows down over the course of a couple days

### ISSUE THREAD

**Issue by jasekiw** [ytmdesktop/ytmdesktop#825]
- [ x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x ] I verified that there is no open issue for the same subject.

**Describe the bug**
This is similar to other slowness issues people are having but I'm creating a new issue because mine seems unique in the fact that it is not immediately slow but over the course of a day or two the UI becomes almost unusable. Almost every interaction takes almost 5 seconds to complete.

Interesting enough Puase/Play works immediately but expanding/shrinking the current playing songs takes anywhere from immediately to 3 seconds. Changing tabs at the top take about 5 -7 seconds. The cursor will show a pointer icon  indicating that no user events are being processed until the whole view is finished rendering. This is not an issue with internet connection because if I restart the app, everything is fast again. The issue seems to be specific to painting new DOM nodes or DOM manipulation. I notice it I hit F12 to try to bring up dev tools (which doesn't work) the music progress bar pauses for a good 5 seconds.

I've had this issue with the old Google Play Music Desktop and Youtube Music Desktop. I'm not sure if it's electron related or app related.

The Memory usage is around 940mb with 6% CPU usage

**To Reproduce**
Use Windows 10, Leave the app open for more than a day.

**Expected behavior**
The app should stay fast or at least not become unusable (multiple seconds in response to paint events).

**Screenshots**
![image](https://user-images.githubusercontent.com/4037224/134694313-8aac520c-b525-40f5-9b96-d6a811b6a1dd.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by Alipoodle** [comment]
This sounds to be General Memory Leak.
This has come up within a number of different issues before.

Although we believe this more to be an Issue you YouTube Music's causing a lot of the Memory Leakage with their own systems.

**Comment by jasekiw** [comment]
On the second day and haven't noticed a slowdown when opened in chrome. I'll keep and updating the progression here.

**Comment by jasekiw** [comment]
Several days in and I didn't notice any slowdown using chrome. Although on the 4th day the tab crashed.

**Comment by jasekiw** [comment]
@Alipoodle Maybe we can try loading youtube music into a default electron app and see if the issue appears there?

**Comment by BlacRyu** [comment]
![image](https://user-images.githubusercontent.com/10762433/144719600-de9cf415-20a5-417b-b61b-5e1c3427f823.png)

![image](https://user-images.githubusercontent.com/10762433/144719598-8db02793-8225-48db-a493-319bbe828b08.png)

YTMD was using ~7GB for me after about 6 days of running. Gonna start using the browser and see if that works better.

This was on the '1.13.0-nightly' build tagged as 'latest'. I see there is a new build out now so I'll try that later as well.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
