### ISSUE TITLE
When unlocking Windows, YTMD sometimes plays music to default WME device instead of configured device

### ISSUE THREAD

**Issue by jwatte** [ytmdesktop/ytmdesktop#831]
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**

Sometimes when I log back into my Windows desktop, YouTube Music Desktop starts playing music on the wrong music device.

**To Reproduce**
1) Configure youtube music desktop to play to a non-default device in settings
2) Play music and verify it's coming from the non-default device
3) Pause and lock Windows screen
4) Unlock Windows screen and start playing again
5) Sometimes, YTMD plays back on the default audio output device, rather than the configured device
6) Opening and closing the settings panel, and then navigating in the UI (e g, going to "home") will usually make it switch back to the configured device

**Expected behavior**
I expect YTMD to still play back on the configured device at all times

**Screenshots**

How it's configured:
![image](https://user-images.githubusercontent.com/481909/135384733-ff1ee456-47a5-490b-9cdb-77449f6f2b92.png)

How it's supposed to play:
![image](https://user-images.githubusercontent.com/481909/135384751-995d80c6-11d1-4c07-a926-8e2b002cdfa5.png)

How it actually plays when this happens:
![image](https://user-images.githubusercontent.com/481909/135384760-45640eba-c5f4-4d92-8959-6e1d1e8d5c16.png)

What my Sound Devices control panel says:
![image](https://user-images.githubusercontent.com/481909/135384784-2b0d2a93-3cef-45fb-9aed-ba2e06e7c2d8.png)
(This is less helpful than the old one IMO, but it's what we get these days. I clicked the menu to show the available devices.)

This is using a RME Babyface Pro FS USB sound device, with the latest driver (firmware version 125, driver 1.212.)

"Speakers" is the default output on the computer, a k a "Analog (1 + 2)" inside the RME setup panel and is labeled "Computer" in the RME mixer screen shot.
As you can see above, YTMD is configured to play through "Analog (3 + 4)" which is labeled "Music" in the RME mixer screen shot.

**Environment (please complete the following information):**
 * YTMDesktop version: 1.13.0
 * OS: Windows 10 Pro
 * OS version: 19043
 * Arch: x64
* Installation way: Self-updated after regular Windows download install.

**Comment by agaertner** [comment]
+1 Extremely annoying when you are trying to redirect music while streaming. Makes ytmusicdesktop unusable for this purpose. 
It just switches back to the default device when the next song starts playing. Essentially, device selection is not usable and broken.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
