### ISSUE TITLE
Enable windows 11 media service

### ISSUE THREAD

**Issue by Mrangelito** [ytmdesktop/ytmdesktop#832]
- [ ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ ] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Alipoodle** [comment]
Hi there, Can you please fill out the information within the issue and not leave everything blank.
Additionally please include your Win11 version and YTM Version

This sounds like this is just an issue with Windows 10 Media service not correctly building, which has been fixed in the Development build as per #614

**Comment by dansauve** [comment]
When I play music from Edge I get a card like this in Action Center. This doesn't appear for me using either 1.14 or the 1.13 nightly.

![image](https://user-images.githubusercontent.com/17929251/138091093-f1e0389d-d5b4-43d4-8883-7117c9a9101d.png)

**Comment by NinjaShuriken** [comment]
This already works for me on my PC including play/pause/next/prev but it can take a second for the album art/name to update
![image](https://user-images.githubusercontent.com/59803779/141050158-8bb13456-c59c-4cca-b81d-0cbe99b80606.png)

**Comment by adkeyz** [comment]
Not working for me either in 1.14 or 1.13 nightly.

**Comment by Alipoodle** [comment]
Nightly (Basically 1.13 with 1/2 added features) & 1.14 sadly do not have the #614 fixes added into them which are a "minor" patch to the Windows Media services fix.

I'm planning on updating the nightly to be a Pre-release of a more real 1.14 which should have a better fix for the Media Service.

There's a Draft PR being made for Xosms which will hopefully fix this issue for good being a cross platform implementation of a Media service.

**Comment by adkeyz** [comment]
Thanks @Alipoodle, look forward to a future update.

**Comment by Alipoodle** [comment]
Looking through some information and test stuff, Win11 doesn't actually need anything done.
My guess is that the build of the NodeRT was just broken in the version used. 🤔

Can I get an update if this is still an issue, otherwise I will make this as stale in a week!

**Comment by dansauve** [comment]
Works for me on 1.14.2 nightly (W11 beta 22621.1)

**Comment by SomeAspy** [comment]
This also works fine for me.
Win 11 Pro 22616.100
Youtube Music 1.14.2

https://user-images.githubusercontent.com/33640860/170133285-5f6a31a9-01d1-4f07-bdb3-85abb73bc203.mp4

**Comment by Alipoodle** [comment]
My assumptions were correct! Am closing this issue!

**Comment by Mrangelito** [comment]
For the moment is ok in my two device, I install new preview. Only need to restart windows media setting. Work to lock screen

https://user-images.githubusercontent.com/70352855/170607224-40a973a4-3e1a-4519-8bc7-e7a0588f0d54.mp4


https://user-images.githubusercontent.com/70352855/170607227-ba7d4d1a-e505-474f-9223-5d72a2159ad9.mp4
