### ISSUE TITLE
Like/Dislike positioning

### ISSUE THREAD

**Issue by DorCoMaNdO** [ytmdesktop/ytmdesktop#836]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
This is quite nitpicky but I prefer to have the Like button on the left and Dislike on the right, it's how YouTube has it, it's how GPM had it, but for some weird reason, it's reversed in YouTube Music.

**Describe the solution you'd like**
A toggle to reverse the order of the two buttons, both in the main program UI as well as the peek thumbnail in the taskbar.

**Describe alternatives you've considered**
In the browser I use a styling rule with uBlock that utilizes the fact that the order flips when using RTL languages:
`music.youtube.com##ytmusic-like-button-renderer:style(direction:rtl)`
~~However the following does not work with YTMDesktop's theme feature:~~ Right after posting this I realized the theme rule is supposed to target an element not a class (remove the dot), so this now works with YTMDesktop, however this does not affect the taskbar buttons.
```css
.ytmusic-like-button-renderer
{
    direction: rtl;
}
```
Unless I'm missing something, dev tools appear to be disabled (F12, CTRL+SHIFT+I and CTRL+SHIFT+C for inspect element do not work) ~~so I can't create a proper rule for YTMDesktop.~~

**Additional context**
![image](https://user-images.githubusercontent.com/5393267/136826414-cedd2264-461e-48a8-bdb7-0dd20ce02303.png)

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
