### ISSUE TITLE
Bug: Playback controls cropped off with system titlebar

### ISSUE THREAD

**Issue by Margiris** [ytmdesktop/ytmdesktop#85]
When "System" is selected as Title Bar Style the playback controls get cropped off and only top half is visible, as seen in this pic:
![image](https://user-images.githubusercontent.com/34870816/72605729-0003a200-3926-11ea-8651-7b81d089d5e4.png)

Resizing, restarting the program etc. didn't help.

System info:

- Windows 10 v1909
- YTMDesktop v1.8.1

**Comment by adlerluiz** [comment]
@Margiris thanks, I will check this bug and fix it.
