### ISSUE TITLE
Auto Set Region to Global

### ISSUE THREAD

**Issue by Nou4r** [ytmdesktop/ytmdesktop#861]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

![YouTube_Music_Desktop_App_wh2zlbxAGh](https://user-images.githubusercontent.com/12816677/139576821-513f1fc1-cc69-4f30-a8f5-db4436df9de6.png)
Would be a very useful  and appreciate feature, im sure.
Thanks for the hard work on the cool project^^

**Comment by Alipoodle** [comment]
Closing this issue as a "too niche" of a feature to have. 🤷
