### ISSUE TITLE
ShortCut Key & System Tray Control Broken

### ISSUE THREAD

**Issue by criticalsoft** [ytmdesktop/ytmdesktop#867]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Previous Track Is Pause Now
Next Track Is Previous 10 Second

### Expected Behavior

Previous Track Is Previous Track
Next Track Is Next Track

### Steps To Reproduce

Just Run And Control Music Using ShortCut Key Or System Tray

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Within YTM Desktop can you run `SHIFT + /`
Can you confirm that it looks like the following:

![image](https://user-images.githubusercontent.com/17199186/141326716-4748afd7-963c-449a-a1e3-d7f71f462a7b.png)

**Comment by criticalsoft** [comment]
The J / K Shortcut At Normal YouTube Music (Not YouTube Music Premium) Is
![141481832-d40f26e7-7182-49d6-8822-5f91080d0235](https://user-images.githubusercontent.com/68728459/141495332-3f3cf977-1c9d-49b8-a52e-a45f7f57a5af.png)

But, Anyway The Common Shortcut Key Is Shift + P / N

**Comment by Alipoodle** [comment]
First of all you're showing YT and not YTM.
    The controls on YouTube Match-up with what I see on YouTube, but are different to YouTube's ones.
Additionally you're showing what looks to be the a different application than us, or a very old version of YTM Desktop and not the version 1.13 which you have said you are using.

I'm a little confused at the moment towards everything here. 😅

**Comment by criticalsoft** [comment]
> 
> 
> First of all you're showing YT and not YTM. (Premium makes no difference) The controls on YouTube Match-up with what I see on YouTube. However the Controls which are shown on YouTube are different to the ones on YouTube Music. Additionally you're showing what looks to be the a different application than us, or a very old version of YTM Desktop and not the version 1.13 which you have said you are using.
> 
> I'm a little confused at the moment towards everything here. 😅

App differrent It Doesn't Matter, You have same problem.
I'm just lazy to install your app & capture & uninstall ....

**Comment by criticalsoft** [comment]
![20211113_023340_YouTube_Music (YouTube_Music_Desktop_App)](https://user-images.githubusercontent.com/68728459/141509986-cf9a254b-2947-4e46-81e5-61765b1feda2.png)

**Comment by criticalsoft** [comment]
![20211113_023832_mediaProvider js_-_ytmdesktop_-_Visual_Studio_Code (Code)](https://user-images.githubusercontent.com/68728459/141510813-27f538ac-d1ce-4c94-9248-6a3b2ca91519.png)
I Can't Submit, Because I'm facing build Error https://github.com/ytmdesktop/ytmdesktop/issues/868
