### ISSUE TITLE
Build Stucked At "rebuilding native dependencies  dependencies=bufferutil"

### ISSUE THREAD

**Issue by criticalsoft** [ytmdesktop/ytmdesktop#868]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Build Stucked

### Expected Behavior

Secessfully Build

### Steps To Reproduce

git clone
npm install / yarn install

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

npm / yarn

**Comment by Alipoodle** [comment]
The current stable version of building in the Master/Main Build may have issues at the moment.
We've moved over to using the Development Branch at the moment to fix issues with the lock files and issues with Windows' Specific libraries being a complete mess.

Please try the development build, and can you please note you node & yarn version you are using if you are still having issues with the development build!

**Comment by criticalsoft** [comment]
> 
> 
> The current stable version of building in the Master/Main Build may have issues at the moment. We've moved over to using the Development Branch at the moment to fix issues with the lock files and issues with Windows' Specific libraries being a complete mess.
> 
> Please try the development build, and can you please note you node & yarn version you are using if you are still having issues with the development build!

OK, Thanks for the reply.

**Comment by criticalsoft** [comment]
> 
> 
> > The current stable version of building in the Master/Main Build may have issues at the moment. We've moved over to using the Development Branch at the moment to fix issues with the lock files and issues with Windows' Specific libraries being a complete mess.
> > Please try the development build, and can you please note you node & yarn version you are using if you are still having issues with the development build!
> 
> OK, Thanks for the reply.

Development Branch is the same.

**Comment by criticalsoft** [comment]
Development Branch Is The Same.

**Comment by criticalsoft** [comment]
> 
> 
> The current stable version of building in the Master/Main Build may have issues at the moment. We've moved over to using the Development Branch at the moment to fix issues with the lock files and issues with Windows' Specific libraries being a complete mess.
> 
> Please try the development build, and can you please note you node & yarn version you are using if you are still having issues with the development build!

Development Branch Is The Same.

**Comment by Alipoodle** [comment]
Can you provide:
Node & Yarn version and any errors you're getting

**Comment by criticalsoft** [comment]
v14.18.1 1.7.0

**Comment by criticalsoft** [comment]
> 
> 
> Can you provide: Node & Yarn version and any errors you're getting

v14.18.1 1.7.0

**Comment by criticalsoft** [comment]
Building the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.
  _nodert_generated.cpp
  NodeRtUtils.cpp
  OpaqueWrapper.cpp
  CollectionsConverterUtils.cpp
  win_delay_load_hook.cc
..\\OpaqueWrapper.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\\DESKTOP\\ytmdesktop-development\\node_modules\\@nodert-win10-rs4\\windows.storage.streams\\build\\binding.vcxproj]
..\\_nodert_generated.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\\DESKTOP\\ytmdesktop-development\\node_modules\\@nodert-win10-rs4\\windows.storage.streams\\build\\binding.vcxproj]
..\\CollectionsConverterUtils.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\\DESKTOP\\ytmdesktop-development\\node_modules\\@nodert-win10-rs4\\windows.storage.streams\\build\\binding.vcxproj]
..\\NodeRtUtils.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\\DESKTOP\\ytmdesktop-development\\node_modules\\@nodert-win10-rs4\\windows.storage.streams\\build\\binding.vcxproj]
C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\src\\win_delay_load_hook.cc : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\\DESKTOP\\ytmdesktop-development\\node_modules\\@nodert-win10-rs4\\windows.storage.streams\\build\\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd D:\\DESKTOP\\ytmdesktop-development\\node_modules\\@nodert-win10-rs4\\windows.storage.streams
[12/12] ⠄ windows.media.playback
[9/12] ⡀ @nodert-win10-rs4/windows.foundation
[3/12] ⡀ register-scheme
[10/12] ⡀ @nodert-win10-rs4/windows.media
error D:\DESKTOP\ytmdesktop-development\node_modules\windows.media.playback: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\DESKTOP\ytmdesktop-development\node_modules\windows.media.playback
Output:
D:\DESKTOP\ytmdesktop-development\node_modules\windows.media.playback>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.18.1 | win32 | x64
gyp info find Python using Python version 3.7.3 found at "C:\Users\ME\AppData\Local\Programs\Python\Python37\python.exe"
gyp info find VS using VS2015 (14.0) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\ME\AppData\Local\Programs\Python\Python37\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\DESKTOP\\ytmdesktop-development\\node_modules\\windows.media.playback\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\DESKTOP\\ytmdesktop-development\\node_modules\\windows.media.playback\\common.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ME\\AppData\\Local\\node-gyp\\Cache\\14.18.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ME\\AppData\\Local\\node-gyp\\Cache\\14.18.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\ME\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.18.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\DESKTOP\\ytmdesktop-development\\node_modules\\windows.media.playback',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\DESKTOP\\ytmdesktop-development\\node_modules\\windows.media.playback\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  _nodert_generated.cpp
  NodeRtUtils.cpp
  OpaqueWrapper.cpp
  CollectionsConverterUtils.cpp
  win_delay_load_hook.cc
..\_nodert_generated.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\DESKTOP\ytmdesktop-development\node_modules\windows.media.playback\build\binding.vcxproj]
..\NodeRtUtils.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\DESKTOP\ytmdesktop-development\node_modules\windows.media.playback\build\binding.vcxproj]
..\CollectionsConverterUtils.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\DESKTOP\ytmdesktop-development\node_modules\windows.media.playback\build\binding.vcxproj]
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\DESKTOP\ytmdesktop-development\node_modules\windows.media.playback\build\binding.vcxproj]
..\OpaqueWrapper.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\DESKTOP\ytmdesktop-development\node_modules\windows.media.playback\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\DESKTOP\ytmdesktop-development\node_modules\windows.media.playback

**Comment by criticalsoft** [comment]
success Saved lockfile.
$ npx electron-builder install-app-deps
  • electron-builder  version=22.13.1
  • loaded configuration  file=D:\DESKTOP\ytmdesktop-development\electron-builder.yml
  • rebuilding native dependencies  dependencies=bufferutil@4.0.5, register-scheme@0.0.2, utf-8-validate@5.0.7 platform=win32 arch=x64
  • rebuilding native dependency  name=bufferutil version=4.0.5

**Comment by Alipoodle** [comment]
From your most recent message, it looks like you've got it to install the stuff HOWEVER, you don't seem to have the window specific libraries needed for the Windows Media service. (The main issue of this all)

Seems like you're missing some libraries which are needed for the Windows specific libraries to install. 😅 [From the errors]

There's two options.
1. Due to this being an issue which is not directly due to us and more with Window's Build, it's not something which I'm going to spend Hours to try and fix, but I'll try what I can find online.
   However it seems like someone may have a potential fix here: https://stackoverflow.com/questions/42157554/nodert-could-not-find-assembly

2. Run the Build without the Windows specific libraries, and remove them from the Package.json and try re-building.
   The software is setup so that you can run it if these libraries don't exist as we've had a few issues with them for a while.

**Comment by criticalsoft** [comment]
> 
> 
> From your most recent message, it looks like you've got it to install the stuff HOWEVER, you don't seem to have the window specific libraries needed for the Windows Media service. (The main issue of this all)
> 
> Seems like you're missing some libraries which are needed for the Windows specific libraries to install. 😅 [From the errors]
> 
> There's two options.
> 
>     1. Due to this being an issue which is not directly due to us and more with Window's Build, it's not something which I'm going to spend Hours to try and fix, but I'll try what I can find online.
>        However it seems like someone may have a potential fix here: https://stackoverflow.com/questions/42157554/nodert-could-not-find-assembly
> 
>     2. Run the Build without the Windows specific libraries, and remove them from the Package.json and try re-building.
>        The software is setup so that you can run it if these libraries don't exist as we've had a few issues with them for a while.

yarn upgrade Passed.
I Should Do A Little More Search Or I Should Not Start This Issue.

**Comment by criticalsoft** [comment]
I Should Not Start This Issue.
Good Luck.

**Comment by criticalsoft** [comment]
> 
> 
> From your most recent message, it looks like you've got it to install the stuff HOWEVER, you don't seem to have the window specific libraries needed for the Windows Media service. (The main issue of this all)
> 
> Seems like you're missing some libraries which are needed for the Windows specific libraries to install. 😅 [From the errors]
> 
> There's two options.
> 
>     1. Due to this being an issue which is not directly due to us and more with Window's Build, it's not something which I'm going to spend Hours to try and fix, but I'll try what I can find online.
>        However it seems like someone may have a potential fix here: https://stackoverflow.com/questions/42157554/nodert-could-not-find-assembly
> 
>     2. Run the Build without the Windows specific libraries, and remove them from the Package.json and try re-building.
>        The software is setup so that you can run it if these libraries don't exist as we've had a few issues with them for a while.

master Branch Passed yarn upgrade, development Branch Not.
I'm not sure how long it will take to resolve, I Should Not Start This Issue.
Good Luck.
