### ISSUE TITLE
Discord Rich Presence should say "Listening to" instead of "Playing"

### ISSUE THREAD

**Issue by Da1Penguan** [ytmdesktop/ytmdesktop#869]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Right now, when you play a song with Discord integration, it says that you are "playing YouTube Music", when it should really say "Listening to YouTube Music" like Spotify does.
![image](https://user-images.githubusercontent.com/48372164/141566035-28b34b74-fb1d-4a2b-b0f2-8abf19a091f6.png)
![image](https://user-images.githubusercontent.com/48372164/141569688-7e8b5ff3-0a27-4146-83ae-446484d7bdc5.png)

**Comment by NovusTheory** [comment]
This is not possible, Discord limitations

**Comment by Da1Penguan** [comment]
oh okay, didn't know that. too bad then
