### ISSUE TITLE
Full Screen Background

### ISSUE THREAD

**Issue by vy0** [ytmdesktop/ytmdesktop#870]
### Consent

- [x] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

A better full screen option at least for the background.

### Solution

Using the song cover and zooming it in all the way makes it look odd and is overall not friendly when it comes to white images. I recommend doing what YouTube did and having maybe a drop shadow over the progress bar and having a darker background regardless of the image with the image in the center.

**Comment by Alipoodle** [comment]
Is this for the Miniplayer?

**Comment by Alipoodle** [comment]
Hi there, can you please provide some more information of this.

This sounds like something which can be achieved through custom CSS of your own rather than something to be implemented entirely into the app.

**Comment by Alipoodle** [comment]
No information has been provided in 24 days, so closing the issue.
