### ISSUE TITLE
Playlist disappear when click on any track after started a "radio" 

### ISSUE THREAD

**Issue by juanobrach** [ytmdesktop/ytmdesktop#872]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When you start a radio and the app redirects to the playlist songs and then you click on any track the playlist disappears.

![image](https://user-images.githubusercontent.com/7152145/142502069-f30e8cff-cfe6-4ee8-85ce-b84888063ab6.png)

### Expected Behavior

The playlist should be visible ever

### Steps To Reproduce

1. Click on start radio from a track menu
2. App goes to the playlist
3. Click on any track in the playlist
4. Playlist disappear :*(

### YTMDesktop

v1.13.0

### OS

Linux Pop Os

### OS Version

21.04

### Arch

x64

### Installation way

snapshot

**Comment by Alipoodle** [comment]
Can you confirm that this issue doesn't happen within the Web / PWA of YouTube Music.
We don't really do anything regarding manipulating of the current queue, but we do look at what songs are being played.

**Comment by Alipoodle** [comment]
No information provided within 24 days, closing issue.
