### ISSUE TITLE
Is there no way to see Comments for a video, or otherwise get to the web page for it?

### ISSUE THREAD

**Issue by rw3iss** [ytmdesktop/ytmdesktop#873]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

It seems there's no link to the webpage for any given song that is playing, as I'm looking for a way to see comments or discussion for a track. 
Does this not exist, or am I missing it/

### Solution

Either a tab next to 'Lyrics', for example, to show the comment thread. Otherwise, a simple link or button to the webpage for the playing track somewhere.

**Comment by Alipoodle** [comment]
YouTube music natively does not have an option to be able to show comments.

- YouTube music uploaded videos have comments disabled as of about 6 months ago, and therefore will never have them.
- Only the videos/music videos would have them.

**Comment by Alipoodle** [comment]
[YT Music](https://music.youtube.com/watch?v=tH9Imv5afwQ&feature=share)
[YouTube copy](https://youtube.com/watch?v=tH9Imv5afwQ&feature=share)

At the bottom is showing the comments are disabled
![Screenshot_20211123-210857__01](https://user-images.githubusercontent.com/17199186/143128649-5e7d4464-3149-4822-8f87-2238c11c8bbe.jpg)

**Comment by rw3iss** [comment]
Ahh, thanks for clarifying. I just subscribed. I thought YouTube music was just YouTube Premium housed from a music perspective ;p.
