### ISSUE TITLE
Tracks are being scrobbled with the wrong title

### ISSUE THREAD

**Issue by skerit** [ytmdesktop/ytmdesktop#875]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I made a playlist with quite a few songs in them. When I shuffle play it, each song that is played is being reported as the first song that started playing.

For example:

![image](https://user-images.githubusercontent.com/755212/143854303-9eea3e73-2470-4788-ada8-304fa4ad2773.png)

"Main Title" was the first song that started playing, but I only played it once.

### Expected Behavior

Every played song should be scrobbled with the correct data

### Steps To Reproduce

1. Create a playlist (in my case: a Star Trek OST playlist)
2. Shuffle play
3. See that the songs are being scrobbled incorrectly

### YTMDesktop

v1.14.0

### OS

Linux

### OS Version

Manjaro (Kernel 5.10.79)

### Arch

x64

### Installation way

Repository

**Comment by Alipoodle** [comment]
Is it possible to provide the playlist here?
I've tested out with playing through the album of songs and it cannot reproduce it with the album that the "Main Theme" is from.

**Comment by skerit** [comment]
Sure, here it is:
https://music.youtube.com/playlist?list=PLn3w3vOczNSk2XJf9yd3t2Y72BQNebx8I&feature=share

I don't know if this is important (and/or wrong behaviour) but every time I restart the Youtube Music Desktop, it will restart the playlist from the beginning. (So once again, from "Main Title")

**Comment by dflock** [comment]
This also happens to me, with pretty much any playlist, I think. It seems to just re-use the name of whatever track you started with, for all subsequent tracks. It's like the name gets stuck on the first one.
