### ISSUE TITLE
Playing music turns down volume of other applications, have an option to turn this off.

### ISSUE THREAD

**Issue by vakkD** [ytmdesktop/ytmdesktop#877]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

When playing music, other applications that have sound are turned down (can be seen in the volume mixer). A few seconds after pausing the song, the volume goes back to normal. Having an option to disable this and make the other apps keep the same volume would be useful.

### Anything else?

![Screenshot 2021-12-02 230017](https://user-images.githubusercontent.com/64450096/144418125-874964b0-f824-4d6b-9993-5a3e5f85d675.png)

**Comment by Alipoodle** [comment]
Yea, as above, we do not do this.

Can you see if you have this setting enabled within the Sound Control panel, and if it is what is causing it to dim the volume.
![image](https://user-images.githubusercontent.com/17199186/144669418-33f6c5ad-eee7-470a-8cd5-3450de28191a.png)

**Comment by vakkD** [comment]
> Yea, as above, we do not do this.
> 
> Can you see if you have this setting enabled within the Sound Control panel, and if it is what is causing it to dim the volume. ![image](https://user-images.githubusercontent.com/17199186/144669418-33f6c5ad-eee7-470a-8cd5-3450de28191a.png)

Ah yes, after changing this setting the volume issue does not happen anymore, thanks. :)

**Comment by NovusTheory** [comment]
Closing issue as resolved
