### ISSUE TITLE
Multimedia pause is prioritized by YTMD

### ISSUE THREAD

**Issue by zealiosexe** [ytmdesktop/ytmdesktop#879]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Whenever i press the "Pause" multimedia key, YTMD doesnt just prioritize itself above what the lastest media i played was.

**Comment by A-Matt** [comment]
Dupe of #512

**Comment by Alipoodle** [comment]
Dupe of #512
