### ISSUE TITLE
unistall because can not use, unsecure browser

### ISSUE THREAD

**Issue by latinomx** [ytmdesktop/ytmdesktop#882]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

unistall because can not use, unsecure browser, and not any form can work

### Expected Behavior

can not login account unsecure browser

### Steps To Reproduce

1. clic on login
2. write the email, next and ......

### YTMDesktop

v 10

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by fabrola22** [comment]
Right click tray icon.
Click on Guest
New window opens
Log there.
Close guest window
Close main window
Close tray icon
Open app again
Log in on main window
Done.

**Comment by Alipoodle** [comment]
Please see the pinned issue. #866 
This is known and we are investigating the issue.

There's a few ways to fix the issue at the bottom of it
