### ISSUE TITLE
player-set-seekbar command not working

### ISSUE THREAD

**Issue by quintindunn** [ytmdesktop/ytmdesktop#885]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When sending a POST request to `http://localhost:9863/query` with the body being `{"command": "player-set-seekbar", "value": "100"}` the response is `{"command": "player-set-seekbar", "value": "100"}` though on the YTM app the seekbar doesn't change

### Expected Behavior

The YTM desktop app changes the time the song is at to 100 seconds (1 minute 40 seconds)

### Steps To Reproduce

1.) On the YTM desktop app enable remote in settings, disable password.
2.) In Postman create a POST request to `http://127.0.0.1:9863/query` go to the `Body` section select `raw` and paste `{"command": "player-set-seekbar", "value": "100"}`
3.) Send request
4.) Observer on YTMDesktop app.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
I think it might be instead worth implementing a secondary value of `player-set-seekbar-seconds` and  possibly rename that to `player-set-seekbar-percentage` (although we'll keep `player-set-seekbar` as valid for the time being, and deprecate it eventually.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
