### ISSUE TITLE
Custom Theme stops working when I play a song.

### ISSUE THREAD

**Issue by Hershey025** [ytmdesktop/ytmdesktop#890]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When I select the custom theme, It works fine but when I play a song, It automatically changes the background color according to the color of the song/album photo.

### Expected Behavior

When I select the custom theme, It works fine. The custom theme should also work when I play a song. The background color should remain the same as I put in the custom theme when I play a song.  
Thank You.

### Steps To Reproduce

https://chrome.google.com/webstore/detail/ytm%20-for-youtube-music/jcdmcpefbebkldopabclefjaggejocff?hl=en

This extension completely changes the background color according to your custom theme. It also works when I play a song.

### YTMDesktop

1.13.0

### OS

Windows 

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
You have enabled a settings within YTM Desktop to do this.
Please disable it within the Settings right of your profile, likely within Appearance tab.

**Comment by Hershey025** [comment]
I checked again, I have not enabled any setting.

**Comment by Hershey025** [comment]
![Screenshot (145)](https://user-images.githubusercontent.com/94620635/152640551-fc74a150-70b7-4b8c-8ccc-fd2c445de2a6.png)
![Screenshot (144)](https://user-images.githubusercontent.com/94620635/152640559-e4abbd73-2729-4705-9e7b-c22b6d2d4662.png)
The custom theme works great but stops working when I play a song.

**Comment by Alipoodle** [comment]
Mind sharing the CSS for it.
And nothing that I see really is changing anything noticeable?

**Comment by Hershey025** [comment]
If you look closely the custom theme is there when i am not on the song page. But when I go back to the song the background becomes black instead of grey. That is the issue.

**Comment by Hershey025** [comment]
html, body { background: #1D1D1D !important; }
This is the code I used.

**Comment by Alipoodle** [comment]
That's a theme issue.
They are different components and therefore are different things which need to be coloured for it.

I suggest looking at learning CSS so build your own theme or using a pre existing CSS theme by someone else.
The discord server has a few in it, or searching on GitHub may find some.
