### ISSUE TITLE
ui and discord presence

### ISSUE THREAD

**Issue by thijsi123** [ytmdesktop/ytmdesktop#893]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

The close, minimize, etc... buttons would be better in the (far) top right for easy closing the app.
and the discord presence should have the youtube thumbnails like in: *removed*
That's all I gonna say bye.

### Solution

*removed*

### Alternatives

*removed*

### Anything else?

nope.

**Comment by Alipoodle** [comment]
Album art: #888, this is in a PR and not merged into Development or a stable release.

Otherwise please elaborate with the close minimise?

**Comment by Alipoodle** [comment]
Lack of information being provided. Closing issue.
