### ISSUE TITLE
💎 Remote Control stopped working

### ISSUE THREAD

**Issue by eltharynd** [ytmdesktop/ytmdesktop#898]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Remote Control doesn't work

### Expected Behavior

Remote Control Should be working

### Steps To Reproduce

1. Start Remote Control
2. Verify it's not working 😄 

### YTMDesktop

any

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

I know this is not much Orthodox... 
But i really needed to bump this.

It should be an easy fix, I detailed in #476 .

> Same here on Win11.. It used to work as intended till not long ago then it stopped for some reason. I noticed there's a bunch of different issues that seem to be linked to the same issue.
> 
> For some reason the socket doesn't start. Even the stream deck YTMD connector fails, so does an app I developed myself to show playing track on screen.
> 
> I tried downloading the repo to debug it but it fails on npm install... Might try to build it again tomorrow
> 
> EDIT: I managed to run the app through some shenanigans...
> 
> **FINDINGS:**
> 
> * If you change the port it works flawlessly
> * I double checked that nothing on my setup is blocking or doing anything with that port
> * I tried running another app i developed but changing to same port (9863) and it doesn't work on that port.
> * I tried running that same app from the development server on port (9863) and still the same result
> * I tried running http/https requests to that port, those work fine. it's literally just websockets for some reason
> 
> **CONCLUSIONS:** Something, somewhere is blocking that port... I even tried a bunch of other stuff from the same port, nothing works. i tried googling but it doesn't seem to be used for anything... You can try yourself running any app you have but changing the port to 9863, it just doesn't work
> 
> **SUGGESTION:** Just change the port and possibly give the user the chance to change it from settings

**Comment by KillerBOSS2019** [comment]
You should use `yarn install` and `yarn start`

**Comment by Alipoodle** [comment]
Do you use any Anti-virus software, if so have you tried disabling it and trying again?

**Comment by Alipoodle** [comment]
> that's part of how I made it work... but the readme says npm
Main/Master branch does still state npm.

Development branch now suggest yarn, as we've moved over to yarn for that.
npm or yarn will work fine within master branch.

Main branch has a few issues with building in regards to requiring VS 2015 for compiling some windows specific libraries, so that's probably why it failed.

**Comment by eltharynd** [comment]
Well i did a little coding...
#899 

It should be ready for deployment

**Comment by eltharynd** [comment]
> Do you use any Anti-virus software, if so have you tried disabling it and trying again?

Yes like i said i double checked all of that... and i tested and get the same result on 2 different local networks, form mobile network and from a server hosted on linode... 

All of those  tested both as host and client (except mobile only client).

This is truely the weirdest thing I've ever seen. But anyways allowing the users to change the port should be fine, right?

**Comment by manuth** [comment]
In my case, the remote control works using the current version. However, when installing the current nightly version, all my remote control shows is "Ready to play".
Is this the same error as the one you're faced with or should I open up a separate issue?

**Comment by manuth** [comment]
Okay... looks I'm facing neither #898 nor #901.
The Remote Control App works as long as I have YTMD's internal volume set to 100% or 0%... looks like the Remote Control component in the nightly release doesn't like decimal values...? 😂😅

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
