### ISSUE TITLE
🐛 Remote control socket.io is not guaranteed to receive password header

### ISSUE THREAD

**Issue by eltharynd** [ytmdesktop/ytmdesktop#901]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

If you enable password on your remote control, localhost clients can connect (cause it's hardcoded that way) but remote clients cant.

### Expected Behavior

You should be able to connect when you provide a password in your headers

### Steps To Reproduce

1. Comment the localhost hardcode bypass, or try to connect from a remote client when password is enabled.

2. Make sure on your client you set transports to websocket only
``` typescript
this.client = io(URL, {
    transports: ['websocket'],
})
```
3. Try to connect and you won't receive the password headers on the server side, thus failing to connect.

### YTMDesktop

irrelevant

### OS

irrelevant

### OS Version

irrelevant

### Arch

x64

### Installation way

irrelevant

### Anything else?

I've already created a PR to update to newer version and best practice whilst preserving existing method for retro-compatibility.

#900

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
