### ISSUE TITLE
header menu bar items not clickable on macOS maximized window

### ISSUE THREAD

**Issue by cameronsuorsa** [ytmdesktop/ytmdesktop#902]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When macOS app window is maximized, the top menu bar in the app is no longer clickable. The song results on the page are clickable, but not that top menu bar where you have the options for:
- Home
- Explore
- Library
- Search
- Account/Login

When I hit the green circle again to un-maximize the screen, the menu does work. Please see the attached GIF file that shows a screen recording of the issue.

![BUG_2-5-2022_macOS_10-15-7_YTMDA-v1-13-0](https://user-images.githubusercontent.com/69701934/152646659-84c9b09f-d786-416e-878c-f3e8cce9f65c.gif)

### Expected Behavior

I expect to be able to utilize the top menu bar items (Home/Explore/Library/Search/Login) in the maximized window view. 

### Steps To Reproduce

1. Install and launch app on mac
2. Hit the mac green full screen circle to maximize window size
3. Go to top bar / header... and try to click menu items. (Home/Explore/Library/Search/Login)

### YTMDesktop

v1.13.0

### OS

macOS Catalina

### OS Version

Version 10.15.7 (19H1713)

### Arch

x64

### Installation way

.exe

**Comment by mingjun97** [comment]
Looks like you are in a out-dated release. Could you try the release in development branch?

**Comment by Alipoodle** [comment]
I agree that this looks like an old version, I do suggest that you try this again in the Nightly release.

Please respond within a week or I'll close this issue assuming that the new Nightly has solved the problem.

**Comment by Alipoodle** [comment]
No response in 2 months, closing this as Stale
