### ISSUE TITLE
Communication with Remote Control not working if Volume is In-between 0% and 100%

### ISSUE THREAD

**Issue by manuth** [ytmdesktop/ytmdesktop#904]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

If one of these cases apply
  - The volume is not set to 100%
  - The volume is not set to 0%
No new data will be shown on the Remote Control App (tested on android).
Instead, the Remote Control App is stuck (either at `Ready to play` or at the most recently received data (i.e. before the volume was lowered/increased)).

### Expected Behavior

Data should always be sent to the controller and the controller should always be able to decode the data that was received.

### Steps To Reproduce

1. Open up the settings
2. Set the volume to something other than 0% or 100%
3. Connect your YTMDesktop Remote app to your player (tested on android)
4. Notice that the remote app is stuck at `Ready to play`
5. Set the volume to either 0% or 100%
6. Notice that everything works as expected if the volume is 0% or 100%

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

The same issue occurs in the current nightly version:
"Nightly Release (Nov 2021)"

**Comment by nikdo3** [comment]
same problem here!

**Comment by alexpalyan** [comment]
same problem on YTM Desktop for Linux v1.13.0 and YTMDesktop Remote for Android 1.1.1

**Comment by cadergator10** [comment]
Same issue here. Using latest beta version on desktop and latest version of remote

**Comment by GoldandGore** [comment]
Also started having this same issue after updating to 1.14.2 yesterday. At 100 or 0 volume, the controller app shows the current song and the play time counting down, but with any alteration of the volume between those values, the time freezes and the album art/song info doesn't update to the next track that then plays in the queue. All other features function on the controller except the play button which is not functioning at all, regardless of the volume level, after this update.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
