### ISSUE TITLE
Settings in same window.

### ISSUE THREAD

**Issue by Hershey025** [ytmdesktop/ytmdesktop#905]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

It would be great if the settings and lyrics could open up in the same YouTube Music window. Currently it opens as a separate new window.  It would be nice if you could do this.

**Comment by d12bb** [comment]
-1
Preferences have been opening in new windows for ages, and it is great that way.

**Comment by Alipoodle** [comment]
Closing as a Won't Fix.
We've got some changes for YTM Desktop V2 but keeping it as a same window requires bits which I think is prefered to not have.

Thanks for the suggestion but this is something I don't think we should change.
