### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by NarasimaPandiyan** [ytmdesktop/ytmdesktop#906]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Everything was alright until I tried to play a different song from the playlist by using the remote app.

![image](https://user-images.githubusercontent.com/35830653/153257191-2eac7dd7-c534-4819-84bf-5ac6da2aa9f3.png)

this error message started to spam error all time and its so annoying...

### Expected Behavior

To play the song selected from the ytmdesktop Remote app correctly without any error

### Steps To Reproduce

>Connect the remote app to the desktop app.
>play a song from the playlist(in the remote app)

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

I have been using this app for 2 years now its part of my daily apps. Please help me... :(

**Comment by Alipoodle** [comment]
Question, have you enabled Last.fm and placed valid Login information in?
this issue appears to be a problem with the Last.fm trying to do "NowPlaying" but login information is invalid.

**Comment by NarasimaPandiyan** [comment]
yes you are right. I didn't realize that...
Thank you so much
