### ISSUE TITLE
Uploaded music doesn't appear in recommendations.

### ISSUE THREAD

**Issue by Griffork** [ytmdesktop/ytmdesktop#908]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The top recommendation area on the home page never shows albums that you've uploaded.

### Expected Behavior

Albums that I've uploaded that I listen to frequently should show up in the recommendations, not just playlists I've made.

### Steps To Reproduce

1. Upload music.
2. Put your uploaded music into an album.
3. Listen to it a lot more than any other music.
4. Check the home page, see that it's not there.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.msi?

**Comment by Alipoodle** [comment]
This is a feature provided by YouTube Music and not us.
This is sadly not something that we have the capacity to replicate for tracking and then suggesting music to people, when it would be better if YouTube implemented this
