### ISSUE TITLE
Youtube Brand account

### ISSUE THREAD

**Issue by Carmando21** [ytmdesktop/ytmdesktop#913]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Made a youtube brand account signed into ytm desktop app with it and then deleted the brand account and now I'm stuck in the non-existent account on the app with no way to sign out and sign in with a different account. only option is using the guest account button to sign in with a different account in that instance but that's not very convenient.

### Expected Behavior

Being able to sign out or had been automatically singed out from the account that had been deleted.

### Steps To Reproduce

1. youtube.com
2. sign into ur account 
3. make a brand account under it
4. download ytm app
5. sign in with your brand account gmail
6. go back to youtube and manage the brand account, deleting it (at this point for even trying to open yt on my browser wasnt working had to delete ytm app and clear cookies to get it to work again)
7. reopen ytm, notice that the pfp in the top right is grey, and that you can't log out.

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

10

### Arch

x86

### Installation way

YouTube-Music-Desktop-App-Setup-1.13.0.exe

### Anything else?

Sorry if this bug report is bad, its my first time making one. :)
This problem may be related to the current issue of not being able to sign in to the app when downloaded as I had that problem as well and had to use google chrome instead of firefox to get it to work.
Thanks for reading.

**Comment by Alipoodle** [comment]
As a temporary fix:
- Close YTM Desktop
- Uninstall it.
- Go to `%appdata%`
- delete the entire contents of the **youtube-music-desktop-app** folder.
- Reinstall the app.

This will entirely delete all memory from the application, as typically it will keep a bit of information after uninstalling for improved user experience if a user wishes to come back.
I should note, this will probably never get fixed, as it's such a low chance anyone will really do it.

**Comment by Carmando21** [comment]
FIXED Thank you very much!
