### ISSUE TITLE
Win 11: Can't login because browser "is not secure"

### ISSUE THREAD

**Issue by FireCloudz** [ytmdesktop/ytmdesktop#914]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I installed YTMD and it started up as normal. Then I tried to login and after I put in my email the feedback popped up
![cdnsign](https://user-images.githubusercontent.com/100076505/154843967-9d236168-4b30-4f42-950b-5d3bd8888550.png)
:

### Expected Behavior

Usually you login as you in every Google Login Window would do.

### Steps To Reproduce

Windows 11:
1. Start up
2. try to login
3.  put in email
4. error

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

YouTube-Music-Desktop-App-Setup-1.13.0.exe

### Anything else?

Also tried this steps: https://github.com/ytmdesktop/ytmdesktop/issues/866#issuecomment-974205806
Same problem.

**Comment by FireCloudz** [comment]
Got it
Made it like the steps in #866 with the guest window but added two accounts in the guest window.
Then clicked in the main window on "try again" as often as needed until you can type in your password.
Then quit YTMD completely and try again without the guest window as often as needed.
But there is no determined solution..

**Comment by Alipoodle** [comment]
#866 is our master ticket!
We are still looking into it and have a potential fix but not been able to investigate it fully yet.
