### ISSUE TITLE
Bug: Miniplayer thumbs down button lowers volume instead of disliking

### ISSUE THREAD

**Issue by smsp** [ytmdesktop/ytmdesktop#92]
Hi,

When using the miniplayer, if I click the thumbs down button, ytmdesktop lowers the volume instead of disliking the music.

**Comment by rickinbsb** [comment]
what operating system are you on?

**Comment by smsp** [comment]
Windows 10 Pro 1903 (18362.592)

**Comment by rickinbsb** [comment]
Found it! Will be fixed on 1.8.2

**Comment by smsp** [comment]
Great!
Keep up the good work.
