### ISSUE TITLE
Dynamic Theme

### ISSUE THREAD

**Issue by aRealCatTBH** [ytmdesktop/ytmdesktop#925]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Like this [chrome extension](https://chrome.google.com/webstore/detail/themesong-for-youtube-mus/bgfiegdbajagebogifobkhambpljbfmk) I think it would be great to have dynamic backgrounds along with the song

a. The built in css editor isn't for everyone as it requires css knowledge

b. The pure black theme can cause eye strain.

c. Some people have glossy screens and said black background turns said screen into a mirror

### Solution

I'd like at least *something* implemented into the app to help with eye strain.

### Alternatives

Switching over to chrome just for the extension as its not on Firefox atm.
Creating my own YTM desktop app with said extension included.

**Comment by Alipoodle** [comment]
This is already partially implemented and is already a feature which YT Music is trailing on some devices:
![image](https://user-images.githubusercontent.com/17199186/160366329-34caa2a2-5795-483d-b36d-59314d6c9049.png)

I do agree some more customisability would be lovely for this, but I feel in the current state that it is doing a good job and eventually we can look into implementing this, or adjusting our current method for to achieve a similar outcome.
