### ISSUE TITLE
Snap install on Linux floods system log.

### ISSUE THREAD

**Issue by bjwest** [ytmdesktop/ytmdesktop#926]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

My system logs are flooded with the following information level entries several times a minute:

`audit: type=1326 audit(1647291035.850:133808): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.youtube-music-desktop-app.youtube-music-desktop-app pid=9149 comm="youtube-music-d" exe="/snap/youtube-music-desktop-app/6/youtube-music-desktop-app" sig=0 arch=c000003e syscall=203 compat=0 ip=0x7fdfe3ac8c7f code=0x50000`

The only thing that changes is the audit number, and my system logs are huge since installing.  I see no way to limit logging to eliminate information level entries.

This is occurring in the system, kernal and journald logs, even when playback is paused.  Literally hundreds of thousands of information entries throughout those log files since I started using the app.

### Expected Behavior

Information log entries should not be clogging up system logs, and should have a way to be turned off if the user desires.  Critical errors are the only entries that should be forced to log.

### Steps To Reproduce

Start snap.youtube-music-desktop-app
Wait a couple of seconds
open system.log
notice the very many (useless) information entries

### YTMDesktop

v1.13.0

### OS

Linux

### OS Version

KDE Neon 5.24

### Arch

x64

### Installation way

Snap package

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
