### ISSUE TITLE
Upgrade to an efficient framework

### ISSUE THREAD

**Issue by droukd** [ytmdesktop/ytmdesktop#927]
### Consent

- [x] I verified that there is no open issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I would like apps to be unable to run system OOM / run restartless / run saving full state [as any good interface do]. Please, thank you.

### Solution

Tauri, Nodegui, Neutralino, Flutter.

**Comment by Alipoodle** [comment]
Overall this doesn't seem like a helpful suggestions at all.

To redo everything is overkill as it functions in its current state. 
Out of Memory issue is 100% YouTube musics issue and has been a problem for over 2 years. 
Saving the state of the window is a feature already exists.

This is more or less asking for a new project to build the app in an entirely different Desktop framework.
