### ISSUE TITLE
Browser doesn't let login Google<title>

### ISSUE THREAD

**Issue by BoscoChung1234** [ytmdesktop/ytmdesktop#929]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The browser doesn't let me to login Google account because of security issues

### Expected Behavior

The browser normally should let users login into Google

### Steps To Reproduce

Update the browser

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
Duplicate of #866
