### ISSUE TITLE
Every time it closed it throws an error in event viewer (and realibility monitor)

### ISSUE THREAD

**Issue by ichigayamate** [ytmdesktop/ytmdesktop#931]
### Consent

- [x] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When the app closes normally by using X button, a new error is thrown to event viewer and realibility monitor (I don't use close to tray option):

```
Description
Faulting application name: YouTube Music Desktop App.exe, version: 1.13.0.0, time stamp: 0x5f4dbeb4
Faulting module name: ntdll.dll, version: 10.0.22000.527, time stamp: 0x931cda92
Exception code: 0xc0000374
Fault offset: 0x000000000010c0a9
Faulting process id: 0xf94
Faulting application start time: 0x01d83b7c0fdaf206
Faulting application path: C:\Users\{users}\AppData\Local\Programs\youtube-music-desktop-app\YouTube Music Desktop App.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 60915f16-a371-445f-969c-6f22fe526036
Faulting package full name: 
Faulting package-relative application ID: 
```

### Expected Behavior

It shouldn't throw an error to event viewer and realibility monitor and closes as normal

### Steps To Reproduce

Just close a program, wait few minutes, then open realibility monitor in security & maintenance and/or event viewer. An exact error as described in current behavior is shown

### YTMDesktop

v1.13.0.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

```
Description
Faulting application name: YouTube Music Desktop App.exe, version: 1.13.0.0, time stamp: 0x5f4dbeb4
Faulting module name: ntdll.dll, version: 10.0.22000.527, time stamp: 0x931cda92
Exception code: 0xc0000374
Fault offset: 0x000000000010c0a9
Faulting process id: 0xf94
Faulting application start time: 0x01d83b7c0fdaf206
Faulting application path: C:\Users\{users}\AppData\Local\Programs\youtube-music-desktop-app\YouTube Music Desktop App.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 60915f16-a371-445f-969c-6f22fe526036
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 2206213409266739051, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: YouTube Music Desktop App.exe
P2: 1.13.0.0
P3: 5f4dbeb4
P4: StackHash_fbea
P5: 10.0.22000.527
P6: 931cda92
P7: c0000374
P8: PCH_7B_FROM_ntdll+0x00000000000A42A4
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.969527d3-c6c5-496a-bc38-750a35ec8211.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.27d4a095-667f-420a-b911-612cab3a5f48.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.91a7ab8d-7752-46ce-a85b-4c3833de4c7c.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.25e88385-2924-4b6d-ae10-741d014a241c.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.892ff550-fae7-4ff6-9e19-996fe836412a.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_YouTube Music De_9b1faea7a55616959fb0d49df84bebaec763d9_47491aff_f062cbd6-e432-40a1-88f2-4b954835b5af

Analysis symbol: 
Rechecking for solution: 0
Report Id: 60915f16-a371-445f-969c-6f22fe526036
Report Status: 268435456
Hashed bucket: 591f975ddbef9f8b4e9e0b681e0c276b
Cab Guid: 0
```

**Comment by Alipoodle** [comment]
It has nothing directly to do with us and likely a problem within Electron itself. (Reviewing their GitHub this has been a reported issue back in v1.7.4, We're on V11)
Going through my Logs in Event Viewer, I've seen Adobe Software causing this same error, and 0 entries of YouTube Music Desktop erroring with this.

Considering this is an issue which is only displayed within Event Viewer and not publicly to the user, This issue is also visible within other programs, and we are not do anything ourselves with DLLs like this.
I do not see this as an issue for YTM Desktop.

_I will leave this open for a short while for a comment, however I do not see this changing my mind_
