### ISSUE TITLE
interface error

### ISSUE THREAD

**Issue by ramunozp** [ytmdesktop/ytmdesktop#933]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

in macos, monterrey the control bar is not fully displayed.

### Expected Behavior

make the full control bar appear without cutting off the icons.

### Steps To Reproduce

just open ymd and play a song

### YTMDesktop

1.13.0 and 1.14.1

### OS

macOS Monterrey

### OS Version

12.3

### Arch

x64

### Installation way

dmg

### Anything else?

no

**Comment by Alipoodle** [comment]
Could you please provide a picture for this?

**Comment by ramunozp** [comment]
look at the final part of the image, where the audio controls are.


![Captura de Pantalla 2022-03-28 a la(s) 10 49 45](https://user-images.githubusercontent.com/24207310/160412624-617483b9-a801-4bb6-9b2f-8a472f6569c7.png)

**Comment by ramunozp** [comment]
¿...?

**Comment by rycette** [comment]
Having the same bug here as well

**Comment by Alipoodle** [comment]
This issue has been untouched for a while as I've yet to be able to reproduce this with a Daily usage of the application on multiple PCs with Multiple versions made as well. 😅

There's nothing I can do about an Issue I can't diagnose or reproduce myself.
