### ISSUE TITLE
"Add to playlist" popup each time a new track plays

### ISSUE THREAD

**Issue by cheickit** [ytmdesktop/ytmdesktop#937]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Each time a new song plays the "add to playlist" popup opens for half a second then disappears on the far left of the screen, i've tried fiddling with options but no luck. I used to not have this issue but now its very consistent and happens systematically 
![image](https://user-images.githubusercontent.com/82844936/162197677-10b305b6-e3ae-4d51-a4e7-40fb0686999d.png)

### Expected Behavior

No "add to playlist" popup when a new track plays

### Steps To Reproduce

1. Play any song
2. Skip to the next song

### YTMDesktop

1.13 and 1.14

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by dextronox** [comment]
Yep, same issue. Although the popup only flashes for me.

**Comment by NomenNescio92** [comment]
I'm only getting the flash on my desktop pc, but on my laptop it stays for a bit before going away again. I assume it's the difference in CPU that makes the difference between flash or longer.

**Comment by joheiska** [comment]
Same here... Started happening maybe a week or two ago.

**Comment by TheShadowFTW** [comment]
Same here, just started today for me. On v1.13

**Comment by waleramir** [comment]
same bug

**Comment by smsteward** [comment]
Can confirm this bug on my system as well; on selecting a new track, the "add to playlist" menu flashes on my screen for a split second and disappears. I'm on Arch Linux using the 1.14.1 Nightly AppImage.

**Comment by KillerBOSS2019** [comment]
Just curious do you have remote api enabled? Cuz I know that if remote control is enabled It will pop up playlist so it can grab your playlist names for the api

**Comment by KillerBOSS2019** [comment]
nvm Just tested this It seems to happen doesn't matter if remote control is enabled or not

**Comment by tophattwaffle** [comment]
Same issue on 1.14.2. Flashes quickly each track change.

**Comment by NovusTheory** [comment]
Issue seems to be tied to our infoPlayerProvider, which should make us investigate where we simulate clicks everywhere else and try to minimize that as that is what seems to cause these flashes.
https://github.com/ytmdesktop/ytmdesktop/blob/48513278641722b47e57f8bd7861f3819541212c/src/providers/infoPlayerProvider.js#L389-L390

**Comment by cjglasgow88** [comment]
I have the same exact problem. It results in me accidentally adding a song to a random playlist in my library and if I miss the popup that displays the "View" button (to view the playlist that you added the song to), it becomes a much bigger hassle to remove it. Although it's not the biggest thing, it can get pretty annoying.

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
