### ISSUE TITLE
Changing the font

### ISSUE THREAD

**Issue by qkar1m4k** [ytmdesktop/ytmdesktop#939]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I would like to be able to change the font in css with one line for example:

... {
font-family: "Comic Sans MS";
}

unfortunately I didn't find how to do it myself

### Solution

? {
font-family: "Comic Sans MS";
}

### Anything else?

![image](https://user-images.githubusercontent.com/95557958/163103921-fbf2d8d5-00e3-4b15-b764-22f89911f32e.png)

**Comment by Alipoodle** [comment]
using

```css
*:not(.material-icons) {
   font-family: 'Comic Sans MS' !important;
}
```
Should apply it.

![image](https://user-images.githubusercontent.com/17199186/163139389-e076b11d-b4e5-4d3d-af04-e11441d43594.png)
However this does messes with ALL fonts used across YTM. And May break the experience.
