### ISSUE TITLE
Bug: Can't install the snap package

### ISSUE THREAD

**Issue by renanrfranca** [ytmdesktop/ytmdesktop#94]
Trying to install the snap package is met with "Failed to install file: not supported" on the Software & Updates app.

I'm on Ubuntu 19.10 eoan x64.

**Comment by renanrfranca** [comment]
I'm still having the same issue on the 1.8.2 snap release.

Also the download links in the webpage are for the 1.8.1 release it seems.

**Comment by rickinbsb** [comment]
can you share the full error returned?

**Comment by renanrfranca** [comment]
Sorry for the delay, I've been away from my PC. 

I don't know if I'm doing this right since I usually install packages with the Ubuntu Software app, but when I run `sudo snap install youtube-music-desktop-app_1.8.2_amd64.snap` in the terminal I get the following: `error: cannot find signatures with metadata for snap "youtube-music-desktop-app_1.8.2_amd64.snap"`

In the software app I get `Failed to install file: not supported`.

I just managed to install it successfully with `sudo snap install youtube-music-desktop-app`, retrieving it from snapcraft, so I'm guessing there's something wrong with the files on the website and github release pages.

**Comment by rickinbsb** [comment]
oh, that is because the snap app from the website is not signed, you would have to install it with the ```--dangerous``` flag. But it is preferable to install it from snapcraft.

**Comment by renanrfranca** [comment]
Oh, alright, thanks for the help. Might be worth it to add that info on the website/readme or maybe link to snapcraft or something. Great app btw, thank you.

**Comment by adlerluiz** [comment]
@renanrfranca Thank's for your suggestion, the website now has a badge for snapcraft.

![image](https://user-images.githubusercontent.com/2112638/74656278-94069a80-516c-11ea-9542-9d399990662d.png)

**Comment by renanrfranca** [comment]
@adlerluiz Awesome! Glad I could contribute somehow.
