### ISSUE TITLE
Miniplayer | Always on top is not functioning

### ISSUE THREAD

**Issue by D0t-Matrix** [ytmdesktop/ytmdesktop#950]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When you turn the "Always on Top" option on, it is not being respected, and once an app gets placed on top, it gets placed behind all apps, with no way to reset this.

### Expected Behavior

When the "Always on Top" option is enabled, the miniplayer should always be placed higher than any other application.

### Steps To Reproduce

1. Go to miniplayer settings
2. turn on "Always on Top"
3. turn miniplayer on
4. click on application that the miniplayer is in front of
5. See that the miniplayer gets Z-indexed behind the other application
6. See that you are unable to bring the miniplayer to the front without exiting miniplayer mode.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
`alwaysOnTop` option is handled by Electron itself, and should update upon changing the setting within the menu at all times.

However in versions 1.13, 1.14, 1.14.1 I've not experienced any issues with this.

Can I ask what programs you are having Issues with (Some specific and/or all)?
Are they being ran as Admin? is YTM Desktop being ran as Admin?

**Comment by D0t-Matrix** [comment]
This occurred with any program i had running (Discord, Firefox, Chrome, File Explorer, Visual Studio) and none were running in admin, nor was YTM Desktop.

**Comment by Alipoodle** [comment]
Thank you for the update, hopefully this is something which is possible to be solved in the future, but without more information as to why this is a problem I agree with you that we should probably close the ticket.
