### ISSUE TITLE
Tray icon left-click opens context menu (libappindicator)

### ISSUE THREAD

**Issue by LRitzdorf** [ytmdesktop/ytmdesktop#952]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Without `libappindicator` installed, a left-click on the system tray icon reopens the app, as expected.

If `libappindicator` is installed, even as a dependency for an unrelated package, left-clicks (as well as right-clicks) now open the context menu.

### Expected Behavior

With `libappindicator` installed, left-clicking the tray icon should continue to open the app as normal.

### Steps To Reproduce

1. Install YTMDesktop and `libappindicator`.
2. Open YTMDesktop and left-click the system tray icon.
3. The context menu opens, rather than the app itself.

### YTMDesktop

1.14.1

### OS

Arch Linux

### OS Version

Latest

### Arch

x64

### Installation way

AUR

### Anything else?

This actually appears to be an underlying issue in Electron, described in [electron/14941](https://github.com/electron/electron/issues/14941). However, there should be workarounds available.

One particularly interesting method to disable this is recorded in [a Bodhi Linux forum post](https://bodhilinux.boards.net/thread/896/make-discord-open-click-system), and I can confirm that it continues to work on Discord (which is also Electron-based). Since Discord installs to `/opt/discord`, at least on Arch, placing empty files there as described in the forum post works.

If YTMDesktop users would like to do the same, this should be possible, provided we know where YTMDesktop's installation root directory is located. Even if YTMDesktop itself is not updated to fix this issue, motivated users could do so themselves with this method. So, question: where exactly is the installation root for YTMDesktop?

**Comment by LRitzdorf** [comment]
Looks like this has been resolved upstream! I can't personally verify that it works, since the AUR package for Electron 13 is currently broken for me, but this is a good sign, at least.

See https://github.com/electron/electron/issues/14941 and https://github.com/electron/electron/pull/36333

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
