### ISSUE TITLE
<Javascript pop up>

### ISSUE THREAD

**Issue by FrankieGuns** [ytmdesktop/ytmdesktop#953]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Whenever I open the application is keeps popping with this no matter how many times and start/restart it shows this 
![image](https://user-images.githubusercontent.com/25517845/165426477-fda4d12d-00d5-4372-bbb2-6ec40c78f91d.png)

### Expected Behavior

I've tried starting my pc and opening task manager and ending it's process, even uninstalled it and reinstalled nothing as worked.

### Steps To Reproduce

1. Close ytmdesktop
2. Open ytmdesktop
3. pop up happens

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

10

### Arch

x86

### Installation way

.exe

### Anything else?

![image](https://user-images.githubusercontent.com/25517845/165426851-6b9cb50d-87f9-4e2b-be8c-7c0001960354.png)

**Comment by Alipoodle** [comment]
Issue #1 Cannot read `getPosition()` of null.
This is a bit more of a Surprise considering that this has failed to correctly get the "mainWindow" 😅

Secondly this appears to be that Last.FM feature is enabled but not actually signed in.
Please Sign In / Turn this feature off.

**Comment by FrankieGuns** [comment]
How do I turn it off if it keeps me from going to settings?

**Comment by FrankieGuns** [comment]
Nevermind fixed it, Thank you!

**Comment by FrankieGuns** [comment]
The 1st problem still remains thought but isn't causing any issues

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
