### ISSUE TITLE
Tab is off set of the display!<title>

### ISSUE THREAD

**Issue by reHamad** [ytmdesktop/ytmdesktop#957]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The app is not displaying on my main monitor, it is opening out of my screen space and whenever I try to resize the window it won't work. Using ( Windows 11 Pro ).

I can access the settings but there isn't an option to resize the app or get it back to my main screen.

### Expected Behavior

I tried to delete the app and reinstall it again and it still shows the same problem.

### Steps To Reproduce

None

### YTMDesktop

1.14.1 Pre Release

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

I think adding a button to resize and fit the app back to the middle of the screen will fix this issue 👍.

**Comment by reHamad** [comment]
Hi, I'm still having the same problem and I didn't receive an answer from you guys? 

The window opens outside of the display view making it impossible to get it back on display!!

**Comment by reHamad** [comment]
Even after installing the latest version of the nightly release, I thought that this release fixed this problem.

**Comment by dragonshardz** [comment]
I am experiencing the same issue. I've tried every trick known to man to return the app to my desktop with no success.

**Comment by reHamad** [comment]
> I am experiencing the same issue. I've tried every trick known to man to return the app to my desktop with no success.

The only way that solved this issue for me is I deleted every file related to the software after un-installing, even the files that existed in the registry. 

After this restart and re-install the app again. 

I hope this fixes the issue in you side.

**Comment by dragonshardz** [comment]
I just gave up and uninstalled to use YTM as a PWA.

**Comment by Alipoodle** [comment]
There's a few ways of solving this:

- Some have suggested using `Win + D` (Show Desktop) Twice and has restored the item back onto screen 
- Manually editing the X/Y Axis for the Window which is having issues.

Uninstalling won't help as the config file is still kept as it's stored in a different location.

I'm closing this for our master ticket in #918
