### ISSUE TITLE
Force sorting albums

### ISSUE THREAD

**Issue by nalexeyev** [ytmdesktop/ytmdesktop#959]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

YTM shows albums on an Artist page in a Google-only-knows order. Please add feature to override it and sort in alphabetical order or by year (bidirectional)

E.g. for Queen:
https://music.youtube.com/browse/UCEPMVbUzImPl4p8k4LkGevA

The album list is sorted neither by year nor by title

**Comment by Alipoodle** [comment]
As this is a thing which is handled FULLY on YTM side, this is something which I do not thing we can do.
Especially as YTM Does not pre-load **all** Albums that a Artist provide, causing it to be that if we were to load more items it would then have to re-order the whole list and cause a bunch of things to move position.
 
This is a suggestion better left given to YTM themselves and not us.
