### ISSUE TITLE
Snap app opens to just a black rectangle box on Ubtuntu Mate 20.04

### ISSUE THREAD

**Issue by pallebone** [ytmdesktop/ytmdesktop#96]
Hi there,

When installing the snap package and running it (sudo snap install youtube-music-desktop-app) all that happens when launching the app is a black rectangle appears on the screen. I believe I am missing some dependencies for the snap? Can anyone confirm what should be installed to run this snap package?

Here is the terminal output when launched:

aragorn@aragorn:~$ youtube-music-desktop-app 
Gtk-Message: 08:42:18.234: Failed to load module "appmenu-gtk-module"
Checking for update
Error: Error: ENOENT: no such file or directory, open '/snap/youtube-music-desktop-app/2/resources/app-update.yml'
(node:5727) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/snap/youtube-music-desktop-app/2/resources/app-update.yml'
(node:5727) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/snap/youtube-music-desktop-app/2/resources/app-update.yml'
(node:5727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5727) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5727) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5727) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
(node:5727) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
(node:5727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5727) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
(node:5727) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
(node:5727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5727) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
(node:5727) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
(node:5727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:5727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

Kind regards
P

**Comment by rickinbsb** [comment]
Are u on a fresh install or you've updated from 19.10?

**Comment by rickinbsb** [comment]
I'm downloading the daily iso to see if I can reproduce it

**Comment by pallebone** [comment]
Hi,

It was a fresh install from Ubuntu Mate 20.04 - about a two week old image but has been kept up to date daily with sudo apt-get dist-upgrade.

**Comment by pallebone** [comment]
Hi,

Sorry for wasting your time on this. I apologize profusely. My ad blocker has blocked a DNS address the app was trying to access, and the default behaviour of the snap is to show nothing (just a black box) if it cannot resolve a URL it needs. I found this while troubleshooting further on my own. If I disable my Pi Hole adblocker instead of a black box, it loads a page. Apologies again, please do not harm me, I am but a simple peasant worker who logged a ticket without due diligence.

P

**Comment by pallebone** [comment]
Do not harm me please.

**Comment by rickinbsb** [comment]
hahaha, that's okay, thanks for explaining this! Can you share the url that was blocked?

**Comment by pallebone** [comment]
I believe it was this dns address, sorry again :) : 
s.ytimg.com

**Comment by rickinbsb** [comment]
no worries, it serves as xp to track similar errors in the future
