### ISSUE TITLE
When will the full Russian translation be available? Will a portable version be real? Will there be a backup of settings?

### ISSUE THREAD

**Issue by userskill** [ytmdesktop/ytmdesktop#962]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Когда будет полный русский перевод? Будет ли реальна портативная версия? Будет ли Бэкап настроек?

**Comment by Alipoodle** [comment]
> When will the full Russian translation be available?

https://github.com/ytmdesktop/ytmdesktop-locales/blob/master/locales/ru.json
If you would like to contribute to the Russian Translation, please add the string into this file here 🥰
These are dynamically updated with the new version of the thing.

And remember we aren't YTM so we aren't planning on doing locale work for the actual contents of the website.

> Will a portable version be real?

This is a completely new feature which has never been requested and chances are that we won't do it, but not to say it won't be possible in the future.
From my quick google, there does appear to be a a way we can make a build for this.

> Will there be a backup of settings?

You have can go to `%appdata%/youtube-music-desktop-app` and make a copy of the config.json file if you would like to back it up. 😎
