### ISSUE TITLE
[Logitech G Specific?] Enabling Surround Sound Plays Static

### ISSUE THREAD

**Issue by SomeAspy** [ytmdesktop/ytmdesktop#965]
### Consent

- [x] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Upon turning on the surround sound option in settings and restarting, there will only be static when playing music.
This happens regardless of hardware acceleration being turned on.
However, with Surround sound disabled on the headset itself, instead of static there will be no audio at all.
(This may be related to Logitech's G Hub handling of audio???)
On headphones that do not use G Hub, this issue does not seem to occur. I'm not sure if this is related to how youtube music handles surround or if its an issue with Logitech G Hub.
For the meantime, I will keep this issue open.

### Expected Behavior

Music to fill all audio channels

### Steps To Reproduce

1. Enable surround sound in the app
2. Relaunch the app
3. Play a track

### YTMDesktop

1.14.2

### OS

Windows

### OS Version

11 (22H2)

### Arch

x64

### Installation way

.exe file from github releases

### Anything else?

Audio driver is the Microsoft Generic Audio Device driver (10.0.22616.1)
Headphones are Logitech G533 with firmware version 112.1.13

**Comment by Alipoodle** [comment]
Regarding the Surround Sound / Speaker fill, this is a feature which we can't really handle much with.
It's using a Electron/Chromium flag called `try-supported-channel-layouts`.

So there's nothing we can really do in regards to altering this feature 😅

**Comment by Alipoodle** [comment]
Any updates on this? Have you started to play around with some of the new Windows Audio Features? 
![image](https://user-images.githubusercontent.com/17199186/170035465-9a8bcce4-8b92-4abc-bace-0ef8578ba7a0.png)

**Comment by SomeAspy** [comment]
I don't see the Windows Sonic for Headphones option
![image](https://user-images.githubusercontent.com/33640860/170132863-a0ce697c-ba52-4aae-a3ed-dea1029112db.png)

**Comment by Alipoodle** [comment]
It will be in hte Spatial Sound option, although it currently does look to be disabled in that menu 🤔
I tried doing it via right clicking the Sounds icon + going to that but am on Win10

**Comment by SomeAspy** [comment]
I have moved to different software, cannot maintain this issue
