### ISSUE TITLE
Media shortcuts no longer work on v1.14.2

### ISSUE THREAD

**Issue by guaycuru** [ytmdesktop/ytmdesktop#968]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I just updated to v1.14.2 and noticed that media keyboard / mouse shortcuts are no longer working. I.e. pressing play/pause on my keyboard dedicated media key no longer works, while it was working fine on v1.14.3.

### Expected Behavior

I expect media keyboard / mouse keys to still work after upgrading to v1.14.2.

### Steps To Reproduce

Try to use any dedicated media key on a keyboard / mouse that has them on version v1.14.2, it's not going to work.

### YTMDesktop

v1.14.2

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

I reverted back to v1.14.1 and can confirm that media keys are working fine on this version.

**Comment by Alipoodle** [comment]
Can I ask what keyboard you are using? Do you have the Keyboards custom Software open (If it has one, I.E. iCUE for Corsair)?
Are you using Native Media Keys or Custom Keybinds?

**Comment by guaycuru** [comment]
The keyboard is a Corsair K55 RGB on which I'm using native media keys.
I've also mapped some mouse buttons to be media keys and they also stopped working.

**Comment by Gratenes** [comment]
My keyboard still works on the latest update, using my FN keys to skip tracks/pause.

**Comment by Alipoodle** [comment]
I presume you have the Win10 Media service on.
I've just installed the version fixed of 1.14.2 which displays the correct message and I can see that the media keys aren't working (i think this did break in the building process)

**Comment by Alipoodle** [comment]
@Gratenes I presume if you go to Settings -> About it will say 1.13 - DEVELOPMENT BUILD?

**Comment by Gratenes** [comment]
@Alipoodle  I just updated to the new builder before updating (im on windows 11 although *forgot about that*)

**Comment by Alipoodle** [comment]
![image](https://user-images.githubusercontent.com/17199186/169143645-27a16641-a5cd-435e-b9a7-2c4cbf4cab80.png)
👌 I will try and rebuild and see if I can fix out build process.

**Comment by Alipoodle** [comment]
https://github.com/ytmdesktop/ytmdesktop/runs/6496172203?check_suite_focus=true
Appears to have fixed the issue 😎 so will push a new a new file for it in a bit.

**Comment by Alipoodle** [comment]
https://github.com/ytmdesktop/ytmdesktop/releases/tag/1.14.2
![image](https://user-images.githubusercontent.com/17199186/169146593-c8f0fa0f-2eca-4282-9aae-d5ed3aeda126.png)

Should be working again! 👍
