### ISSUE TITLE
The miniplayer is no longer working after the 1.14.2 update.

### ISSUE THREAD

**Issue by Hershey025** [ytmdesktop/ytmdesktop#969]
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The miniplayer has stopped working (not showing on screen) after the latest 1.14.2 update. I also changed the miniplayer size and position to 100 by editing config.json  but it did not work. I also restarted my computer and cleaned the ytmdesktop app data but that also did not work. It would be nice if you would look into this matter

### Expected Behavior

The miniplayer should come on when i click on the miniplayer button.

### Steps To Reproduce

Install previous version. It is working fine in the previous versions.

### YTMDesktop

1.14.2

### OS

Windows

### OS Version

11

### Arch

x86

### Installation way

.exe

**Comment by dansauve** [comment]
It's working for me... sometimes. Based on start/restart of the app:

- Sometimes it works as expected
- Sometimes it doesn't show at all on desktop or in Task View
- Sometimes it shows in Task View but not on desktop. Window must be out of bounds or something and I cannot get to it (clicking on Task View does nothing)

**Comment by Hershey025** [comment]
> It's working for me... sometimes. Based on start/restart of the app:
> 
> - Sometimes it works as expected
> - Sometimes it doesn't show at all on desktop or in Task View
> - Sometimes it shows in Task View but not on desktop. Window must be out of bounds or something and I cannot get to it (clicking on Task View does nothing)

Are you using version 1.14.2?

**Comment by dansauve** [comment]
> Are you using version 1.14.2?

Yes, same details at OP. Windows 11 beta insider build 22621.1

**Comment by Alipoodle** [comment]
Please can you provide the settings you have enabled within the Miniplayer Settings.

There is a setting to Hide/Show the Miniplayer in the Taskbar so this is why it can hide.
The going off screen is a known issue which is still being looked into, but editing the config to reposition it is the best I can suggest.

**Comment by Alipoodle** [comment]
One person has recommended doing `Win + D` Twice to Show/Hide the desktop and has restored the miniplayer to a visible location.

**Comment by dansauve** [comment]
<img width="673" alt="image" src="https://user-images.githubusercontent.com/17929251/169389614-8acea17a-a454-422b-8884-140af60fc318.png">

The "Show on taskbar" option being enabled or disabled has no effect. With that setting enable the miniplayer still behave oddly. To reiterate, if I restarting the application sometimes the miniplayer shows up where I expect it, but if I restart the app again it's hit or miss if it shows up or just doesn't display.

**Comment by dansauve** [comment]
> One person has recommended doing `Win + D` Twice to Show/Hide the desktop and has restored the miniplayer to a visible location.

When the miniplayer doesn't work / doesn't show, Win+D does nothign to help it get back.

**Comment by Alipoodle** [comment]
Show on Taskbar requires the Miniplayer to restart and helps regarding it being showing in various views.
But it going off screen is a thing I've said is been made aware of and the only fix is really to fix it in the config.json

What resolution are you using? are you using Windows scaling on that monitor?

**Comment by Hershey025** [comment]
![Screenshot (170)](https://user-images.githubusercontent.com/94620635/169483688-75605977-3017-4755-8904-682836eddbdf.png)

https://user-images.githubusercontent.com/94620635/169483830-67702cd5-a8e0-48c0-bc6c-70858369dbeb.mp4

**Comment by Hershey025** [comment]
> Show on Taskbar requires the Miniplayer to restart and helps regarding it being showing in various views. But it going off screen is a thing I've said is been made aware of and the only fix is really to fix it in the config.json
> 
> What resolution are you using? are you using Windows scaling on that monitor?

No not using Windows scaling.

**Comment by Alipoodle** [comment]
@Hershey025 And I presume you have played with the `config.json` to display the Miniplayer back on a monitor again?

**Comment by Hershey025** [comment]
No

**Comment by Hershey025** [comment]
i just changed size of the miniplayer from config.json

**Comment by Alipoodle** [comment]
I'd recommend changing it's location presuming that this is just the issue regarding it going off screen and not it "not working" then I will close this for the master ticket we have for things going off screen. 😅
Will give you a chance to respond but will close in a few days.

**Comment by Hershey025** [comment]
I changed its position but it did not work. In fact when I tried V1.14.0 and 1.13.0 it worked fine but only in this version it is not working. I even tried re-installing this version. I feel there is just more than it going off screen.

**Comment by Hershey025** [comment]
If you think it is going off screen then, how should I fix it?

**Comment by Alipoodle** [comment]
Could you go to `%appdata%/youtube-music-desktop-app` and open the `config.json` file

And look for the following values:
```json
	"miniplayer-position": {
		"x": 142,
		"y": 906
	}
```

Change them to be something like 100 each.

**Comment by Hershey025** [comment]
I have already tried that a lot of times, It does not work.

**Comment by Alipoodle** [comment]
- Can you make sure that your YTMD is Closed and Edit the `config.json`? (Remember to save)
- Is the Miniplayer size something of a reasonable size? I.E. 200+
- When you do edit it, and open YTMD Back up, and select to display the Miniplayer, does it edit these values or keep them the same? [I'd recommend re-opening the file, or using something like notepad++ where it says when the file updates]

**Comment by Hershey025** [comment]
I tried doing this, It worked once but when reopened ytmd after a while this problem came back. Every time I have to open YTMD, I have to edit the config.json and change the miniplayer position before opening it.

**Comment by Alipoodle** [comment]
Can you say that the values are when you reopen the client?

**Comment by Hershey025** [comment]
"miniplayer-position": {
		"x": -204,
		"y": -243
	},

**Comment by flleeppyy** [comment]
I don't believe this has anything to do with my changes to the miniplayer I made about a year ago in 5df6f08535a9d8e3537e6a371b47b7f9ae17d25d?

**Comment by Hershey025** [comment]
could be.. idk

**Comment by Hershey025** [comment]
> I tried doing this, It worked once but when reopened ytmd after a while this problem came back. Every time I have to open YTMD, I have to edit the config.json and change the miniplayer position before opening it.

I keep changing the miniplayer size before opening it.

**Comment by Alipoodle** [comment]
This appears to be following the same issues as #918 , and I can't see any other reason to why it would not be that.
My guess is that you seem to clearly be having this issue more often than expected with the Miniplayer going out of bounds than it should be.

**Comment by Hershey025** [comment]
yes I face this problem often but I don't use multiple monitors. maybe it could be the same issue

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
