### ISSUE TITLE
Feature Request: Add "Back" button to enable easier navigation when browsing

### ISSUE THREAD

**Issue by dansauve** [ytmdesktop/ytmdesktop#97]
When browsing (albums, etc) there is no on-screen navigation to get "back" to previous screens. When using a mouse I can use buttons (back button works), or swipe actions on a touchpad, but an on-screen back button would be very helpful.

MS Edge web app installs and has a back button added in the top left which is helpful:

![Uploading YTM PWA Back Button Example.png…]()

The [GPDMP](https://www.googleplaymusicdesktopplayer.com/) app also has a back button but I don't have it installed anymore to take a screenshot.

Issue #55 partially addresses this but it requires two clicks (right-click and then click Back button) which isn't ideal.

**Comment by fgimian** [comment]
Yes please along with a keyboard shortcut for **Back** too if you would be so kind 😄

**Comment by adlerluiz** [comment]
No problem, I will add these features, thanks =D

**Comment by adlerluiz** [comment]
Now available on v1.9.0
