### ISSUE TITLE
Use Album covers for Discord rich presence

### ISSUE THREAD

**Issue by Hamsterland** [ytmdesktop/ytmdesktop#980]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Currently when Discord rich presence is activated, the YTMD logo appears.
![image](https://user-images.githubusercontent.com/57412787/173486702-347a91bc-b7ff-4e2d-92d0-1ea6cb690a78.png)

**Describe the solution you'd like**
It would be better if this displayed the album cover.

**Describe alternatives you've considered**
I'm not aware of other approaches to this.

**Additional context**
Nope.

**Comment by Alipoodle** [comment]
This was added in #888
Currently only available in pre-release 1.14.2
