### ISSUE TITLE
Precise volume control request

### ISSUE THREAD

**Issue by AuracleTech** [ytmdesktop/ytmdesktop#986]
I used to use this application for [YouTube music](https://github.com/th-ch/youtube-music)
It had an included extension where the mouse wheel scroll on the album cover would control the volume precisely and display number from 0% to 100% at the top left.

Could we get a similar feature? It's very useful as the default YouTube volume control is terribly unprecise.

**Comment by AuracleTech** [comment]
There was no template to start from are you kidding me.

**Comment by Alipoodle** [comment]
There is, clicking the new issue should suggest one of two templates to follow.

Currently scrolling on the volume slider will allow for changing volume but not exact value is shown.
But over the album art doesn't do this.

**Comment by AuracleTech** [comment]
I see, unfortunately the incident and the missing feature made me uninstall the app already and re-download the previous one.
But thank you for the information, also I see the _Feature request_ option now.
I think I wasn't logged into GitHub so when I clicked issue it prompted me with the login page and ignored the templates.
Bug should probably be reported.
