### ISSUE TITLE
Discord RPC Album Cover and Listen together

### ISSUE THREAD

**Issue by Mnky56** [ytmdesktop/ytmdesktop#988]
I think it would be sweet to have album covers appear on the discord rich presence as you can do so with Spotify as well as YTM with Premid. It would also be nice if you had to pay a small fee for it.

**Comment by Alipoodle** [comment]
@Mnky56 This is a feature in 1.14.2
![image](https://user-images.githubusercontent.com/17199186/176254621-fe187a9c-e81e-4ffd-9aae-99b3bab73b16.png)
