### ISSUE TITLE
Bugs with cover of the song and ads

### ISSUE THREAD

**Issue by VyrekXD** [ytmdesktop/ytmdesktop#991]
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
Cover of the music is cropped and when getting an ad, the ad doesnt display and cant omit it it just appears the cover of the song like a thumbnail
![image](https://user-images.githubusercontent.com/65917996/177205752-94ddf842-7ff6-49a5-aa78-a2a057e0442a.png)
This is the ad bug
![image](https://user-images.githubusercontent.com/65917996/177205812-185c6857-cf88-49da-a571-59566c6d8310.png)

**To Reproduce**
1. Get the latest release here on github
2. Go to any song and play it (cant reproduce the ad bug with youtube premium)
3. Try to get an ad

**Expected behavior**
It should show the ad video and the omit button and it should not crop the cover of the song

**Screenshots**
Already in description

**Environment (please complete the following information):**
 
 * YTMDesktop version: ***1.14.2*** (Hash: DEVELOPMENT_BUILD, https://github.com/ytmdesktop/ytmdesktop/releases/tag/1.14.2 )
 * OS: ***Windows***
 * OS version: ***Version	10.0.19044 Build 19044***
 * Arch: ***x64***
* Installation way: ***The instalation exe***

**Comment by Alipoodle** [comment]
Not seen the first issue myself, and feel like this is a bit more of a YTM Issue (will look out for that)

The #2 issue is likely YTM providing a Non-skippable ads. I'm a YT Premium Member so cannot test this on my normal account, but YouTube does do annoying things like this 🙄
Considering this is a "YouTube Shorts" Ad by the title, it seems to push more to the fact that it's a non-skippable ad.

**Comment by VyrekXD** [comment]
Yeah, but it stills doesnt show the ad if its non-skippable it just shows the cropped cover

**Comment by Alipoodle** [comment]
Oh I see you are using the Audio/Video selector which is kinda "cheated in" 😓
That likely has side effects for Ads.
Unsure to why the album art is broken now

**Comment by Hershey025** [comment]
I also face these problems. I also tested the ytm web but I did not find these problems on the website. both these issues are somehow related to the app I feel

**Comment by LRitzdorf** [comment]
Same issue here. Actually, I mentioned it all the way back in https://github.com/ytmdesktop/ytmdesktop/issues/945#issuecomment-1100798145, if that helps isolate the issue any. I've also tested the normal web version, and this issue does not manifest.

I've installed YTMDesktop from the AUR, for reference.

**Comment by Hershey025** [comment]
yes right bro. Something with the audio video switcher maybe

**Comment by farsdewibs0n** [comment]
> Not seen the first issue myself, and feel like this is a bit more of a YTM Issue (will look out for that)
> 
> The #2 issue is likely YTM providing a Non-skippable ads. I'm a YT Premium Member so cannot test this on my normal account, but YouTube does do annoying things like this 🙄 Considering this is a "YouTube Shorts" Ad by the title, it seems to push more to the fact that it's a non-skippable ad.

Apparently its unskippable even the ad is skippable (found out that the ad I got is a full song cover).

**Comment by Hershey025** [comment]
> > Not seen the first issue myself, and feel like this is a bit more of a YTM Issue (will look out for that)
> > The #2 issue is likely YTM providing a Non-skippable ads. I'm a YT Premium Member so cannot test this on my normal account, but YouTube does do annoying things like this 🙄 Considering this is a "YouTube Shorts" Ad by the title, it seems to push more to the fact that it's a non-skippable ad.
> 
> Apparently its unskippable even the ad is skippable (found out that the ad I got is a full song cover).

Yes

**Comment by Alipoodle** [comment]
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.
